### ISSUE TITLE
YouTube crashes after updating it to 17.43.36 and patching

### ISSUE THREAD

**Issue by Atexor** [revanced/revanced-patches#1016]
### Type

Error at runtime

### Bug description

Hello,
I just updated YT from 17.36.37 to recommended v17.43.36 and after patching it with latest manager, YouTube became unusable. I am using rooted custom Android 13 system on POCO F4.

### Steps to reproduce

1. Have YouTube 17.36.37.
2. Update to recommended v17.43.36 (downloaded from apkmirror, not bundle, apk)
3. Open ReVanced Manager (v0.0.40
4. Select following patches:
Return YouTube Dislike (v.0.0.1)
Theme (v.0.01)
Premium Heading (v0.0.1)
General Ads (v0.0.1)
Downloads (v0.0.1)
Custom Video Buffer (v.0.0.1)
Client Spoof (v.0.01)
Minimized Playback (v.0.0.1)
Custom Video Speed (v.0.0.1)
5. Install as root (I've error while installing as non-root that it can't be done with selected patches)
6. Open YouTube
7. Crash.
8. Noticed that YouTube app changed name in Android Settings/Recanved manager to something like "user_key..." (forgot name because reinstalled YT again).

### Relevant log output

```shell
11-10 19:17:53.820  9675  9675 E android.youtube: expected 8 dex files but found 6
11-10 19:17:53.821  9675  9675 E android.youtube: expected 8 dex files but found 6
11-10 19:17:53.821  9675  9675 W ziparchive: Unable to open '/data/app/~~Bo7l9-LfgP5o8l6xIs4pUQ==/com.google.android.youtube-GSRW-T7fneIAmj2JjexnDA==/base.dm': No such file or directory
11-10 19:17:53.821  9675  9675 W ziparchive: Unable to open '/data/app/~~Bo7l9-LfgP5o8l6xIs4pUQ==/com.google.android.youtube-GSRW-T7fneIAmj2JjexnDA==/base.dm': No such file or directory
11-10 19:17:54.195   683  4007 W libperfmgr: Failed to write to node: /dev/stune/top-app/schedtune.boost with value: 10, fd: -1
11-10 19:17:54.284  9675  9675 E AndroidRuntime: FATAL EXCEPTION: main
11-10 19:17:54.284  9675  9675 E AndroidRuntime: Process: com.google.android.youtube, PID: 9675
11-10 19:17:54.284  9675  9675 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.google.android.apps.youtube.app.YouTubeTikTokRoot_Application package com.google.android.youtube: java.lang.RuntimeException: Failed to parse XML configuration from offline_prefs
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1466)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6753)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7900)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
11-10 19:17:54.284  9675  9675 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failed to parse XML configuration from offline_prefs
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.security.net.config.XmlConfigSource.ensureInitialized(XmlConfigSource.java:89)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.security.net.config.XmlConfigSource.getPerDomainConfigs(XmlConfigSource.java:55)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.security.net.config.ManifestConfigSource.getPerDomainConfigs(ManifestConfigSource.java:45)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.security.net.config.ApplicationConfig.ensureInitialized(ApplicationConfig.java:175)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.security.net.config.ApplicationConfig.isCleartextTrafficPermitted(ApplicationConfig.java:130)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.security.net.config.NetworkSecurityConfigProvider.handleNewApplication(NetworkSecurityConfigProvider.java:60)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1457)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        ... 11 more
11-10 19:17:54.284  9675  9675 E AndroidRuntime: Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected start tag: found PreferenceScreen, expected network-security-config
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at com.android.internal.util.XmlUtils.beginDocument(XmlUtils.java:1699)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.security.net.config.XmlConfigSource.parseNetworkSecurityConfig(XmlConfigSource.java:315)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        at android.security.net.config.XmlConfigSource.ensureInitialized(XmlConfigSource.java:83)
11-10 19:17:54.284  9675  9675 E AndroidRuntime:        ... 17 more
11-10 19:17:54.292  1610  5771 W ActivityTaskManager:   Force finishing activity com.google.android.youtube/.app.honeycomb.Shell$HomeActivity
11-10 19:17:54.320  1610  2178 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
11-10 19:17:54.323  1610  2178 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
11-10 19:17:54.413  1610  2171 W InputManager-JNI: Input channel object 'b584ccd Splash Screen com.google.android.youtube (client)' was disposed without first being removed with the input manager!
11-10 19:17:54.421  1610 11416 W WindowManager: Failed looking up window session=Session{d7408c4 2980:u0a10299} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5906 com.android.server.wm.WindowManagerService.removeWindow:2032 com.android.server.wm.Session.remove:223
11-10 19:17:54.422  1610 11416 W InputManager-JNI: Input channel object 'Embedded{} (client)' was disposed without first being removed with the input manager!
11-10 19:17:54.423  1610  4522 W WindowManager: Failed looking up window session=Session{d7408c4 2980:u0a10299} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:5906 com.android.server.wm.WindowManagerService.removeWindow:2032 com.android.server.wm.Session.remove:223
11-10 19:17:54.441  1610  4522 W ActivityTaskManager: Request to remove task ignored for non-existent task 1275
11-10 19:17:54.443  1610  3713 W JobScheduler: Job didn't exist in JobStore: ef9e071 #u0a350/55 com.devexpert.weather/.controller.UpdateService
11-10 19:17:54.443 29224 29224 E FullInputEventModel: onStartInput event aborted: km1: could not obtain extracted text (class km1)
11-10 19:17:54.696   683  4007 W libperfmgr: Failed to write to node: /dev/stune/top-app/schedtune.boost with value: 10, fd: -1
11-10 19:17:54.796  1610  2170 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{97df3f6 u0 com.google.android.youtube/.app.honeycomb.Shell$HomeActivity} t-1 f}}
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please record the patching of the apk file entirely.

**Comment by matthoendorf** [comment]
Same issue, here's my full log:

```
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing all patches
Executing 'resource-mapping' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Skipping 'locale-config-fix' because it has already been applied
Executing 'general-resource-ads' of type: resource
Executing 'general-ads' of type: bytecode
Applied general-ads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'integrations' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'video-information' of type: bytecode
Skipping 'settings' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'fix-playback' of type: resource
Executing 'video-ads' of type: bytecode
Applied video-ads
Skipping 'locale-config-fix' because it has already been applied
Executing 'bottom-controls-resource-patch' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'downloads-resource-patch' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'player-controls-bytecode-patch' of type: bytecode
Skipping 'video-id-hook' because it has already been applied
Executing 'downloads' of type: bytecode
Applied downloads
Skipping 'locale-config-fix' because it has already been applied
Executing 'premium-heading' of type: resource
premium-heading failed.
Error:
kotlin.Unit
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-fullscreen-panels' of type: bytecode
Applied disable-fullscreen-panels
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'hide-album-cards-resource-patch' of type: resource
Executing 'hide-album-cards' of type: bytecode
Applied hide-album-cards
Skipping 'resource-mapping' because it has already been applied
Skipping 'general-ads' because it has already been applied
Executing 'hide-artist-card' of type: resource
Applied hide-artist-card
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'crowdfunding-box-resource-patch' of type: resource
Executing 'hide-crowdfunding-box' of type: bytecode
Applied hide-crowdfunding-box
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'hide-endscreen-cards-resource-patch' of type: resource
Executing 'hide-endscreen-cards' of type: bytecode
Applied hide-endscreen-cards
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'Class' of type: resource
Executing 'hide-info-cards' of type: bytecode
Applied hide-info-cards
Skipping 'integrations' because it has already been applied
Executing 'hide-my-mix' of type: bytecode
Applied hide-my-mix
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'old-quality-layout' of type: bytecode
Applied old-quality-layout
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'hide-email-address-resource-patch' of type: resource
Executing 'hide-email-address' of type: bytecode
Applied hide-email-address
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-shorts-button' of type: bytecode
Applied hide-shorts-button
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-auto-player-popup-panels' of type: bytecode
Applied disable-auto-player-popup-panels
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'return-youtube-dislike-resource-patch' of type: resource
Executing 'return-youtube-dislike' of type: bytecode
Applied return-youtube-dislike
Skipping 'video-information' because it has already been applied
Skipping 'player-controls-bytecode-patch' because it has already been applied
Skipping 'integrations' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'sponsorblock-resource-patch' of type: resource
Skipping 'video-id-hook' because it has already been applied
Executing 'sponsorblock' of type: bytecode
Applied sponsorblock
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'disable-startup-shorts-player' of type: bytecode
Applied disable-startup-shorts-player
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-watch-in-vr' of type: bytecode
Applied hide-watch-in-vr
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-watermark' of type: bytecode
Applied hide-watermark
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'enable-wide-searchbar' of type: bytecode
Applied enable-wide-searchbar
Skipping 'integrations' because it has already been applied
Executing 'always-autorepeat' of type: bytecode
Applied always-autorepeat
Executing 'client-spoof' of type: bytecode
Applied client-spoof
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hdr-auto-brightness' of type: bytecode
Applied hdr-auto-brightness
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'minimized-playback' of type: bytecode
Applied minimized-playback
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'open-links-directly' of type: bytecode
Applied open-links-directly
Skipping 'settings' because it has already been applied
Applied settings
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'remember-video-quality' of type: bytecode
Applied remember-video-quality
Skipping 'integrations' because it has already been applied
Executing 'custom-video-speed' of type: bytecode
Applied custom-video-speed
Repacking patched apk
Compiling resources
Creating new dex file
Writing modified dex files
Finished!
Installing patched file using root method
Installed!
```

**Comment by Atexor** [comment]
I updated my ROM and patched YT stopped working (despite working root access) so I reinstalled apk v17.43.36 and re-patched YouTube ReVanced (version was detected correctly). I got again the same issue, where YouTube changed name after patching to auto_play_key and was crashing on opening. You can see it here:
![obraz](https://user-images.githubusercontent.com/34380553/201780236-aba3e472-83b4-4773-bbf9-8626366b19f2.png)

On Android settings app version also was detected as older and YouTube was crashing on start.
![obraz](https://user-images.githubusercontent.com/34380553/201780330-99a2fff7-9b1a-4220-bd0b-61f3c1d2cadc.png)

On second tab I noticed that patching v17.43.36 and installing as root caused that version was downgraded to 17.36.37.
I didn't check after ROM installation, but maybe it's default vorsion for my Android built and for unkown reason it's overwriting ReVanced patched during installation as root.

If it's important, my YT is detached it from Play Store to prevent auto-updates using [TeMeFi](https://forum.xda-developers.com/t/app-tool-temefi-comprehensive-system-administration.3806260/) app.

Now I traced entire installation progress since opening app and YouTube is working, but noticed some errors in logcat so I am sharing logs (2 parts, too much for one paste). Hope that helps.
https://pastebin.com/w8H0mufj
https://pastebin.com/W50wEJgV

**Comment by oSumAtrIX** [comment]
Please record patching the app, make sure to also show which version of the app is installed on your device.

**Comment by Atexor** [comment]
Did you mean that log below? Hopefully I saved it, but thought you wanted logcat during patching. 

Installed version during patching was v17.43.36 and was same as suggested in ReVanced Manager. I know that Android stores some kind of backups of original base of installed apps and if you want to uninstall sometimes certain preinstalled app, Android ask whether you want to uninstall all updates of it instead deleting the app. That's what I meant before with restoring default version.

```
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing all patches
Executing 'resource-mapping' of type: resource
Executing 'integrations' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'locale-config-fix' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Skipping 'locale-config-fix' because it has already been applied
Executing 'general-resource-ads' of type: resource
Executing 'general-ads' of type: bytecode
Applied general-ads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'integrations' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'video-information' of type: bytecode
Skipping 'settings' because it has already been applied
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'fix-playback' of type: resource
Executing 'video-ads' of type: bytecode
Applied video-ads
Skipping 'locale-config-fix' because it has already been applied
Executing 'bottom-controls-resource-patch' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'downloads-resource-patch' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'player-controls-bytecode-patch' of type: bytecode
Skipping 'video-id-hook' because it has already been applied
Executing 'downloads' of type: bytecode
Applied downloads
Skipping 'locale-config-fix' because it has already been applied
Executing 'premium-heading' of type: resource
Applied premium-heading
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'return-youtube-dislike-resource-patch' of type: resource
Executing 'return-youtube-dislike' of type: bytecode
Applied return-youtube-dislike
Executing 'litho-components-theme' of type: bytecode
Skipping 'locale-config-fix' because it has already been applied
Executing 'theme' of type: resource
Applied theme
Executing 'client-spoof' of type: bytecode
Applied client-spoof
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'minimized-playback' of type: bytecode
Applied minimized-playback
Skipping 'settings' because it has already been applied
Applied settings
Skipping 'integrations' because it has already been applied
Executing 'custom-video-speed' of type: bytecode
Applied custom-video-speed
Skipping 'settings' because it has already been applied
Executing 'custom-video-buffer' of type: bytecode
Applied custom-video-buffer
Repacking patched apk
Compiling resources
Creating new dex file
Writing modified dex files
Finished!
Installing patched file using root method
Installed!
```

**Comment by oSumAtrIX** [comment]
So did I understand correctly, you have v17.43.36 installed on your phone, and also patch the base apk from your device?

**Comment by Atexor** [comment]
Installed version was v17.43.36 and that installed version was patched (not .apk file from Storage). Both version matched as you can see now here
![obraz](https://user-images.githubusercontent.com/34380553/201850180-81a52b68-74de-4994-ac1e-de5e0e2edb0c.png)

After installation, YouTube version was somehow downgraded.

**Comment by oSumAtrIX** [comment]
Can you record a video of the issue?

**Comment by Atexor** [comment]
It might be problematic for now because it happened to me only one time after updating YouTube and one after updating ROM. I don't know how to reproduce it every time.

However I noticed something new. After rebooting my phone, entering PIN and password, after short while I am getting error on my screen that application "com.youtube.android.apps.youtube.app.YouTubeTikTokRoot_Application" stopped working. Package version of it is still "com.google.android.youtube" and version is.... v17.36.37. Yes, it downgrades back.

Icon for YouTube changed name to "Click to start exploring chart."., which is also visible on ReVanced Manager with v17.36.37 version. I clicked to "unpatch" that application, but it is still crashing.

After installing v17.43.36 (.apk from apkmirror, not bundle) YouTube started working, patched it again and works. I checked that twice.

**Comment by oSumAtrIX** [comment]
I am not sure what you mean by it downgrades back, apps can not downgrade.

**Comment by Canny1913** [comment]
This can be caused by conflicting mount scripts/packages.

Delete /data/adb/revanced and try patching again.

**Comment by Atexor** [comment]
Hello, I had some time and made some more tests in recent time. There was no folder /data/aadb/revanced, just "vanced" folder with ~20mb apk, but removed it).

Fortunately I found reason of that issue. It has conflict with [TeMeFi](https://forum.xda-developers.com/t/app-tool-temefi-comprehensive-system-administration.3806260/) app which I use to detach YouTube revanced from play store. When I am using it on YouTube and then patch apk using manager I am getting these issues with downgrading or "YouTubeTikTokRoot_Application". I'm unable to patch YT using manager and then detach because for unkown reason package is unavailable in TeMeFi app. It looks like patched yt hides partially its package.

I tried to build patched .apk and install it by patching .apk from apkmirror however I am getting conflicts with vanilla YT. Is it possible to detaach YT ReVanced from google play to not get auto-updates or notifications about it? Custom branding patch is not enough.

**Comment by oSumAtrIX** [comment]
You need the same version installed on your phone to mount the patched base apk over. Issue seems stale, create a new one with latest updates.

**Comment by Atexor** [comment]
Well, it was the same version. I am able to overwrite patched YT with normal YT but I can't in reverse order.
![obraz](https://user-images.githubusercontent.com/34380553/208322314-6e833edb-1237-498c-84a3-838d54ecc3d7.png)

![obraz](https://user-images.githubusercontent.com/34380553/208322322-df328f0b-6b67-4603-9f7d-a0232d2b0b89.png)

![obraz](https://user-images.githubusercontent.com/34380553/208322347-0eebae52-78b8-4bda-850d-4a778cf50a7a.png)
