### ISSUE TITLE
bug: Custom Speed Patch Fail

### ISSUE THREAD

**Issue by furquim87** [revanced/revanced-patches#1089]
### Type

Error while patching

### Bug description

While using ReVanced Manager (0.0.40) to patch my YouTube (17.43.36) app I receive the following error: 
```
Executing 'custom-video-speed' of type: bytecode custom-video-speed failed.
Error:
kotlin.Unit
```
The process completes and I'm able to install the app but, as expected, the Custom Speed Patch doesn't work

### Steps to reproduce

Step 1. Select the YouTube app and patches on ReVanced Manager
Step 2. Start patching
Step 3. Receive error message
Step 4. Install the app
Step 5. Custom video speed patch doesn't work

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing all patches
Executing 'locale-config-fix' of type: resource
Executing 'integrations' of type: bytecode
Executing 'Class' of type: bytecode
Skipping 'integrations' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Executing 'resource-mapping' of type: resource
Executing 'settings-resource-patch' of type: resource
Executing 'settings' of type: bytecode
Skipping 'resource-mapping' because it has already been applied
Executing 'Class' of type: resource
Executing 'general-ads' of type: bytecode
Applied general-ads
Skipping 'locale-config-fix' because it has already been applied
Executing 'bottom-controls-resource-patch' of type: resource
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'downloads-resource-patch' of type: resource
Skipping 'resource-mapping' because it has already been applied
Executing 'player-controls-bytecode-patch' of type: bytecode
Skipping 'integrations' because it has already been applied
Executing 'video-id-hook' of type: bytecode
Executing 'downloads' of type: bytecode
Applied downloads
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'seekbar-tapping' of type: bytecode
Applied seekbar-tapping
Skipping 'locale-config-fix' because it has already been applied
Executing 'premium-heading' of type: resource
Applied premium-heading
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'old-quality-layout' of type: bytecode
Applied old-quality-layout
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'return-youtube-dislike-resource-patch' of type: resource
Executing 'return-youtube-dislike' of type: bytecode
Applied return-youtube-dislike
Skipping 'integrations' because it has already been applied
Executing 'video-information' of type: bytecode
Skipping 'player-controls-bytecode-patch' because it has already been applied
Skipping 'integrations' because it has already been applied
Skipping 'locale-config-fix' because it has already been applied
Skipping 'settings' because it has already been applied
Skipping 'resource-mapping' because it has already been applied
Executing 'sponsorblock-resource-patch' of type: resource
Skipping 'video-id-hook' because it has already been applied
Executing 'sponsorblock' of type: bytecode
Applied sponsorblock
Executing 'litho-components-theme' of type: bytecode
Skipping 'locale-config-fix' because it has already been applied
Executing 'theme' of type: resource
Applied theme
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hide-watermark' of type: bytecode
Applied hide-watermark
Executing 'client-spoof' of type: bytecode
Applied client-spoof
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'hdr-auto-brightness' of type: bytecode
Applied hdr-auto-brightness
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'minimized-playback' of type: bytecode
Applied minimized-playback
Skipping 'integrations' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'open-links-directly' of type: bytecode
Applied open-links-directly
Skipping 'settings' because it has already been applied
Applied settings
Skipping 'integrations' because it has already been applied
Skipping 'video-id-hook' because it has already been applied
Skipping 'settings' because it has already been applied
Executing 'remember-video-quality' of type: bytecode
Applied remember-video-quality
Skipping 'integrations' because it has already been applied
Executing 'custom-video-speed' of type: bytecode
custom-video-speed failed.
Error:
kotlin.Unit
Repacking patched apk
Compiling resources
Creating new dex file
Writing modified dex files
Finished!
Installing patched file using root method
Installed!
```

### Additional context

I'm using the following patches:

- Sponsorblock (v0.0.1)
- Return Youtube Dislike (v0.0.1)
- Theme (v0.0.1)
- Hide Watermark (v0.0.1)
- Premium Heading (v0.0.1)
- Old Quality Layout (v0.0.1)
- General Ads (v0.0.1)
- Downloads (v0.0.1)
- Seekbar Tapping (v0.0.1)
- Open Links Directly (v0.0.1)
- Client Spoof (v0.0.1)
- Minimized Playback (v0.0.1)
- Custom Video Speed (v0.0.1)
- Remember Video Quality (v0.0.1)
- Hdr Auto Brightness (v0.0.2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kyan5221** [comment]
I have 4 errors with v17.45.36 + v2.121.0 patch.
- wide searchbar
- hide shorts button
- hide create button
- custom video speed

![20221124_180638](https://user-images.githubusercontent.com/9549962/203741867-047a4e8a-f46f-4fc4-b80e-c0f9a2feb009.jpg)

**Comment by oSumAtrIX** [comment]
You are using an unofficial tool @kyan5221.

**Comment by udoxi** [comment]
Executing 'custom-video-speed' of type: bytecode
custom-video-speed failed.
Error:
kotlin.Unit
Skipping 'settings' because it has already been applied
Executing 'custom-video-buffer' of type: bytecode
Applied custom-video-buffer
Skipping 'settings' because it has already been applied
Executing 'disable-zoom-haptics' of type: bytecode
Applied disable-zoom-haptics
Repacking patched apk
Compiling resources
Creating new dex file
Writing modified dex files
Finished!

**Comment by FineFindus** [comment]
Seems like it was broken by bd6adbd23152371e99c1575fbd9611590ad0d477. It works before, but breaks after.
I've tested it with `17.43.36` and `17.45.36`, it breaks on both versions.

<details>
<summary>Logs</summary>

Generated by running
```sh
java -jar revanced-cli-2.15.0-all.jar -a apks/youtube_17.43.36.apk  -c  -o output.apk -b patches/revanced-patches-2.118.0.jar -m  integrations.apk -i custom-video-speed --exclusive
```
```
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Merging integrations.apk 
INFO: Skipping unlock-premium, reason: excluded by default 
INFO: Skipping pflotsh-ecmwf-subscription-unlock, reason: excluded by default 
INFO: Skipping disable-ads, reason: excluded by default 
INFO: Skipping unlock-pro, reason: excluded by default 
INFO: Skipping music-video-ads, reason: excluded by default 
INFO: Skipping codecs-unlock, reason: excluded by default 
INFO: Skipping exclusive-audio-playback, reason: excluded by default 
INFO: Skipping compact-header, reason: excluded by default 
INFO: Skipping minimized-playback-music, reason: excluded by default 
INFO: Skipping hide-get-premium, reason: excluded by default 
INFO: Skipping tasteBuilder-remover, reason: excluded by default 
INFO: Skipping upgrade-button-remover, reason: excluded by default 
INFO: Skipping music-microg-support, reason: excluded by default 
INFO: Skipping background-play, reason: excluded by default 
INFO: Skipping unlock-pro, reason: excluded by default 
INFO: Skipping general-reddit-ads, reason: excluded by default 
INFO: Skipping premium-icon-reddit, reason: excluded by default 
INFO: Skipping disable-capture-restriction, reason: excluded by default 
INFO: Skipping spotify-theme, reason: excluded by default 
INFO: Skipping hide-premium-navbar, reason: excluded by default 
INFO: Skipping unlock-themes, reason: excluded by default 
INFO: Skipping tiktok-ads, reason: excluded by default 
INFO: Skipping tiktok-feed-filter, reason: excluded by default 
INFO: Skipping tiktok-download, reason: excluded by default 
INFO: Skipping tiktok-seekbar, reason: excluded by default 
INFO: Skipping tiktok-speed, reason: excluded by default 
INFO: Skipping tiktok-force-login, reason: excluded by default 
INFO: Skipping tiktok-web-login, reason: excluded by default 
INFO: Skipping tiktok-settings, reason: excluded by default 
INFO: Skipping block-audio-ads, reason: excluded by default 
INFO: Skipping block-video-ads, reason: excluded by default 
INFO: Skipping show-deleted-messages, reason: excluded by default 
INFO: Skipping debug-mode, reason: excluded by default 
INFO: Skipping timeline-ads, reason: excluded by default 
INFO: Skipping dynamic-color, reason: excluded by default 
INFO: Skipping monochrome-icon, reason: excluded by default 
INFO: Skipping promo-code-unlock, reason: excluded by default 
INFO: Skipping spoof-signature, reason: excluded by default 
INFO: Skipping general-ads, reason: excluded by default 
INFO: Skipping video-ads, reason: excluded by default 
INFO: Skipping downloads, reason: excluded by default 
INFO: Skipping seekbar-tapping, reason: excluded by default 
INFO: Skipping swipe-controls, reason: excluded by default 
INFO: Skipping disable-auto-captions, reason: excluded by default 
INFO: Skipping hide-autoplay-button, reason: excluded by default 
INFO: Skipping premium-heading, reason: excluded by default 
INFO: Skipping custom-branding, reason: excluded by default 
INFO: Skipping hide-video-buttons, reason: excluded by default 
INFO: Skipping hide-cast-button, reason: excluded by default 
INFO: Skipping comments, reason: excluded by default 
INFO: Skipping disable-fullscreen-panels, reason: excluded by default 
INFO: Skipping hide-album-cards, reason: excluded by default 
INFO: Skipping hide-artist-card, reason: excluded by default 
INFO: Skipping hide-captions-button, reason: excluded by default 
INFO: Skipping hide-crowdfunding-box, reason: excluded by default 
INFO: Skipping hide-endscreen-cards, reason: excluded by default 
INFO: Skipping hide-info-cards, reason: excluded by default 
INFO: Skipping hide-my-mix, reason: excluded by default 
INFO: Skipping hide-time-and-seekbar, reason: excluded by default 
INFO: Skipping old-quality-layout, reason: excluded by default 
INFO: Skipping hide-email-address, reason: excluded by default 
INFO: Skipping hide-create-button, reason: excluded by default 
INFO: Skipping hide-shorts-button, reason: excluded by default 
INFO: Skipping disable-auto-player-popup-panels, reason: excluded by default 
INFO: Skipping return-youtube-dislike, reason: excluded by default 
INFO: Skipping sponsorblock, reason: excluded by default 
INFO: Skipping disable-startup-shorts-player, reason: excluded by default 
INFO: Skipping tablet-mini-player, reason: excluded by default 
INFO: Skipping theme, reason: excluded by default 
INFO: Skipping hide-watch-in-vr, reason: excluded by default 
INFO: Skipping hide-watermark, reason: excluded by default 
INFO: Skipping enable-wide-searchbar, reason: excluded by default 
INFO: Skipping always-autorepeat, reason: excluded by default 
INFO: Skipping client-spoof, reason: excluded by default 
INFO: Skipping debugging, reason: excluded by default 
INFO: Skipping hdr-auto-brightness, reason: excluded by default 
INFO: Skipping microg-support, reason: excluded by default 
INFO: Skipping minimized-playback, reason: excluded by default 
INFO: Skipping open-links-directly, reason: excluded by default 
INFO: Skipping settings, reason: excluded by default 
INFO: Skipping remember-video-quality, reason: excluded by default 
INFO: Skipping custom-video-buffer, reason: excluded by default 
INFO: Skipping disable-zoom-haptics, reason: excluded by default 
SEVERE: custom-video-speed failed: 
app.revanced.patcher.patch.PatchResultError
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:346)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:362)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
	at app.revanced.patches.youtube.misc.video.speed.custom.patch.CustomVideoSpeedPatch.execute(CustomVideoSpeedPatch.kt:43)
	at app.revanced.patches.youtube.misc.video.speed.custom.patch.CustomVideoSpeedPatch.execute(CustomVideoSpeedPatch.kt:26)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:342)
	... 16 more
INFO: Not compiling resources because resource patching is not required 
INFO: Writing modified dex files 
INFO: Writing dex file classes2.dex 
INFO: Writing dex file classes3.dex 
INFO: Writing dex file classes4.dex 
INFO: Writing dex file classes.dex 
INFO: Writing dex file classes8.dex 
INFO: Writing dex file classes5.dex 
INFO: Writing dex file classes6.dex 
INFO: Writing dex file classes7.dex 
INFO: Aligning output_raw.apk to output_aligned.apk 
INFO: Signing output_aligned.apk to output_signed.apk 
INFO: Found existing keystore: output.keystore 
INFO: Copying output_signed.apk to output.apk 
INFO: Cleaned up cache directory 
INFO: Finished 
```
</details>

**Comment by udoxi** [comment]
Getting custom-speed-video failed error
Vanced Manager : `0.0.41`
Patch Version : `2.121.0`
Patch Logs :
[revanced-manager_patcher_20221125084858667525.log](https://github.com/revanced/revanced-patches/files/10088357/revanced-manager_patcher_20221125084858667525.log)

**Comment by udoxi** [comment]
https://user-images.githubusercontent.com/115417493/203897937-b618943a-1f78-482c-b870-0a27d9f1834a.mp4


https://user-images.githubusercontent.com/115417493/203897971-e6f330a3-83b2-440e-8a6d-96d119fcdc55.mp4

**Comment by jaum20** [comment]
same problem
![image](https://user-images.githubusercontent.com/36702273/204068062-614f2466-141e-425d-8c10-7f165d771743.png)

**Comment by FineFindus** [comment]
A fix has been merged. Please test if it works and close the issue.

**Comment by Impulse666** [comment]
**custom-video-speed** is working fine.
**hide-create-button**, **enable-wide-searchbar** and **enable-wide-searchbar** still need a fix.

**Comment by Suznyan** [comment]
> A fix has been merged. Please test if it works and close the issue.
enable-wide-searchbar, hide-shorts-button, hide-create-button failed are still failed

**Comment by oSumAtrIX** [comment]
Offtopic isue.

**Comment by AMSAMSAMSAMS** [comment]
```
SEVERE: enable-wide-searchbar failed: 
app.revanced.patcher.patch.PatchResultError: Failed to resolve IsInOfflineModeCheckResultFingerprint
	at app.revanced.extensions.ExtensionsKt.toErrorResult(Extensions.kt:19)
	at app.revanced.patches.youtube.layout.widesearchbar.patch.WideSearchbarPatch.execute(WideSearchbarPatch.kt:81)
	at app.revanced.patches.youtube.layout.widesearchbar.patch.WideSearchbarPatch.execute(WideSearchbarPatch.kt:27)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:336)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:356)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
```


Still failed on:
- YouTube: v17.43.36
- CLI: v2.16.1
- Patches: v2.130.0
- Integration: 0.78.0

**Comment by oSumAtrIX** [comment]
@AMSAMSAMSAMS  Wrong patch.
