### ISSUE TITLE
bug: Autoplay Not Working in Google Feed (aka discover) and Play Store (While clicking on the video of an app)

### ISSUE THREAD

**Issue by AdishSagarawat** [revanced/revanced-patches#1096]
### Type

Other

### Bug description

These works fine with Official YouTube.

Broken on ReVanced.

### Steps to reproduce

Open Google Feed and scroll a bit till you find a YouTube Video.

Also,
Open any app on Play Store (Say Asphalt 9) Click on the video it will not work.

### Relevant log output

```shell
java.lang.ExceptionInInitializerError
at app.revanced.integrations.patches.LayoutSwitchOverridePatch.getLayoutSwitchOverride(LayoutSwitchOverridePatch.java:1)
at ued.bV(PG:1)
at ued.ce(PG:1)
at wez.M(PG:5)
at wez.a(PG:14)
at aqim.a(PG:1)
at led.a(PG:7)
at ldj.run(PG:39)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6186)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
at app.revanced.integrations.sponsorblock.StringRef.toString(StringRef.java:11)
at app.revanced.integrations.sponsorblock.StringRef.str(StringRef.java:1)
at app.revanced.integrations.settings.SettingsEnum.(SettingsEnum.java:67)
... 16 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#955
