### ISSUE TITLE
Login not works in Native MicroG [Rooted users]

### ISSUE THREAD

**Issue by Milor123** [revanced/revanced-patches#111]
I have an old vanced issue, my phone is Poco x3 pro with CrDroid 12.1, rooted, magisk and microG installed from magisk package

The YouTube ReVanced [Root variant] (disable the external vanced `microg-support`) **don't recognize my Google account devices added from my navite MicroG**, and when I try to add the account, it said that `already exits`. (And my Google account is correctly configured to **be visible to all apps in account settings**)

![image](https://user-images.githubusercontent.com/14153649/177013927-c6f3b6fb-4b45-4c4f-8ea9-7000c26719a2.png)

Only works when i keep the `microg-support` but then i must install the external app vanced MicroG, when i have installed the native MicroG

Like you can see in the next image, my Google account can be detected by all apps:

![Screenshot_20220702-145112_microG Services Core.png](https://user-images.githubusercontent.com/14153649/177014550-1ea87437-c4cd-47b7-a278-54ec54234c5e.png)

In my case, I Can use Vanced or YouTube (stock APK) and stay logged using my Google account, using my Native MicroG, it maybe was an old problem in vanced, but it is not problem now in decapred vanced or in a official youtube app (basically is NOT microG bug), and in ReVanced the problem returns!

Is it a Revanced Problem
Thank you very much

**Comment by Mubelotix** [comment]
<details>

<summary>Some slightly different new logs</summary>

```
10-05 19:57:59.592  5254  5315 E VerityUtils: Failed to measure fs-verity, errno 1: /data/app/~~4Uujdw0dAGAlD6nS4uMtPg==/app.revanced.android.youtube-kKQ5mteNkpLRPPx0nrEFWQ==/base.apk
10-05 19:57:59.599 16105 16180 E YouTube : Failed to construct CronetEngine using CronetProvider: App-Packaged-Cronet-Provider, 106.0.5228.2
10-05 19:57:59.599 16105 16180 E YouTube : dye: libcronet.106.0.5228.2.so
10-05 19:57:59.599 16105 16180 E YouTube : 	at cal.p(PG:51)
10-05 19:57:59.599 16105 16180 E YouTube : 	at uhe.bA(PG:7)
10-05 19:57:59.599 16105 16180 E YouTube : 	at sut.loadLibrary(PG:1)
10-05 19:57:59.599 16105 16180 E YouTube : 	at atfc.loadLibrary(PG:1)
10-05 19:57:59.599 16105 16180 E YouTube : 	at org.chromium.net.impl.CronetLibraryLoader.a(PG:5)
10-05 19:57:59.599 16105 16180 E YouTube : 	at org.chromium.net.impl.CronetUrlRequestContext.<init>(PG:8)
10-05 19:57:59.599 16105 16180 E YouTube : 	at ateq.build(PG:2)
10-05 19:57:59.599 16105 16180 E YouTube : 	at org.chromium.net.ExperimentalCronetEngine$Builder.build(PG:2)
10-05 19:57:59.599 16105 16180 E YouTube : 	at sus.a(PG:32)
10-05 19:57:59.599 16105 16180 E YouTube : 	at suo.a(PG:10)
10-05 19:57:59.599 16105 16180 E YouTube : 	at szv.ao(PG:1)
10-05 19:57:59.599 16105 16180 E YouTube : 	at ehv.i(PG:147)
10-05 19:57:59.599 16105 16180 E YouTube : 	at ehv.a(PG:36)
10-05 19:57:59.599 16105 16180 E YouTube : 	at aqkt.a(PG:1)
10-05 19:57:59.599 16105 16180 E YouTube : 	at sjp.run(PG:20)
10-05 19:57:59.599 16105 16180 E YouTube : 	at nrq.run(PG:5)
10-05 19:57:59.599 16105 16180 E YouTube : 	at nru.run(PG:23)
10-05 19:57:59.599 16105 16180 E YouTube : 	at nsc.run(PG:55)
10-05 19:57:59.599 16105 16180 E YouTube : 	at mwd.run(PG:6)
10-05 19:57:59.599 16105 16180 E YouTube : 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.p.run(PG:5)
10-05 19:57:59.599 16105 16180 E YouTube : 	at java.lang.Thread.run(Thread.java:1012)
10-05 19:57:59.607 16210 16210 E ocess.gservice: Not starting debugger since process cannot load the jdwp agent.
10-05 19:57:59.625 16210 16210 E USNET   : USNET: appName: com.google.process.gservices
10-05 19:57:59.637  5254  8150 I ActivityManager: DSS OFF for com.google.android.gsf
10-05 19:57:59.667 16105 16234 I libEGL  : EGL_ANDROID_blob_cache_path advertised, but unable to get eglSetBlobCachePathANDROID
10-05 19:57:59.737 16105 16172 E YouTube : Error loading store
10-05 19:57:59.737 16105 16172 E YouTube : dye: libelements.so
10-05 19:57:59.737 16105 16172 E YouTube : 	at cal.p(PG:51)
10-05 19:57:59.737 16105 16172 E YouTube : 	at uhe.bA(PG:7)
10-05 19:57:59.737 16105 16172 E YouTube : 	at eje.a(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at afyf.e(PG:8)
10-05 19:57:59.737 16105 16172 E YouTube : 	at afyf.f(PG:5)
10-05 19:57:59.737 16105 16172 E YouTube : 	at afyf.c(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at nuu.a(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ulv.<init>(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at umd.<init>(PG:6)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ulz.g(PG:4)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ulz.d(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ulz.a(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at fce.b(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at fce.<init>(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at fah.h(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ehv.n(PG:9)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ehv.a(PG:31)
10-05 19:57:59.737 16105 16172 E YouTube : 	at aqkt.a(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ehw.x(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ehw.u(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ehv.n(PG:12)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ehv.a(PG:31)
10-05 19:57:59.737 16105 16172 E YouTube : 	at aqla.a(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ehw.zV(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ehw.dF(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ehv.m(PG:63)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ehv.a(PG:32)
10-05 19:57:59.737 16105 16172 E YouTube : 	at aqkt.a(PG:1)
10-05 19:57:59.737 16105 16172 E YouTube : 	at ejd.run(PG:66)
10-05 19:57:59.737 16105 16172 E YouTube : 	at syy.run(PG:7)
10-05 19:57:59.737 16105 16172 E YouTube : 	at nrq.run(PG:5)
10-05 19:57:59.737 16105 16172 E YouTube : 	at nru.run(PG:23)
10-05 19:57:59.737 16105 16172 E YouTube : 	at nsc.run(PG:55)
10-05 19:57:59.737 16105 16172 E YouTube : 	at mwd.run(PG:6)
10-05 19:57:59.737 16105 16172 E YouTube : 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.p.run(PG:5)
10-05 19:57:59.737 16105 16172 E YouTube : 	at java.lang.Thread.run(Thread.java:1012)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: FATAL EXCEPTION: main
10-05 19:57:59.741 16105 16105 E AndroidRuntime: Process: app.revanced.android.youtube, PID: 16105
10-05 19:57:59.741 16105 16105 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{app.revanced.android.youtube/com.google.android.apps.youtube.app.application.Shell_HomeActivity}: java.lang.RuntimeException: EntityStore failed loading from .so
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4035)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4201)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8663)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: Caused by: java.lang.RuntimeException: EntityStore failed loading from .so
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ulz.d(PG:4)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ulz.a(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at fce.b(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at fce.<init>(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at fah.h(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.n(PG:9)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.a(PG:31)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at aqkt.a(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehw.x(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehw.u(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.n(PG:12)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.a(PG:31)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at aqla.a(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehw.zV(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehw.dF(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.m(PG:63)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.a(PG:32)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at aqkt.a(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at hox.n(PG:5)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ejj.run(PG:22)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at afat.execute(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at com.google.android.apps.youtube.app.application.Shell_HomeActivity.l(PG:6)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ejj.run(PG:25)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at syy.run(PG:7)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at sza.m(PG:9)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at sza.n(PG:10)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at emv.onCreate(PG:16)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at com.google.android.apps.youtube.app.application.Shell_HomeActivity.onCreate(PG:6)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8290)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8270)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4009)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	... 12 more
10-05 19:57:59.741 16105 16105 E AndroidRuntime: Caused by: dye: libelements.so
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at cal.p(PG:51)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at uhe.bA(PG:7)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at eje.a(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at afyf.e(PG:8)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at afyf.f(PG:5)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at afyf.c(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at nuu.a(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ulv.<init>(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at umd.<init>(PG:6)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ulz.g(PG:4)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ulz.d(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ulz.a(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at fce.b(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at fce.<init>(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at fah.h(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.n(PG:9)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.a(PG:31)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at aqkt.a(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehw.x(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehw.u(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.n(PG:12)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.a(PG:31)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at aqla.a(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehw.zV(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehw.dF(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.m(PG:63)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ehv.a(PG:32)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at aqkt.a(PG:1)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at ejd.run(PG:66)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at syy.run(PG:7)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at nrq.run(PG:5)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at nru.run(PG:23)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at nsc.run(PG:55)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at mwd.run(PG:6)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.p.run(PG:5)
10-05 19:57:59.741 16105 16105 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: Uncaught exception from runnable
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: dye: libelements.so
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at cal.p(PG:51)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at uhe.bA(PG:7)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at eje.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at afyf.e(PG:8)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at afyf.f(PG:5)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at afyf.c(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at nuu.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ulv.<init>(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at umd.<init>(PG:6)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ulz.g(PG:4)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ulz.d(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ulz.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at fce.b(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at fce.<init>(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at fah.h(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.n(PG:9)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.a(PG:31)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at aqkt.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehw.x(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehw.u(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.n(PG:12)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.a(PG:31)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at aqla.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehw.zV(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehw.dF(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.m(PG:63)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.a(PG:32)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at aqkt.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ejd.run(PG:66)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at syy.run(PG:7)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at nrq.run(PG:5)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at nru.run(PG:23)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at nsc.run(PG:55)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at mwd.run(PG:6)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.p.run(PG:5)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at java.lang.Thread.run(Thread.java:1012)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: Uncaught exception from runnable
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: dye: libelements.so
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at cal.p(PG:51)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at uhe.bA(PG:7)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at eje.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at afyf.e(PG:8)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at afyf.f(PG:5)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at afyf.c(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at nuu.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ulv.<init>(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at umd.<init>(PG:6)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ulz.g(PG:4)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ulz.d(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ulz.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at fce.b(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at fce.<init>(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at fah.h(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.n(PG:9)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.a(PG:31)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at aqkt.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehw.x(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehw.u(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.n(PG:12)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.a(PG:31)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at aqla.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehw.zV(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehw.dF(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.m(PG:63)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ehv.a(PG:32)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at aqkt.a(PG:1)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at ejd.run(PG:66)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at syy.run(PG:7)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at nrq.run(PG:5)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at nru.run(PG:23)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at nsc.run(PG:55)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at mwd.run(PG:6)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.p.run(PG:5)
10-05 19:57:59.756 16105 16172 E ErrorLoggingExecutor: 	at java.lang.Thread.run(Thread.java:1012)
```
</details>

**Comment by oSumAtrIX** [comment]
It is very hard to understand your issue, please open a new one with precise explanations. You need Vanced MicroG if you want to use patched YouTube without root.
