### ISSUE TITLE
bug: swipe-controls recursive loop

### ISSUE THREAD

**Issue by Canny1913** [revanced/revanced-patches#1171]
### Type

Error while patching

### Bug description

Sometimes when patching Youtube, swipe-controls patch can get stuck in a recursive loop and fail to apply.

### Steps to reproduce

Attempt to patch YT with all patches enabled.
(Please note that this issue is super random so might be irreproducible)

### Relevant log output

```shell
java.lang.StackOverflowError: stack size 1043KB
at app.revanced.patcher.util.proxy.mutableTypes.encodedValue.MutableStringEncodedValue.(MutableStringEncodedValue.kt:9)
at app.revanced.patcher.util.proxy.mutableTypes.encodedValue.MutableEncodedValue$Companion.toMutable(MutableEncodedValue.kt:25)
at app.revanced.patcher.util.proxy.mutableTypes.encodedValue.MutableArrayEncodedValue$_value$2.invoke(MutableArrayEncodedValue.kt:10)
at app.revanced.patcher.util.proxy.mutableTypes.encodedValue.MutableArrayEncodedValue$_value$2.invoke(MutableArrayEncodedValue.kt:9)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at app.revanced.patcher.util.proxy.mutableTypes.encodedValue.MutableArrayEncodedValue.get_value(MutableArrayEncodedValue.kt:9)
at app.revanced.patcher.util.proxy.mutableTypes.encodedValue.MutableArrayEncodedValue.getValue(MutableArrayEncodedValue.kt:14)
at org.jf.dexlib2.base.value.BaseArrayEncodedValue.hashCode(BaseArrayEncodedValue.java:47)
at org.jf.dexlib2.base.BaseAnnotationElement.hashCode(BaseAnnotationElement.java:43)
at java.util.HashMap.hash(HashMap.java:338)
at java.util.HashMap.put(HashMap.java:611)
at java.util.HashSet.add(HashSet.java:219)
at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
at java.util.LinkedHashSet.(LinkedHashSet.java:169)
at kotlin.collections.CollectionsKt___CollectionsKt.toMutableSet(_Collections.kt:1696)
at app.revanced.patcher.util.proxy.mutableTypes.MutableAnnotation$_elements$2.invoke(MutableAnnotation.kt:10)
at app.revanced.patcher.util.proxy.mutableTypes.MutableAnnotation$_elements$2.invoke(MutableAnnotation.kt:10)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at app.revanced.patcher.util.proxy.mutableTypes.MutableAnnotation.get_elements(MutableAnnotation.kt:10)
at app.revanced.patcher.util.proxy.mutableTypes.MutableAnnotation.getElements(MutableAnnotation.kt:17)
at org.jf.dexlib2.base.BaseAnnotation.hashCode(BaseAnnotation.java:45)
at java.util.HashMap.hash(HashMap.java:338)
at java.util.HashMap.put(HashMap.java:611)
at java.util.HashSet.add(HashSet.java:219)
at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
at java.util.LinkedHashSet.(LinkedHashSet.java:169)
at kotlin.collections.CollectionsKt___CollectionsKt.toMutableSet(_Collections.kt:1696)
at app.revanced.patcher.util.proxy.mutableTypes.MutableMethod$_annotations$2.invoke(MutableMethod.kt:18)
at app.revanced.patcher.util.proxy.mutableTypes.MutableMethod$_annotations$2.invoke(MutableMethod.kt:18)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at app.revanced.patcher.util.proxy.mutableTypes.MutableMethod.get_annotations(MutableMethod.kt:18)
at app.revanced.patcher.util.proxy.mutableTypes.MutableMethod.getAnnotations(MutableMethod.kt:40)
at app.revanced.patches.youtube.interaction.swipecontrols.patch.bytecode.SwipeControlsBytecodePatch$execute$1$1.invoke(SwipeControlsBytecodePatch.kt:60)
at app.revanced.patches.youtube.interaction.swipecontrols.patch.bytecode.SwipeControlsBytecodePatch$execute$1$1.invoke(SwipeControlsBytecodePatch.kt:53)
at app.revanced.extensions.ExtensionsKt.transformMethods(Extensions.kt:50)
at app.revanced.patches.youtube.interaction.swipecontrols.patch.bytecode.SwipeControlsBytecodePatch$execute$1.invoke(SwipeControlsBytecodePatch.kt:53)
at app.revanced.patches.youtube.interaction.swipecontrols.patch.bytecode.SwipeControlsBytecodePatch$execute$1.invoke(SwipeControlsBytecodePatch.kt:51)
at app.revanced.extensions.ExtensionsKt.traverseClassHierarchy(Extensions.kt:38)
at app.revanced.extensions.ExtensionsKt.traverseClassHierarchy(Extensions.kt:40)
// log spam
at app.revanced.extensions.ExtensionsKt.traverseClassHierarchy(Extensions.kt:40)
at app.revanced.extensions.ExtensionsKt.traverseClassHierarchy(Extensions.kt:40)
```

### Solution

Find out why this patch is failing to apply then fix it.

### Additional context

Both general-ads and video-ads patches fail too when this issue occurs, unfortunately i haven't been able to get the stacktrace for those patches.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The stack should never overfloe realistically and I am unsure why it even does that. Infinite recursion can only happen if there is a cycle in the inheritance hierarchy which in terms of polymorphism should be impossible and which would throw a compiler error in JAVA. Thus the method in question should not end in a recursive loop.

**Comment by Sculas** [comment]
I can somehow still comment here while this repo is "disabled". GitHub moment.

**Comment by oSumAtrIX** [comment]
Not reproducible anymore.
