### ISSUE TITLE
bug: Youtube Music Revanced does not work with Android Auto

### ISSUE THREAD

**Issue by hax4dazy** [ReVanced/revanced-patches#1182]
### Type

Error at runtime

### Bug description

Youtube Music Revanced does not work with Android auto. This got "fixed" in ReVanced/revanced-patches-template#2279 but it doesn't seem like its fixed. I'm using the latest pre-release patches as of 5/4/2023 (that's Europe date format).

### Steps to reproduce

Step 1: Patch YouTube music using the latest pre-release patches while including MicroG support
Step 2: Verify that the app works by starting it on your phone 
Step 3: Use the [Android's SDK DHU ](https://developer.android.com/training/cars/testing#test-auto)app to launch Android Auto on your PC
Step 4: Open the YouTube Music Revanced app on android auto 

### Relevant log output

```shell
FATAL EXCEPTION: main
04-05 19:13:10.733 23637 23637 E AndroidRuntime: Process: com.google.android.projection.gearhead:projection, PID: 23637
04-05 19:13:10.733 23637 23637 E AndroidRuntime: java.lang.IllegalArgumentException: No matching component for intent: Intent { cmp=app.revanced.android.apps.youtube.music/com.google.android.apps.youtube.music.mediabrowser.MusicBrowserService (has extras) }
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at isd.a(SourceFile:3)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at ixb.p(SourceFile:1)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at isp.x(SourceFile:9)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at kdf.cp(SourceFile:1)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at fjl.a(SourceFile:13)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at drx.a(SourceFile:29)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at dqg.j(SourceFile:1)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at dqg.e(SourceFile:1)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at fjm.i(SourceFile:39)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at fjm.h(SourceFile:1)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at fkj.c(SourceFile:16)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at nog.onClick(SourceFile:38)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at android.view.View.performClick(View.java:7488)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7464)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at android.view.View.access$3700(View.java:841)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28911)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:233)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:344)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8212)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
04-05 19:13:10.733 23637 23637 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/16256978/230172746-39693b9a-872b-4eb0-af3e-4c84e6de6d42.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Radical4ever** [comment]
Is there been any improvements on this issue, on the part of using the app on car screen directly without having to use the phone?
