### ISSUE TITLE
bug: TikTok fails to patch 

### ISSUE THREAD

**Issue by hehewtf** [revanced/revanced-patches#1252]
### Type

Error while patching

### Bug description

always fails regardless of apk version or patches used 

### Steps to reproduce

download com.zhiliaoapp.musically apk from apkmirror

try to patch

fails 

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
feed-filter failed.
Error:
kotlin.Unit
Applied hide-ads
settings failed.
Error:
kotlin.Unit
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
An error occurred! Aborting
Error:
java.lang.OutOfMemoryError: Failed to allocate a 94902920 byte allocation with 25165824 free bytes and 76MB until OOM, target footprint 482165744, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3670)
	at org.jf.dexlib2.writer.io.MemoryDataStore.growBufferIfNeeded(MemoryDataStore.java:61)
	at org.jf.dexlib2.writer.io.MemoryDataStore.access$000(MemoryDataStore.java:9)
	at org.jf.dexlib2.writer.io.MemoryDataStore$1.write(MemoryDataStore.java:49)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:182)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:354)
	at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:301)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:148)
	at lanchon.multidexlib2.DexIO.lambda$writeMultiDexDirectoryMultiThread$0(DexIO.java:92)
	at lanchon.multidexlib2.DexIO$$ExternalSyntheticLambda0.call(Unknown Source:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

### Additional context

device: Xiaomi 11T pro

MIUI 13 (Android 12)

4+ GB RAM available while patching

revanced updated to latest version

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1248
