### ISSUE TITLE
Error while patching YouTube on non root device

### ISSUE THREAD

**Issue by BetterMobs** [revanced/revanced-patches#1260]
### Type

Error while patching

### Bug description

![Uploading Screenshot_2022-12-14-00-32-23-458_app.revanced.manager.flutter.jpg…]()

### Steps to reproduce

1. Install Vanced MicroG
2. Install ReVanced Manager
3. Open ReVanced Manager
4. Patch Recommended YouTube 17.45.36 version

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied always-autorepeat
Applied amoled
Applied client-spoof
Applied client-spoof-v2
Applied custom-branding-icon-red
Applied custom-branding-name
Applied custom-playback-speed
Applied custom-video-buffer
Applied default-video-speed
Applied disable-auto-captions
Applied disable-auto-player-popup-panels
Applied disable-create-button
Applied disable-startup-shorts-player
Applied enable-wide-searchbar
An error occurred! Aborting
Error:
java.lang.NoSuchMethodError: No static method softCompareTo(Lorg/jf/dexlib2/iface/Method;Lorg/jf/dexlib2/iface/reference/MethodReference;)Z in class Lapp/revanced/patcher/extensions/ExtensionsKt; or its super classes (declaration of 'app.revanced.patcher.extensions.ExtensionsKt' appears in /data/app/~~ZBh6Drv38AF5S2W9bvX0Uw==/app.revanced.manager.flutter-yGbCACAwlT4_EAAZujkRIQ==/base.apk)
	at app.revanced.extensions.MethodExtensions.findMutableMethodOf$revanced_patches(MethodExtensions.kt:37)
	at app.revanced.patches.youtube.extended.extended.bytecode.patch.ExtendedPatch.execute(ExtendedPatch.kt:221)
	at app.revanced.patches.youtube.extended.extended.bytecode.patch.ExtendedPatch.execute(ExtendedPatch.kt:27)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:389)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:42)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:409)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:327)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Screenshots or videos

![Uploading Screenshot_2022-12-14-00-32-23-458_app.revanced.manager.flutter.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You are using a patch bundle which is broken. Reset it in the settings of the ReVanced Manager.
