### ISSUE TITLE
bug: Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/data/ContextKt

### ISSUE THREAD

**Issue by PatrykMis** [revanced/revanced-patches#1277]
### Type

Error while patching

### Bug description

Error shows while building Youtube ReVanced. All components including revanced-integrations are on the latest versions.

### Steps to reproduce

<code>java -jar revanced-cli-2.18.1-all.jar -a youtube_17.45.36.apk -c -i theme -o output.apk -b revanced-patches-2.144.0.jar -m app-release-unsigned.apk</code>

### Relevant log output

```shell
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Merging app-release-unsigned.apk
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
INFO: always-autorepeat succeeded
INFO: client-spoof succeeded
INFO: comments succeeded
INFO: custom-branding succeeded
INFO: custom-video-buffer succeeded
INFO: custom-video-speed succeeded
INFO: debugging succeeded
INFO: disable-auto-captions succeeded
INFO: disable-auto-player-popup-panels succeeded
INFO: disable-fullscreen-panels succeeded
INFO: disable-startup-shorts-player succeeded
INFO: disable-zoom-haptics succeeded
INFO: downloads succeeded
Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/data/ContextKt
        at app.revanced.patches.youtube.layout.widesearchbar.patch.WideSearchbarPatch$Companion.walkMutable(WideSearchbarPatch.kt:48)
        at app.revanced.patches.youtube.layout.widesearchbar.patch.WideSearchbarPatch.execute(WideSearchbarPatch.kt:89)
        at app.revanced.patches.youtube.layout.widesearchbar.patch.WideSearchbarPatch.execute(WideSearchbarPatch.kt:27)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:425)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.data.ContextKt
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 20 more

```
```


### Screenshots or videos

_No response_

### Solution

_No response_

### Additional context

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Cypher-Emm** [comment]
Facing the same error.
If you exclude wide search bar patch then minimized playback will fail

**Comment by PatrykMis** [comment]
Exactly

**Comment by oSumAtrIX** [comment]
This is not a problem with patches. A duplicate issue is open in the CLI repository.
