### ISSUE TITLE
bug: YouTube `return-youtube-dislike` patch failed

### ISSUE THREAD

**Issue by SCP-017** [revanced/revanced-patches#1306]
### Type

Error while patching

### Bug description

SEVERE: `return-youtube-dislike` failed

### Steps to reproduce

1. Download the latest CLI, Patches, and Integrations.
2. Patch the YouTube app `v.17.49.37`.

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Merging integrations.apk 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping premium-heading: Manually excluded 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: always-autorepeat succeeded 
INFO: client-spoof succeeded 
INFO: comments succeeded 
INFO: custom-branding succeeded 
INFO: custom-video-buffer succeeded 
INFO: custom-video-speed succeeded 
INFO: debugging succeeded 
INFO: disable-auto-captions succeeded 
INFO: disable-auto-player-popup-panels succeeded 
INFO: disable-fullscreen-panels succeeded 
INFO: disable-startup-shorts-player succeeded 
INFO: disable-zoom-haptics succeeded 
INFO: downloads succeeded 
INFO: enable-wide-searchbar succeeded 
INFO: general-ads succeeded 
INFO: hdr-auto-brightness succeeded 
INFO: hide-album-cards succeeded 
INFO: hide-artist-card succeeded 
INFO: hide-autoplay-button succeeded 
INFO: hide-captions-button succeeded 
INFO: hide-cast-button succeeded 
INFO: hide-create-button succeeded 
INFO: hide-crowdfunding-box succeeded 
INFO: hide-email-address succeeded 
INFO: hide-endscreen-cards succeeded 
INFO: hide-info-cards succeeded 
INFO: hide-my-mix succeeded 
INFO: hide-shorts-button succeeded 
INFO: hide-time-and-seekbar succeeded 
INFO: hide-video-buttons succeeded 
INFO: hide-watch-in-vr succeeded 
INFO: hide-watermark succeeded 
INFO: microg-support succeeded 
INFO: minimized-playback succeeded 
INFO: old-quality-layout succeeded 
INFO: open-links-directly succeeded 
INFO: remember-video-quality succeeded 
INFO: remove-player-button-background succeeded 
SEVERE: return-youtube-dislike failed: 
app.revanced.patcher.patch.PatchResultError
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:429)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
	at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:55)
	at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:24)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:425)
	... 16 more
INFO: seekbar-tapping succeeded 
INFO: settings succeeded 
INFO: sponsorblock succeeded 
INFO: swipe-controls succeeded 
INFO: tablet-mini-player succeeded 
INFO: theme succeeded 
INFO: video-ads succeeded 
INFO: Compiling resources 
INFO: Writing modified dex files
```

### Screenshots or videos

![Screenshot_2022-12-19-09-26-42-479_com vivaldi browser](https://user-images.githubusercontent.com/112224835/208331061-a32c9b44-bd4f-4508-8050-fd39d0bc5f7d.jpg)

### Solution

None.

### Additional context

None.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You need to be on the latest commit for the CLI to use the latest changes required for the patches.
