### ISSUE TITLE
bug: SEVERE: return-youtube-dislike failed

### ISSUE THREAD

**Issue by AMSAMSAMSAMS** [revanced/revanced-patches#1307]
### Type

Error while patching

### Bug description

SEVERE: return-youtube-dislike failed: 
app.revanced.patcher.patch.PatchResultError

### Steps to reproduce

CLI                   2.18.2
Patches:          2.146.0
Integrations:  0.84.1
YouTube:         17.49.37

### Relevant log output

```shell
SEVERE: return-youtube-dislike failed: 
app.revanced.patcher.patch.PatchResultError
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:429)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
	at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:55)
	at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:24)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:425)
	... 16 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1306
