### ISSUE TITLE
bug: YouTube return dislike patch does not work.

### ISSUE THREAD

**Issue by KoleckOLP** [revanced/revanced-patches#1314]
### Type

Error while patching

### Bug description

return youtube dislike patch does not work, fails while patching.

### Steps to reproduce

I am using revanced-builder-win.exe version 3.7.0
I choose all my patches including return youtube dislike and the patch fails,
see the log

### Relevant log output

```shell
[builder] INFO: Reading dex files
[builder] INFO: Decoding AndroidManifest.xml only, because resources are not needed
[builder] INFO: Merging C:\revanced\revanced-integrations-v0.84.1.apk
[builder] INFO: Skipping always-autorepeat: Manually excluded
[builder] INFO: Skipping comments: Manually excluded
[builder] INFO: Skipping custom-video-buffer: Manually excluded
[builder] INFO: Skipping custom-video-speed: Manually excluded
[builder] INFO: Skipping debugging: Manually excluded
[builder] INFO: Skipping disable-auto-captions: Manually excluded
[builder] INFO: Skipping disable-auto-player-popup-panels: Manually excluded
[builder] INFO: Skipping disable-fullscreen-panels: Manually excluded
[builder] INFO: Skipping disable-startup-shorts-player: Manually excluded
[builder] INFO: Skipping disable-zoom-haptics: Manually excluded
[builder] INFO: Skipping enable-wide-searchbar: Manually excluded
[builder] INFO: Skipping hide-album-cards: Manually excluded
[builder] INFO: Skipping hide-artist-card: Manually excluded
[builder] INFO: Skipping hide-autoplay-button: Manually excluded INFO: Skipping hide-captions-button: Manually excluded INFO: Skipping hide-cast-button: Manually excluded
[builder] INFO: Skipping hide-create-button: Manually excluded INFO: Skipping hide-crowdfunding-box: Manually excluded INFO: Skipping hide-email-address: Manually excluded INFO: Skipping hide-endscreen-cards: Manually excluded INFO: Skipping hide-info-cards: Manually excluded INFO: Skipping hide-my-mix: Manually excluded INFO: Skipping hide-shorts-button: Manually excluded INFO: Skipping hide-time-and-seekbar: Manually excluded INFO: Skipping hide-video-buttons: Manually excluded INFO: Skipping hide-watch-in-vr: Manually excluded INFO: Skipping hide-watermark: Manually excluded INFO: Skipping predictive-back-gesture: Manually excluded INFO: Skipping premium-heading: Manually excluded INFO: Skipping remove-player-button-background: Manually excluded INFO: Skipping swipe-controls: Manually excluded INFO: Skipping tablet-mini-player: Manually excluded
[builder] INFO: Deleting existing resource cache directory
[builder] SEVERE: Failed to delete existing resource cache directory
[builder] INFO: Decoding resources
[builder] INFO: client-spoof succeeded
[builder] INFO: custom-branding succeeded
[builder] INFO: downloads succeeded
[builder] INFO: general-ads succeeded
[builder] INFO: hdr-auto-brightness succeeded
[builder] INFO: microg-support succeeded
[builder] INFO: minimized-playback succeeded
[builder] INFO: old-quality-layout succeeded
[builder] INFO: open-links-directly succeeded
[builder] INFO: remember-video-quality succeeded
[builder] SEVERE: return-youtube-dislike failed:
[builder] app.revanced.patcher.patch.PatchResultError
[builder] at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:429) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
[builder] at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.lang.NullPointerException at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:55) at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:24) at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:425) ... 16 more
[builder] INFO: seekbar-tapping succeeded
[builder] INFO: settings succeeded
[builder] INFO: sponsorblock succeeded
[builder] INFO: theme succeeded
[builder] INFO: video-ads succeeded
[builder] INFO: Compiling resources
[builder] INFO: Writing modified dex files
[builder] INFO: Aligning com.google.android.youtube.apk to revanced_aligned.apk
[builder] INFO: Signing revanced_aligned.apk to revanced_signed.apk
[builder] INFO: Found existing keystore: revanced.keystore
[builder] INFO: Copying revanced_signed.apk to revanced.apk
[builder] INFO: Finished
[builder] ReVanced has been built! Please transfer over revanced/ReVanced-YouTube-v17.49.37-cli_v2.18.2-patches_v2.146.0.apk and if you are using YT/YTM, revanced/microg.apk and install them!
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Unofficial tool.

**Comment by AMSAMSAMSAMS** [comment]
> Unofficial tool.

Then please release the latest CLI that support the latest patched please...

**Comment by oSumAtrIX** [comment]
Not possible without a releasing commit via semantic release
