### ISSUE TITLE
bug: TikTok patching crashes when compiling

### ISSUE THREAD

**Issue by MichalKormanik** [revanced/revanced-patches#1327]
### Type

Error while patching

### Bug description

I've got error while compiling TikTok app. Exported log in description. Patching TikTok 27.4.5
[revanced-manager_patcher_20221220193603625749.log](https://github.com/revanced/revanced-patches/files/10271261/revanced-manager_patcher_20221220193603625749.log)

### Steps to reproduce

1. Download TikTok 27.4.5 from APK mirror
2. Patch everything (or except failed feed-filter)
3. Crash

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied disable-login-requirement
Applied downloads
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Applied predictive-back-gesture
Applied settings
Applied show-seekbar
Applied sim-spoof
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~4bqF8nkR1TUZulERqsFrgA==/app.revanced.manager.flutter-ZKPAubpk6J4t42fB_mZ7Tg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EMWNQP/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EMWNQP/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:235)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~4bqF8nkR1TUZulERqsFrgA==/app.revanced.manager.flutter-ZKPAubpk6J4t42fB_mZ7Tg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EMWNQP/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-EMWNQP/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Looks like you are using an Armv7 device, which is not supported as mentioned in the ReVanced Manager.

**Comment by MichalKormanik** [comment]
But then all the other patches would fail. Every patched app I've tried is working perfectly fine except this.

**Comment by oSumAtrIX** [comment]
Exclude patches until the error is gone.

**Comment by MichalKormanik** [comment]
Does not work either. Few months ago it worked, don't know the reason for change.

**Comment by oSumAtrIX** [comment]
Try the patches and the Manager where it last worked.

**Comment by MichalKormanik** [comment]
Does not work either. Thanks for trying to help! Guess will have to try after som updates.
