### ISSUE TITLE
bug: <Return Youtube Dislike Don't Work>

### ISSUE THREAD

**Issue by Parsa307** [revanced/revanced-patches#1382]
### Type

Error while patching

### Bug description

Return Youtube Dislike Failed

### Steps to reproduce

i can't explain

### Relevant log output

```shell
i don't have log
```

### Solution

I Have No Solution

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please fill out all of the requested information in this issue properly.

**Comment by Sappurit** [comment]
I faced the same problem with 
```
revanced-cli-2.18.2.jar
revanced-integrations-0.87.0.apk
revanced-patches-2.147.0.jar
```

Command:
`java -jar revanced-cli-2.18.2.jar -m revanced-integrations-0.87.0.apk -b revanced-patches-2.147.0.jar --keystore=revanced.keystore --options=options.toml -c -t %temp%/ReVanced-Cache -a Build/17.49.37/com.google.android.youtube_17.49.37.apk -o Build/17.49.37/app.revanced.andr
oid.youtube_17.49.37.apk.1`





```
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:429)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:55)
        at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:24)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:425)
        ... 16 more
```

**Comment by oSumAtrIX** [comment]
@Sappurit #1333
