### ISSUE TITLE
bug: SEVERE: `hide-views-stats` failed

### ISSUE THREAD

**Issue by SCP-017** [revanced/revanced-patches#1394]
### Type

Error while patching

### Bug description

The `hide-views-stats` failed while patching.

### Steps to reproduce

1. Download the latest CLI, Patches, and Integrations.
2. Patch the Twitter app.

### Relevant log output

```shell
INFO: dynamic-color succeeded 
SEVERE: hide-views-stats failed: 
app.revanced.patcher.patch.PatchResultError: 'hide-views-stats' depends on 'HideViewsBytecodePatch' but the following error was raised: java.lang.NullPointerException
	at app.revanced.patches.twitter.layout.hideviews.patch.HideViewsBytecodePatch$transformMethodAtPattern$1.invoke(HideViewsBytecodePatch.kt:100)
INFO: monochrome-icon succeeded 
	at app.revanced.patches.twitter.layout.hideviews.patch.HideViewsBytecodePatch$transformMethodAtPattern$1.invoke(HideViewsBytecodePatch.kt:97)
	at app.revanced.patches.twitter.layout.hideviews.patch.HideViewsBytecodePatch.transformMethod(HideViewsBytecodePatch.kt:108)
	at app.revanced.patches.twitter.layout.hideviews.patch.HideViewsBytecodePatch.transformMethodAtPattern(HideViewsBytecodePatch.kt:97)
	at app.revanced.patches.twitter.layout.hideviews.patch.HideViewsBytecodePatch.removeViewsFromTimeline(HideViewsBytecodePatch.kt:46)
	at app.revanced.patches.twitter.layout.hideviews.patch.HideViewsBytecodePatch.execute(HideViewsBytecodePatch.kt:28)
	at app.revanced.patches.twitter.layout.hideviews.patch.HideViewsBytecodePatch.execute(HideViewsBytecodePatch.kt:19)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:426)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:399)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:446)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:162)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:402)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:446)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:162)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: timeline-ads succeeded 
INFO: Compiling resources
```

### Screenshots or videos

![Screenshot_2022-12-30-13-00-03-596_org.bromite.bromite.jpeg](https://add.pics/images/2022/12/30/Screenshot_2022-12-30-13-00-03-596_org.bromite.bromite.jpeg)

### Solution

None

### Additional context

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Are you using the latest version of the CLI?

**Comment by SCP-017** [comment]
@oSumAtrIX 

I'm using the CLI of inotia00 because the `return-youtube-dislike` still doesn't work for me even I downloaded the latest CLI.

**Comment by oSumAtrIX** [comment]
The fork is not from us.
