### ISSUE TITLE
bug: return-youtube-dislike build error

### ISSUE THREAD

**Issue by 3v01ut10n** [revanced/revanced-patches#1395]
### Type

Error while patching

### Bug description

Build error occurs:

```
SEVERE: return-youtube-dislike failed: 
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:429)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:445)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:55)
        at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:24)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:425)
        ... 16 more
```

### Steps to reproduce

```
java -jar revanced-cli-2.18.2-all.jar \                                   ✔ 
-a youtube_17.49.37.apk \
-c \
-o revanced_2.149.0.apk \
-b revanced-patches-2.149.0.jar \
-m app-release-unsigned.apk \
-e always-autorepeat \
-e comments \
-e debugging \
-e downloads \
-e disable-auto-player-popup-panels \
-e disable-fullscreen-panels \
-e disable-zoom-haptics \
-e hdr-auto-brightness \
-e hide-time-and-seekbar \
-e hide-captions-button \
-e hide-video-buttons \
-e hide-endscreen-cards \
-e hide-autoplay-button \
-e remove-player-button-background \
-e theme \
-e swipe-controls
```

### Relevant log output

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1333
