### ISSUE TITLE
bug: (messenger/disable-switching-emoji-to-sticker) patch not working due to changes

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#14]
### Bug description

This patch no longer works as in it needs to be updated due to server sided changes (possible a/b testing). Now the default behavior when you tap the emoji icon (while typing or not) is to automatically switch to the star tab on the far left (the one circled below), not the sticker tab.

![Screenshot_2023-12-12-05-17-19-465-edit_com facebook orca-2](https://github.com/ReVanced/revanced-patches/assets/107653639/d2d10423-5577-4af1-8efe-60b0b67104f6)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by ABCPascal** [comment]
Yeah for anybody who wants a log here it is:

```
- Device Info
ReVanced Manager: 1.18.0
Model: motorola edge 30 ultra
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.facebook.orca v440.0.0.0.270 (Suggested: Any)
Patches version: v3.2.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Executing patches
Disable switching emoji to sticker failed: app.revanced.patcher.patch.PatchException: Failed to resolve SwitchMessangeInputEmojiButtonFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
	at app.revanced.patches.messenger.inputfield.patch.DisableSwitchingEmojiToStickerPatch.execute(DisableSwitchingEmojiToStickerPatch.kt:34)
	at app.revanced.patches.messenger.inputfield.patch.DisableSwitchingEmojiToStickerPatch.execute(DisableSwitchingEmojiToStickerPatch.kt:13)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:341)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:340)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Applied 2 patches
Compiling patched dex files
Compiled 8 dex files
Signing APK
Patched APK
```

**Comment by Wojtaz0w** [comment]
Same problem on 440 stable

```- Device Info
ReVanced Manager: 1.18.0
Model: Redmi 9
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.facebook.orca v440.0.0.30.352 (Suggested: Any)
Patches version: v3.2.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Executing patches
Disable switching emoji to sticker failed: app.revanced.patcher.patch.PatchException: Failed to resolve SwitchMessangeInputEmojiButtonFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
	at app.revanced.patches.messenger.inputfield.patch.DisableSwitchingEmojiToStickerPatch.execute(DisableSwitchingEmojiToStickerPatch.kt:34)
	at app.revanced.patches.messenger.inputfield.patch.DisableSwitchingEmojiToStickerPatch.execute(DisableSwitchingEmojiToStickerPatch.kt:13)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:341)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:340)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Applied 2 patches
Compiling patched dex files
Compiled 10 dex files
Signing APK
Patched APK```

**Comment by n1cKz1** [comment]
Even if the patch applied it would still be of no use because of the new behavior described above

**Comment by kazimmt** [comment]
After the A/B testing is over, I guess it's working again on the patched Messenger.
Could you please take a look at yours?

**Comment by n1cKz1** [comment]
> After the A/B testing is over, I guess it's working again on the patched Messenger. Could you please take a look at yours?

The patch fails to apply on recent versions of Messenger

**Comment by kazimmt** [comment]
> The patch fails to apply on recent versions of Messenger

Patch fails on version over 440
But it still works without issues in 439

**Comment by n1cKz1** [comment]
That version will soon completely stop working anyway due to update prompts

**Comment by kazimmt** [comment]
That's a different issue i guess.
Not relevant with this issue!

**Comment by n1cKz1** [comment]
Closing in favor of #3090
