### ISSUE TITLE
bug: ``Predictive Back Gesture`` Broken on Tiktok

### ISSUE THREAD

**Issue by 2Epik4u** [revanced/revanced-patches#1421]
### Type

Error while patching

### Bug description

Found the bug by using all patches and crashing, then removng predictive back gesture makes the patch work again.

### Steps to reproduce

Download tiktok v27.2.5 from apkmirror
Patch tiktok with 1 patch
Predictive back gesture

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Deleting existing resource cache directory
Decoding resources
Applied predictive-back-gesture
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~RVwbmK0JvT2Dyx_kUFUYkA==/app.revanced.manager.flutter-7NCmheYUCHoVFaPFs2WiFQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BUFCMO/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BUFCMO/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:235)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~RVwbmK0JvT2Dyx_kUFUYkA==/app.revanced.manager.flutter-7NCmheYUCHoVFaPFs2WiFQ==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BUFCMO/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-BUFCMO/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371)
	... 6 more
```

### Solution

Patch tiktok without the Predictive  back gesture

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Try with another patch

**Comment by BitGrub** [comment]
Can't apply ANY patch(es) on any version (27.0.X - 27.6.X). Sometimes I get the same error as in the bug report, most times I get:
"Failed to apply settings: 'settings' did not succeed previously." for every patch and then it aborts

**Comment by BitGrub** [comment]
It's not off topic if all patches produce the same error as described..

**Comment by oSumAtrIX** [comment]
This issue is about a specific patch making your issue off topic to the current one.

**Comment by oSumAtrIX** [comment]
Patch is not explicitly supporting the app.
