### ISSUE TITLE
bug: Can't patched twitter 9.70.0-release0

### ISSUE THREAD

**Issue by daywalk3r666** [revanced/revanced-patches#1430]
### Type

Error while patching

### Bug description

Trying to patch the last twitter release

### Steps to reproduce

Download the last twitter apk from apkmirror.
Run the patcher

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Merging ./revanced-integrations-v0.91.2.apk 
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.jf.dexlib2.util.DexUtil.verifyDexHeader(DexUtil.java:91)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:53)
	at lanchon.multidexlib2.RawDexIO.readRawDexFile(RawDexIO.java:43)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:66)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:51)
	at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:42)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:36)
	at app.revanced.patcher.Patcher.addFiles(Patcher.kt:85)
	at app.revanced.utils.patcher.PatcherKt.mergeFiles(Patcher.kt:72)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:16)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)



Variant: root
Arch: arm64
App: Twitter-9.70.0-release.0.apk
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The integrations apk file you have there does not exist with the name you gave it. Review it.
