### ISSUE TITLE
bug: Twitter `hide-views-stats` patch failed in Revanced Manager

### ISSUE THREAD

**Issue by someone5678** [revanced/revanced-patches#1445]
### Type

Error while patching

### Bug description

`hide-views-stats` patch failed due to NullPointerException in Revanced Manager `0.0.52` with Twitter `9.70.0-release.0` .

*(Used official Twitter package is not split apks, Which you can find in [APKMirror](https://www.apkmirror.com/apk/twitter-inc/twitter/twitter-9-70-0-release-0-release/twitter-9-70-0-release-0-2-android-apk-download/))

### Steps to reproduce

Step 1. Select `hide-views-stats` patch targeted official Twitter `9.70.0-release.0` with official Revanced Manager `0.0.52`.

Step 2. Patch it.

Step 3 (Additional). Delete keystore/temp files/logs with manager's settings menu
 and Uninstall & Re-Install Revanced Manager and try again Step 1~2.

Result: Patch failed with NullPointerException.

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Deleting existing resource cache directory
Decoding resources
Applied dynamic-color
Failed to apply hide-views-stats: 'hide-views-stats' depends on 'HideViewsBytecodePatch' but the following error was raised: java.lang.NullPointerException
	at app.revanced.patches.twitter.layout.hideviews.patch.HideViewsBytecodePatch.transformMethod(HideViewsBytecodePatch.kt:106)
	at app.revanced.patches.twitter.layout.hideviews.patch.HideViewsBytecodePatch.removeViewDelegateBinderSubscription(HideViewsBytecodePatch.kt:88)
	at app.revanced.patches.twitter.layout.hideviews.patch.HideViewsBytecodePatch.execute(HideViewsBytecodePatch.kt:31)
	at app.revanced.patches.twitter.layout.hideviews.patch.HideViewsBytecodePatch.execute(HideViewsBytecodePatch.kt:19)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:426)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:399)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:446)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:327)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Applied monochrome-icon
Applied predictive-back-gesture
Applied timeline-ads
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
```

### Additional context

Unlike https://github.com/revanced/revanced-patches/issues/1394 , I used official Revanced Manager.
But the result is same as above issue.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1394

**Comment by someone5678** [comment]
> #1394

Yes. I saw that issue.
In this case, can you open again #1394 ?
Because issue is not fixed yet.

**Comment by someone5678** [comment]
@oSumAtrIX 

You just linked the same issue that I mentioned which you also closing it with the comment "The fork is not from us."

This issue is, however, reproduced with official Revanced Manager, Patches, Integrations and Patcher.
Not like the issue that you mentioned.

It's a bit confusing that you just closing issue without any context.

**Comment by oSumAtrIX** [comment]
The issue is unrelated to the CLI and Manager, but with the patches making it a dupe of the other. I'll open this one as it supersedes the other.

**Comment by Franckyi** [comment]
Patch author here, it seems to be working fine with 9.71.0.

One of the fingerprints fails to resolve for 9.70.0, namely [TweetStatsViewDelegateBinderFingerprint](https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/twitter/layout/hideviews/fingerprints/TweetStatsViewDelegateBinderFingerprint.kt). I would like to make it more stable so it doesn't break again but I don't really know how to proceed.

More technical details on the issue: the patched method is FocalTweetStatsViewDelegateBinder#b. It seems that the int constants used in the method change between versions, and in 9.70.0 one of these constants is used twice so I suppose that's why there's a CONST_16 opcode that disappears.

<details>
  <summary>Decompiled/Smali code screenshots to show what I mean. Decompiled code is the full method I'm fingerprinting, and Smali code is the exact part of the method that I'm fingerprinting with the CONST_16 opcode being here in 9.71.0 but not in 9.70.0.</summary>

In 9.70.0:
![image](https://user-images.githubusercontent.com/17572738/212282416-8637b07f-56b8-4361-8b3b-dc0cfcb8b751.png)
![image](https://user-images.githubusercontent.com/17572738/212296750-213d1175-d3a8-4b7f-a61a-5ba57d8ed21a.png)

In 9.71.0:
![image](https://user-images.githubusercontent.com/17572738/212294700-06e16dd1-711b-4f63-ba43-17a3a4db5e1e.png)
![image](https://user-images.githubusercontent.com/17572738/212296876-97d5f74a-e9ed-4d7f-b380-4779d77502a7.png)

</details>

**Comment by oSumAtrIX** [comment]
There are multiple ways how to overcome this:

- Use the fuzzy scan annotation `@FuzzyPatternScanMethod`
- Use a smaller fingerprint or fingerprint different traits of the method
- Fingerprint another method; find this one through a reference from the other via `MethodWalker`

Depending on how this method changes over versions you should choose either. If the method changes a lot, you should fingerprint a different method. If the pattern only randomly changes once, use the `@FuzzyPatternScanMethod` annotation or adjust your fingerprint so it is smaller.

**Comment by ILoveOpenSourceApplications** [comment]
Fixed for now with #1646
