### ISSUE TITLE
TikTok not patching with resource patches enabled

### ISSUE THREAD

**Issue by TheJeterLP** [revanced/revanced-patches#1487]
### Type

Error while patching

### Bug description

When resource patches are selected,
Patching fails with latest patches and recommended TikTok version

### Steps to reproduce

Download TikTok v27.8.3 and try to patch with patches 2.154.0

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied disable-login-requirement
Failed to apply downloads: 'downloads' depends on 'settings' but the following error was raised: java.lang.NullPointerException
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.findOptionsOnClickIndex(SettingsPatch.kt:91)
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.execute(SettingsPatch.kt:47)
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.execute(SettingsPatch.kt:30)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:426)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:399)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:44)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:446)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:327)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Failed to apply feed-filter: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Applied predictive-back-gesture
Failed to apply settings: 'settings' did not succeed previously
Applied show-seekbar
Failed to apply sim-spoof: 'sim-spoof' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Xj_1uidh1HbRkFnfFtdHtQ==/app.revanced.manager.flutter-2XHAQ45UkTdj2J0CF6mbwA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZMWSFV/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZMWSFV/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:375)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:629)
	at app.revanced.patcher.Patcher.save(Patcher.kt:235)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:218)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~Xj_1uidh1HbRkFnfFtdHtQ==/app.revanced.manager.flutter-2XHAQ45UkTdj2J0CF6mbwA==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZMWSFV/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZMWSFV/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:371)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
RE: https://github.com/revanced/revanced-patches/pull/1483/files#diff-846b189342c6a0b23e67ccef98b17d238157397e1cccd92f303d2ee42bc97957L9-L25

**Comment by d4rkk3y** [comment]
In the log, I can see "Decoding resources". But all tiktok patch do not use ResourcePatch, maybe it is the manager problem. In addition, tiktok patch will not work until the patcher release the new version because of https://github.com/revanced/revanced-patcher/pull/150

**Comment by TheJeterLP** [comment]
It says decoding resources because it's merging the integrations.

**Comment by d4rkk3y** [comment]
> It says decoding resources because it's merging the integrations.

Afaik, currently merging integrations doesn't need decoding resources. It happen because you include predictive-back-gesture patch.

**Comment by TheJeterLP** [comment]
> > It says decoding resources because it's merging the integrations.
> 
> Afaik, currently merging integrations doesn't need decoding resources. It happen because you include predictive-back-gesture patch.

Yes you're right, my bad. Disabling patches with resource patching fixed it.

**Comment by oSumAtrIX** [comment]
Still odd, why would the `settings` patch fail just because of the `predictive-back-gesture` patch, those shouldn't conflict.

**Comment by TheJeterLP** [comment]
> Still odd, why would the `settings` patch fail just because of the `predictive-back-gesture` patch, those shouldn't conflict.

That's true tho. I'll reopen then

**Comment by oSumAtrIX** [comment]
#1421
