### ISSUE TITLE
Tiktok sim-spoof patch NullPointerException

### ISSUE THREAD

**Issue by abra1l** [revanced/revanced-patches#1491]
### Type

Error while patching

### Bug description

When trying to patch tiktok 27.8.3 getting this error

### Steps to reproduce

I'm Using Genymotion Android 11 ARM version

### Relevant log output

```shell
On the picture
```

### Screenshots or videos

<img width="421" alt="image" src="https://user-images.githubusercontent.com/35950371/212498581-605f8c18-87eb-439f-8595-618e90c3cfd4.png">

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by d4rkk3y** [comment]
Could you try patching with recanced-cli?

**Comment by leehwongxing** [comment]
Im getting kinda the same OutOfMemory error as 256mb alloc seems not enough, a part of catlog: 
`
------ beginning of system
01-26 20:26:09.905 11023 11023 W ActivityThread: registerApplicationScoutThread result:true
01-26 20:26:10.233 11023 11023 I ForceDarkHelper: mForceDarkOrigin true
01-26 20:26:10.273 11023 11023 I ContentProviderMonitor: PerfMonitor installContentProviders : before publish content providers
01-26 20:26:10.536 11023 11023 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=254ms latency=393ms running=120ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.LaunchActivityItem] lifecycleRequest=android.app.servertransaction.ResumeActivityItem } historyMsgCount=2 (msgIndex=2 wall=375ms seq=2 running=281ms runnable=35ms io=28ms late=33ms h=android.app.ActivityThread$H w=110)
01-26 20:26:10.537 11023 11023 W Looper  : PerfMonitor looperActivity : package=app.revanced.manager.flutter/.MainActivity time=0ms latency=645ms running=1ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=3 (msgIndex=2 wall=375ms seq=2 running=281ms runnable=35ms io=28ms late=33ms h=android.app.ActivityThread$H w=110) (msgIndex=3 wall=254ms seq=3 running=120ms runnable=11ms io=15ms late=393ms h=android.app.ActivityThread$H w=159)
01-26 20:26:12.671 11023 11023 W Looper  : PerfMonitor doFrame : time=22ms vsyncFrame=4804 latency=599ms procState=2 historyMsgCount=2 (msgIndex=1 wall=602ms seq=123 running=57ms io=8ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0)
01-26 20:26:20.243 11023 11023 I Timeline: Timeline: Activity_launch_request time:164069
--------- beginning of main
01-26 20:26:24.821 11023 11844 I chatty  : uid=10339(app.revanced.manager.flutter) expire 3 lines
01-26 20:26:24.846 11023 11276 I chatty  : uid=10339(app.revanced.manager.flutter) expire 21 lines
01-26 20:26:24.876 11023 11023 I chatty  : uid=10339(app.revanced.manager.flutter) expire 26 lines
01-26 20:26:26.150 11023 11023 W PackageParsing: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_27.8.3-2022708030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com(1).apk Binary XML file line #204
01-26 20:26:26.151 11023 11023 W PackageParsing: Unknown element under <manifest>: meta-data at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_27.8.3-2022708030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com(1).apk Binary XML file line #223
01-26 20:26:26.196 11023 11023 W PackageParsing: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_27.8.3-2022708030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com(1).apk Binary XML file line #1594
01-26 20:26:26.196 11023 11023 W PackageParsing: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_27.8.3-2022708030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com(1).apk Binary XML file line #1595
01-26 20:26:26.196 11023 11023 W PackageParsing: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_27.8.3-2022708030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com(1).apk Binary XML file line #1596
01-26 20:26:26.196 11023 11023 W PackageParsing: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_27.8.3-2022708030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com(1).apk Binary XML file line #1597
01-26 20:26:26.196 11023 11023 W PackageParsing: Unknown element under <application>: uses-native-library at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_27.8.3-2022708030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com(1).apk Binary XML file line #1598
01-26 20:26:26.207 11023 11023 W PackageParsing: Unknown element under <application>: enable-feature at /data/user/0/app.revanced.manager.flutter/cache/file_picker/com.zhiliaoapp.musically_27.8.3-2022708030_minAPI21(arm64-v8a,armeabi-v7a)(nodpi)_apkmirror.com(1).apk Binary XML file line #1982
01-26 20:26:35.913 11023 11023 I chatty  : uid=10339(app.revanced.manager.flutter) expire 10 lines
01-26 20:26:47.342 11023 11023 I chatty  : uid=10339(app.revanced.manager.flutter) expire 10 lines
01-26 20:26:58.488 11023 11023 I chatty  : uid=10339(app.revanced.manager.flutter) expire 12 lines
01-26 20:27:07.050 11955 11955 I chatty  : uid=10339(app.revanced.manager.flutter) /system/bin/sh expire 7 lines
01-26 20:27:10.274 12225 12225 I chatty  : uid=10339(app.revanced.manager.flutter) /system/bin/sh expire 8 lines
01-26 20:27:11.019 11023 11037 I chatty  : uid=10339(app.revanced.manager.flutter) expire 10 lines
01-26 20:27:11.342 12445 12445 I chatty  : uid=10339(app.revanced.manager.flutter) /system/bin/sh expire 1 line
01-26 20:27:11.378 12459 12459 I chatty  : uid=10339(app.revanced.manager.flutter) /system/bin/sh expire 1 line
01-26 20:27:11.446 12473 12473 I chatty  : uid=10339(app.revanced.manager.flutter) /system/bin/sh expire 1 line
01-26 20:27:11.476 11023 11023 W Looper  : PerfMonitor longMsg : seq=446 plan=20:27:10.253 late=0ms wall=1220ms running=192ms runnable=12ms h=android.os.Handler c=io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0 procState=2
01-26 20:27:13.485 11023 11035 I chatty  : uid=10339(app.revanced.manager.flutter) expire 30 lines
01-26 20:27:17.492 11023 12487 I chatty  : uid=10339(app.revanced.manager.flutter) expire 102 lines
01-26 20:27:18.926 11023 11846 I chatty  : uid=10339(app.revanced.manager.flutter) expire 22 lines
01-26 20:27:21.950 11023 11023 I chatty  : uid=10339(app.revanced.manager.flutter) expire 14 lines
01-26 20:27:31.950 11023 11197 I chatty  : uid=10339(app.revanced.manager.flutter) expire 18 lines
01-26 20:27:32.867 11023 12487 I chatty  : uid=10339(app.revanced.manager.flutter) expire 133 lines
01-26 20:27:34.124 11023 11035 I chatty  : uid=10339(app.revanced.manager.flutter) expire 21 lines
01-26 20:27:34.451 11023 11200 I chatty  : uid=10339(app.revanced.manager.flutter) expire 10 lines
01-26 20:27:35.404 11023 11846 I chatty  : uid=10339(app.revanced.manager.flutter) expire 20 lines
01-26 20:27:40.245 11023 11037 I chatty  : uid=10339(app.revanced.manager.flutter) expire 42 lines
01-26 20:27:42.621 11023 11197 I chatty  : uid=10339(app.revanced.manager.flutter) expire 12 lines
01-26 20:27:44.630 11023 11035 I chatty  : uid=10339(app.revanced.manager.flutter) expire 17 lines
01-26 20:27:45.811 11023 12487 I chatty  : uid=10339(app.revanced.manager.flutter) expire 91 lines
01-26 20:27:47.634 11023 11846 I chatty  : uid=10339(app.revanced.manager.flutter) expire 25 lines
01-26 20:27:50.994 11023 11023 I chatty  : uid=10339(app.revanced.manager.flutter) expire 96 lines
01-26 20:27:52.968 11023 11200 I chatty  : uid=10339(app.revanced.manager.flutter) expire 35 lines
01-26 20:27:59.188 11023 11034 I chatty  : uid=10339(app.revanced.manager.flutter) expire 27 lines
01-26 20:27:59.194 11023 11846 I chatty  : uid=10339(app.revanced.manager.flutter) expire 23 lines
01-26 20:27:59.194 11023 11037 I chatty  : uid=10339(app.revanced.manager.flutter) expire 24 lines
01-26 20:27:59.195 11023 12487 I chatty  : uid=10339(app.revanced.manager.flutter) expire 24 lines
01-26 20:28:00.418 11023 11039 I chatty  : uid=10339(app.revanced.manager.flutter) expire 28 lines
01-26 20:28:01.016 11023 11033 I chatty  : uid=10339(app.revanced.manager.flutter) expire 27 lines
.....
01-26 20:28:30.313 11023 12546 I manager.flutte: Alloc young concurrent copying GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 255MB/256MB, paused 58us total 7.354ms
01-26 20:28:30.313 11023 12546 I manager.flutte: Starting a blocking GC Alloc
01-26 20:28:30.313 11023 11276 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.313 11023 11902 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.313 11023 11037 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.313 11023 11846 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.313 11023 12487 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.314 11023 11023 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.314 11023 11200 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.888 11023 12546 I manager.flutte: Clamp target GC heap from 279MB to 256MB
01-26 20:28:30.888 11023 12546 I manager.flutte: Alloc concurrent copying GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 255MB/256MB, paused 62us total 574.869ms
01-26 20:28:30.888 11023 12546 I manager.flutte: Forcing collection of SoftReferences for 120B allocation
01-26 20:28:30.888 11023 12546 I manager.flutte: Starting a blocking GC Alloc
01-26 20:28:30.888 11023 11276 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.888 11023 11902 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.888 11023 11037 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.888 11023 11846 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.889 11023 12487 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.889 11023 11023 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:30.889 11023 11200 I manager.flutte: Waiting for a blocking GC Alloc
01-26 20:28:31.698 11023 12546 I manager.flutte: Clamp target GC heap from 279MB to 256MB
01-26 20:28:31.698 11023 12546 I manager.flutte: Alloc concurrent copying GC freed 5(376B) AllocSpace objects, 0(0B) LOS objects, 0% free, 255MB/256MB, paused 45us total 810.275ms
01-26 20:28:31.698 11023 11276 I manager.flutte: WaitForGcToComplete blocked Alloc on ProfileSaver for 15.469s
01-26 20:28:31.698 11023 11276 I manager.flutte: Starting a blocking GC Alloc
....
01-26 20:28:45.446 11023 12487 I manager.flutte: Clamp target GC heap from 280MB to 256MB
01-26 20:28:45.446 11023 12487 I manager.flutte: Alloc concurrent copying GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 256MB/256MB, paused 45us total 814.105ms
01-26 20:28:45.446 11023 11846 I manager.flutte: WaitForGcToComplete blocked Alloc on ProfileSaver for 8.144s
01-26 20:28:45.446 11023 11846 I manager.flutte: Starting a blocking GC Alloc
01-26 20:28:45.446 11023 12487 W manager.flutte: Throwing OutOfMemoryError "Failed to allocate a 24 byte allocation with 0 free bytes and 0B until OOM, target footprint 268435456, growth limit 268435456" (VmSize 10232024 kB)
`

**Comment by Eggtouch** [comment]
> Could you try patching with recanced-cli?

Having the same issue, getting NullPointerException when trying to apply sim-spoof patch.
TikTok version 27.8.3, couldn't patch with the manager, tried it with revanced-cli, had the same issue:
```
java -jar revanced-cli-2.20.0-all.jar -a com.zhiliaoapp.musically_27.8.3-2022708030.apk -c -o output.apk -b revanced-patches.jar -i sim-spoof -i settings --exclusive -m integrations.apk
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x71020000
INFO: Merging integrations.apk
INFO: Skipping disable-login-requirement: Excluded by default
INFO: Skipping downloads: Excluded by default
INFO: Skipping feed-filter: Excluded by default
INFO: Skipping fix-google-login: Excluded by default
INFO: Skipping hide-ads: Excluded by default
INFO: Skipping playback-speed: Excluded by default
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping show-seekbar: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default
INFO: settings succeeded
SEVERE: sim-spoof failed:
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:339)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.tiktok.misc.spoof.sim.patch.SpoofSimPatch.execute(SpoofSimPatch.kt:88)
        at app.revanced.patches.tiktok.misc.spoof.sim.patch.SpoofSimPatch.execute(SpoofSimPatch.kt:26)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:335)
        ... 16 more
INFO: Not compiling resources because resource patching is not required
INFO: Writing modified dex files
INFO: Aligning com.zhiliaoapp.musically_27.8.3-2022708030.apk to output_aligned.apk
INFO: Signing output_aligned.apk to output_signed.apk
INFO: Found existing keystore: output.keystore
INFO: Copying output_signed.apk to output.apk
INFO: Failed to clean up cache directory
INFO: Finished
```

**Comment by kazimmt** [comment]
I patched all latest version using CLI (sim spoof patch included)
& all patched perfectly without any issue.

**Comment by leehwongxing** [comment]
![image](https://user-images.githubusercontent.com/32384712/219875104-72820838-1a12-4d86-a5cc-2c662cf5e917.png)

I guess A SINGLE LINE that make the patching failed on Revanced Manager and successful on CLI, and the patched app indeed working.

**Comment by ILoveOpenSourceApplications** [comment]
Currently it's working fine with TikTok v27.8.3, all patches are getting applied.

**Comment by ILoveOpenSourceApplications** [comment]
Closing as it's not an existing issue.
