### ISSUE TITLE
Revanced keeps on aborting, Please help

### ISSUE THREAD

**Issue by owenvava** [revanced/revanced-patches#1514]
### Type

Error while patching

### Bug description

I installed the correct version of micro G and I installed the correct version of youtube but while it is trying to partch it aborts.

Im also on a oneplus 7 pro if that helps any.

### Steps to reproduce

download micro g
install correct version of youtube
install manager (0.53), also tried (0.52)
attempt to patch
get aborted

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
An error occurred! Aborting
Error:
java.lang.NoSuchMethodError: No static method isAndroid()Z in class Lbrut/util/OSDetection; or its super classes (declaration of 'brut.util.OSDetection' appears in /data/app/~~dQvuV2LCc6xV-yi319kjtw==/app.revanced.manager.flutter-fUN6AMf85lDRTM7Uwy2O5Q==/base.apk)
	at brut.androlib.res.decoder.Res9patchStreamDecoder.<init>(Res9patchStreamDecoder.java:43)
	at brut.androlib.res.AndrolibResources.getResFileDecoder(AndrolibResources.java:693)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:221)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:140)
	at app.revanced.patcher.Patcher.decodeResources(Patcher.kt:225)
	at app.revanced.patcher.Patcher.access$decodeResources(Patcher.kt:37)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:347)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$20(MainActivity.kt:327)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$VzOqgSVOualTn6WBlAKw3muxHF8(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
Not an issue with patches.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-manager/issues/648
