### ISSUE TITLE
bug: YT crashing in background

### ISSUE THREAD

**Issue by cyberboh** [revanced/revanced-patches#1572]
### Type

Error at runtime

### Bug description

I get random YT crashing in background while patch `spoof-app-version` is included

### Steps to reproduce

Patch YT 18.03.36 with `spoof-app-version` patch in root mode

### Relevant log output

```shell
E/AndroidRuntime]
FATAL EXCEPTION: cronet-ui-innertube5-3
Process: com.google.android.youtube.player, PID: 14107
java.lang.NoClassDefFoundError: app.revanced.integrations.settings.SettingsEnum
	at app.revanced.integrations.patches.SpoofAppVersionPatch.getYouTubeVersionOverride(SpoofAppVersionPatch.java:1)
	at usb.c(PG:5)
	at wjc.b(PG:1)
	at uri.a(PG:2)
	at wje.d(PG:8)
	at wje.a(PG:1)
	at vnp.a(PG:1)
	at wjh.b(PG:4)
	at yzx.B(PG:1)
	at wjh.c(Unknown Source:0)
	at adrt.F(PG:6)
	at wjb.u(PG:1)
	at wkb.G(PG:2)
	at wkb.sh(PG:2)
	at ujb.a(PG:15)
	at ujb.run(PG:21)
	at afvw.run(PG:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at tnk.run(PG:21)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.ExceptionInInitializerError
	at app.revanced.integrations.patches.SpoofAppVersionPatch.getYouTubeVersionOverride(SpoofAppVersionPatch.java:1)
	at usb.c(PG:5)
	at tyn.ag(PG:1)
	at uhk.loadLibrary(PG:1)
	at avpk.loadLibrary(PG:1)
	at org.chromium.net.impl.CronetLibraryLoader.a(PG:5)
	at org.chromium.net.impl.CronetUrlRequestContext.<init>(PG:8)
	at avoy.build(PG:2)
	at org.chromium.net.ExperimentalCronetEngine$Builder.build(PG:2)
	at uhj.a(PG:32)
	at uhf.a(PG:10)
	at tyn.y(PG:1)
	at qdt.a(PG:19)
	at asvf.a(PG:1)
	at asve.a(PG:2)
	at mgx.run(PG:76)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7867)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at app.revanced.integrations.settings.SettingsEnum.getBoolean(SettingsEnum.java:5)
	at app.revanced.integrations.utils.LogHelper.printException(LogHelper.java:8)
	at app.revanced.integrations.utils.LogHelper.printException(LogHelper.java:1)
	at app.revanced.integrations.utils.ReVancedUtils.getContext(ReVancedUtils.java:12)
	at app.revanced.integrations.settings.SettingsEnum.load(SettingsEnum.java:1)
	at app.revanced.integrations.settings.SettingsEnum.<clinit>(SettingsEnum.java:145)
	... 24 more
```

### Additional context

Full log
Tested on Android 13

[logcat.txt](https://github.com/revanced/revanced-patches/files/10547961/logcat.txt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Did you update the integrations?

**Comment by cyberboh** [comment]
> Did you update the integrations?

Yes, im using
`revanced-integrations-0.94.1.apk`

**Comment by oSumAtrIX** [comment]
Please attach a full recording of the following:

1. Close and reppen the ReVanced Manager
2. Patch the app
3. Show the issue

**Comment by cyberboh** [comment]
> Please attach a full recording of the following:
> 
>     1. Close and reppen the ReVanced Manager
> 
>     2. Patch the app
> 
>     3. Show the issue

here the vid https://streamable.com/hytkkh
all patching process are done successfully.
but the i ge rarelt random yt fc :(

**Comment by oSumAtrIX** [comment]
You forgot to follow step 1. 

Reinstall the ReVanced Manager as well.

**Comment by cyberboh** [comment]
> You forgot to follow step 1.
> 
> Reinstall the ReVanced Manager as well.

done here
`https://jmp.sh/OviQEgMM`

**Comment by oSumAtrIX** [comment]
For mounting with root, exclude the `microg-support` patch. It is intended for non-root.
