### ISSUE TITLE
YouTube crashing

### ISSUE THREAD

**Issue by LostCat123** [revanced/revanced-patches#1621]
### Type

Error at runtime

### Bug description

The YouTube crash

### Steps to reproduce

Patch youtube

### Relevant log output

```shell
02-12 19:31:35.023 E/AndroidRuntime(22665): FATAL EXCEPTION: main
02-12 19:31:35.023 E/AndroidRuntime(22665): Process: com.google.android.youtube, PID: 22665
02-12 19:31:35.023 E/AndroidRuntime(22665): java.lang.RuntimeException: Unable to instantiate application com.google.android.apps.youtube.app.YouTubeTikTokRoot_Application package com.google.android.youtube: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.youtube.app.YouTubeTikTokRoot_Application" on path: DexPathList[[zip file "/data/app/~~cDmxF1-7VnAQnSIQf2ZMIQ==/com.google.android.youtube-BOOD8PpjSHcE-TaZF7C07A==/base.apk"],nativeLibraryDirectories=[/data/app/~~cDmxF1-7VnAQnSIQf2ZMIQ==/com.google.android.youtube-BOOD8PpjSHcE-TaZF7C07A==/lib/arm64, /data/app/~~cDmxF1-7VnAQnSIQf2ZMIQ==/com.google.android.youtube-BOOD8PpjSHcE-TaZF7C07A==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1466)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1395)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6720)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2133)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.os.Looper.loopOnce(Looper.java:201)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.os.Looper.loop(Looper.java:288)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at java.lang.reflect.Method.invoke(Native Method)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
02-12 19:31:35.023 E/AndroidRuntime(22665): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.apps.youtube.app.YouTubeTikTokRoot_Application" on path: DexPathList[[zip file "/data/app/~~cDmxF1-7VnAQnSIQf2ZMIQ==/com.google.android.youtube-BOOD8PpjSHcE-TaZF7C07A==/base.apk"],nativeLibraryDirectories=[/data/app/~~cDmxF1-7VnAQnSIQf2ZMIQ==/com.google.android.youtube-BOOD8PpjSHcE-TaZF7C07A==/lib/arm64, /data/app/~~cDmxF1-7VnAQnSIQf2ZMIQ==/com.google.android.youtube-BOOD8PpjSHcE-TaZF7C07A==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at androidx.core.app.CoreComponentFactory.instantiateApplication(PG:1)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.app.Instrumentation.newApplication(Instrumentation.java:1244)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1458)
02-12 19:31:35.023 E/AndroidRuntime(22665): 	... 11 more
02-12 19:31:35.023 E/AndroidRuntime(22665): 	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lfew;
02-12 19:31:35.023 E/AndroidRuntime(22665): 		at java.lang.VMClassLoader.findLoadedClass(Native Method)
02-12 19:31:35.023 E/AndroidRuntime(22665): 		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
02-12 19:31:35.023 E/AndroidRuntime(22665): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
02-12 19:31:35.023 E/AndroidRuntime(22665): 		... 16 more
02-12 19:31:35.023 E/AndroidRuntime(22665): 	Caused by: java.lang.ClassNotFoundException: few
02-12 19:31:35.023 E/AndroidRuntime(22665): 		... 19 more
```

### Screenshots or videos

![Screenshot_20230212-192839_ReVanced Manager](https://user-images.githubusercontent.com/91554842/218308642-87ec17dc-d817-4626-8158-8f3130e5eb3e.png)

### Solution

I can't find one

### Additional context

I'm using the proper version 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Reproduction steps do not suffice to reproduce this issue.

**Comment by LostCat123** [comment]
> Reproduction steps do not suffice to reproduce this issue.

,I've updated

**Comment by oSumAtrIX** [comment]
Only include recommended patches

**Comment by kazimmt** [comment]
MicroG Support patch is missing.
