### ISSUE TITLE
bug: SEVERE: `hide-ads` failed

### ISSUE THREAD

**Issue by quyleanh** [revanced/revanced-patches#1658]
### Type

Error while patching

### Bug description

Patching Twitter app version 9.76.0-release.0 fails

### Steps to reproduce

Patching Twitter app version 9.76.0-release.0 with latest patches-v2.163 fails

### Relevant log output

```shell
SEVERE: hide-ads failed: 
app.revanced.patcher.patch.PatchResultError: 'hide-ads' depends on 'json-hook' but the following error was raised: Could not find integrations.
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:158)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Can not reproduce on ReVanced CLI.

**Comment by kick-the-bucket** [comment]
Have the same issue on Revanced Manager

**Comment by oSumAtrIX** [comment]
This error happens due to this:
https://github.com/revanced/revanced-patches/blob/3dbc5ff2722559211232999ae29e7fabafe3b857/src/main/kotlin/app/revanced/patches/twitter/misc/hook/json/patch/JsonHookPatch.kt#L24-L25

The constant refers to a descriptor of a class:
https://github.com/revanced/revanced-patches/blob/3dbc5ff2722559211232999ae29e7fabafe3b857/src/main/kotlin/app/revanced/patches/twitter/misc/hook/json/patch/JsonHookPatch.kt#L104-L106

This class exists in the latest integrations:

https://github.com/revanced/revanced-integrations/blob/665598836abfcead9c5e68ce7831a4137465df39/app/src/main/java/app/revanced/twitter/patches/hook/json/JsonHookPatch.kt#L1-L9

**Comment by quyleanh** [comment]
Evan when using CLI, it still has same erro:

```bash
% java -jar revanced-cli-2.20.0-all.jar -c -a com.twitter.android_9.76.0-release.0 -o twitter-revanced-9.76.0.apk -b revanced-patches-2.164.0.jar --keystore=../ks.keystore -e dynamic-color -e hide-recommended-users -e hide-views-stats -e monochrome-icon  --experimental
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Skipping dynamic-color: Manually excluded
INFO: Skipping hide-recommended-users: Manually excluded
INFO: Skipping hide-views-stats: Manually excluded
INFO: Skipping monochrome-icon: Manually excluded
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default
SEVERE: hide-ads failed:
app.revanced.patcher.patch.PatchResultError: 'hide-ads' depends on 'json-hook' but the following error was raised: Could not find integrations.
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: Not compiling resources because resource patching is not required
INFO: Writing modified dex files
INFO: Aligning com.twitter.android_9.76.0-release.0 to twitter-revanced-9.76.0_aligned.apk
INFO: Signing twitter-revanced-9.76.0_aligned.apk to twitter-revanced-9.76.0_signed.apk
INFO: Found existing keystore: ks.keystore
INFO: Copying twitter-revanced-9.76.0_signed.apk to twitter-revanced-9.76.0.apk
INFO: Cleaned up cache directory
INFO: Finished
```

**Comment by NatoBoram** [comment]
While this issue is about `9.76.0-release.0`, it also affects the recommended version, `9.71.0-release.0`

**Comment by oSumAtrIX** [comment]
@quyleanh you forgot to merge the integrations, thee exception hinted that.

**Comment by quyleanh** [comment]
@oSumAtrIX thank you for clarifying. I forgot about adding `-m revanced-integrations.apk` to command.

I will close this issue.

**Comment by oSumAtrIX** [comment]
You are not using the dev branch.
