### ISSUE TITLE
bug: Citra breaks when patching with premium-unlock

### ISSUE THREAD

**Issue by thepwrtank18** [revanced/revanced-patches#1700]
### Type

Error at runtime

### Bug description

I found it by patching Citra with ReVanced Manager.

### Steps to reproduce

1. Download latest APK of Citra from apkmirror
2. Patch Citra with ReVanced Manager and install
3. Run Citra
4. crash on startup

### Relevant log output

```shell
--unavailable, nonroot--
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please attach logs as well as the last working version.

**Comment by thepwrtank18** [comment]
How can you get logs with nonroot?

**Comment by oSumAtrIX** [comment]
Via ADB.

**Comment by thepwrtank18** [comment]
```
03-03 19:52:51.229   676   676 E AndroidRuntime: Process: org.citra.citra_emu, PID: 676
03-03 19:52:51.229   676   676 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String[] org.citra.citra_emu.NativeLibrary.GetInstalledGamePaths() (tried Java_org_citra_citra_1emu_NativeLibrary_GetInstalledGamePaths and Java_org_citra_citra_1emu_NativeLibrary_GetInstalledGamePaths__)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at org.citra.citra_emu.NativeLibrary.GetInstalledGamePaths(Native Method)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at org.citra.citra_emu.model.GameDatabase.scanLibrary(GameDatabase.java:170)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at org.citra.citra_emu.ui.main.MainPresenter.refeshGameList(MainPresenter.java:79)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at org.citra.citra_emu.ui.main.MainPresenter.onCreate(MainPresenter.java:28)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at org.citra.citra_emu.ui.main.MainActivity.onCreate(MainActivity.java:61)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8591)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8570)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4315)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8747)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
03-03 19:52:51.229   676   676 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)03-03 19:52:57.897   892   892 E AndroidRuntime: FATAL EXCEPTION: main
```

**Comment by oSumAtrIX** [comment]
The APK is malformed. Please attach a recording of the entire patching process in exact and full detail.

**Comment by thepwrtank18** [comment]
https://streamable.com/fti26d

**Comment by oSumAtrIX** [comment]
Check if installing the APK without patching works

**Comment by thepwrtank18** [comment]
Installing the APK works,

**Comment by oSumAtrIX** [comment]
Exclude all patches and patch, check if it works

**Comment by thepwrtank18** [comment]
Removing all patches works.

**Comment by oSumAtrIX** [comment]
Please check, which last version of the app worked

**Comment by Caddy8970** [comment]
any progress for a fix?

**Comment by Aunali321** [comment]
This can be closed as we no longer provide patches for citra.
