### ISSUE TITLE
bug(Twitch): block-video-ads fails for 14.7.0

### ISSUE THREAD

**Issue by caneleex** [revanced/revanced-patches#1717]
### Type

Error while patching

### Bug description

Tried patching Twitch `14.7.0` (latest stable as of Mar 7th, 2023) with the `block-video-ads` patch but it failed.

### Steps to reproduce

Step 1: [download Twitch `14.7.0`](https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/twitch-14-7-0-release/twitch-live-game-streaming-14-7-0-2-android-apk-download/)
Step 2: try patching the apk with revanced-cli
Step 3: observe

### Relevant log output

```shell
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Merging revanced-integrations-v0.99.0.apk
INFO: Skipping block-audio-ads: Excluded by default
INFO: Skipping block-embedded-ads: Excluded by default
INFO: Skipping debug-mode: Excluded by default
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping settings: Excluded by default
INFO: Skipping show-deleted-messages: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
SEVERE: block-video-ads failed:
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:339)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.twitch.ad.video.patch.VideoAdsPatch.execute(VideoAdsPatch.kt:88)
        at app.revanced.patches.twitch.ad.video.patch.VideoAdsPatch.execute(VideoAdsPatch.kt:24)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:335)
        ... 16 more
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Aligning tv.twitch.android.app.apk to patched_aligned.apk
INFO: Signing patched_aligned.apk to patched_signed.apk
INFO: Found existing keystore: revanced.keystore
INFO: Copying patched_signed.apk to patched.apk
INFO: Failed to clean up cache directory
INFO: Finished
```

### Additional context

revanced-patches v2.164.0
revanced-integrations v0.99.0
revanced-cli v2.20.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
#1736

**Comment by caneleex** [comment]
@ILoveOpenSourceApplications why was this closed? it's used for tracking issues with this patch that have not been fixed yet.

**Comment by ILoveOpenSourceApplications** [comment]
The latest known working version for twitch with all the patches supported have been released. I don't see how keeping this issue open would make any sense given that there could be other apps with such issues happening for an unsupported version. I hope you understand.
