### ISSUE TITLE
bug: SEVERE: hide-timeline-ads failed `(Instagram 276.0.0.26.103)`

### ISSUE THREAD

**Issue by cyberboh** [revanced/revanced-patches#1816]
### Type

Error while patching

### Bug description

Patch Instagram with cli and latest patches & integration

### Steps to reproduce

1. Download Instagram [276.0.0.26.103](https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-276-0-0-26-103-release/instagram-276-0-0-26-103-3-android-apk-download/)
2. Patch with cli `java -jar cli.jar -a insta.apk -c -o re-insta.apk -b patches.jar -m inte.apk`

### Relevant log output

```shell
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Skipping export-all-activities: Excluded by default
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default
SEVERE: hide-timeline-ads failed:
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:332)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:155)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.instagram.patches.ads.timeline.fingerprints.ads.ShoppingAdFingerprint.toString(ShoppingAdFingerprint.kt:20)
        at app.revanced.patches.instagram.patches.ads.timeline.patch.HideTimelineAdsPatch.execute(HideTimelineAdsPatch.kt:65)
        at app.revanced.patches.instagram.patches.ads.timeline.patch.HideTimelineAdsPatch.execute(HideTimelineAdsPatch.kt:24)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
        ... 16 more
INFO: Not compiling resources because resource patching is not required
INFO: Writing modified dex files
INFO: Aligning insta.apk to re-insta_aligned.apk
INFO: Signing re-insta_aligned.apk to re-insta_signed.apk
INFO: Found existing keystore: re-insta.keystore
INFO: Copying re-insta_signed.apk to re-insta.apk
INFO: Cleaned up cache directory
INFO: Finished
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/99109969/228558339-428b1c77-6df4-4816-a514-e8d07a714c9a.png)

### Additional context

cli version 2.20.1
integration version 0.101.0
patches version 2.167.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by selfmusing** [comment]
Cool i was just going to report this issue !! 👽

**Comment by oSumAtrIX** [comment]
Closing in favour of #1966.

**Comment by CrypticCus** [comment]
Any progress? also what about hiding reels and shop?
