### ISSUE TITLE
bug: Error while patching SEVERE

### ISSUE THREAD

**Issue by AMSAMSAMSAMS** [revanced/revanced-patches#2062]
### Type

Error while patching

### Bug description

Error while patching.

### Steps to reproduce

All latest also Youtube version according to the latest supoerted.

### Relevant log output

```shell
SEVERE: Error while setting option packageName for patch change-package-name: Invalid option value type: null, expected java.lang.Object 
app.revanced.patcher.patch.InvalidTypeException: Invalid option value type: null, expected java.lang.Object
	at app.revanced.utils.OptionsLoader.readAndSet(OptionsLoader.kt:82)
	at app.revanced.utils.OptionsLoader.init(OptionsLoader.kt:26)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:137)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Crescendo-BLYAT** [comment]
I have the same issue & yes I'm using the dev branch of CLI.

**Comment by evilmtv** [comment]
Can confirm that issue persists on latest dev branch of CLI
```
> .\zulu17.42.19-ca-jdk17.0.7-win_x64\bin\java.exe -jar .\revanced-cli-2.20.2-dev.1-all.jar -b .\revanced-patches-2.173.0.jar -a .\18.16.37.apk -e debugging -o output.apk -c -m .\revanced-integrations-0.107.0.apk
SEVERE: Error while setting option packageName for patch change-package-name: Invalid option value type: null, expected java.lang.Object
app.revanced.patcher.patch.InvalidTypeException: Invalid option value type: null, expected java.lang.Object
        at app.revanced.utils.OptionsLoader.readAndSet(OptionsLoader.kt:82)
        at app.revanced.utils.OptionsLoader.init(OptionsLoader.kt:26)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:137)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

**Comment by evilmtv** [comment]
Update:
Had to delete `options.toml` file and error does not occur anymore

**Comment by sin-ack** [comment]
Just deleting the `change-package-name` section of `options.toml` is enough and preserves your other options.
