### ISSUE TITLE
bug: YouTube 18.16.37 fails to patch for root

### ISSUE THREAD

**Issue by Redn2000** [revanced/revanced-patches#2093]
### Type

Error while patching

### Bug description

Device info:
OnePlus 9 Pro
Android 13
Magisk version: 26.1
YouTube play store updates disabled. 
YouTube installation: Is unfortunately a system app as of 13, but the updates can be mostly uninstalled to allow installtion of the current recommend version.

I've tested patching a few times with different versions of YouTube, especially 18.16.37,that are supposedly supported, but keep getting the same error that root install is not possible with the current patch selection from the revanced app. 

### Steps to reproduce

1. Grab and install YouTube 18.16.37 apk (apk pure and mirror were both tested).
2. Give revanced app root permissions.
3. Leave default patch options enabled.
4. Try to patch with the latest revanced app.
5. Patches finish, but attempting to Install as Root gives the error that root install is not possible with the current patch selection. 

### Relevant log output

```shell
--------- beginning of crash
05-06 14:00:17.847 27269 27269 E AndroidRuntime: FATAL EXCEPTION: main
05-06 14:00:17.847 27269 27269 E AndroidRuntime: Process: app.revanced.manager.flutter, PID: 27269
05-06 14:00:17.847 27269 27269 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5032)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5075)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:60)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.os.Handler.dis
patchMessage(Handler.java:106)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:240)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:351)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8321)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1012)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=212, result=-1, data=null} to activity {app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5626)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5007)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	... 13 more
05-06 14:00:17.847 27269 27269 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.app.Activity.getPackageManager()' on a null object reference
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at com.baseflow.permissionhandler.PermissionManager.onActivityResult(PermissionManager.java:78)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEngineConnectionRegistry.java:807)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onActivityResult(FlutterEngineConnectionRegistry.java:430)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:811)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:771)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8729)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5619)
05-06 14:00:17.847 27269 27269 E AndroidRuntime: 	... 14 more
--------- beginning of system
05-06 15:20:33.504 30881 30881 D ActivityThread: do gfx trim 40 success
05-06 15:21:24.548 30881 30881 I Quality : Skipped: false 7 cost 61.174496 refreshRate 8339163 bit true processName app.revanced.manager.flutter
05-06 15:21:29.737 30881 30881 D ActivityThread: do gfx trim 40 success
--------- beginning of main
05-06 15:24:49.659 30881  4890 D ColorModeChangeItem: preExecute mColorMode=0,token=android.os.BinderProxy@fe56bdd
05-06 15:24:49.679 30881 30881 I Quality : Skipped: false 1 cost 12.850582 refreshRate 8347183 bit true processName app.revanced.manager.flutter
05-06 15:24:49.694 30881 30881 D BufferQueueConsumer: [](id:78a100000004,api:0,p:-1,c:30881) connect: controlledByApp=false
05-06 15:24:49.694 30881 30881 E IPCThreadState: attemptIncStrongHandle(56): Not supported
05-06 15:24:49.694 30881 30881 E IPCThreadState: attemptIncStrongHandle(64): Not supported
05-06 15:24:49.696 30881  2391 D BufferQueueProducer: [VRI[MainActivity]#4(BLAST Consumer)4](id:78a100000004,api:1,p:30881,c:30881) connect: api=1 producerControlledByApp=true
05-06 15:24:49.697 30881 30881 D BufferQueueConsumer: [](id:78a100000005,api:0,p:-1,c:30881) connect: controlledByApp=false
05-06 15:24:49.698 30881  2397 D BufferQueueProducer: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#5(BLAST Consumer)5](id:78a100000005,api:1,p:30881,c:30881) connect: api=1 producerControlledByApp=true
05-06 15:24:49.704 30881 30881 E SurfaceSyncer: Failed to find sync for id=0
05-06 15:24:49.704 30881 30881 E SurfaceSyncer: Failed to find sync for id=1
05-06 15:24:49.704 30881 30881 E SurfaceSyncer: Failed to find sync for id=2
05-06 15:24:49.704 30881 30881 E SurfaceSyncer: Failed to find sync for id=3
05-06 15:24:49.707 30881  3193 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff]
05-06 15:24:49.716 30881  3193 D SurfaceComposerClient: VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff]
05-06 15:24:49.719 30881 30881 D VRI[MainActivity]: onFocusEvent true
05-06 15:24:50.361 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:24:50.510 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:24:50.633 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:24:50.752 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:24:51.606 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:24:52.923 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:24:53.426 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:24:53.428 30881 30881 D OplusSystemUINavigationGesture: [GESTURE_BUTTON] swipe from 1
05-06 15:24:53.428 30881 30881 D OplusSystemUINavigationGesture: [GESTURE_BUTTON] Hit Gesture Region !
05-06 15:24:54.307 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:24:55.428 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:24:57.731 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:25:00.093 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:25:01.618 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
05-06 15:25:02.702 30881 30881 V AutofillManager: requestHideFillUi(null): anchor = null
```

### Screenshots or videos

![Screenshot_2023-05-06-15-20-27-38_a85b47aaa863e3bc831e16d29c27a79c](https://user-images.githubusercontent.com/6705326/236643173-7f28aa0d-cc65-4789-9e04-11a42f4fe710.jpg)

### Solution

Remove the patch for microG

### Additional context

For usability, would it be possible to add an indicator to relevant patches that might cause issues with root? 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Simple issue. You've included `vanced microg support` which is a patch required for non-root users. Exclude that patch and try repatching and everything should work fine.
