### ISSUE TITLE
bug: Youtube error after rebooting the device.

### ISSUE THREAD

**Issue by NoneDev-git** [revanced/revanced-patches#2179]
### Type

Error at runtime

### Bug description

After youtube patch with the standard set of patches except Micro G, everything works fine. But as soon as you reboot the device, the name of YouTube changes to "any" and stops running, giving an error that the library "libjsapi.so" is not found. The installation method I use root. Xiaomi MIUI phone flashing.

### Steps to reproduce

1. Patting YouTube by default setting but removing MicroG
2. After installing, reboot phone
3. Try to start YouTube
After that YouTube is renamed to "Any" and gives you an error.

### Relevant log output

```shell
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsapi.so" not found
 at java.lang.Runtime.load0(Runtime.java:938)
 at java.lang.System.load(System.java:1631)
 at fjz.G(PG:54)
 at ysx.bK(PG:7)
 at fmn.a(PG:1)
 at ahqn.b(PG:8)
 at ahqn.c(PG:5)
 at ahqn.a(PG:1)
 at phq.a(PG:3)
 at flm.c(PG:45)
 at flm.a(PG:1)
 at atah.a(PG:1)
 at fln.yz(PG:3)
 at flm.c(PG:58)
 at flm.a(PG:1)
 at ataa.a(PG:1)
 at aszz.a(PG:2)
 at flm.k(PG:31)
 at flm.a(PG:1)
 at atah.a(PG:1)
 at fln.dO(PG:1)
 at flm.k(PG:32)
 at flm.a(PG:1)
 at zor.a(PG:1)
 at utr.A(PG:1)
 at flm.b(PG:68)
 at flm.a(PG:1)
 at ataa.a(PG:1)
 at aszz.a(PG:2)
 at flm.m(Unknown Source:2232)
 at flm.a(PG:1)
 at ataa.a(PG:1)
 at aszz.a(PG:2)
 at fqy.run(PG:130)
 at afvi.run(PG:3)
 at agxm.execute(PG:1)
 at com.google.android.apps.youtube.app.application.Shell_HomeActivity.l(PG:6)
 at fqy.run(PG:104)
 at uxc.run(PG:7)
 at uxe.l(PG:8)
 at uxe.m(PG:7)
 at fqx.onCreate(PG:16)
 at com.google.android.apps.youtube.app.application.Shell_HomeActivity.onCreate(PG:6)
 at android.app.Activity.performCreate(Activity.java:7893)
 at android.app.Activity.performCreate(Activity.java:7880)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:224)
 at android.app.ActivityThread.main(ActivityThread.java:7562)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### Screenshots or videos

![image](https://github.com/revanced/revanced-patches/assets/77238864/cf002ae2-b411-422b-a05d-083ade8d354b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You removed the necessary patch to use the app without root after patching.
