### ISSUE TITLE
problem: `hide-autoplay-button`

### ISSUE THREAD

**Issue by tillnelown** [revanced/revanced-patches#220]
## 🐞 Issue

The hide-autoplay-button patch causes Youtube 17.27.39 to crash.  

## ⚙ Reproduce
Using the mount method:
Running
`java -jar revanced-cli-all.jar -a ~/Downloads/com.google.android.youtube_17.27.39-1530396096_minAPI23\(arm64-v8a,armeabi-v7a,x86,x86_64\)\(nodpi\)_apkmirror.com.apk -e seekbar-tapping -e autorepeat-by-default -e microg-support  -b revanced-patches.jar -m revanced-integrations.apk --mount -o ../revanced.apk -t cache -d [device id]`
creates a broken apk that doesn't work and instead crashes on startup, it works after adding `-e hide-autoplay-button`

## ⚠ Additional context

```
07-22 13:45:43.698 11053 11053 E AndroidRuntime: java.lang.NoSuchMethodError: No static method isButtonHidden()Z in class Lapp/revanced/integrations/patches/HideAutoplayButtonPatch; or its super classes (declaration of 'app.revanced.integrations.patches.HideAutoplayButtonPatch' appears in /data/app/~~rPxhm27IC8We3oVLY01-9w==/com.google.android.youtube-fa7KkEoVZ9ggsaKGjKKLQQ==/base.apk!classes6.dex)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at com.google.android.libraries.youtube.player.features.prefetch.WillAutonavInformer.k(PG:1)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at ifu.h(PG:1)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at ifu.d(PG:11)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at ikm.<init>(PG:5)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at ihe.k(PG:1)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.c(PG:11)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.a(PG:15)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at apoe.a(PG:2)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.c(PG:12)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.a(PG:15)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at apoe.a(PG:2)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.c(PG:35)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.a(PG:15)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at apoe.a(PG:2)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.j(PG:52)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.a(PG:14)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at apoe.a(PG:2)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.j(PG:53)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.a(PG:14)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at apoe.a(PG:2)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.c(PG:69)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at egh.a(PG:15)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at apoe.a(PG:2)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.o(PG:41)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at izs.a(PG:56)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at ra.onCreate(PG:3)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at br.onCreate(PG:1)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at erc.onCreate(PG:8)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at kua.onCreate(PG:1)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:4)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8215)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8199)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3824)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4027)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:247)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8676)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
07-22 13:45:43.698 11053 11053 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by oSumAtrIX** [comment]
Wrong version of patches. Update to the latest version.
