### ISSUE TITLE
bug: TikTok & Instagram Failing to patch with the latest patches.

### ISSUE THREAD

**Issue by giwrgosmant** [revanced/revanced-patches#2245]
### Type

Error while patching

### Bug description

Failing to patch properly TikTok and Instagram with default (recommended) patches.
Some patches fail.

- ReVanced Manager Version: **1.3.0**
- Patches Version: **v2.174.0**
- Integrations Version: **v0.108.0**
- TikTok Version: Suggested **27.8.3**
- Instagram Version: Tried with **284.0.0.22.85** and **275.0.0.27.98**.

**Logs:**
- [TikTok.log](https://github.com/revanced/revanced-patches/files/11561434/TikTok.log)
- [Instagram.log](https://github.com/revanced/revanced-patches/files/11561435/Instagram.log)

### Steps to reproduce

- Open ReVanced Manager
- Select TikTok/Instgram app
- Select Default (Recommended) patches
- Patch
- Fail

### Relevant log output

```shell
TikTok Logs:

Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Applied disable-login-requirement
Failed to apply downloads: 'downloads' depends on 'settings' but the following error was raised: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.patchOptionNameAndOnClickEvent(SettingsPatch.kt:119)
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.execute(SettingsPatch.kt:54)
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.execute(SettingsPatch.kt:29)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Failed to apply feed-filter: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Failed to apply settings: 'settings' did not succeed previously
Applied show-seekbar
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
Finished!



Instagram Log:

Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Failed to apply hide-timeline-ads: Failed to resolve MediaFingerprint
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
Finished!
```

### Screenshots or videos

**TikTok Screenshots:**
![TikTok 1](https://github.com/revanced/revanced-patches/assets/51835189/4a2dde56-f7fa-4570-8b77-7007402875c6)
![TikTok 2](https://github.com/revanced/revanced-patches/assets/51835189/8c235a66-d45c-4cd1-bf96-53518602c26a)
![TikTok 3](https://github.com/revanced/revanced-patches/assets/51835189/4eda6d7c-8503-4453-8e52-155f61202e3e)

**Instagram Screenshots:**
![Instagram 1](https://github.com/revanced/revanced-patches/assets/51835189/3120ad8f-cb37-46b9-ab86-a6b67e4e98d0)
![Instagram 2](https://github.com/revanced/revanced-patches/assets/51835189/203df8f7-f270-43a4-841e-a9cc36495f9c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/1966 open a new issue for TikTok
