### ISSUE TITLE
bug: TikTok Failing to patch with the latest patches.

### ISSUE THREAD

**Issue by giwrgosmant** [ReVanced/revanced-patches#2254]
### Type

Error while patching

### Bug description

Failing to patch properly TikTok with default (recommended) patches.
Some patches fail.

- ReVanced Manager Version: **1.3.0**
- Patches Version: **v2.174.0**
- Integrations Version: **v0.108.0**
- TikTok Version: Suggested **27.8.3**

**Logs:**
- [TikTok.log](https://github.com/revanced/revanced-patches/files/11561434/TikTok.log)

### Steps to reproduce

- Open ReVanced Manager
- Select TikTok app
- Select Default (Recommended) patches
- Patch
- Fail

### Relevant log output

```shell
TikTok Logs:

Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Applied disable-login-requirement
Failed to apply downloads: 'downloads' depends on 'settings' but the following error was raised: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.patchOptionNameAndOnClickEvent(SettingsPatch.kt:119)
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.execute(SettingsPatch.kt:54)
	at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.execute(SettingsPatch.kt:29)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Failed to apply feed-filter: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Failed to apply settings: 'settings' did not succeed previously
Applied show-seekbar
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
Finished!
```

### Screenshots or videos

![TikTok 1](https://github.com/revanced/revanced-patches/assets/51835189/a349902a-f30b-43f2-acb2-1c453b4dcf13)
![TikTok 2](https://github.com/revanced/revanced-patches/assets/51835189/8164889a-b3b4-4384-b714-acb5b91303ca)
![TikTok 3](https://github.com/revanced/revanced-patches/assets/51835189/eacba15f-070b-4b14-b1b1-066002fcee54)

### Additional context

I opened this as a new issue only for TikTok as you told me [here](https://github.com/revanced/revanced-patches/issues/2245).

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gerald-lnj** [comment]
same with revanced-cli:
```
PS C:\Users\geral> java -jar revanced-cli.jar -a tk.apk -c -o re.apk -b revanced-patches.jar -m in.apk --exclusive -i downloads -i feed-filter -i hide-ads -i settings -i show-seekbar -i sim-spoof -i settings
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=value, value=0x71020000
INFO: Skipping change-package-name: Excluded by default
INFO: Skipping disable-login-requirement: Excluded by default
INFO: Skipping enable-android-debugging: Excluded by default
INFO: Skipping export-all-activities: Excluded by default
INFO: Skipping fix-google-login: Excluded by default
INFO: Skipping playback-speed: Excluded by default
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default
INFO: Merging in.apk
SEVERE: downloads failed:
app.revanced.patcher.patch.PatchResultError: 'downloads' depends on 'settings' but the following error was raised: java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.patchOptionNameAndOnClickEvent(SettingsPatch.kt:119)
        at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.execute(SettingsPatch.kt:54)
        at app.revanced.patches.tiktok.misc.settings.patch.SettingsPatch.execute(SettingsPatch.kt:29)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: feed-filter failed:
app.revanced.patcher.patch.PatchResultError: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: hide-ads succeeded
SEVERE: settings failed:
app.revanced.patcher.patch.PatchResultError: 'settings' did not succeed previously
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:290)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: show-seekbar succeeded
SEVERE: sim-spoof failed:
app.revanced.patcher.patch.PatchResultError: 'sim-spoof' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: Not compiling resources because resource patching is not required
INFO: Writing modified dex files
INFO: Aligning tk.apk to re_aligned.apk
INFO: Signing re_aligned.apk to re_signed.apk
INFO: Found existing keystore: re.keystore
INFO: Copying re_signed.apk to re.apk
INFO: Failed to clean up cache directory
INFO: Finished
```

**Comment by JadenJSJ** [comment]
Yup, I can confirm, this happens on Revanced CLI and Revanced manager

**Comment by prossberg** [comment]
The issue still persists with the newest version

**Comment by oSumAtrIX** [comment]
Open a new issue for it. This issue description does not match it.

**Comment by oSumAtrIX** [comment]
The description of the issue does not this particular issue is solved.
