### ISSUE TITLE
feat(twitch): bump patches compatibility

### ISSUE THREAD

**Issue by kazimmt** [revanced/revanced-patches#2288]
### Application

Twitch

### Issue

ReVanced patches supports an old version of Twitch (14.6.1)
There is no problem with this
But recently, When we open Twitch
It shows a pop-up to update the app.
Yes we can close the pop-up but it's annoying.
![Screenshot_2023-05-27-12-51-21-495_com android vending](https://github.com/revanced/revanced-patches/assets/82371061/c4acffe3-cbe7-4da0-bb06-fc290ba01d37)

### Patch

Bump patches compatibility

### Motivation

As Twitch asks for update, older version may also stops working in near future.
So i think it's necessary to updates patches compatibility.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
I'll try some versions later today

**Comment by NewbieH4x** [comment]
Patches fail to apply on any version of the app newer than 14.6.1 with the following exception.

`INFO: Merging /home/runner/work/RevancedYT/RevancedYT/revanced-integrations/app/build/outputs/apk/release/revanced-integrations-v0.109.1-dev.1.apk 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: auto-claim-channel-points succeeded 
INFO: block-audio-ads succeeded 
SEVERE: block-embedded-ads failed: 
app.revanced.patcher.patch.PatchResultError: 'block-embedded-ads' depends on 'block-video-ads' but the following error was raised: java.lang.NullPointerException
	at app.revanced.patches.twitch.ad.video.patch.VideoAdsPatch.execute(VideoAdsPatch.kt:88)
INFO: settings succeeded 
	at app.revanced.patches.twitch.ad.video.patch.VideoAdsPatch.execute(VideoAdsPatch.kt:24)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:[32](https://github.com/NewbieH4x/RevancedYT/actions/runs/5235150885/jobs/9451780576#step:4:33)8)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:[33](https://github.com/NewbieH4x/RevancedYT/actions/runs/5235150885/jobs/9451780576#step:4:34))
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)

	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:[35](https://github.com/NewbieH4x/RevancedYT/actions/runs/5235150885/jobs/9451780576#step:4:36)0)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: block-video-ads failed: 
app.revanced.patcher.patch.PatchResultError: 'block-video-ads' did not succeed previously
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:290)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:[36](https://github.com/NewbieH4x/RevancedYT/actions/runs/5235150885/jobs/9451780576#step:4:37))
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2[41](https://github.com/NewbieH4x/RevancedYT/actions/runs/5235150885/jobs/9451780576#step:4:42)5)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:21[70](https://github.com/NewbieH4x/RevancedYT/actions/runs/5235150885/jobs/9451780576#step:4:71))
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: show-deleted-messages succeeded`

**Comment by NewbieH4x** [comment]
Twitch has stopped working for me. Streams give a Network error on 14.6.1.
I've compiled 15.4.0 with all patches except `block-video-ads` and `block-embedded-ads` which fail to apply on any version higher than 14.6.1.
