### ISSUE TITLE
bug: got java.lang.reflect.InvocationTargetException when patching youtube

### ISSUE THREAD

**Issue by hn24** [revanced/revanced-patches#2328]
### Type

Error while patching

### Bug description

Hello everyone, currently I'm unable to patch YouTube with version 2.21.2 of the CLI and patch 2.174.0.

### Steps to reproduce

I downloaded and ran the following command:

```shell
java -jar "working\revanced-cli-2.21.2-all.jar" -b "working\revanced-patches-2.174.0.jar" -a "working\com.google.android.youtube_v18.19.35.apk" -m "working\revanced-integrations-0.108.0.apk" -o working\revanced_youtube_v18.19.35.apk 
```

### Relevant log output

```shell
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Skipping change-package-name: Excluded by default
INFO: Skipping custom-video-buffer: Excluded by default
INFO: Skipping enable-android-debugging: Excluded by default
INFO: Skipping enable-debugging: Manually excluded
INFO: Skipping export-all-activities: Excluded by default
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-player-button-background: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default
INFO: Merging working\revanced-integrations-0.108.0.apk
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine
```
```


### Screenshots or videos

_No response_

### Solution

_No response_

### Additional context

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by hn24** [comment]
> Which JDK do you have installed? Must install Azul or OpenJDK version 17 or later.
> 
> Try using the latest patches and integrations (released today), and try changing to the 'working' directory before patching (just in case the sub directory path is confusing it)

Thank you, it worked when I downloaded and used the latest version that was released a few hours ago.
