### ISSUE TITLE
bug: Facebook messenger can't compile

### ISSUE THREAD

**Issue by KAJIKK** [revanced/revanced-patches#2343]
### Type

Error while patching

### Bug description

I applied default patches to the app - doesn't work, I tried different combination of patches - always the same error

### Steps to reproduce

Step 1: Download messenger from google play
Step 2: Export the apk file
Step 3: Open the apk file in Revanced Manager
Step 4: Apply patches

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied disable-switching-emoji-to-sticker-in-message-input-field
Applied disable-typing-indicator
Applied hide-inbox-ads
Applied predictive-back-gesture
Applied remove-screen-capture-restriction
Applied remove-screenshot-restriction
Repacking patched apk
Compiling resources
An error occurred! Aborting
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~xdV_3FeBSSZR5sbqp1XBAg==/app.revanced.manager.flutter-uxZ38NMZLsrRnCKJQWfrow==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CPCPRS/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CPCPRS/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:365)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:126)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~xdV_3FeBSSZR5sbqp1XBAg==/app.revanced.manager.flutter-uxZ38NMZLsrRnCKJQWfrow==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CPCPRS/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-CPCPRS/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:361)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Othmane-ElAlami** [comment]
I managed to compile it but it's crashing nonstop

**Comment by oSumAtrIX** [comment]
Send crash logs in a new issue
