### ISSUE TITLE
bug: patched APK fails to install (round 2)

### ISSUE THREAD

**Issue by twig** [revanced/revanced-patches#2390]
### Type

Other

### Bug description

Unable to install patched APK

### Steps to reproduce

* Existing twitter app already uninstalled
* Cleared caches and any remaining Twitter app files (using SD Maid)

I downloaded the recommended universal twitter apk from [9.71.0 apkmirror](https://www.apkmirror.com/apk/x-corp/twitter/twitter-9-71-0-release-0-release/twitter-9-71-0-release-0-android-apk-download/) and patched 2 things (in Revanced manager via storage)

* Hide ads
* remove screenshot restrictions
* Process completes, click install but install fails with "app not installed" (for both normal and root methods) 

### Relevant log output

```shell
2023-06-11 10:22:52.822 10281-11031 GOS:NetworkConnector    pid-10281                            D  mBaseUrl: https://service.game-mode.net/gamemode/
2023-06-11 10:22:52.822 10281-11031 GOS:NetworkConnector    pid-10281                            D  mBaseUrlForPost: https://c-api.game-mode.net/v3/
2023-06-11 10:22:52.823 10281-11031 GOS:NetworkConnector    pid-10281                            D  getPkgData(), packageName : com.twitter.android
2023-06-11 10:22:53.627 32068-11032 Finsky                  pid-32068                            I  [7213] omm.e(3): Task 7 requested foreground
2023-06-11 10:22:53.628 32068-11032 Finsky                  pid-32068                            I  [7213] omm.e(7): Not entering foreground
2023-06-11 10:22:53.644 10281-11031 GOS:NetworkConnector    pid-10281                            D  doDirectly(), Response, responseCode: 200, URL: https://service.game-mode.net/gamemode/v3/packages/?type=install&device_name=beyond0&package_names=com.twitter.android, response: {"code":"201001","message":"Success","packages":[{"package_name":"com.twitter.android","category_code":"non-game","game_genre":"N/A","device_group":"beyond0lte","game_oracle_cache":true,"cache":false}]}
2023-06-11 10:22:53.652 10281-11031 GOS:NetworkConnector    pid-10281                            D  getPkgData(), request: https://service.game-mode.net/gamemode/v3/packages/?type=install&device_name=beyond0&package_names=com.twitter.android, response: {"code":"201001","message":"Success","packages":[{"package_name":"com.twitter.android","category_code":"non-game","game_genre":"N/A","device_group":"beyond0lte","game_oracle_cache":true,"cache":false}]}
2023-06-11 10:22:53.652 10281-11031 GOS:ResponseParser      pid-10281                            D  parsePkgDataList(), response: {"code":"201001","message":"Success","packages":[{"package_name":"com.twitter.android","category_code":"non-game","game_genre":"N/A","device_group":"beyond0lte","game_oracle_cache":true,"cache":false}]}
2023-06-11 10:22:53.653 10281-11031 GOS:ResponseParser      pid-10281                            D  code: 201001
2023-06-11 10:22:53.653 10281-11031 GOS:ResponseParser      pid-10281                            D  message: Success
2023-06-11 10:22:53.653 10281-11031 GOS:ResponseParser      pid-10281                            D  parsePkgDataList(), pkgArray: [{"package_name":"com.twitter.android","category_code":"non-game","game_genre":"N\/A","device_group":"beyond0lte","game_oracle_cache":true,"cache":false}]
2023-06-11 10:22:53.653 10281-11031 GOS:ResponseParser      pid-10281                            D  parsePkgDataJsonObj()
2023-06-11 10:22:53.653 10281-11031 GOS:ResponseParser      pid-10281                            D  parsePkgDataJsonObj(), packageName: com.twitter.android
2023-06-11 10:22:53.653 10281-11031 GOS:PackageDAO          pid-10281                            D  getPkgData(), begin
2023-06-11 10:22:53.674 10281-11031 GOS:PkgData             pid-10281                            D  PkgData(), pkgName: com.twitter.android
2023-06-11 10:22:53.674 10281-11031 GOS:PkgData             pid-10281                            D  setCustomFeatureFlag, pkgName: com.twitter.android, old featureFlag: 342277969730895875, new featureFlag: 342277969730895875
2023-06-11 10:22:53.676 10281-11031 GOS:ResponseParser      pid-10281                            D  parsePkgDataJsonObj(), serverCategory and category are same. non-game
2023-06-11 10:22:53.676 10281-11031 GOS:ResponseParser      pid-10281                            D  game_genre: N/A
2023-06-11 10:22:53.676 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for each_mode_dss
2023-06-11 10:22:53.677 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for default_dss
2023-06-11 10:22:53.677 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for each_mode_dfs
2023-06-11 10:22:53.677 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for default_dfs
2023-06-11 10:22:53.677 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for feature_flag_inst
2023-06-11 10:22:53.678 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for aspect_ratio_values
2023-06-11 10:22:53.678 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for siop_level
2023-06-11 10:22:53.678 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for default_cpu_level
2023-06-11 10:22:53.678 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for default_gpu_level
2023-06-11 10:22:53.678 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for each_mode_target_short_side
2023-06-11 10:22:53.678 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for default_target_short_side
2023-06-11 10:22:53.678 10281-11031 GOS:ResponseParser      pid-10281                            D  No value for governor_settings
2023-06-11 10:22:53.678 10281-11031 GOS:ResponseParser      pid-10281                            D  JSONException. No value for shift_temperature
2023-06-11 10:22:53.678 10281-11031 GOS:ResponseParser      pid-10281                            D  JSONException. No value for game_sdk
2023-06-11 10:22:53.678 10281-11031 GOS:ResponseParser      pid-10281                            D  parsePkgDataJsonObj(), pkgName: com.twitter.android, customFeatureFlag: 342277969730895875
2023-06-11 10:22:53.679 10281-11031 GOS:ResponseParser      pid-10281                            D  parsePkgDataJsonObj(), get data from existingPkgData, pkgName: com.twitter.android, customFeatureFlag: 342277969730895875
2023-06-11 10:22:53.681 10281-11031 GOS:FeaturePolicyParser pid-10281                            D  FeaturePolicyParser(), map : {os_sdk_ver=28.0, optimizer_ver=2110.0, manager_ver=90.014, service_ver=11.0}
2023-06-11 10:22:53.681 10281-11031 GOS:PkgData             pid-10281                            D  PkgData(), pkgName: com.twitter.android
2023-06-11 10:22:53.681 10281-11031 GOS:PkgData             pid-10281                            D  setCustomFeatureFlag, pkgName: com.twitter.android, old featureFlag: 342277969730895875, new featureFlag: 342277969730895875
2023-06-11 10:22:53.682 10281-11031 GOS:FeaturePolicyParser pid-10281                            D  FeaturePolicyParser(), map : {os_sdk_ver=28.0, optimizer_ver=2110.0, manager_ver=90.014, service_ver=11.0}
2023-06-11 10:22:53.682 10281-11031 GOS:ResponseParser      pid-10281                            D  parsePkgDataJsonObj(), SOS policy : null
2023-06-11 10:22:53.682 10281-11031 GOS:PackageDAO          pid-10281                            D  updateOrAddPkgDataList(), begin
2023-06-11 10:22:53.683 10281-11031 GOS:PackageDAO          pid-10281                            D  getPackageRO(), begin
2023-06-11 10:22:53.701 10281-11031 GOS:PackageDAO          pid-10281                            D  updateTimeStamp() - TimeStampOpt.ADD_PKG_DATA:
2023-06-11 10:22:53.702 10281-11031 GOS:PackageDAO          pid-10281                            D  updateTimeStamp(): com.twitter.android
2023-06-11 10:22:53.702 10281-11031 GOS:PackageDAO          pid-10281                            D  updateTimeStamp() - PkgAddedTime: 2023-06-11 10:17:02 AEST
2023-06-11 10:22:53.702 10281-11031 GOS:PackageDAO          pid-10281                            D  updateTimeStamp() - ServerPkgUpdatedTime: 2023-06-11 10:22:53 AEST
2023-06-11 10:22:53.774 10281-11031 GOS:SystemEventReactor  pid-10281                            D  addPkgDataFromServer(), A package was added : com.twitter.android as non-game
2023-06-11 10:22:53.796 10281-11031 GOS:PkgData             pid-10281                            D  PkgData(), pkgName: com.twitter.android
2023-06-11 10:22:53.797 10281-11031 GOS:PkgData             pid-10281                            D  setCustomFeatureFlag, pkgName: com.twitter.android, old featureFlag: 342277969730895875, new featureFlag: 342277969730895875
2023-06-11 10:22:53.804 10281-10281 GOS:MainIntentService   pid-10281                            D  onDestroy
2023-06-11 10:22:53.816  5771-6550  Pageboost               pid-5771                             I  Launcher App Execution
2023-06-11 10:22:53.925  5771-6550  Pageboost               pid-5771                             I  Launcher App Execution
2023-06-11 10:22:54.019  5771-9721  GameManagerService      pid-5771                             D  identifyGamePackage. com.google.android.packageinstaller, mCurrentUserId: 0, callerUserId: 0
2023-06-11 10:22:54.020  5771-9721  GamePkgDataHelper       pid-5771                             D  getGamePkgData(). com.google.android.packageinstaller
2023-06-11 10:22:54.084 32068-11043 Finsky                  pid-32068                            I  [7217] agoe.f(3): VerifyApps: Verification package=com.twitter.android, id=43, response=0, upload_requested=false
2023-06-11 10:22:54.135 32068-11032 PackageParser           pid-32068                            W  Unknown element under <manifest>: queries at /data/app/vmdl1088522029.tmp/base.apk Binary XML file line revanced/revanced-patcher#30
2023-06-11 10:22:54.137 32068-11032 PackageParser           pid-32068                            W  Unknown element under <application>: profileable at /data/app/vmdl1088522029.tmp/base.apk Binary XML file line revanced/revanced-patcher#125
2023-06-11 10:22:54.354 32068-11032 Finsky                  pid-32068                            I  [7213] VerifyMissingSplitsInstallTask.agK(13): Package com.twitter.android blocked since it is missing required splits.
2023-06-11 10:22:54.354 32068-11032 Finsky                  pid-32068                            I  [7213] VerifyInstallTask.k(2): VerifyApps: Returning package verification result id=43, result=REJECT
2023-06-11 10:22:54.355  5771-8495  PackageManager          pid-5771                             D  [VERIFY] verifyPendingInstall(43, REJECT), uid=10069
2023-06-11 10:22:54.355  5771-5817  PackageManager          pid-5771                             D  [VERIFY] PACKAGE_VERIFIED: 
                                                                                                    PackageVerificationState{
                                                                                                        verifier packages=com.android.vending(10069),com.samsung.android.sm.devicesecurity(5012),
                                                                                                        intent=Intent { act=android.intent.action.PACKAGE_NEEDS_VERIFICATION dat=file:///data/app/vmdl1088522029.tmp typ=application/vnd.android.package-archive flg=0x10000001 cmp=com.android.vending/com.google.android.finsky.verifier.impl.PackageVerificationReceiver (has extras) }
                                                                                                        others=43, false, false, false, false, false
                                                                                                    }
2023-06-11 10:22:54.355  5771-5817  PackageManager          pid-5771                             D  [VERIFY] setVerifierResponse {verificationID=43, uid=10069, code=-1}
2023-06-11 10:22:54.355  5771-5817  PackageManager          pid-5771                             D  [VERIFY] packageVerificationCompletion: completed id=43
2023-06-11 10:22:54.358 32068-32068 Finsky                  pid-32068                            I  [2] VerifyInstallTask.agJ(7): VerifyApps: Verification complete: id=43, package_name=com.twitter.android
2023-06-11 10:22:54.359 32068-32068 Finsky                  pid-32068                            I  [2] agtr.i(3): VerifyApps: Install verification already finished, ignoring sub-task callback, id=43
2023-06-11 10:22:54.363  5771-5817  PackageManager          pid-5771                             D  result of install: -22{29641316}
2023-06-11 10:22:54.375  5771-5782  ActivityManager         pid-5771                             I  START u0 {act=null typ=null flg=0x2000000 cmp=ComponentInfo{com.google.android.packageinstaller/com.android.packageinstaller.InstallFailed}} from uid 10047
```

### Screenshots or videos

![Screenshot_20230528-130207](https://github.com/revanced/revanced-manager/assets/59689/cc58eab6-379c-41a5-a58e-a2c387b90fac)

Device info
![Screenshot_20230528-130348](https://github.com/revanced/revanced-manager/assets/59689/648ccb73-7e18-4091-baa1-3187e996637c)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by twig** [comment]
The error seems to be at this line

> VerifyMissingSplitsInstallTask

Recording https://imgur.com/a/AdjWyCZ

**Comment by oSumAtrIX** [comment]
Have you tried installnig the APK file without patching it?

**Comment by twig** [comment]
Yep, it installs fine

![Screenshot_20230612-085750_Package installer.jpg](https://github.com/revanced/revanced-patches/assets/59689/961ccba6-02db-438c-bc27-578e17d78094)

**Comment by oSumAtrIX** [comment]
Exclude patches one by one and check which one causes this issue

**Comment by twig** [comment]
Yep will do.

FYI playing around with it a bit, just got this notification when trying to patch the APK installed from Play store

![Screenshot_20230612-090801.jpg](https://github.com/revanced/revanced-patches/assets/59689/5df17e34-7f92-4677-87c7-f4916c2fa5ab)

Interesting because my phone should be arm v8.

![Screenshot_20230612-091915_Device Info HW.jpg](https://github.com/revanced/revanced-patches/assets/59689/e5c2863d-ca30-4027-b75e-1c7894b67bea)

**Comment by oSumAtrIX** [comment]
This is a ReVanced Manager issue, try on CLI

**Comment by twig** [comment]
So I looked up the [docs for Revanced CLI](https://github.com/revanced/revanced-documentation/blob/main/docs/revanced-cli) and didn't get much...

the recommended Reddit posts are all locked down due to blackout

so I gave it a try myself and this is as far as I got through guess-work

```
jdk-20.0.1\bin\java.exe -jar revanced-cli-2.21.3-all.jar -b revanced-patches-2.177.0.jar -a "com.twitter.android_9.71.0-release.0-29710000_minAPI21(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk" -o twitter.apk -i remove-ads
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Skipping change-package-name: Excluded by default
INFO: Skipping enable-android-debugging: Excluded by default
INFO: Skipping export-all-activities: Excluded by default
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Skipping remove-screen-capture-restriction: Excluded by default
INFO: Skipping remove-screenshot-restriction: Excluded by default
INFO: Skipping spoof-wifi-connection: Excluded by default
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
INFO: dynamic-color succeeded
SEVERE: hide-ads failed:
app.revanced.patcher.patch.PatchResultError: 'hide-ads' depends on 'json-hook' but the following error was raised: app.revanced.patcher.patch.PatchResultError: Could not find integrations.
        at app.revanced.patches.twitter.misc.hook.json.patch.JsonHookPatch.execute(JsonHookPatch.kt:33)
        at app.revanced.patches.twitter.misc.hook.json.patch.JsonHookPatch.execute(JsonHookPatch.kt:22)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: hide-recommended-users failed:
app.revanced.patcher.patch.PatchResultError: 'hide-recommended-users' depends on 'json-hook' but the following error was raised: 'json-hook' did not succeed previously
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: hide-views-stats succeeded
kotlin.UninitializedPropertyAccessException: lateinit property hooks has not been initialized
        at app.revanced.patches.twitter.misc.hook.json.patch.JsonHookPatch$Companion.getHooks$revanced_patches(JsonHookPatch.kt:150)
        at app.revanced.patches.twitter.misc.hook.json.patch.JsonHookPatch.close(JsonHookPatch.kt:134)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:363)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

Let me know if I'm missing anything.

**Comment by oSumAtrIX** [comment]
>  'hide-ads' depends on 'json-hook' but the following error was raised: PatchResultError: Could not find integrations.

You are missing merging the integrations. Do so with `-m`

**Comment by twig** [comment]
ah so I added `-m revanced-integrations-0.110.0.apk` and it compiled an APK successfully

I finally see the reason why the APKs are failing to install. This popup appears when trying to install the generated APK

I tried using `-i change-package-name` but unsure how to pass in the name of the alternative package and can't seem to find non-reddit docs for it anywhere

```
INFO: Decoding resources
SEVERE: change-package-name failed:
app.revanced.patcher.patch.PatchResultError: No package name provided
        at app.revanced.patches.all.misc.packagename.patch.ChangePackageNamePatch.execute(ChangePackageNamePatch.kt:35)
        at app.revanced.patches.all.misc.packagename.patch.ChangePackageNamePatch.execute(ChangePackageNamePatch.kt:11)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

**Comment by oSumAtrIX** [comment]
Check `--options` and if you are at it, `--help`.

**Comment by twig** [comment]
hah `--help` is the only reason I've gotten this far, but it's pretty hard to guess what half the args are without context of how the whole thing works together

ok so I found that `--options` works in conjunction with `options.json` which contains the custom apk name

patched with renamed package, APK still triggers Play protection 😑

**Comment by twig** [comment]
Thanks for highlighting "install anyway", I didn't notice it was clickable.

> There is no changing package name for Reddit, idk how you applied it

This was regarding me trying to find information on how to use the CLI, and most of the results were linking to Reddit posts (not app) which are no longer visible due to the blackout.
