### ISSUE TITLE
bug: building failed `java.lang.NoClassDefFoundError`

### ISSUE THREAD

**Issue by cyberboh** [revanced/revanced-patches#2408]
### Type

Error while patching

### Bug description

Building all apps failed, e.g i tried to build intagram

### Steps to reproduce

1. build with j-hc tool `https://github.com/j-hc/revanced-magisk-module`
2. it will fail while building process

### Relevant log output

```shell
[+] Building 'Instagram (arm64-v8a)' in 'apk' mode
[+] java -jar temp/jhc-rv/revanced-cli-2.22.0-all.jar --rip-lib x86_64 --rip-lib x86 --temp-dir=temp/tmp.5wWYyQKSub -c -a temp/com.instagram.android-275.0.0.27.98-arm64-v8a.apk -o temp/instagram-revanced-275.0.0.27.98-arm64-v8a.apk -b temp/revanced-rv/revanced-patches-2.176.1.jar --keystore=ks.keystore   -m temp/revanced-rv/revanced-integrations-0.110.0.apk
INFO: Reading dex files 
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping change-package-name: Excluded by default 
INFO: Skipping custom-branding: Manually excluded 
INFO: Skipping custom-video-buffer: Excluded by default 
INFO: Skipping enable-android-debugging: Excluded by default 
INFO: Skipping export-all-activities: Excluded by default 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping remove-player-controls-background: Excluded by default 
INFO: Skipping remove-screen-capture-restriction: Excluded by default 
INFO: Skipping remove-screenshot-restriction: Excluded by default 
INFO: Skipping spoof-wifi-connection: Excluded by default 
INFO: Merging temp/revanced-rv/revanced-integrations-0.110.0.apk 
INFO: Skipping change-package-name: Excluded by default 
INFO: Skipping enable-android-debugging: Excluded by default 
INFO: Skipping export-all-activities: Excluded by default 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping remove-screen-capture-restriction: Excluded by default 
INFO: Skipping remove-screenshot-restriction: Excluded by default 
INFO: Skipping spoof-wifi-connection: Excluded by default 
INFO: Skipping change-package-name: Excluded by default 
INFO: Skipping enable-android-debugging: Excluded by default 
INFO: Skipping export-all-activities: Excluded by default 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping remove-screen-capture-restriction: Excluded by default 
INFO: Skipping remove-screenshot-restriction: Excluded by default 
INFO: Skipping spoof-wifi-connection: Excluded by default 
Error: Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/extensions/InstructionExtensions
	at app.revanced.patches.instagram.patches.ads.timeline.patch.HideTimelineAdsPatch.execute(HideTimelineAdsPatch.kt:58)
	at app.revanced.patches.instagram.patches.ads.timeline.patch.HideTimelineAdsPatch.execute(HideTimelineAdsPatch.kt:24)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:328)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:172)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.extensions.InstructionExtensions
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 19 more
[+] Building 'Instagram (arm-v7a)' failed!
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Unofficial tools
