### ISSUE TITLE
bug(tiktok): version 30.0.2 fails to patch

### ISSUE THREAD

**Issue by xscd** [ReVanced/revanced-patches#2426]
### Type

Error while patching

### Bug description

tiktok bumped a major version and that one fails to patch

### Steps to reproduce

1) get the latest (30.0.2) tiktok apk
2) try to patch (java -jar revanced-cli-2.21.3-all.jar -a tiktok.apk -c -o re-tiktok.apk -b revanced-patches-2.177.1-dev.2.jar -m revanced-integrations-0.110.1-dev.2.apk)
3) see fail

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x6a020000 
INFO: Skipping change-package-name: Excluded by default 
INFO: Skipping enable-android-debugging: Excluded by default 
INFO: Skipping export-all-activities: Excluded by default 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping remove-screen-capture-restriction: Excluded by default 
INFO: Skipping remove-screenshot-restriction: Excluded by default 
INFO: Skipping sim-spoof: Excluded by default 
INFO: Skipping spoof-wifi-connection: Excluded by default 
INFO: Merging revanced-integrations-0.110.1-dev.2.apk 
INFO: disable-login-requirement succeeded 
SEVERE: downloads failed: 
app.revanced.patcher.patch.PatchResultError: 'downloads' depends on 'settings' but the following error was raised: Hardcoded offset changed.
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
SEVERE: feed-filter failed: 
app.revanced.patcher.patch.PatchResultError: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: fix-google-login succeeded 
INFO: hide-ads succeeded 
INFO: playback-speed succeeded 
SEVERE: settings failed: 
app.revanced.patcher.patch.PatchResultError: 'settings' did not succeed previously
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:290)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: show-seekbar succeeded 
INFO: Not compiling resources because resource patching is not required 
INFO: Writing modified dex files 
INFO: Aligning tiktok.apk to re-tiktok_aligned.apk 
INFO: Signing re-tiktok_aligned.apk to re-tiktok_signed.apk 
INFO: Found existing keystore: re-tiktok.keystore 
INFO: Copying re-tiktok_signed.apk to re-tiktok.apk 
INFO: Cleaned up cache directory 
INFO: Finished 

```
```


### Screenshots or videos

_No response_

### Solution

_No response_

### Additional context

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Everytime the patch failed, it was due to the hardcoded offset. This should be changed

**Comment by samaraboy** [comment]
> Everytime the patch failed, it was due to the hardcoded offset. This should be changed

Versions 30.0.1, 30.0.2 do not work. 29.9.4 and below versions work. I was clearing caches reinstalling Revanced Manager

**Comment by irrweg** [comment]
Same Issues with version 30.1.3 & 30.2.2.
Clearing Cache and restarting Phone didn't help.

[revanced-manager_patcher_20230630184930338962.log](https://github.com/revanced/revanced-patches/files/11919125/revanced-manager_patcher_20230630184930338962.log)
[revanced-manager_patcher_20230630185219872852.log](https://github.com/revanced/revanced-patches/files/11919126/revanced-manager_patcher_20230630185219872852.log)
[revanced-manager_patcher_20230630185658789910.log](https://github.com/revanced/revanced-patches/files/11919127/revanced-manager_patcher_20230630185658789910.log)

**Comment by oSumAtrIX** [comment]
#2254
