### ISSUE TITLE
Gmscore patch fail on YT

### ISSUE THREAD

**Issue by Julienraptor01** [ReVanced/revanced-patches#2442]
### Bug description

Download the recommended version of YT on apkmirror
Apply the default patches
It will produce an error on the gmscore patch

### Error logs

```shell
- Device Info
ReVanced Manager: 1.17.3
Build: release
Model: SM-A528B
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.45.43 (Suggested: v18.45.43)
Patches version: v3.1.0
Patches added: Alternative thumbnails, Always autorepeat, Announcements, Bypass URL redirects, Change start page, Client spoof, Comments, Copy video url, Custom player overlay opacity, Disable auto captions, Disable fullscreen ambient mode, Disable player popup panels, Disable precise seeking gesture, Disable resuming Shorts on startup, Disable rolling number animations, Disable suggested video end screen, Disable zoom haptics, Enable debugging, Enable slide to seek, Enable tablet layout, External downloads, GmsCore support [GmsCore Vendor: com.mgoogle], HDR auto brightness, Hide 'Load more' button, Hide Shorts components, Hide ads, Hide album cards, Hide autoplay button, Hide breaking news shelf, Hide captions button, Hide cast button, Hide crowdfunding box, Hide email address, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Hide info cards, Hide layout components, Hide player buttons, Hide seekbar, Hide timestamp, Hide video action buttons, Minimized playback, Navigation buttons, Open links externally, Playback speed, Player flyout menu, Premium heading [Use premium heading: true], Remember video quality, Remove tracking query parameter, Restore old seekbar thumbnails, Restore old video quality menu, Return YouTube Dislike, Seekbar tapping, SponsorBlock, Spoof app version, Spoof device dimensions, Swipe controls, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Video ads, Wide searchbar
Patches removed: Hide ads, Video ads, Copy video url, External downloads, Disable precise seeking gesture, Seekbar tapping, Enable slide to seek, Swipe controls, Disable auto captions, Premium heading [Use premium heading: true], Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Hide breaking news shelf, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Hide email address, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Alternative thumbnails, Announcements, Always autorepeat, Enable debugging, Spoof device dimensions, Client spoof, Bypass URL redirects, Minimized playback, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Remember video quality, Playback speed, Restore old video quality menu, GmsCore support [GmsCore Vendor: com.mgoogle], Open links externally
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 62 patches
GmsCore support failed: app.revanced.patcher.patch.PatchException: Failed to resolve GmsCoreSupportFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
	at app.revanced.patches.shared.misc.gms.AbstractGmsCoreSupportPatch.execute(AbstractGmsCoreSupportPatch.kt:91)
	at app.revanced.patches.youtube.misc.gms.GmsCoreSupportPatch.execute(GmsCoreSupportPatch.kt:65)
	at app.revanced.patches.youtube.misc.gms.GmsCoreSupportPatch.execute(GmsCoreSupportPatch.kt:16)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched
```

### Additional context

The old patch for vanced micro did work
I tried uninstalling and reinstalling both vanced microg, Revanced manager and redowloading the apk 

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Julienraptor01** [comment]
> This could be manager still using old `options.json` , uninstall completely manager and install it should solve your issue.

I already did that, but i'll retry once again

**Comment by Julienraptor01** [comment]
> > > This could be manager still using old `options.json` , uninstall completely manager and install it should solve your issue.
> > 
> > I already did that, but i'll retry once again
> 
> Clearing it's data first 

I indeed did not clear It's data last time, i just did here and it fixed it...
I would expect data to be cleared upon uninstall of an app... But i guess this has to be a stupid Android thing of "we'll keep your data in case you want to reinstall it later" right ?
