### ISSUE TITLE
bug: youtube ReVanced custom branding

### ISSUE THREAD

**Issue by starstriker0** [ReVanced/revanced-patches#25]
### Bug description

when trying to use the custom branding icon feature it would fail saying the directory doesn't exist when I use the app to find it each time

### Error logs

```shell
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: VOG-L29
Android version: 10
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v18.45.43
Patches version: v2.202.0
Patches added: Alternative thumbnails, Announcements, Client spoof, Copy video url, Custom branding [App name: YouTube Premium, App icon: /data/user/0/app.revanced.manager.flutter/cache/111249047_p0_master1200.webp], Enable debugging, Enable tablet layout, External downloads, HDR auto brightness, Hide ads, Minimized playback, Navigation buttons, Open links externally, Playback speed, Premium heading [Use premium heading: true], Remember video quality, Remove screen capture restriction, Remove screenshot restriction, Restore old video quality menu, Return YouTube Dislike, Seekbar tapping, SponsorBlock, Spoof device dimensions, Swipe controls, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Vanced MicroG support, Video ads, Wide searchbar
Patches removed: Hide ads, Video ads, Copy video url, External downloads, Disable precise seeking gesture, Seekbar tapping, Enable slide to seek, Swipe controls, Disable auto captions, Premium heading [Use premium heading: true], Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Hide breaking news shelf, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Hide email address, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Alternative thumbnails, Announcements, Always autorepeat, Enable debugging, Spoof device dimensions, Client spoof, Bypass URL redirects, Vanced MicroG support, Minimized playback, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Remember video quality, Playback speed, Restore old video quality menu, Open links externally
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 29 patches
Custom branding failed: app.revanced.patcher.patch.PatchException: /data/user/0/app.revanced.manager.flutter/cache/111249047_p0_master1200.webp/mipmap-xxxhdpi/adaptiveproduct_youtube_background_color_108.png: open failed: ENOTDIR (Not a directory)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:185)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.io.FileNotFoundException: /data/user/0/app.revanced.manager.flutter/cache/111249047_p0_master1200.webp/mipmap-xxxhdpi/adaptiveproduct_youtube_background_color_108.png: open failed: ENOTDIR (Not a directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:63)
	at app.revanced.patches.youtube.layout.branding.CustomBrandingPatch.execute(CustomBrandingPatch.kt:92)
	at app.revanced.patches.youtube.layout.branding.CustomBrandingPatch.execute(CustomBrandingPatch.kt:13)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177)
	... 18 more
Caused by: android.system.ErrnoException: open failed: ENOTDIR (Not a directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8464)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 23 more
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by KobeW50** [comment]
> This is an issue in ReVanced Manager. You can ReVanced CLI or wait for a fix, or enter the full path manually given that you gave ReVanced Manager all files permission in the settings 

From my understanding, the issue is that the Manager uses content URIs (ie: `content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fcustom-icon`) while the patch only supports file URIs as input (ie: `/storage/emulated/0/Download/custom-icon`)

I was thinking that the solution should be for the patch to support content URIs, or for the user to be able to choose to use a file URI when selecting a path using the manager.

Lmk if i should open any issues, and if yes, for what and where.

**Comment by oSumAtrIX** [comment]
The patch supports a string with which a File object can be constructed. I don't know how ReVanced Manager should handle that
