### ISSUE TITLE
bug: Reddit (any version) not applying hide-ads, relies on hide-comments

### ISSUE THREAD

**Issue by zakafx** [revanced/revanced-patches#2504]
### Type

Error while patching

### Bug description

Was using patched 2023.9.1 version before. The other day I noticed my trending feat at the top was not updating after more than 24 hours of seeing the same images and topics. Cleared all of the apps data/cache, still no updating. Uninstalled patched app, tried latest version of the app and it was also showing the same problem (with ads of course). Tried to repatch 2023.9.1 again but am now getting a bunch of java errors relating to hide-comments patch. Tried to patch latest version of APK (2023.24.1) with same error output. Have tried 2023.20.1 as well. I have downgraded the manager just in case but that did not work. Am now on latest manager version again. I have been selecting the APK (obtained through apkmirror) using the "storage" option to patch, then installing after. I have tried clean installs and upgrade-type installs.

### Steps to reproduce

1. Obtain APK from apkmirror (2023.9.1, 2023.20.1, 2023.24.1)
2. Open manager app, select Patcher, select application.
3. Tap "Storage" and select APK from above
4. Apply hide-ads patch 
5. Seems to happen only if I select this patch. Have tried the others and they seem to work.

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Failed to apply hide-ads: 'hide-ads' depends on 'hide-comment-ads' but the following error was raised: java.lang.NullPointerException
	at app.revanced.patches.reddit.ad.comments.patch.HideCommentAdsPatch.execute(HideCommentAdsPatch.kt:22)
	at app.revanced.patches.reddit.ad.comments.patch.HideCommentAdsPatch.execute(HideCommentAdsPatch.kt:14)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:333)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:306)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Repacking patched apk
Compiling resources
Writing modified dex files
Finished!
Installing patched file using nonroot method
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by zakafx** [comment]
My apologies with aversioning. They end in .0, with the exception being 2023.9.1.

I tried 2023.21.0 as you suggested and it worked.

When I tried 2023.24.0 from play store, it didn't.

I will stay on 2023.21.0. my only issue with this version is that the font is smaller than 2023.9.1.

Thank you for your timely responses.
