### ISSUE TITLE
bug: Unable to patch instagram and tiktok

### ISSUE THREAD

**Issue by Temepest74** [ReVanced/revanced-patches#2511]
### Bug description

I am unable to patch instagram and tiktok, I took them from apkmirror. I will post the logs/patches for both aps, in this order: instagram -> tiktok

### Error logs

```shell
- Device Info
ReVanced Manager: 1.17.3
Build: release
Model: SM-A536B
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.instagram.android v275.0.0.27.98 (Suggested: v275.0.0.27.98)
Patches version: v3.1.0
Patches added: Change package name [Package name: Default], Hide timeline ads, Remove screen capture restriction, Remove screenshot restriction
Patches removed: Hide timeline ads
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 4 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~aJMG2M1Jpw325iqpMpbfHQ==/app.revanced.manager.flutter-MeZZ2daf7u1YTFF1crdbng==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RJBTOV/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RJBTOV/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:354)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~aJMG2M1Jpw325iqpMpbfHQ==/app.revanced.manager.flutter-MeZZ2daf7u1YTFF1crdbng==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RJBTOV/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RJBTOV/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
	... 7 more
========================================================================
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 48 byte allocation with 1813648 free bytes and 1771KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.nio.CharBuffer.allocate(CharBuffer.java:172)
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:797)
	at brut.androlib.res.decoder.StringBlock.decodeString(StringBlock.java:225)
	at brut.androlib.res.decoder.StringBlock.getString(StringBlock.java:115)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:409)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:334)
	at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(ARSCDecoder.java:95)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:44)
	at brut.androlib.res.data.ResTable.loadResPackagesFromApk(ResTable.java:182)
	at brut.androlib.res.data.ResTable.loadMainPkg(ResTable.java:134)
	at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:148)
	at app.revanced.patcher.data.ResourceContext.decodeResources$revanced_patcher(ResourceContext.kt:51)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:195)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Additional context

- Device Info
ReVanced Manager: 1.17.3
Build: release
Model: SM-A536B
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.instagram.android v275.0.0.27.98 (Suggested: v275.0.0.27.98)
Patches version: v3.1.0
Patches added: Change package name [Package name: Default], Hide timeline ads, Remove screen capture restriction, Remove screenshot restriction
Patches removed: Hide timeline ads
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations
===============================================
- Device Info
ReVanced Manager: 1.17.3
Build: release
Model: SM-A536B
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.zhiliaoapp.musically v32.5.3 (Suggested: v32.5.3)
Patches version: v3.1.0
Patches added: Change package name [Package name: Default], Disable login requirement, Downloads, Feed filter, Fix Google login, Playback speed, Remove screen capture restriction, Remove screenshot restriction, Settings, Show seekbar
Patches removed: Feed filter, Downloads, Show seekbar, Playback speed, Disable login requirement, Fix Google login, Settings
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Temepest74** [comment]
@oSumAtrIX  closing just for the sake of it?
