### ISSUE TITLE
bug: latest Relay For Reddit 11.0.19 can't be patched due to being unable to find the client ID fingerprint

### ISSUE THREAD

**Issue by autovalue** [ReVanced/revanced-patches#2532]
### Bug description

Attempting to spoof the client ID returns in a crash of the patcher.
It's apparently unable to resolve the client ID fingerprint.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.17.3
Build: release
Model: SM-G998B
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: reddit.news v11.0.19 (Suggested: Any)
Patches version: v3.1.0
Patches added: Spoof client [OAuth client ID: <redacted>]
Patches removed: Spoof client [OAuth client ID: <redacted>]
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Executing patches
Spoof client failed: app.revanced.patcher.patch.PatchException: Failed to resolve LoginActivityClientIdFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
	at app.revanced.patches.reddit.customclients.AbstractSpoofClientPatch.execute$executePatch(AbstractSpoofClientPatch.kt:44)
	at app.revanced.patches.reddit.customclients.AbstractSpoofClientPatch.execute(AbstractSpoofClientPatch.kt:46)
	at app.revanced.patches.reddit.customclients.AbstractSpoofClientPatch.execute(AbstractSpoofClientPatch.kt:11)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 4 dex files
Signing APK
Patched
```

### Additional context

Installed the app from the play store, then extracted the APK and attempted to patch that.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by autovalue** [comment]
I've attached a copy of the `LoginActivity.smali`, it seems that the pro version uses a different `client_id` and `redirect_uri` than what we have in the patcher.

The client ID is now `Zc9CN7DbImGrdkXonahfUQ` rather than `dj-xCIZQYiLbEg`.
And the Redirect URI is now `https://www.relayforreddit.com` rather than `dbrady://relay`.

So it probably needs special handling for both instances if possible.

[LoginActivity.smali.txt](https://github.com/ReVanced/revanced-patches/files/13760450/LoginActivity.smali.txt)

--------

@cyberboh What would you recommend? From looking at the xapk file, the split apk is fairly simple, and we don't patch any of the split files.

**Comment by oSumAtrIX** [comment]
The fingerprints can be resolved if either client ID is present to fix this. Please check if the regular variant updates the client id and redirect uri as well in the future as we can simply use the new redirect uri & client id in that case.

**Comment by KobeW50** [comment]
> Please check if the regular variant updates the client id and redirect uri as well in the future as we can simply use the new redirect uri & client id in that case.

The standard Relay app hasn't been updated since August. The fingerprints can still be resolved

**Comment by oSumAtrIX** [comment]
I can only find a single version of Relay on Play Store

**Comment by oSumAtrIX** [comment]
I do  it understand what you mean. The sentence is incomplete

**Comment by KobeW50** [comment]
> I can only find a single version of Relay on Play Store

Cyberboh means that this Relay currently on the Play store is Relay Pro (reddit.news)

Regular Relay can only be found on APK sites, since it is not being developed and was removed from the Play store.

**Comment by oSumAtrIX** [comment]
In this case support for the old version can be dropped and the new version can be patched

**Comment by Yukai-Qian** [comment]
In case anyone needs it, this is the APK bundle of Relay Pro 11.0.19. Installing from split APK files is a bit more complicated than standalone APK, requiring a tool such as Split APKs Installer, but it's doable. I think it suffices that ReVanced just patches the base.apk. Then we can manually save the patched version and overwrite the original base.apk.

[Relay_Pro_11.0.19.zip](https://github.com/ReVanced/revanced-patches/files/13847972/Relay_Pro_11.0.19.zip)

**Comment by oSumAtrIX** [comment]
Please avoid sending binary files and get them from their original/trusted source

**Comment by Yukai-Qian** [comment]
Fair, I was just hoping to help people who arrived at this issue. In that case I'll just describe how to get them. I downloaded the APKs through [Aurora Store](https://gitlab.com/AuroraOSS/AuroraStore), which I configured to save its downloads to a user-accessible path, through Settings > Downloads. This process will give split APK files.

It seems a universal APK has not been made by anyone yet.

**Comment by Aryan-Chauhan** [comment]
I converted Relay Pro v11.0.9 split-APKs to normal APK.

Then I tried to patch it, but getting errors.

I also used https://www.relayforreddit.com as Redirect URI.

**Comment by Yukai-Qian** [comment]
> I converted Relay Pro v11.0.9 split-APKs to normal APK.
> 
> Then I tried to patch it, but getting errors.

We need to wait for the author to update the patch so it supports Relay Pro.

**Comment by folkemat** [comment]
Guys, the new Relay versions all have a prompt for the payment, they will never work just by changing the id. Bypassing the payment is also against Revanced's guidelines. You have to use the old versions.

**Comment by oSumAtrIX** [comment]
Because the client id changes the developer is not charged which is why this falls under the acceptable by case by case scenario

**Comment by KobeW50** [comment]
> Because the client id changes the developer is not charged which is why this falls under the acceptable by case by case scenario 

The developer is still losing out on profits that would've been made from users who would've paid for the subscription plan. This is because the subscription plan is not only to cover the costs of the API calls, but also for the "Pro" features that Relay offers.

This table on the Relay FAQ page explains how the money gets split.

![Screenshot_20240117_112555_Relay Pro.jpg](https://github.com/ReVanced/revanced-patches/assets/84587632/a5ef2180-3397-4041-8eaa-45eadc773a78)

The dev loses a minimum of $0.52 profit per month if a private client ID would be used.

**Comment by oSumAtrIX** [comment]
With every pro unlocking patch this is an implication that is too obvious to be necessary to point out. Regardless my previous comment remains as the developer still is not charged as the client id is changed and therefore this falls under the acceptable case.

**Comment by Toiletmason** [comment]
Is this dead?

**Comment by limaceous-bushwhacker** [comment]
> Is this dead?

Looks like it. Maybe you can try Infinity.

**Comment by mateus2k2** [comment]
Is it possible to convert the xapk to an apk, bypass pairip, decompile the apk, modify the apk directly then recompile it? 

I think the hardest part would be to bypass pairip, found this method on the internet, no ideia if it would work. https://platinmods.com/threads/how-to-bypass-pairip-protections-latest-too-easy.203105/

Then I have no ideia how hard it is to modify the apk directly. Is it as easy as changing the lines in LoginActivity.smali?

**Comment by barium56** [comment]
So I tried some stuff out, got further then I thought but it's still not enough. Writing this here to maybe catch someone more knowledgeable. 

I used Lucky Patcher mostly for convince, steps I do with it can be done otherwise. 

Removed Pairip with [this](https://github.com/Technoindian/RKPairip) by creating an .apks with Lucky Patcher, -x worked for relay 13.0.16. 

Manually patched clientid (still `Zc9CN7DbImGrdkXonahfUQ` and 4 instances to replace), verified it works by starting the oauth activity manually, my own application shows up. Used the redirect_url `https://www.relayforreddit.com`. 
I used apktool for decompiling and rebuilding (the pairip removed apk) and using Lucky Patcher to add back the original app signature. 

Don't know how to bypass the Subscription screen. Got the 3 day trial and used it on the patch app just to see if patching the clientid worked correctly, but sadly nothing loads but the subscription screen is theoretically bypassed (for testing). 

I tried also patching the opcode with the `Reddit Disabled` mentioned in the [original patch](https://github.com/ReVanced/revanced-patches/tree/7e9bb8568bf4dbcab10762ef729391d7f8bbaac2/patches/src/main/kotlin/app/revanced/patches/reddit/customclients/relayforreddit/api), found it by comparing decompiled patched old 10.2.40 relay app. Didn't make anything magically work so I don't know at all what it does. Didn't find the `FirebaseRemoteConfig` thing.

**Comment by ZxeTV** [comment]
> > Really cool, any way you could elaborate on the steps to do this.
> 
> I basically patched everything in the original patches and some client ids more by searching in all files, for the alternative login to work there was some binary needed to be modified, something like that.
> 
> > And any advancements on bypassing the screen?
> 
> No. I'm not knowledgeable enough to figure out how to do it. I randomly changed some stuff so far without a real understanding but no luck (so far?).

Hi can u link me ur rkpairip relay. I'll see what I can do with the subscription page
