### ISSUE TITLE
bug: Sync for Reddit change-oauth-client-id patch fails when being applied via ReVanced CLI

### ISSUE THREAD

**Issue by Thogsit** [revanced/revanced-patches#2551]
### Type

Error while patching

### Bug description

Because applying the patch on Android 10 with ReVanced Manager didn't work at first (same as in #2546) I tried to to use the ReVanced CLI.

The complete output including the installed Java version can be found below; the relevant error is `java.lang.NoSuchMethodException: app.revanced.patches.reddit.customclients.ChangeOAuthClientIdPatchAnnotation.<init>()`.

After following the previously mentioned issue's instructions, it finally worked on Android 10 with the Manager so I don't need the working CLI anymore, but still wanted to notify you of the bug if it's not known already.

### Steps to reproduce

Try to apply the patch from the ReVanced CLI, e.g. with `java -jar revanced-cli-2.21.4-all.jar -a sync_for_reddit.apk -b revanced-patches-2.179.0.jar -o sync_for_reddit_patched.apk`

### Relevant log output

```shell
❯ java -jar revanced-cli-2.21.4-all.jar -a sync_for_reddit.apk -b revanced-patches-2.179.0.jar -o sync_for_reddit_patched.apk       
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping change-package-name: Excluded by default 
INFO: Skipping enable-android-debugging: Excluded by default 
INFO: Skipping export-all-activities: Excluded by default 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping remove-screen-capture-restriction: Excluded by default 
INFO: Skipping remove-screenshot-restriction: Excluded by default 
INFO: Skipping spoof-wifi-connection: Excluded by default 
java.lang.NoSuchMethodException: app.revanced.patches.reddit.customclients.ChangeOAuthClientIdPatchAnnotation.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3685)
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2854)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

❯ java -version
openjdk version "20.0.1" 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9)
OpenJDK 64-Bit Server VM (build 20.0.1+9, mixed mode, sharing)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by drphero** [comment]
> #2548
> 
> Use the dev cli release until the main release is updated.

Now it gives this error:
`SEVERE: change-oauth-client-id failed:
app.revanced.patcher.patch.PatchResultError: No client ID provided
	at app.revanced.patches.reddit.customclients.AbstractChangeOAuthClientIdPatch.execute(AbstractChangeOAuthClientIdPatch.kt:22)
	at app.revanced.patches.reddit.customclients.AbstractChangeOAuthClientIdPatch.execute(AbstractChangeOAuthClientIdPatch.kt:11)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:333)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)`
