### ISSUE TITLE
bug (reddit): patch makes the app crash 

### ISSUE THREAD

**Issue by lpuglia** [ReVanced/revanced-patches#2571]
### Bug description

I'm using the following tools:

Java version: OpenJDK 17
CLI version: 4.4.0-all
Patch version: 3.2.0
Tested Reddit apk: 2023.47.0 and 2023.50.1

The patching process of the apk goes smoothly:

```
>  java -jar .\revanced-cli-4.4.0-all.jar patch -b .\revanced-patches-3.2.0.jar --exclusive --ii 132 .\com.reddit.frontpage_2023.47.0.apk
INFO: Loading patches
INFO: Decoding app manifest
INFO: Predictive back gesture excluded
INFO: Spoof Wi-Fi connection excluded
INFO: Spoof SIM country excluded
INFO: Override certificate pinning excluded
INFO: Enable Android debugging excluded
INFO: Change package name excluded
INFO: Remove screenshot restriction excluded
INFO: Remove screen capture restriction excluded
INFO: Export all activities excluded
INFO: Unlock premium Reddit icons excluded
INFO: Disable screenshot popup excluded
INFO: Sanitize sharing links excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: Hide ads succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Compiled classes9.dex
INFO: Compiled classes10.dex
INFO: Compiled classes11.dex
INFO: Compiled classes12.dex
INFO: Compiling modified resources
INFO: Aligning com.reddit.frontpage_2023.47.0.apk
INFO: Signing com.reddit.frontpage_2023.47.0.apk
INFO: Saved to C:\Users\Luca\Desktop\com.reddit.frontpage_2023.47.0-patched.apk
```
as well as the installation:
```
> .\adb.exe install com.reddit.frontpage_2023.47.0-patched.apk
Performing Streamed Install
Success
```
i can login from the installed app, but as soon as the feed gets populated with posts the app crashes. This happens every time I open the app. Are the tools i'm using at the correct version?

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please add crashlogs using logcat

**Comment by lpuglia** [comment]
here you are:
```
01-01 16:56:56.926 20178 20266 E AndroidRuntime: Process: com.reddit.frontpage, PID: 20178
01-01 16:56:56.926 20178 20266 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lapp/revanced/reddit/patches/FilterPromotedLinksPatch;
01-01 16:56:56.926 20178 20266 E AndroidRuntime:        at com.reddit.domain.model.listing.Listing.<init>(Listing.kt:2)
01-01 16:56:56.926 20178 20266 E AndroidRuntime:        at com.reddit.domain.model.listing.Listing.<init>(Listing.kt:12)
01-01 16:56:56.926 20178 20266 E AndroidRuntime:        at com.reddit.data.remote.RemoteGqlLinkDataSource.p(RemoteGqlLinkDataSource.kt:499)
01-01 16:56:56.926 20178 20266 E AndroidRuntime:        at com.reddit.link.impl.data.repository.RedditLinkRepository.S(RedditLinkRepository.kt:112)
01-01 16:56:56.926 20178 20266 E AndroidRuntime:        at com.reddit.feeds.impl.data.RedditFeedLinkRepository.d(RedditFeedLinkRepository.kt:236)
01-01 16:56:56.926 20178 20266 E AndroidRuntime:        at com.reddit.feeds.impl.domain.paging.RedditFeedPager$load$1.invokeSuspend(RedditFeedPager.kt:1301)
01-01 16:56:56.926 20178 20266 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: app.revanced.reddit.patches.FilterPromotedLinksPatch
```

**Comment by oSumAtrIX** [comment]
This patch needs integrations. Please merge [them](https://github.com/revanced/revanced-integrations/) using the option `-m`.

**Comment by lpuglia** [comment]
lovely, the solution was to download the release and do:
```
java -jar .\revanced-cli-4.4.0-all.jar patch -b .\revanced-patches-3.2.0.jar -m .\revanced-integrations-1.1.0.apk --exclusive --ii 132 .\com.reddit.frontpage_2023.50.1.apk
```
thanks again

**Comment by oSumAtrIX** [comment]
The APK does not need it. The specific patch does

**Comment by KobeW50** [comment]
The patch should error if it depends on integrations and those integrations weren't supplied by the user.

**Comment by oSumAtrIX** [comment]
@cyberboh The integrations are not supposed to be separate to begin with. The patches erroring out is just a workaround to that problem until they are merged.
