### ISSUE TITLE
bug: Revanced crashes on home screen.

### ISSUE THREAD

**Issue by AlessandroG200** [revanced/revanced-patches#258]
### Type

Error at runtime

### Bug description

When updating ReVanced using the versions provided in "Additional Context" (latest as of July 31st, 5 PM CEST), opening Revanced will crash after a few seconds. This can be avoided by quickly changing away from the home screen to the Library tab.

### Steps to reproduce

Download the Patches, CLI and integrations described on "Additional Context".
Youtube APK: 17.29.34

Run Revanced CLI with these parameters:

```
java -jar revanced-cli-2.8.0-all.jar -a Youtube.apk -c -d (ID from 'adb devices') -o revanced.apk -b revanced-patches-2.28.0.jar -m app-release-unsigned.apk -e microg-support -i enable-debugging --mount

```

### Relevant log output

```shell
07-31 17:34:26.280 10355 10355 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-31 17:34:26.283 10355 10355 I AndroidRuntime: Using default boot image
07-31 17:34:26.283 10355 10355 I AndroidRuntime: Leaving lock profiling enabled
07-31 17:34:26.369 10355 10355 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-31 17:34:26.393 10355 10355 D AndroidRuntime: Shutting down VM
07-31 17:34:26.825 10471 10471 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-31 17:34:26.828 10471 10471 I AndroidRuntime: Using default boot image
07-31 17:34:26.828 10471 10471 I AndroidRuntime: Leaving lock profiling enabled
07-31 17:34:26.928 10471 10471 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-31 17:34:26.939 10471 10471 D AndroidRuntime: Shutting down VM
07-31 17:34:27.895 10599 10599 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-31 17:34:27.899 10599 10599 I AndroidRuntime: Using default boot image
07-31 17:34:27.899 10599 10599 I AndroidRuntime: Leaving lock profiling enabled
07-31 17:34:27.997 10599 10599 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-31 17:34:28.007 10599 10599 D AndroidRuntime: Shutting down VM
07-31 17:34:28.976 10642 10642 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-31 17:34:28.979 10642 10642 I AndroidRuntime: Using default boot image
07-31 17:34:28.980 10642 10642 I AndroidRuntime: Leaving lock profiling enabled
07-31 17:34:29.063 10642 10642 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-31 17:34:29.081 10642 10642 D AndroidRuntime: Shutting down VM
07-31 17:34:30.057 10706 10706 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
07-31 17:34:30.060 10706 10706 I AndroidRuntime: Using default boot image
07-31 17:34:30.060 10706 10706 I AndroidRuntime: Leaving lock profiling enabled
07-31 17:34:30.152 10706 10706 D AndroidRuntime: Calling main entry com.android.commands.content.Content
07-31 17:34:30.163 10706 10706 D AndroidRuntime: Shutting down VM
07-31 17:34:30.623  4737  4737 E AndroidRuntime: FATAL EXCEPTION: main
07-31 17:34:30.623  4737  4737 E AndroidRuntime: Process: com.google.android.youtube, PID: 4737
07-31 17:34:30.623  4737  4737 E AndroidRuntime: aqrd: 2 exceptions occurred. 
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at arpw.b(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at arpw.sX(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at aqxj.sX(PG:10)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at arbg.g(PG:16)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at arbf.sX(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at aqzj.d(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at aqzj.sX(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at arra.a(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at arra.b(PG:7)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at arrb.sX(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at aavx.h(PG:4)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at xom.h(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at xza.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at xxl.u(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at xxl.g(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at xsj.at(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at ayv.a(PG:29)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at qy.run(PG:46)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at achd.j(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at achd.n(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at azh.ag(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at azh.km(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at axt.run(PG:35)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7833)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-31 17:34:30.623  4737  4737 E AndroidRuntime:   ComposedException 1 :
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:302)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at app.revanced.integrations.utils.SharedPrefHelper.getInt(SharedPrefHelper.java:39)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at app.revanced.integrations.patches.VideoQualityPatch.setVideoQuality(VideoQualityPatch.java:92)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at kjr.a(Unknown Source:4)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at iht.o(PG:7)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aaed.o(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aaeg.j(PG:14)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.google.android.libraries.youtube.mdx.player.MdxVideoQualitySelectorPresenter.j(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aadi.a(PG:44)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arpw.sX(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqxj.sX(PG:10)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arbg.g(PG:16)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arbf.sX(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqzj.d(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqzj.sX(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arra.a(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arra.b(PG:7)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arrb.sX(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aavx.h(PG:4)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xom.h(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xza.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xxl.u(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xxl.g(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xsj.at(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at ayv.a(PG:29)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at qy.run(PG:46)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at achd.j(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at achd.n(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at azh.ag(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at azh.km(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at axt.run(PG:35)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Handler.handleCallback(Handler.java:938)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Handler.dispatchMessage(Handler.java:99)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Looper.loopOnce(Looper.java:201)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Looper.loop(Looper.java:288)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.app.ActivityThread.main(ActivityThread.java:7833)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at java.lang.reflect.Method.invoke(Native Method)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.util.Log.getStackTraceString(Log.java:359)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aciu.uncaughtException(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at fme.uncaughtException(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at asmc.n(PG:12)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arpw.b(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arpw.sX(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqxj.sX(PG:10)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arbg.g(PG:16)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arbf.sX(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqzj.d(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqzj.sX(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arra.a(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arra.b(PG:7)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arrb.sX(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aavx.h(PG:4)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xom.h(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xza.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xxl.u(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xxl.g(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xsj.at(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at ayv.a(PG:29)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at qy.run(PG:46)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at achd.j(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at achd.n(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at azh.ag(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at azh.km(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at axt.run(PG:35)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Handler.handleCallback(Handler.java:938)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Handler.dispatchMessage(Handler.java:99)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Looper.loopOnce(Looper.java:201)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Looper.loop(Looper.java:288)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.app.ActivityThread.main(ActivityThread.java:7833)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at java.lang.reflect.Method.invoke(Native Method)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-31 17:34:30.623  4737  4737 E AndroidRuntime:   ComposedException 2 :
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	tdi: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at qpo.D(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aaax.a(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arpw.b(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arpw.sX(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqxj.sX(PG:10)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arbg.g(PG:16)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arbf.sX(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqzj.d(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqzj.sX(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arra.a(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arra.b(PG:7)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arrb.sX(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aavx.h(PG:4)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xom.h(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xza.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xxl.u(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xxl.g(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xsj.at(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at ayv.a(PG:29)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at qy.run(PG:46)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at achd.j(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at achd.n(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at azh.ag(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at azh.km(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at axt.run(PG:35)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Handler.handleCallback(Handler.java:938)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Handler.dispatchMessage(Handler.java:99)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Looper.loopOnce(Looper.java:201)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Looper.loop(Looper.java:288)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.app.ActivityThread.main(ActivityThread.java:7833)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at java.lang.reflect.Method.invoke(Native Method)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:302)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at app.revanced.integrations.utils.SharedPrefHelper.getInt(SharedPrefHelper.java:39)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at app.revanced.integrations.patches.VideoQualityPatch.setVideoQuality(VideoQualityPatch.java:92)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at kjr.a(Unknown Source:4)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at iht.o(PG:7)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aaed.o(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aaeg.j(PG:14)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.google.android.libraries.youtube.mdx.player.MdxVideoQualitySelectorPresenter.j(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aadi.a(PG:44)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arpw.sX(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqxj.sX(PG:10)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arbg.g(PG:16)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arbf.sX(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqzj.d(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqzj.sX(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arra.a(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arra.b(PG:7)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arrb.sX(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aavx.h(PG:4)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xom.h(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xza.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xxl.u(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xxl.g(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xsj.at(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at ayv.a(PG:29)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at qy.run(PG:46)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at achd.j(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at achd.n(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at azh.ag(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at azh.km(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at axt.run(PG:35)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Handler.handleCallback(Handler.java:938)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Handler.dispatchMessage(Handler.java:99)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Looper.loopOnce(Looper.java:201)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Looper.loop(Looper.java:288)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.app.ActivityThread.main(ActivityThread.java:7833)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at java.lang.reflect.Method.invoke(Native Method)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 	Caused by: java.lang.RuntimeException: Duplicate found in causal chain so cropping to prevent loop ...
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.util.Log.getStackTraceString(Log.java:359)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aciu.uncaughtException(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at fme.uncaughtException(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at asmc.n(PG:12)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arpw.b(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arpw.sX(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqxj.sX(PG:10)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arbg.g(PG:16)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arbf.sX(PG:3)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqzj.d(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aqzj.sX(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arra.a(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arra.b(PG:7)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at arrb.sX(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at aavx.h(PG:4)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xom.h(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xza.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xra.h(PG:1)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xxl.u(PG:6)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xxl.g(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at xsj.at(PG:5)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at ayv.a(PG:29)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at qy.run(PG:46)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at achd.j(PG:8)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at achd.n(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at azh.ag(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at azh.km(PG:2)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at axt.run(PG:35)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Handler.handleCallback(Handler.java:938)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Handler.dispatchMessage(Handler.java:99)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Looper.loopOnce(Looper.java:201)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.os.Looper.loop(Looper.java:288)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at android.app.ActivityThread.main(ActivityThread.java:7833)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at java.lang.reflect.Method.invoke(Native Method)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
07-31 17:34:30.623  4737  4737 E AndroidRuntime: 
INFO: Stopped logging because the app was closed
```

### Solution

Don't know.

### Additional context

Revanced Patches: 2.28.0
Revanced CLI: 2.8.0
Integrations: 0.30.1
YT: 17.29.34

openjdk 18.0.2 2022-07-19
OpenJDK Runtime Environment (build 18.0.2+9)
OpenJDK 64-Bit Server VM (build 18.0.2+9, mixed mode)

**Comment by Cypher-Emm** [comment]
Faced the same issue at first and fixed it by deleting cache folder from the directory where all of files needed for building rv are(folder in which you are building rv).If u have revanced.apk file in same directory(which in my case was there and shouldn't be as i was building root version) delete that. Then clear the data of youtube app and build again. Hope this works for you

**Comment by AlessandroG200** [comment]
Your solution worked (I built root btw), but I don't think that is intended to have to clear ReVanced's data when we upgraded. I will leave this issue open as I think that this is a regression from the settings patch.

**Comment by oSumAtrIX** [comment]
The cache folder gets deleted automatically before running ReVanced. Please try to reproduce the issue.

**Comment by AlessandroG200** [comment]
> The cache folder gets deleted automatically before running ReVanced. Please try to reproduce the issue.

Clearing ReVanced's data as @Cypher-Emm mentioned fixed the crash. Maybe when we first upgraded ReVanced's data from previous versions may have caused a conflict (not sure but I will give my 2 cents on the cause).
