### ISSUE TITLE
bug: Patching revanced app failed

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#2646]
### Bug description

As per update of patches today, i can't patch any revanced apps, ended up with failed error
I'm using CLI with this command for youtube:

```
java -jar revanced-cli-4.4.0-all.jar patch -r "revanced-cache" -p -o Install\YouTube_19.03.35-all_ReVanced.apk --options options.json -b revanced-patches-4.0.1.jar --alias=********** --keystore-password=********** --keystore-entry-password=********** --keystore=**********.keystore -m revanced-integrations-1.2.0.apk Apps\com.google.android.youtube-19.03.35-all.apk -i "Change header"
```

### Error logs

```shell
SEVERE: null failed:
app.revanced.patcher.patch.PatchException: 'null' raised an exception while being closed: app.revanced.patcher.patch.PatchException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:232)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.FileNotFoundException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at app.revanced.patcher.util.DomFileEditor.<init>(DomFileEditor.kt:41)
        at app.revanced.patcher.data.ResourceContext$XmlFileHolder.get(ResourceContext.kt:169)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close$invoke(AddResourcesPatch.kt:252)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close(AddResourcesPatch.kt:272)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:226)
        ... 23 more

        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:239)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: app.revanced.patcher.patch.PatchException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:232)
        ... 23 more
Caused by: java.io.FileNotFoundException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at app.revanced.patcher.util.DomFileEditor.<init>(DomFileEditor.kt:41)
        at app.revanced.patcher.data.ResourceContext$XmlFileHolder.get(ResourceContext.kt:169)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close$invoke(AddResourcesPatch.kt:252)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close(AddResourcesPatch.kt:272)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:226)
        ... 23 more
```

### Additional context

**Full logs:**

```
java -jar revanced-cli-4.4.0-all.jar patch -r "revanced-cache" -p -o Install\YouTube_19.03.35-all_ReVanced.apk --options options.json -b revanced-patches-4.0.1.jar --alias=********** --keystore-password=********** --keystore-entry-password=********** --keystore=**********.keystore -m revanced-integrations-1.2.0.apk Apps\com.google.android.youtube-19.03.35-all.apk -i "Change header"
INFO: Loading patches
INFO: Decoding app manifest
INFO: Predictive back gesture excluded
INFO: Remove screenshot restriction excluded
INFO: Spoof SIM country excluded
INFO: Enable Android debugging excluded
INFO: Override certificate pinning excluded
INFO: Change package name excluded
INFO: Export all activities excluded
INFO: Spoof Wi-Fi connection excluded
INFO: Remove screen capture restriction excluded
INFO: Enable slide to seek excluded
INFO: Remove player controls background excluded
INFO: Custom branding excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: Alternative thumbnails succeeded
INFO: Always repeat succeeded
INFO: Announcements succeeded
INFO: Bypass URL redirects succeeded
INFO: Change header succeeded
INFO: Change start page succeeded
INFO: Client spoof succeeded
INFO: Comments succeeded
INFO: Copy video URL succeeded
INFO: Custom player overlay opacity succeeded
INFO: Disable auto captions succeeded
INFO: Disable fullscreen ambient mode succeeded
INFO: Disable player popup panels succeeded
INFO: Disable precise seeking gesture succeeded
INFO: Disable resuming Shorts on startup succeeded
INFO: Disable rolling number animations succeeded
INFO: Disable suggested video end screen succeeded
INFO: Disable zoom haptics succeeded
INFO: Enable debugging succeeded
INFO: Enable tablet layout succeeded
INFO: External downloads succeeded
INFO: GmsCore support succeeded
INFO: HDR auto brightness succeeded
INFO: Hide 'Load more' button succeeded
INFO: Hide Shorts components succeeded
INFO: Hide ads succeeded
INFO: Hide album cards succeeded
INFO: Hide autoplay button succeeded
INFO: Hide breaking news shelf succeeded
INFO: Hide captions button succeeded
INFO: Hide cast button succeeded
INFO: Hide crowdfunding box succeeded
INFO: Hide endscreen cards succeeded
INFO: Hide filter bar succeeded
INFO: Hide floating microphone button succeeded
INFO: Hide info cards succeeded
INFO: Hide layout components succeeded
INFO: Hide player buttons succeeded
INFO: Hide seekbar succeeded
INFO: Hide timestamp succeeded
INFO: Hide video action buttons succeeded
INFO: Minimized playback succeeded
INFO: Navigation buttons succeeded
INFO: Open links externally succeeded
INFO: Playback speed succeeded
INFO: Player flyout menu succeeded
INFO: Remember video quality succeeded
INFO: Remove tracking query parameter succeeded
INFO: Remove viewer discretion dialog succeeded
INFO: Restore old seekbar thumbnails succeeded
INFO: Restore old video quality menu succeeded
INFO: Return YouTube Dislike succeeded
INFO: Seekbar tapping succeeded
INFO: SponsorBlock succeeded
INFO: Spoof app version succeeded
INFO: Spoof device dimensions succeeded
INFO: Swipe controls succeeded
INFO: Tablet mini player succeeded
INFO: Theme succeeded
INFO: Video ads succeeded
INFO: Wide searchbar succeeded
SEVERE: null failed:
app.revanced.patcher.patch.PatchException: 'null' raised an exception while being closed: app.revanced.patcher.patch.PatchException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:232)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.FileNotFoundException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at app.revanced.patcher.util.DomFileEditor.<init>(DomFileEditor.kt:41)
        at app.revanced.patcher.data.ResourceContext$XmlFileHolder.get(ResourceContext.kt:169)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close$invoke(AddResourcesPatch.kt:252)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close(AddResourcesPatch.kt:272)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:226)
        ... 23 more

        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:239)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: app.revanced.patcher.patch.PatchException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:232)
        ... 23 more
Caused by: java.io.FileNotFoundException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at app.revanced.patcher.util.DomFileEditor.<init>(DomFileEditor.kt:41)
        at app.revanced.patcher.data.ResourceContext$XmlFileHolder.get(ResourceContext.kt:169)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close$invoke(AddResourcesPatch.kt:252)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close(AddResourcesPatch.kt:272)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:226)
        ... 23 more

INFO: Change package name succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Compiling modified resources
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\layout\revanced_sb_inline_sponsor_overlay.xml:4: error: resource string/revanced_sb_skip_button_compact_highlight (aka app.revanced.android.youtube:string/revanced_sb_skip_button_compact_highlight) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\layout\revanced_sb_inline_sponsor_overlay.xml:15: error: resource string/revanced_sb_skip_button_compact (aka app.revanced.android.youtube:string/revanced_sb_skip_button_compact) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\layout\revanced_sb_skip_sponsor_button.xml:13: error: resource string/revanced_sb_skip_button_compact (aka app.revanced.android.youtube:string/revanced_sb_skip_button_compact) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\layout\revanced_settings_with_toolbar.xml:18: error: resource string/revanced_settings (aka app.revanced.android.youtube:string/revanced_settings) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_misc_screen_summary (aka app.revanced.android.youtube:string/revanced_misc_screen_summary) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_misc_screen_title (aka app.revanced.android.youtube:string/revanced_misc_screen_title) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_pref_import_export_summary (aka app.revanced.android.youtube:string/revanced_pref_import_export_summary) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_pref_import_export_title (aka app.revanced.android.youtube:string/revanced_pref_import_export_title) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_auto_repeat_summary_off (aka app.revanced.android.youtube:string/revanced_auto_repeat_summary_off) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_auto_repeat_summary_on (aka app.revanced.android.youtube:string/revanced_auto_repeat_summary_on) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_auto_repeat_title (aka app.revanced.android.youtube:string/revanced_auto_repeat_title) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_announcements_summary_off (aka app.revanced.android.youtube:string/revanced_announcements_summary_off) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_announcements_summary_on (aka app.revanced.android.youtube:string/revanced_announcements_summary_on) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_announcements_title (aka app.revanced.android.youtube:string/revanced_announcements_title) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_bypass_url_redirects_summary_off (aka app.revanced.android.youtube:string/revanced_bypass_url_redirects_summary_off) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_bypass_url_redirects_summary_on (aka app.revanced.android.youtube:string/revanced_bypass_url_redirects_summary_on) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_bypass_url_redirects_title (aka app.revanced.android.youtube:string/revanced_bypass_url_redirects_title) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_spoof_signature_verification_summary (aka app.revanced.android.youtube:string/revanced_spoof_signature_verification_summary) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_spoof_signature_verification_title (aka app.revanced.android.youtube:string/revanced_spoof_signature_verification_title) not found.
WARNING: E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\res\xml\revanced_prefs.xml:2: error: resource string/revanced_spoof_signature_verification_enabled_summary_off (aka app.revanced.android.youtube:string/revanced_spoof_signature_verification_enabled_summary_off) not found.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\*****~1\AppData\Local\Temp\brut_util_Jar_133023414209000163079124872370746936969.tmp, link, -o, E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\*****~1\AppData\Local\Temp\APKTOOL2186742846478718706.tmp, -0, arsc, -I, E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\1.apk, --manifest, E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\AndroidManifest.xml, E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\build\resources.zip]
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
        at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
        at app.revanced.patcher.Patcher.get(Patcher.kt:265)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:301)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\*****~1\AppData\Local\Temp\brut_util_Jar_133023414209000163079124872370746936969.tmp, link, -o, E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\*****~1\AppData\Local\Temp\APKTOOL2186742846478718706.tmp, -0, arsc, -I, E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\1.apk, --manifest, E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\AndroidManifest.xml, E:\ANDROID\APPS\ReVanced\Patched\revanced-cache\build\resources.zip]
        at brut.util.OS.exec(OS.java:104)
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
        ... 13 more
```

**Logs from patched YT-Music:**

```
java -jar revanced-cli-4.4.0-all.jar patch -r "revanced-cache" -p -o Install\YouTube_Music_6.36.54-arm64-v8a_ReVanced.apk --options options.json -b revanced-patches-4.0.1.jar --alias=********** --keystore-password=********** --keystore-entry-password=********** --keystore=**********.keystore -m revanced-integrations-1.2.0.apk Apps\com.google.android.apps.youtube.music-6.36.54-arm64-v8a.apk
INFO: Loading patches
INFO: Decoding app manifest
INFO: Predictive back gesture excluded
INFO: Remove screenshot restriction excluded
INFO: Spoof SIM country excluded
INFO: Enable Android debugging excluded
INFO: Override certificate pinning excluded
INFO: Change package name excluded
INFO: Export all activities excluded
INFO: Spoof Wi-Fi connection excluded
INFO: Remove screen capture restriction excluded
INFO: Permanent shuffle excluded
INFO: Permanent repeat excluded
INFO: Compact header excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: Background play succeeded
INFO: Bypass certificate checks succeeded
INFO: Codecs unlock succeeded
INFO: Exclusive audio playback succeeded
INFO: GmsCore support succeeded
INFO: Hide get premium succeeded
INFO: Minimized playback music succeeded
INFO: Music video ads succeeded
INFO: Remove upgrade button succeeded
SEVERE: null failed:
app.revanced.patcher.patch.PatchException: 'null' raised an exception while being closed: app.revanced.patcher.patch.PatchException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:232)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.FileNotFoundException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at app.revanced.patcher.util.DomFileEditor.<init>(DomFileEditor.kt:41)
        at app.revanced.patcher.data.ResourceContext$XmlFileHolder.get(ResourceContext.kt:169)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close$invoke(AddResourcesPatch.kt:252)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close(AddResourcesPatch.kt:272)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:226)
        ... 23 more

        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:239)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: app.revanced.patcher.patch.PatchException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:232)
        ... 23 more
Caused by: java.io.FileNotFoundException: revanced-cache\revanced-cache\res\values\strings.xml (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at app.revanced.patcher.util.DomFileEditor.<init>(DomFileEditor.kt:41)
        at app.revanced.patcher.data.ResourceContext$XmlFileHolder.get(ResourceContext.kt:169)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close$invoke(AddResourcesPatch.kt:252)
        at app.revanced.patches.all.misc.resources.AddResourcesPatch.close(AddResourcesPatch.kt:272)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:226)
        ... 23 more

INFO: Change package name succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Compiling modified resources
INFO: Aligning com.google.android.apps.youtube.music-6.36.54-arm64-v8a.apk
INFO: Signing com.google.android.apps.youtube.music-6.36.54-arm64-v8a.apk
INFO: Saved to E:\ANDROID\APPS\ReVanced\Patched\Install\YouTube_Music_6.36.54-arm64-v8a_ReVanced.apk
INFO: Purging temporary files
INFO: Failed to purge resource cache directory
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
It could be an issue with space, closing until known

**Comment by oSumAtrIX** [comment]
Please remove all CLI options that are not necessary like previously said and test again
