### ISSUE TITLE
bug(YouTube): Root installation crashes and fails to launch - ResourceNotFoundException on app start

### ISSUE THREAD

**Issue by programminghoch10** [ReVanced/revanced-patches#2651]
### Bug description

The YouTube app crashes on the splash screen.
The logs show the issue is originating from the a ReVanced swipecontrols integration.

All default patches and options are applied, except disabled `GmsCore support` and enabled `Custom branding` .

Happens on the latest release (patches `v4.0.1`, integrations `v1.2.0`), 
it did not happen on the previous version (patches `v3.2.0`, integrations `v1.1.0`).

### Error logs

```shell
01-27 10:58:21.139  8842  8842 W YouTube : Forcefully created overlay:jsn@5ed3ec9 helper:Lazy@79b29ce view:null status: ....... {...}
01-27 10:58:21.142  8842  8842 W YouTube : Forcefully created overlay:klt@9834fd7 helper:Lazy@686b0c4 view:null status: ....... {✓..}
01-27 10:58:21.381  8842  8842 E android.youtube: Invalid ID 0x00000000.
01-27 10:58:21.381  8842  8842 D AndroidRuntime: Shutting down VM
01-27 10:58:21.381  8842  8842 E AndroidRuntime: FATAL EXCEPTION: main
01-27 10:58:21.381  8842  8842 E AndroidRuntime: Process: com.google.android.youtube, PID: 8842
01-27 10:58:21.381  8842  8842 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3645)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7924)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
01-27 10:58:21.381  8842  8842 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:239)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.content.res.Resources.getDrawableForDensity(Resources.java:991)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.content.res.Resources.getDrawable(Resources.java:931)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at app.revanced.integrations.youtube.swipecontrols.views.SwipeControlsOverlayLayout.getDrawable(SwipeControlsOverlayLayout.kt:41)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at app.revanced.integrations.youtube.swipecontrols.views.SwipeControlsOverlayLayout.<init>(SwipeControlsOverlayLayout.kt:85)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at app.revanced.integrations.youtube.swipecontrols.SwipeControlsHostActivity.initialize(SwipeControlsHostActivity.kt:131)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at app.revanced.integrations.youtube.swipecontrols.SwipeControlsHostActivity.onCreate(SwipeControlsHostActivity.kt:73)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:4)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8342)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8321)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3626)
01-27 10:58:21.381  8842  8842 E AndroidRuntime:        ... 12 more
01-27 10:58:21.393  5137  5646 W ActivityTaskManager:   Force finishing activity com.google.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalWatchWhileActivity
```

## Solution

Patch using CLI tools and a prior dev release as [described here](https://github.com/ReVanced/revanced-patches/issues/2651#issuecomment-1913328938).

### Additional context

The patched YouTube APK is mounted onto the original APK using root.
Clearing app data and force stopping does not solve the issue.
The unpatched app starts up fine.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Is the unpatched app version the same as the patched app version?

**Comment by oSumAtrIX** [comment]
That patch appearing in the stack trace is because the class super is intercepted by that patch. The stack trace indicates that the mounted APK can not find the resources indicating that the mounted APK resource IDs mismatch the actual resources's IDs as the resources are located in splits which were built with a different version of the app.

**Comment by programminghoch10** [comment]
> Is the unpatched app version the same as the patched app version?

Yes it is.

**Comment by programminghoch10** [comment]
> That patch appearing in the stack trace is because the class super is intercepted by that patch. The stack trace indicates that the mounted APK can not find the resources indicating that the mounted APK resource IDs mismatch the actual resources's IDs as the resources are located in splits which were built with a different version of the app.

Yeah I also thought that, but I don't know how this is possible, I install the APK, then patch the APK then mount the patched APK onto the installed one and this happens.

The same happens for 3 different YouTube versions that I tried.
Maybe I should test another device or something.

**Comment by oSumAtrIX** [comment]
We have received a couple reports similar to yours. Here is another stack trace:

```
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: FATAL EXCEPTION: main
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: Process: com.google.android.apps.youtube, PID: 23123
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: java.lang.RuntimeException: Unable to destroy activity {com.google.android.apps.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity}: java.lang.IllegalStateException: Primes did not observe lifecycle events in the expected order. com.google.android.apps.youtube is not initializing in Application#onCreate
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5309)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5339)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2246)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:233)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8010)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: Caused by: java.lang.IllegalStateException: Primes did not observe lifecycle events in the expected order. com.google.android.apps.youtube is not initializing in Application#onCreate
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at thl.a(PG:5)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at thl.onActivityDestroyed(PG:2)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.Application.dispatchActivityDestroyed(Application.java:582)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.Activity.dispatchActivityDestroyed(Activity.java:1510)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.Activity.onDestroy(Activity.java:2682)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at cd.onDestroy(PG:1)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at fo.onDestroy(PG:1)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at ghb.onDestroy(PG:2)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at nhp.onDestroy(PG:1)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at niv.onDestroy(PG:3)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at com.google.android.apps.youtube.app.watchwhile.MainActivity.onDestroy(PG:2)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:8251)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5294)
2024-01-27 17:43:58.237 23123 23123 ? E AndroidRuntime: 	... 11 more
2024-01-27 17:43:58.291  2047 27184 system I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
2
```

**Comment by Stardusstt** [comment]
same here, but YouTube crashes when I click "revanced(revanced specific settings)" 

and how to select old patch when use manager? try to reinstall 18.45.43 but will fail to patch

---

> Android 13 , manager1.79.0-dev.3 , patches v4.0.1, YouTube 19.03.55

```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.google.android.apps.youtube/com.google.android.libraries.social.licenses.LicenseActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2217)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1859)
at android.app.Activity.startActivityForResult(Activity.java:5633)
at rh.startActivityForResult(PG:4)
at tsb.startActivityForResult(PG:5)
at android.app.Activity.startActivityForResult(Activity.java:5586)
at rh.startActivityForResult(PG:2)
at tsb.startActivityForResult(PG:2)
at android.app.Activity.startActivity(Activity.java:6104)
at tsb.startActivity(PG:5)
at com.google.android.apps.youtube.app.settings.SettingsActivity.startActivity(PG:8)
at android.app.Activity.startActivity(Activity.java:6071)
at tsb.startActivity(PG:2)
at com.google.android.apps.youtube.app.settings.SettingsActivity.startActivity(PG:4)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:442)
at androidx.preference.Preference.D(PG:4)
at androidx.preference.Preference.tH(PG:1)
at jy.onClick(PG:82)
at android.view.View.performClick(View.java:7591)
at android.view.View.performClickInternal(View.java:7564)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:29914)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8321)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:581)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
```

**Comment by Y-T-G** [comment]
I was able to downgrade to 18.45.43. Some patches are unavailable, but it doesn't crash on startup like 19.xx

**Comment by Y-T-G** [comment]
```
com.google.android.youtube AndroidRuntime : FATAL EXCEPTION: main
Process: com.google.android.youtube, PID: 17836
aysi: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.ExceptionInInitializerError
	at ayhh.e(PG:5)
	at ayrs.run(PG:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8103)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.ExceptionInInitializerError
	at kvm.aa(Unknown Source:0)
	at kvm.V(PG:6)
	at kvm.U(PG:1)
	at kvm.qS(PG:5)
	at afjh.qS(PG:2)
	at afjc.f(PG:9)
	at afhc.a(PG:5)
	at azsg.ws(PG:2)
	at azar.f(PG:4)
	at azap.run(PG:3)
	at ayfu.run(PG:2)
	at ayrs.run(PG:1)
	... 8 more
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:244)
	at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2512)
	at android.content.res.Resources.getAnimation(Resources.java:1306)
	at android.view.animation.AnimationUtils.loadAnimation(AnimationUtils.java:138)
	at app.revanced.integrations.shared.Utils.getResourceAnimation(Utils.java:186)
	at app.revanced.integrations.youtube.videoplayer.BottomControlButton.<clinit>(BottomControlButton.java:28)
	... 20 more
```

**Comment by Y-T-G** [comment]
> > I was able to downgrade to 18.45.43. Some patches are unavailable, but it doesn't crash on startup like 19.xx
> 
> Try patching `18.49.37`. All patches support that version.
> 
> If that still doesn't work, try `18.48.39` which supports all patches except ReturnYouTubeDislike.

Both of them crash unfortunately. I removed "Copy Video URL" patch and 19.x doesn't crash. I guess anything that adds an icon or resource causes a crash. Many of the icons are broken too.

![image](https://github.com/ReVanced/revanced-patches/assets/32206511/ac77d6ed-3663-4454-a9de-11f6b8f9ab41)

**Comment by andrea-musci** [comment]
If you have root, disable patch auto update in revanced manager settings and then you can manually edit /data/user/0/app.revanced.manager.flutter/shared_prefs/FlutterSharedPreferences.xml to make it point to patches and integrations reported by LisoUseInAIKyrios.
In this way, revanced manager will use the custom patches version and make a patched youtube that can be installed with root method and that doesn't crash.
I just did it and it's working.
Thanks LisoUseInAIKyrios for sharing working patches version.

**Comment by Y-T-G** [comment]
> If you have root on your android phone, disable patch auto update in revanced manager settings and then you can manually edit /data/user/0/app.revanced.manager.flutter/shared_prefs/FlutterSharedPreferences.xml to make it point to patches and integrations reported by LisoUseInAIKyrios. In this way, revanced manager will use the custom patches version and make a patched youtube that can be installed with root method and that doesn't crash. I just did it and it's working. Thanks LisoUseInAIKyrios for sharing working patches version.

Also had to delete everything in the folder except shared_prefs for it to stick.

**Comment by Ashkumar7** [comment]
> If you have root on your android phone, disable patch auto update in revanced manager settings and then you can manually edit /data/user/0/app.revanced.manager.flutter/shared_prefs/FlutterSharedPreferences.xml to make it point to patches and integrations reported by LisoUseInAIKyrios. In this way, revanced manager will use the custom patches version and make a patched youtube that can be installed with root method and that doesn't crash. I just did it and it's working. Thanks LisoUseInAIKyrios for sharing working patches version.

`flutter.integrationsDownloadURL` this reverts back to the original url even after setting up integration url from up there. So even after patch is successful app still crashes. I think I have to wait for revanced app update. hope they fix it soon.

**Comment by mariondlsu** [comment]
> If you have root on your android phone, disable patch auto update in revanced manager settings and then you can manually edit /data/user/0/app.revanced.manager.flutter/shared_prefs/FlutterSharedPreferences.xml to make it point to patches and integrations reported by LisoUseInAIKyrios. In this way, revanced manager will use the custom patches version and make a patched youtube that can be installed with root method and that doesn't crash. I just did it and it's working. Thanks LisoUseInAIKyrios for sharing working patches version.

Hi, it's kinda weird but I don't see app.revanced.manager.flutter folder. Am I doing something wrong ?

**Comment by reyqn** [comment]
> Hi, it's kinda weird but I don't see app.revanced.manager.flutter folder. Am I doing something wrong ?

Try /data_mirror/data_ce/null/0/app.revanced.manager.flutter

**Comment by oSumAtrIX** [comment]
This is not a support channel please.move somewhere else. The issue is resolved.
