### ISSUE TITLE
Youtube 19.3.35 cannot be patched 

### ISSUE THREAD

**Issue by Phone-Guru** [ReVanced/revanced-patches#2659]
### Bug description

All patches succeed, classes.dex files compile and then the build fails

### Error logs

```shell
- Device Info
ReVanced Manager: 1.18.0
Model: SM-G973F
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.03.35 (Suggested: v19.03.35)
Patches version: v4.0.2
Patches added: Default
Patches removed: Disable precise seeking gesture, Swipe controls, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Hide player buttons, Hide album cards, Comments, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Hide seekbar, Hide timestamp, Custom player overlay opacity, Wide searchbar, Restore old seekbar thumbnails, Spoof app version, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Enable debugging, Spoof device dimensions, Client spoof, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Remember video quality, Playback speed, Restore old video quality menu, Open links externally
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 22 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~G3fcyNdzOn-pYb4JIAEdjQ==/app.revanced.manager.flutter-0n-27sCQr9ob9RSzIwXt-w==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUADIL/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7295538171486499441.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUADIL/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUADIL/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUADIL/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:371)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~G3fcyNdzOn-pYb4JIAEdjQ==/app.revanced.manager.flutter-0n-27sCQr9ob9RSzIwXt-w==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUADIL/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544019392, --version-name, 19.03.35, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL7295538171486499441.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUADIL/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUADIL/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUADIL/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Check the warnings you got when you toggled settings in ReVanced Manager and reset to default settings

**Comment by Phone-Guru** [comment]
Makes no difference

**Comment by oSumAtrIX** [comment]
<img width="955" alt="image" src="https://github.com/ReVanced/revanced-patches/assets/13122796/f416e295-a58b-4c65-870e-9d9a9035bf9f">

Follow and report back

**Comment by DrymarchonShaun** [comment]
I'm seeing the same issue, even after clearing storage and reinstalling revanced manager.

**Comment by DrymarchonShaun** [comment]
Ok, fair enough, I didn't really add anything to the conversation with my prior message. 

This is still occuring on youtube version 19.04.37, so it's not just limited to version 19.03.35. All I can do is attach my log as well, I'm not sure what you want beyond that. 

```
- Device Info
ReVanced Manager: 1.18.0
Model: KB2005
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.04.37 (Suggested: v19.04.37)
Patches version: v4.1.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Executing patches
Applied 61 patches
Compiling patched dex files
Compiled 16 dex files
Compiling modified resources
Compiling patched dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~hH94REMuNJznC-SDhdjOGQ==/app.revanced.manager.flutter-ifMmJ0Ez5-XsqBSIUnxfpg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FRMUAC/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544154560, --version-name, 19.04.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL5691436717820465421.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FRMUAC/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FRMUAC/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FRMUAC/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:371)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~hH94REMuNJznC-SDhdjOGQ==/app.revanced.manager.flutter-ifMmJ0Ez5-XsqBSIUnxfpg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FRMUAC/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1544154560, --version-name, 19.04.37, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL5691436717820465421.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FRMUAC/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FRMUAC/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-FRMUAC/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

**Comment by oSumAtrIX** [comment]
Either patch a full apk or follow what I sent above.

**Comment by DrymarchonShaun** [comment]
Hey @Phone-Guru if you didn't figure this out, make sure you are using a normal APK (for whatever reason it's the second download option for each version on apkmirror.)

**Comment by Phone-Guru** [comment]
It's an issue on the developers end. I've successfully patched many times before. Now I just download a pre-patched version.
