### ISSUE TITLE
bug (yt music): Manager aborts when patching v6.11.52

### ISSUE THREAD

**Issue by KobeW50** [ReVanced/revanced-patches#2675]
### Type

Error while patching

### Bug description

The manager aborts with exit code 1 when patching YT Music v6.11.52 with the default patches.

Worked with version 6.10.51 and with version 6.08.51.

Another [user also had this exact issue](https://discord.com/channels/952946952348270622/1131613974941675520).

### Steps to reproduce

Patch version 6.11.52 with the Manager using the default patches and see it abort.

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Background play
Applied Bypass certificate checks
Applied Codecs unlock
Applied Exclusive audio playback
Applied Hide get premium
Applied Minimized playback music
Applied Music video ads
Applied Upgrade button remover
Applied Vanced MicroG support
Repacking patched apk
Compiling resources
An error occurred! Aborted
Error:
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~7zNJOHYSRLdQKBEyXvoCgg==/app.revanced.manager.flutter-z4b7EUYvtaS-z3FMo5BrqQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZEZFLK/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL614557636698063437.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZEZFLK/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZEZFLK/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZEZFLK/cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:217)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~7zNJOHYSRLdQKBEyXvoCgg==/app.revanced.manager.flutter-z4b7EUYvtaS-z3FMo5BrqQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZEZFLK/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL614557636698063437.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZEZFLK/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZEZFLK/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-ZEZFLK/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 6 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Try with ReVanced CLI

**Comment by KobeW50** [comment]
> Try with ReVanced CLI

Does Revancify count? :teef:

**Comment by KobeW50** [comment]
In Revancify it also errored out (only with v6.11.52)

IK this isn't what u asked for 🤷

Anyway, here's the error from Revancify, if it's helpful at all. Sorry, I just don't have time to setup and learn the cli.

```
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping change-package-name: Excluded by default 
INFO: Skipping compact-header: Excluded by default 
INFO: Skipping enable-android-debugging: Excluded by default 
INFO: Skipping export-all-activities: Excluded by default 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping remove-screen-capture-restriction: Excluded by default 
INFO: Skipping remove-screenshot-restriction: Excluded by default 
INFO: Skipping spoof-wifi-connection: Excluded by default 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Background play succeeded 
INFO: Bypass certificate checks succeeded 
INFO: Codecs unlock succeeded 
INFO: Exclusive audio playback succeeded 
INFO: Hide get premium succeeded 
INFO: Minimized playback music succeeded 
INFO: Music video ads succeeded 
INFO: Upgrade button remover succeeded 
INFO: Vanced MicroG support succeeded 
INFO: Compiling resources 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6262: error: resource android:color/bright_foreground_dark_disabled is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6265: error: resource android:color/btn_default_material_dark is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6266: error: resource android:color/btn_leanback_color is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6267: error: resource android:color/bright_foreground_dark_inverse is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6268: error: resource android:color/btn_default_material_light is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6269: error: resource android:color/btn_leanback_focused is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6270: error: resource android:color/background_floating_device_default_light is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6271: error: resource android:color/background_device_default_light is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6272: error: resource android:color/car_action1 is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6273: error: resource android:color/car_action1_dark is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6274: error: resource android:color/background_holo_light is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6275: error: resource android:color/background_floating_material_light is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6276: error: resource android:color/car_blue_100 is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6277: error: resource android:color/car_blue_200 is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6278: error: resource android:color/bright_foreground_disabled_holo_light is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6279: error: resource android:color/accent_device_default_700 is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6280: error: resource android:color/btn_colored_borderless_text_material is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6281: error: resource android:color/bright_foreground_dark is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6282: error: resource android:color/background_material_dark is private. 
WARNING: /data/data/com.termux/files/home/revancify-data/revanced-cache/res/values/styles.xml:6283: error: resource android:color/car_blue_50 is private. 
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/revancify-data/revanced-cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL4331316484373550284.tmp, -0, arsc, -I, revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/revancify-data/revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revancify-data/revanced-cache/build/resources.zip]
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:21)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:167)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [./aapt2, link, -o, /data/data/com.termux/files/home/revancify-data/revanced-cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61152240, --version-name, 6.11.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/data/com.termux/files/usr/tmp/APKTOOL4331316484373550284.tmp, -0, arsc, -I, revanced-cache/1.apk, --manifest, /data/data/com.termux/files/home/revancify-data/revanced-cache/AndroidManifest.xml, /data/data/com.termux/files/home/revancify-data/revanced-cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
	... 13 more



Variant: nonRoot
Arch: arm64-v8a
App: YouTube-Music v6.11.52
CLI: revanced-cli-v2.22.0.jar
Patches: revanced-patches-v2.185.0.jar
Integrations: revanced-integrations-v0.113.0.apk
Patches argument: -i background-play
-i bypass-certificate-checks
-i codecs-unlock
-i exclusive-audio-playback
-i hide-get-premium
-i minimized-playback-music
-i music-video-ads
-i upgrade-button-remover
-i vanced-microg-support
```

**Comment by oSumAtrIX** [comment]
Not a patches issue, but patcher, open an issue there
