### ISSUE TITLE
bug: YouTube Music 6.37.50 `Permanent shuffle patches failed` to be applied

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#2680]
### Bug description

Download the apk:

```
https://www.apkmirror.com/apk/google-inc/youtube-music/youtube-music-6-37-50-release/youtube-music-6-37-50-android-apk-download/
```

The patches does not work. Patched with CLI:

```
java -jar revanced-cli-4.4.0-all.jar patch -p -o Install\YouTube_Music_6.37.50-arm64-v8a_ReVanced.apk --options options.json -b revanced-patches-4.0.3-dev.1.jar --alias=****** --keystore-password=***** --keystore-entry-password=****** --keystore=*****.keystore -m revanced-integrations-1.2.2-dev.3.apk Apps\com.google.android.apps.youtube.music-6.37.50-arm64-v8a.apk -i "Permanent shuffle" -i "Permanent repeat"
```

### Error logs

```shell
INFO: Loading patches
INFO: Decoding app manifest
INFO: Predictive back gesture excluded
INFO: Remove screenshot restriction excluded
INFO: Spoof SIM country excluded
INFO: Enable Android debugging excluded
INFO: Override certificate pinning excluded
INFO: Change package name excluded
INFO: Export all activities excluded
INFO: Spoof Wi-Fi connection excluded
INFO: Remove screen capture restriction excluded
INFO: Compact header excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: Background play succeeded
INFO: Bypass certificate checks succeeded
INFO: Codecs unlock succeeded
INFO: Exclusive audio playback succeeded
INFO: GmsCore support succeeded
INFO: Hide get premium succeeded
INFO: Minimized playback music succeeded
INFO: Music video ads succeeded
INFO: Permanent repeat succeeded
SEVERE: Permanent shuffle failed:
app.revanced.patcher.patch.PatchException: Failed to resolve DisableShuffleFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
        at app.revanced.patches.music.interaction.permanentshuffle.PermanentShuffleTogglePatch.execute(PermanentShufflePatch.kt:23)
        at app.revanced.patches.music.interaction.permanentshuffle.PermanentShuffleTogglePatch.execute(PermanentShufflePatch.kt:12)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

INFO: Remove upgrade button succeeded
INFO: Change package name succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Compiling modified resources
INFO: Aligning com.google.android.apps.youtube.music-6.37.50-arm64-v8a.apk
INFO: Signing com.google.android.apps.youtube.music-6.37.50-arm64-v8a.apk
INFO: Saved to E:\ANDROID\APPS\ReVanced\Patched\Install\YouTube_Music_6.37.50-arm64-v8a_ReVanced.apk
INFO: Purging temporary files
INFO: Failed to purge resource cache directory
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by peter9811** [comment]
Same here. 2 months ago was working, but now I have to deselect that patch:
`- Device Info
ReVanced Manager: 1.19.1
Model: NX729J
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.youtube.music v6.42.52 (Suggested: Any)
Patches version: v4.3.0
Patches added: Permanent shuffle
Patches removed: Music video ads, Codecs unlock, Exclusive audio playback, Minimized playback music, Hide get premium, Remove upgrade button, Bypass certificate checks, Background play, GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Executing patches
Permanent shuffle failed: app.revanced.patcher.patch.PatchException: Failed to resolve DisableShuffleFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
	at app.revanced.patches.music.interaction.permanentshuffle.PermanentShuffleTogglePatch.execute(PermanentShufflePatch.kt:23)
	at app.revanced.patches.music.interaction.permanentshuffle.PermanentShuffleTogglePatch.execute(PermanentShufflePatch.kt:12)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:1)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:2)
	at b6.f.b(Unknown Source:2)
	at b6.a.a(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at y5.o0.run(Unknown Source:93)
	at y5.u0.K(Unknown Source:46)
	at y5.e.t0(Unknown Source:23)
	at y5.h.a(Unknown Source:73)
	at y5.g.c(Unknown Source:0)
	at y5.h.b(Unknown Source:6)
	at y5.g.d(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:472)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 8 dex files
Aligning out.apk
Signing out.apk
Patched APK`

**Comment by smtgpm** [comment]
Same here 
Rooted android 12

- Device Info
ReVanced Manager: 1.19.2
Model: RMX2086
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.apps.youtube.music v6.42.52 (Suggested: Any)
Patches version: v4.3.0
Patches added: Permanent shuffle
Patches removed: GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Executing patches
Applied 8 patches
Permanent shuffle failed: app.revanced.patcher.patch.PatchException: Failed to resolve DisableShuffleFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
	at app.revanced.patches.music.interaction.permanentshuffle.PermanentShuffleTogglePatch.execute(PermanentShufflePatch.kt:23)
	at app.revanced.patches.music.interaction.permanentshuffle.PermanentShuffleTogglePatch.execute(PermanentShufflePatch.kt:12)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:1)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:2)
	at b6.f.b(Unknown Source:2)
	at b6.a.a(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at y5.o0.run(Unknown Source:93)
	at y5.u0.P(Unknown Source:46)
	at y5.e.t0(Unknown Source:23)
	at y5.h.a(Unknown Source:73)
	at y5.g.c(Unknown Source:0)
	at y5.h.b(Unknown Source:6)
	at y5.g.d(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 8 dex files
Aligning APK
An error occurred:
java.io.FileNotFoundException: /data/app/~~512G5LGlxZw77U-Wp_FEAQ==/com.google.android.apps.youtube.music-nLad34af11SFvoVR8l3cpw==/base.apk: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
	at n1.s0.M0(Unknown Source:105)
	at n1.s0.Q0(Unknown Source:2)
	at n1.s0.P0(Unknown Source:21)
	at n1.s0.close(Unknown Source:9)
	at kotlin.io.CloseableKt.closeFinally(Unknown Source:4)
	at app.revanced.library.ApkUtils.applyTo(Unknown Source:323)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:517)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8092)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 11 more
