### ISSUE TITLE
bug: TikTok - Downloads and Playback speed patch fails

### ISSUE THREAD

**Issue by mgishere13** [ReVanced/revanced-patches#2700]
### Bug description

Tiktok Version: 33.4.1

Downloaded from APKMirror:
```
https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/
```

Most of the patches still work with the latest version with the exception of `Playback speed` and `Downloads`.

Patched with command:
```
java -jar temp/j-hc-rv/revanced-cli-4.3.0-all.jar patch temp/com.zhiliaoapp.musically-33.4.1-arm64-v8a.apk -p -o temp/tiktok-revanced-33.4.1-arm64-v8a.apk -b temp/revanced-rv/revanced-patches-4.1.0.jar --keystore=ks.keystore --keystore-entry-*** --keystore-*** --signer=jhc --alias=jhc -e "Remember clear display"  -f -m temp/revanced-rv/revanced-integrations-1.3.1.apk --rip-lib x86_64 --rip-lib x86 --rip-lib armeabi-v7a --options=options.json
```

### Error logs
Playback speed patch:
```shell

SEVERE: Playback speed failed:
app.revanced.patcher.patch.PatchException: Failed to resolve OnRenderFirstFrameFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
	at app.revanced.patches.tiktok.interaction.speed.PlaybackSpeedPatch.execute(PlaybackSpeedPatch.kt:70)
	at app.revanced.patches.tiktok.interaction.speed.PlaybackSpeedPatch.execute(PlaybackSpeedPatch.kt:20)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
INFO: Settings succeeded 
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:301)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```

Downloads patch:
```shell
SEVERE: Downloads failed:
app.revanced.patcher.patch.PatchException: Failed to resolve DownloadPathParentFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
	at app.revanced.patches.tiktok.interaction.downloads.DownloadsPatch.execute$getMethod(DownloadsPatch.kt:46)
	at app.revanced.patches.tiktok.interaction.downloads.DownloadsPatch.execute(DownloadsPatch.kt:122)
	at app.revanced.patches.tiktok.interaction.downloads.DownloadsPatch.execute(DownloadsPatch.kt:26)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:302)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:301)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```
```


### Solution

_No response_

### Additional context

I used the `revanced-magisk-module` repository to build the APKs but not sure if it makes a difference.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You are using unofficial tools. Please reproduce the issue with official tools and open a new issue.
