### ISSUE TITLE
bug: Enabling autoplay button in layout settings causes a crash

### ISSUE THREAD

**Issue by PalmDevs** [revanced/revanced-patches#272]
### Type

Error at runtime

### Bug description

Enabling the **Autoplay button** option in **Layout settings** causes a hard crash.

With the new `settings` patch, the menu is for enabling options individually is now available. However, enabling the Autoplay button option and trying to use the player overlay will cause a hard crash.

### Steps to reproduce

1. Patch a specific YouTube package with the `settings` patch enabled
2. Launch the patched app
3. Click on your profile picture on the top right
4. Click **Settings**
5. Scroll down, find and click **ReVanced Settings**
6. Find and click **Layout settings**
7. Toggle on the **Autoplay button** switch
8. Restart the app
9. Relaunch the app and click on a random video
10. Tap once on the player, normally this will show the tools overlay, but with the option enable it crashes
11. Observe

### Relevant log output

```shell
java.lang.IncompatibleClassChangeError: Found interface igm, but class was expected (declaration of 'igm' appears in /data/app/~~O7Aby1Vzumi3u54OHJ02Ig==/com.google.android.youtube-CG9JornkeopHvZ3eLIwywg==/base.apk!classes4.dex)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.F(PG:52)
	at kow.a(PG:1)
	at dez.f(PG:1)
	at ike.y(PG:1)
	at ike.f(PG:1)
	at ike.x(PG:1)
	at ihp.a(PG:8)
	at aqtk.sX(PG:2)
	at arqr.e(PG:4)
	at arro.a(PG:1)
	at arro.b(PG:7)
	at arrp.sX(PG:6)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.Z(PG:12)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.P(PG:6)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.R(PG:2)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.U(PG:3)
	at com.google.android.apps.youtube.app.player.overlay.YouTubeControlsOverlay.b(PG:4)
	at fff.b(PG:3)
	at sfn.run(PG:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7868)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Screenshots or videos

In the screen recording, you will observe crashes once I tried tapping on the player once to get the toolbar to appear. When turning the autoplay button off, it works perfectly fine.

[Screen Recording](https://media-upload.net/file/S3OXQBldixDt)

### Solution

I've figured none at the moment

### Additional context

[Discord Thread](https://discord.com/channels/952946952348270622/1003640437669638144)

**Comment by TheJeterLP** [comment]
Duplication of #263

**Comment by PalmDevs** [comment]
Closed due to issue duplication

**Comment by PalmDevs** [comment]
Hey @TheJeterLP. Are you sure this is a duplicate? Just checked the issue you mentioned and it doesn't seem very related.

**Comment by TheJeterLP** [comment]
> Hey @TheJeterLP. Are you sure this is a duplicate? Just checked the issue you mentioned and it doesn't seem very related.

Yes, it refers to exactly the same problem which is enabling the Autoplay button

**Comment by PalmDevs** [comment]
Alright, thank you
