### ISSUE TITLE
bug: Package name change error during all latest patching

### ISSUE THREAD

**Issue by sssh7710** [ReVanced/revanced-patches#2739]
### Type

Error while patching

### Bug description

Package crash error found during reinstallation to replace from revancify to manager

### Steps to reproduce

Package name change error during patch whether revampify or manager

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Merging revanced-integrations-v0.115.0.apk 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Always autorepeat succeeded 
SEVERE: Change package name failed: 
app.revanced.patcher.patch.PatchResultError: No package name provided
	at app.revanced.patches.all.misc.packagename.patch.ChangePackageNamePatch.execute(ChangePackageNamePatch.kt:33)
	at app.revanced.patches.all.misc.packagename.patch.ChangePackageNamePatch.execute(ChangePackageNamePatch.kt:10)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:333)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:167)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: Client spoof succeeded 
INFO: Comments succeeded 
INFO: Copy video url succeeded 
INFO: Custom branding succeeded 
INFO: Disable Shorts on startup succeeded 
INFO: Disable auto captions succeeded 
INFO: Disable fullscreen panels succeeded 
INFO: Disable player popup panels succeeded 
INFO: Disable zoom haptics succeeded 
INFO: Enable android debugging succeeded 
INFO: Enable debugging succeeded 
INFO: Export all activities succeeded 
INFO: External downloads succeeded 
INFO: HDR auto brightness succeeded 
INFO: Hide Shorts components succeeded 
INFO: Hide ads succeeded 
INFO: Hide album cards succeeded 
INFO: Hide autoplay button succeeded 
INFO: Hide breaking news shelf succeeded 
INFO: Hide captions button succeeded 
INFO: Hide cast button succeeded 
INFO: Hide crowdfunding box succeeded 
INFO: Hide email address succeeded 
INFO: Hide endscreen cards succeeded 
INFO: Hide filter bar succeeded 
INFO: Hide floating microphone button succeeded 
INFO: Hide info cards succeeded 
INFO: Hide layout components succeeded 
INFO: Hide load more button succeeded 
INFO: Hide player buttons succeeded 
INFO: Hide player overlay succeeded 
INFO: Hide seekbar succeeded 
INFO: Hide timestamp succeeded 
INFO: Hide video action buttons succeeded 
INFO: Hide watermark succeeded 
INFO: Minimized playback succeeded 
INFO: Navigation buttons succeeded 
INFO: Old video quality menu succeeded 
INFO: Open links externally succeeded 
INFO: Playback speed succeeded 
INFO: Player flyout menu succeeded 
INFO: Predictive back gesture succeeded 
INFO: Premium heading succeeded 
INFO: Remember video quality succeeded 
INFO: Remove player controls background succeeded 
INFO: Remove screen capture restriction succeeded 
INFO: Remove screenshot restriction succeeded 
INFO: Return YouTube Dislike succeeded 
INFO: Seekbar tapping succeeded 
INFO: SponsorBlock succeeded 
INFO: Spoof app version succeeded 
INFO: Spoof wifi connection succeeded 
INFO: Swipe controls succeeded 
INFO: Tablet mini player succeeded 
INFO: Theme succeeded 
INFO: Vanced MicroG support succeeded 
INFO: Video ads succeeded 
INFO: Wide searchbar succeeded 
INFO: Compiling resources 
INFO: Writing modified dex files
```

### Screenshots or videos

![Screenshot_20230803_231518_Package installer](https://github.com/ReVanced/revanced-patches/assets/98168192/76024112-d10c-4d00-9d55-ea4cc58a74f5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You did not provide a package name, and I can't read korean.

**Comment by khuldraeseth** [comment]
Please reopen. Same problem here. I did provide a package name, and yet:

```
{
  "patchName": "change-package-name",
  "options": [
    {
      "key": "packageName",
      "value": "some.package.name"
    }
  ]
}
```

```
SEVERE: Change package name failed: 
app.revanced.patcher.patch.PatchResultError: No package name provided
	at app.revanced.patches.all.misc.packagename.patch.ChangePackageNamePatch.execute(ChangePackageNamePatch.kt:33)
	at app.revanced.patches.all.misc.packagename.patch.ChangePackageNamePatch.execute(ChangePackageNamePatch.kt:10)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:333)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:167)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
```
Same behavior as with `"value": null`. This is with CLI 2.22.0 and patches 2.187.0.

**Comment by oSumAtrIX** [comment]
Open an issue in the CLI repository as the issue is that you can not use camel cased patch option names
