### ISSUE TITLE
bug: (Tumblr) Some patches fail to be applied in 33.3.0.110+

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#2744]
### Bug description

Some patches failed in tumblr 33.3.0.110+ , they are:
`Disable Tumblr Live` , `Disable gift message popup` , `Disable in-app update`

Download the apk 
```
https://www.apkmirror.com/apk/tumblr-inc/tumblr/tumblr-33-3-0-110-release/tumblr-fandom-art-chaos-33-3-0-110-2-android-apk-download/
```

Patch with CLI:
```
java -jar revanced-cli-4.4.0-all.jar patch -p -o Install\Tumblr_33.3.0.110-all_ReVanced.apk --options options.json -b revanced-patches-4.3.0-dev.2.jar --alias=******** --keystore-password=******** --keystore-entry-password=******** --keystore=********.keystore -m revanced-integrations-1.4.0-dev.3.apk Apps\com.tumblr-33.3.0.110-all.apk
```

### Error logs

```shell
java -jar revanced-cli-4.4.0-all.jar patch -p -o Install\Tumblr_33.3.0.110-all_ReVanced.apk --options options.json -b revanced-patches-4.3.0-dev.2.jar --alias=Zirardi --keystore-password=Muftikhatus0 --keystore-entry-password=Muftikhatus0 --keystore=Zirardi.keystore -m revanced-integrations-1.4.0-dev.3.apk Apps\com.tumblr-33.3.0.110-all.apk
INFO: Loading patches
INFO: Decoding app manifest
INFO: Export all activities excluded
INFO: Change package name excluded
INFO: Enable Android debugging excluded
INFO: Override certificate pinning excluded
INFO: Predictive back gesture excluded
INFO: Remove screenshot restriction excluded
INFO: Remove screen capture restriction excluded
INFO: Spoof SIM country excluded
INFO: Spoof Wi-Fi connection excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Executing patches
SEVERE: Disable Tumblr Live failed:
app.revanced.patcher.patch.PatchException: 'Disable Tumblr Live' depends on 'OverrideFeatureFlagsPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Failed to resolve GetFeatureValueFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
        at app.revanced.patches.tumblr.featureflags.OverrideFeatureFlagsPatch.execute(OverrideFeatureFlagsPatch.kt:115)
        at app.revanced.patches.tumblr.featureflags.OverrideFeatureFlagsPatch.execute(OverrideFeatureFlagsPatch.kt:17)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

INFO: Disable blog notification reminder succeeded
INFO: Disable dashboard ads succeeded
SEVERE: Disable gift message popup failed:
app.revanced.patcher.patch.PatchException: Failed to resolve ShowGiftMessagePopupFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:24)
        at app.revanced.patches.tumblr.annoyances.popups.DisableGiftMessagePopupPatch.execute(DisableGiftMessagePopupPatch.kt:22)
        at app.revanced.patches.tumblr.annoyances.popups.DisableGiftMessagePopupPatch.execute(DisableGiftMessagePopupPatch.kt:11)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

SEVERE: Disable in-app update failed:
app.revanced.patcher.patch.PatchException: 'Disable in-app update' depends on 'OverrideFeatureFlagsPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: 'OverrideFeatureFlagsPatch' did not succeed previously
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:150)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:161)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Aligning com.tumblr-33.3.0.110-all.apk
INFO: Signing com.tumblr-33.3.0.110-all.apk
INFO: Saved to E:\ANDROID\APPS\ReVanced\Patched\Install\Tumblr_33.3.0.110-all_ReVanced.apk
INFO: Purging temporary files
INFO: Failed to purge resource cache directory
```

### Additional context

Something different with previous tumblr is the apk size is huge  reduced. Previous version 33.2.0.110 is ~330 MB, now in version 33.3.0.110 is ~ 38 MB

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Leo40Git** [comment]
In my experience, all patches succeeded on 33.0.0.110, but all patches failed with "fingerprint not resolved" on 34.0.0.109.
(will edit with patch log momentarily)

**Comment by PlumBlossoms13** [comment]
The issue persists on revanced manager 1.19.2

**Comment by SubZero5** [comment]
Slow/no SRT..

When can a fix be pıssible? Any guesses?
