### ISSUE TITLE
bug: Encountered 1 parser syntax errors and 0 lexer syntax errors

### ISSUE THREAD

**Issue by reccesuinth** [ReVanced/revanced-patches#2794]
### Type

Error while patching

### Bug description

When trying to update YouTube Revanced on my device, after having successfully updated it on someone else's, I received the following error: Encountered 1 parser syntax errors and 0 lexer syntax errors. As shown in the Log file, using default patches, latest version, downloading directly from correct apk, having right version of MicroG etc. The same steps I used to successfully download it on someone else's phone. Even after reinstalling everything (MicroG' Revanced, YouTube), I get the same error.

Strangely, it works on a few of the universal patches, as shown in the screenshot.

### Steps to reproduce

Download files. Try to patch YouTube apk. Get encounter parser error.

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Failed to apply Always autorepeat: 'Always autorepeat' depends on 'Integrations' but the following error was raised: java.lang.IllegalStateException: Encountered 1 parser syntax errors and 0 lexer syntax errors!
	at app.revanced.patcher.util.smali.InlineSmaliCompiler$Companion.compile(InlineSmaliCompiler.kt:49)
	at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions(InlineSmaliCompiler.kt:72)
	at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstruction(InlineSmaliCompiler.kt:84)
	at app.revanced.patcher.extensions.InstructionExtensions.addInstruction(InstructionExtensions.kt:93)
	at app.revanced.patches.shared.integrations.patch.AbstractIntegrationsPatch$IntegrationsFingerprint.invoke(AbstractIntegrationsPatch.kt:47)
	at app.revanced.patches.shared.integrations.patch.AbstractIntegrationsPatch.execute(AbstractIntegrationsPatch.kt:65)
	at app.revanced.patches.shared.integrations.patch.AbstractIntegrationsPatch.execute(AbstractIntegrationsPatch.kt:16)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:333)
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:309)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:395)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Failed to apply Client spoof: 'Client spoof' depends on 'Spoof signature verification' but the following error was raised: 'Spoof signature verification' depends on 'SpoofSignatureVerificationResourcePatch' but the following error was raised: 'SpoofSignatureVerificationResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Comments: 'Comments' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Copy video url: 'Copy video url' depends on 'CopyVideoUrlResourcePatch' but the following error was raised: 'CopyVideoUrlResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Applied Custom branding
Failed to apply Disable Shorts on startup: 'Disable Shorts on startup' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Disable auto captions: 'Disable auto captions' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Disable fullscreen panels: 'Disable fullscreen panels' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Disable player popup panels: 'Disable player popup panels' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Disable zoom haptics: 'Disable zoom haptics' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Enable debugging: 'Enable debugging' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply External downloads: 'External downloads' depends on 'ExternalDownloadsResourcePatch' but the following error was raised: 'ExternalDownloadsResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply HDR auto brightness: 'HDR auto brightness' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide Shorts components: 'Hide Shorts components' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide ads: 'Hide ads' depends on 'Hide get premium' but the following error was raised: 'Hide get premium' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide album cards: 'Hide album cards' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide autoplay button: 'Hide autoplay button' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide breaking news shelf: 'Hide breaking news shelf' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide captions button: 'Hide captions button' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide cast button: 'Hide cast button' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide crowdfunding box: 'Hide crowdfunding box' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide email address: 'Hide email address' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide endscreen cards: 'Hide endscreen cards' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide filter bar: 'Hide filter bar' depends on 'HideFilterBarResourcePatch' but the following error was raised: 'HideFilterBarResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide floating microphone button: 'Hide floating microphone button' depends on 'HideFloatingMicrophoneButtonResourcePatch' but the following error was raised: 'HideFloatingMicrophoneButtonResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide info cards: 'Hide info cards' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide layout components: 'Hide layout components' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide load more button: 'Hide load more button' depends on 'HideLoadMoreButtonResourcePatch' but the following error was raised: 'HideLoadMoreButtonResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide player buttons: 'Hide player buttons' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide player overlay: 'Hide player overlay' depends on 'HidePlayerOverlayResourcePatch' but the following error was raised: 'HidePlayerOverlayResourcePatch' depends on 'Settings' but the following error was raised: 'Settings' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide seekbar: 'Hide seekbar' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide timestamp: 'Hide timestamp' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide video action buttons: 'Hide video action buttons' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Hide watermark: 'Hide watermark' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Minimized playback: 'Minimized playback' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Navigation buttons: 'Navigation buttons' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Old video quality menu: 'Old video quality menu' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Open links externally: Encountered 1 parser syntax errors and 0 lexer syntax errors!
Failed to apply Playback speed: 'Playback speed' depends on 'Custom playback speed' but the following error was raised: 'Custom playback speed' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Player flyout menu: 'Player flyout menu' depends on 'LithoFilterPatch' but the following error was raised: 'LithoFilterPatch' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Applied Premium heading
Failed to apply Remember video quality: 'Remember video quality' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Return YouTube Dislike: 'Return YouTube Dislike' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Seekbar tapping: 'Seekbar tapping' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply SponsorBlock: 'SponsorBlock' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Spoof app version: 'Spoof app version' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Swipe controls: 'Swipe controls' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Tablet mini player: 'Tablet mini player' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Theme: 'Theme' depends on 'SeekbarColorBytecodePatch' but the following error was raised: 'SeekbarColorBytecodePatch' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Vanced MicroG support: 'Vanced MicroG support' depends on 'Hide cast button' but the following error was raised: 'Hide cast button' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Video ads: 'Video ads' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Failed to apply Wide searchbar: 'Wide searchbar' depends on 'Integrations' but the following error was raised: 'Integrations' did not succeed previously
Repacking patched apk
Compiling resources
Writing modified dex files
Canceling patching process
Press back to exit
```

### Screenshots or videos

![Screenshot_٢٠٢٣٠٨١١-١٩٥٣٥١](https://github.com/ReVanced/revanced-patches/assets/71776351/1b3e1d64-d8b6-404e-94c8-d0672ba91079)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#2733

**Comment by oSumAtrIX** [comment]
It's a bug, haven't figured out yet how to fix though.
