### ISSUE TITLE
bug: (YouTube: Change header patch) Failed to patch YouTube premium header

### ISSUE THREAD

**Issue by CoolCooler0** [ReVanced/revanced-patches#2800]
### Bug description

The Youtube change header patch is failing. The header I choose is the "Youtube premium header".

### Error logs

```shell
- Device Info
ReVanced Manager: 1.18.0
Model: SM-A346E
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.04.37 (Suggested: v19.04.37)
Patches version: v4.3.0
Patches added: Change header [Header: yt_premium_wordmark_header]
Patches removed: Remove viewer discretion dialog, Disable precise seeking gesture, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Hide breaking news shelf, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Hide layout components, Hide info cards, Hide 'Load more' button, Player flyout menu, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Wide searchbar, Change start page, Enable tablet layout, Alternative thumbnails, Enable debugging, Spoof device dimensions, Disable zoom haptics, HDR auto brightness
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 27 patches
Change header failed: app.revanced.patcher.patch.PatchException: The provided path is not a directory: yt_premium_wordmark_header
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch$execute$toCustom$1.invoke(ChangeHeaderPatch.kt:117)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch$execute$toCustom$1.invoke(ChangeHeaderPatch.kt:115)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch.execute(ChangeHeaderPatch.kt:143)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch.execute(ChangeHeaderPatch.kt:14)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:341)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:340)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched APK
```

### Solution

n/a

### Additional context

n/a

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not an issue with ReVanced Patches, but ReVanced Manager failing to update the option value.

**Comment by CoolCooler0** [comment]
Thanks, that fixed it. It's patched successfully.
