### ISSUE TITLE
bug(Twitter/X): `Unlock downloads` fails with patches `v4.3.0`

### ISSUE THREAD

**Issue by lluni** [ReVanced/revanced-patches#2801]
### Bug description

The Twitter `Unlock downloads` patch from patches `v4.3.0` fails. I have tested this on Twitter `v10.29.0-release.0` and `v10.30.0-release.0` and it fails on both versions. The logs below are for the latter Twitter version.

### Error logs

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Applied 2 patches
Unlock downloads failed: app.revanced.patcher.patch.PatchException: com.android.tools.smali.dexlib2.builder.instruction.BuilderInstruction35c cannot be cast to com.android.tools.smali.dexlib2.iface.instruction.TwoRegisterInstruction
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:185)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:341)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:340)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.ClassCastException: com.android.tools.smali.dexlib2.builder.instruction.BuilderInstruction35c cannot be cast to com.android.tools.smali.dexlib2.iface.instruction.TwoRegisterInstruction
	at app.revanced.patches.twitter.interaction.downloads.UnlockDownloadsPatch$execute$2.invoke(UnlockDownloadsPatch.kt:45)
	at app.revanced.patches.twitter.interaction.downloads.UnlockDownloadsPatch$execute$2.invoke(UnlockDownloadsPatch.kt:43)
	at app.revanced.patches.twitter.interaction.downloads.UnlockDownloadsPatch.execute$patch(UnlockDownloadsPatch.kt:29)
	at app.revanced.patches.twitter.interaction.downloads.UnlockDownloadsPatch.execute(UnlockDownloadsPatch.kt:43)
	at app.revanced.patches.twitter.interaction.downloads.UnlockDownloadsPatch.execute(UnlockDownloadsPatch.kt:18)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	... 18 more
Compiling patched dex files
Compiled 12 dex files
Signing APK
Patched APK
```
```


### Solution

_No response_

### Additional context

_No response_

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by lluni** [comment]
Nevermind, I retryed it again and now it succeeded without any errors...
I guess this issue can be closed.
