### ISSUE TITLE
bug: Youtube (latest recommanded) ~ "Change header" Patch fails.

### ISSUE THREAD

**Issue by Domiiniik** [ReVanced/revanced-patches#2802]
### Bug description

Changr header patch fails upon patching with latest recommended yt and latest patches released 20 minutes ago.
![Screenshot_20240302_202354_ReVanced Manager](https://github.com/ReVanced/revanced-patches/assets/30195961/15c8ec3d-c032-4229-b5cd-a559d3c4d922)

### Error logs

```shell
- Device Info
ReVanced Manager: 1.18.0
Model: SM-G990B2
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.04.37 (Suggested: v19.04.37)
Patches version: v4.3.0
Patches added: Change header [Header: yt_premium_wordmark_header], Enable slide to seek, Remove player controls background, Remove screen capture restriction, Remove screenshot restriction
Patches removed: Disable fullscreen ambient mode, Disable rolling number animations, Enable debugging
Default patch options changed: GmsCore support [GmsCore Vendor: app.revanced]

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 62 patches
Change header failed: app.revanced.patcher.patch.PatchException: The provided path is not a directory: yt_premium_wordmark_header
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch$execute$toCustom$1.invoke(ChangeHeaderPatch.kt:117)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch$execute$toCustom$1.invoke(ChangeHeaderPatch.kt:115)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch.execute(ChangeHeaderPatch.kt:143)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatch.execute(ChangeHeaderPatch.kt:14)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:177)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:341)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:340)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched APK
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2800#issuecomment-1974885599
