### ISSUE TITLE
bug: (revanced-patches v4.3.0) Getting java.util.zip.ZipException: zip END header not found

### ISSUE THREAD

**Issue by NewbieH4x** [ReVanced/revanced-patches#2824]
### Bug description

I'm trying to build an updated Revanced Youtube app but getting `java.util.zip.ZipException: zip END header not found` error.
I'm using Revanced CLI to build and I have OpenJDK 17 (Zulu). It is built on github actions BTW since almost a year but suddenly getting this error.
I've reproduced this locally. Also same version of youtube APK is patched successfully using revanced-patches v4.2.0.
Command I use to build:
```
java -jar $CLI patch \
    -o $CURDIR/${YTNAME}-noroot.apk \
    --keystore=$CURDIR/revanced.keystore \
    --alias=alias \
    --keystore-entry-password=$PASS \
    --keystore-password=$PASS \
    -b $PATCHES \
    -m $INTEG \
    --force \
    -e custom-branding \
    -e enable-debugging \
    -e enable-wide-searchbar \
    -e hide-captions-button \
    -e hide-cast-button \
    -e hide-info-cards \
    -e hide-seekbar \
    -e hide-timestamp \
    -e hide-video-action-buttons \
    -e navigation-buttons \
    -e return-youtube-dislike \
    -e spoof-app-version $YTMODULEPATH/youtube/base.apk
```

### Error logs

```shell
INFO: Loading patches
java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1633)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1641)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1479)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1441)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:718)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:252)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:346)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:317)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:283)
        at app.revanced.patcher.PatchBundleLoader$Jar$2.invoke(PatchBundleLoader.kt:106)
        at app.revanced.patcher.PatchBundleLoader$Jar$2.invoke(PatchBundleLoader.kt:105)
        at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt:140)
        at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt)
        at app.revanced.patcher.PatchBundleLoader.<init>(PatchBundleLoader.kt:34)
        at app.revanced.patcher.PatchBundleLoader$Jar.<init>(PatchBundleLoader.kt:102)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:247)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```

### Solution

Not a solution but I've tried downgrading back to revanced-patches v4.2.0 and it works fine.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The patches file you supply is a broken jar file. Please make sure you supply working files.

**Comment by NewbieH4x** [comment]
@oSumAtrIX Okay I see what might be happening. Until v4.2.0 only one file had `.jar` in the name uploaded in release artifacts but since then there are two files now, the other one being `.jar.asc` and my code is not adapted for it.
Thanks!
