### ISSUE TITLE
bug: SEVERE: `Hide ads failed`: (TikTok 30.9.1)

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#2832]
### Type

Error while patching

### Bug description

`Patch hide ads failed on TikTok 30.9.1`

### Steps to reproduce

1. Download app here [TikTok 30.9.1](https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok/tik-tok-30-9-1-release/tiktok-30-9-1-2-android-apk-download/)
3. Patch with cli
`java -jar revanced-cli-2.23.0-dev.5-all.jar -c -a TikTok_Asia_30.9.1.apk -o TikTok_Asia_ReVanced_30.9.1.apk -b revanced-patches-2.188.0-dev.15.jar --keystore=ks.keystore -m revanced-integrations-0.116.0-dev.4.apk`

### Relevant log output

```shell
INFO: Reading dex files
INFO: Decoding app manifest
INFO: Skipping Change package name: Excluded by default
INFO: Skipping Enable android debugging: Excluded by default
INFO: Skipping Export all activities: Excluded by default
INFO: Skipping Override certificate pinning: Excluded by default
INFO: Skipping Predictive back gesture: Excluded by default
INFO: Skipping Remove screen capture restriction: Excluded by default
INFO: Skipping Remove screenshot restriction: Excluded by default
INFO: Skipping Sim spoof: Excluded by default
INFO: Skipping Spoof wifi connection: Excluded by default
INFO: Merging revanced-integrations-0.116.0-dev.4.apk
INFO: Executing patches
INFO: Disable login requirement succeeded
INFO: Downloads succeeded
INFO: Feed filter succeeded
INFO: Fix google login succeeded
SEVERE: Hide ads failed:
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:319)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:40)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:340)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:176)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.tiktok.ad.patch.HideAdsPatch.execute(HideAdsPatch.kt:35)
        at app.revanced.patches.tiktok.ad.patch.HideAdsPatch.execute(HideAdsPatch.kt:20)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:315)
        ... 16 more
INFO: Playback speed succeeded
INFO: Settings succeeded
INFO: Show seekbar succeeded
INFO: Writing modified dex files
INFO: Aligning TikTok_Asia_30.9.1.apk to TikTok_Asia_ReVanced_30.9.1_aligned.apk
INFO: Signing TikTok_Asia_ReVanced_30.9.1_aligned.apk to TikTok_Asia_ReVanced_30.9.1_signed.apk
INFO: Found existing keystore: ks.keystore
INFO: Copying TikTok_Asia_ReVanced_30.9.1_signed.apk to TikTok_Asia_ReVanced_30.9.1.apk
INFO: Cleaned up cache directory
INFO: Finished
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by CoolCooler0** [comment]
hide ads patch also fails on V30.9.3

**Comment by kazimmt** [comment]
> Wait, Isn't it the feed filter that removes the ads?

No.

**Comment by kazimmt** [comment]
> What does hide-ads do? Because I've never seen a single ads on my tiktok

![image](https://github.com/ReVanced/revanced-patches/assets/82371061/b53ee2b0-b666-48c7-8060-11bcec6d836e)

**Comment by CoolCooler0** [comment]
> > > Wait, Isn't it the feed filter that removes the ads?
> > 
> > 
> > No.
> 
> What does hide-ads do? Because I've never seen a single ads on my tiktok

You have definitely seen ads. It looks like normal tiktoks and you can just scroll by them like normal tiktoks.

**Comment by kazimmt** [comment]
Latest dev CLI shows a new type of log

```
H:\!!!ReVanced Builder\TikTok\2.188.0 dev20>java -jar revanced-cli.jar patch TikTok_31.0.3.apk -o TikTok_31.0.3_withSimSpoof.apk -b revanced-patches.jar -m revanced-integrations.apk -i sim-spoof
INFO: Loading patches
INFO: Setting patch options
INFO: Decoding app manifest
INFO: Export all activities excluded by default
INFO: Override certificate pinning excluded by default
INFO: Change package name excluded by default
INFO: Enable android debugging excluded by default
INFO: Remove screenshot restriction excluded by default
INFO: Spoof wifi connection excluded by default
INFO: Predictive back gesture excluded by default
INFO: Remove screen capture restriction excluded by default
INFO: Sim spoof excluded by default
INFO: Executing patches
INFO: Disable login requirement succeeded
INFO: Fix google login succeeded
INFO: Settings succeeded
SEVERE: Hide ads failed:
app.revanced.patcher.patch.PatchException
INFO: Downloads succeeded
INFO: Playback speed succeeded
INFO: Show seekbar succeeded
INFO: Feed filter succeeded
INFO: Compiling modified dex files
INFO: Aligning TikTok_31.0.3.apk
INFO: Signing TikTok_31.0.3_withSimSpoof_aligned.apk
INFO: Copying to TikTok_31.0.3_withSimSpoof.apk

```

**Comment by Kantotero** [comment]
> Works for me with TikTok 30.9.3 `com.ss.android.ugc.trill` using all stable versions of cli, patches, and integrations

What abt on `com.zhiliaoapp.musically`? What's the latest tiktok version compatible where the `hide-ads` patch works?

**Comment by cyberboh** [comment]
> > Works for me with TikTok 30.9.3 `com.ss.android.ugc.trill` using all stable versions of cli, patches, and integrations
> 
> What abt on `com.zhiliaoapp.musically`? What's the latest tiktok version compatible where the `hide-ads` patch works?

30.8.4 but https://github.com/ReVanced/revanced-patches/issues/2850

**Comment by 54m4d** [comment]
31.0.5

```kotlin
INFO: Loading patches
INFO: Setting patch options
INFO: Decoding app manifest
INFO: Change package name excluded by default
INFO: Enable android debugging excluded by default
INFO: Export all activities excluded by default
INFO: Override certificate pinning excluded by default
INFO: Predictive back gesture excluded by default
INFO: Remove screen capture restriction excluded by default
INFO: Remove screenshot restriction excluded by default
INFO: Sim spoof excluded by default
INFO: Spoof wifi connection excluded by default
INFO: Merging integrations
INFO: Executing patches
INFO: Disable login requirement succeeded
INFO: Downloads succeeded
INFO: Feed filter succeeded
INFO: Fix google login succeeded
SEVERE: Hide ads failed: app.revanced.patcher.patch.PatchException
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:153)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$result$1$1.invokeSuspend(PatchCommand.kt:186)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:185)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.tiktok.ad.patch.HideAdsPatch.execute(HideAdsPatch.kt:33)
        at app.revanced.patches.tiktok.ad.patch.HideAdsPatch.execute(HideAdsPatch.kt:18)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147)
        ... 24 more
```

**Comment by trmdi** [comment]
There are errors while patching but the patch still does its work. I haven't seen any ads while watching.

**Comment by songokussm** [comment]
> There are errors while patching but the patch still does its job. I haven't seen any ads while watching. Tested on Tiktok 31.1.4.

i tried every non beta version on apkmirror from 31.2.4 to 30.6.4. all of them aborted during the patch.

**Comment by CoolCooler0** [comment]
> > There are errors while patching but the patch still does its job. I haven't seen any ads while watching. Tested on Tiktok 31.1.4.
> 
> i tried every non beta version on apkmirror from 31.2.4 to 30.6.4. all of them aborted during the patch.

Tiktok can't be patch with the Manager at the moment. They need to fix it. Patching with cli works. But the hide ads patch still fails.
