### ISSUE TITLE
bug: (Sync for Reddit) Opening certain subreddits crashes the app

### ISSUE THREAD

**Issue by ASleepyCat** [ReVanced/revanced-patches#2854]
### Bug description

Opening certain subreddits like /r/formula1 or /r/touhou causes the app to crash. Even on minimal patches (just client spoof) will cause the app to crash.

This started to happen after the /s/ link fix patch was released.

App version is v23.06.30-13:39.

### Error logs

```shell
03-08 18:03:28.119 30784 30784 D AndroidRuntime: Shutting down VM
03-08 18:03:28.120 30784 30784 E AndroidRuntime: FATAL EXCEPTION: main
03-08 18:03:28.120 30784 30784 E AndroidRuntime: Process: com.laurencedawson.reddit_sync, PID: 30784
03-08 18:03:28.120 30784 30784 E AndroidRuntime: java.lang.ExceptionInInitializerError
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at org.jsoup.nodes.Document$OutputSettings.<init>(Document.java:2)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at org.jsoup.nodes.Document.<init>(Document.java:2)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at org.jsoup.parser.e.c(TreeBuilder.java:3)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at org.jsoup.parser.e.d(TreeBuilder.java:1)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at org.jsoup.parser.HtmlTreeBuilder.d(HtmlTreeBuilder.java:3)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at org.jsoup.parser.Parser.parse(Parser.java:2)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at org.jsoup.Jsoup.parse(Jsoup.java:3)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at t7.l0.a(TableHelper.java:7)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at com.laurencedawson.reddit_sync.ui.views.text.spannable.children.HtmlTableView.h(HtmlTableView.java:15)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at com.laurencedawson.reddit_sync.ui.views.text.spannable.children.HtmlTableView.f(HtmlTableView.java:6)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at com.laurencedawson.reddit_sync.ui.fragments.sidebar.AboutFragment.E3(AboutFragment.java:9)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at com.laurencedawson.reddit_sync.ui.fragments.sidebar.AboutFragment.C3(AboutFragment.java:12)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at com.laurencedawson.reddit_sync.ui.fragments.sidebar.AboutFragment.o2(AboutFragment.java:21)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at androidx.fragment.app.Fragment.N2(Fragment.java:1)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at androidx.fragment.app.l.f(FragmentStateManager.java:26)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at androidx.fragment.app.l.m(FragmentStateManager.java:20)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.e0(FragmentManager.java:34)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.e1(FragmentManager.java:10)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.b0(FragmentManager.java:4)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at androidx.fragment.app.FragmentManager$g.run(Unknown Source:3)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:959)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:232)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:317)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8501)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
03-08 18:03:28.120 30784 30784 E AndroidRuntime: Caused by: java.lang.SecurityException: invalid SHA-256 signature file digest for classes3.dex
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at sun.security.util.SignatureFileVerifier.verifySection(SignatureFileVerifier.java:529)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:325)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:278)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at java.util.jar.JarVerifier.update(JarVerifier.java:233)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at java.util.jar.JarFile.initializeVerifier(JarFile.java:407)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at java.util.jar.JarFile.getInputStream(JarFile.java:474)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:168)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at java.net.URL.openStream(URL.java:1072)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:989)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at java.lang.Class.getResourceAsStream(Class.java:3115)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at org.jsoup.nodes.Entities.e(Entities.java:5)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at org.jsoup.nodes.Entities.a(Unknown Source:0)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at org.jsoup.nodes.Entities$EscapeMode.<init>(Entities.java:2)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        at org.jsoup.nodes.Entities$EscapeMode.<clinit>(Entities.java:1)
03-08 18:03:28.120 30784 30784 E AndroidRuntime:        ... 28 more
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Yes, its the same problem.
