### ISSUE TITLE
YT music remove upgrade button patch not working

### ISSUE THREAD

**Issue by Shazzkid** [ReVanced/revanced-patches#2878]
### Type

Other

### Bug description

Upgrade button patch no longer effective with latest update. Screenshot attached

### Steps to reproduce

Update latest YT music version (6.16.52), with latest patches (2.188.0) using latest manager (1.9.0). 

Patching goes fine and seems successful. Upgrade button was hidden as it should be  at the previous latest versions of app/manager/patches

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original APK
Reading input APK
Loading patches
Music video ads succeeded
Codecs unlock succeeded
Exclusive audio playback
sUcceeded
Minimized playback music
succeeded
Hide get premium succeeded
Remove Upgrade button
succeeded
Bypass certificate checks
succeeded
Vanced Micro6 support
succeeded
Background play succeeded
Finished!
```

### Screenshots or videos

![Screenshot_20230827_005141](https://github.com/ReVanced/revanced-patches/assets/110567772/11647afa-792d-48b4-857e-37b7248cc64a)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
A samples button will appear soon. (2nd button)
Current patches hides 5th button.

**Comment by Barath6** [comment]
for me patch with the same version im getting this error



Applied Codecs unlock
Failed to apply Exclusive audio playback: NullPointerException
Applied Minimized playback music
Applied Hide get premium
Error:
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:484)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:619)
	at app.revanced.patcher.Patcher.save(Patcher.kt:128)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-32(MainActivity.kt:278)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$efRWk2Z7aIFbIqnpE9hv8LpAiuk(Unknown Source:0)
	at java.lang.Thread.run(Thread.java:1012)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at brut.util.OS.exec(OS.java:99)
	at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:480)
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied Bypass certificate checks
Applied Background play
Applied Music video ads
Applied Upgrade button remover
Compiling resources
Applied Vanced MicroG support
An error occurred! Aborted
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~rCTTHaLsqfrg-ufhhLnL9g==/app.revanced.manager.flutter-xcqBKlaSishKzZRiiETkkg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DPXITA/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61652240, --version-name, 6.16.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3961792206323505559.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DPXITA/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DPXITA/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DPXITA/cache/build/resources.zip]
	... 6 more
Reading dex files
Reading input APK
Copying original APK
Creating working directory
Initializing installer
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~rCTTHaLsqfrg-ufhhLnL9g==/app.revanced.manager.flutter-xcqBKlaSishKzZRiiETkkg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DPXITA/cache/aapt_temp_file, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 61652240, --version-name, 6.16.52, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3961792206323505559.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DPXITA/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DPXITA/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-DPXITA/cache/build/resources.zip]

**Comment by Mister-XY** [comment]
same here

**Comment by KobeW50** [comment]
@Barath6 use version 6.10.52

Also ur  issue is unrelated to the OP's
