### ISSUE TITLE
bug: Can't patch any apps

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#2881]
### Type

Error while patching

### Bug description

Patching with cli is unsuccessful, all apps get error while patching

### Steps to reproduce

Use command like this:
`java -jar revanced-cli-3.0.0-all.jar patch --patch-bundle revanced-patches-2.188.1.jar --merge revanced-integrations-0.116.2.apk --keystore=ks.keystore --out YouTube_ReVanced_18.32.39.apk YouTube_18.32.39.apk`

### Relevant log output

```shell
java -jar revanced-cli-3.0.0-all.jar patch --patch-bundle revanced-patches-2.188.1.jar --merge revanced-integrations-0.116.2.apk --keystore=ks.keystore --out YouTube_ReVanced_18.32.39.apk YouTube_18.32.39.apk
INFO: Loading patches
INFO: Setting patch options
Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/patch/PatchResultError
        at java.base/java.lang.Class.getDeclaredFields0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3397)
        at java.base/java.lang.Class.getDeclaredField(Class.java:2705)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:113)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt:108)
        at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242)
        at kotlin.reflect.full.KClasses.getCompanionObjectInstance(KClasses.kt:57)
        at app.revanced.patcher.extensions.PatchExtensions.getOptions(PatchExtensions.kt:60)
        at app.revanced.utils.Options.serialize(Options.kt:27)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.PatchResultError
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 21 more
```

### Screenshots or videos

![image](https://github.com/ReVanced/revanced-patches/assets/99109969/9285dd49-7b76-4b8d-870f-e978ff2562a0)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You are using incompatible patches with the version of CLI. Either use the previous ReVanced CLI or ReVanced Patches version

**Comment by nikhilbadyal** [comment]
@oSumAtrIX  Can you mention the compatible patch versions with new V3 cli. General latest on both the repo are compatible.

**Comment by cyberboh** [comment]
> @oSumAtrIX Can you mention the compatible patch versions with new V3 cli. Generally latest on both the repo are compatible.

inte 0.116.0
patches 2.118.0
but youtube will crash if you're using android 11 or below if you patched with them. actually I already reported since cli dev. 5 but he ignored my bug report. lol

**Comment by nikhilbadyal** [comment]
@cyberboh  [118](https://github.com/ReVanced/revanced-patches/releases/tag/v2.118.0) ? Really

**Comment by cyberboh** [comment]
> @cyberboh [118](https://github.com/ReVanced/revanced-patches/releases/tag/v2.118.0) ? Really

ohh typo
I mean [2.188.0](https://github.com/ReVanced/revanced-patches/releases/tag/v2.188.0)
