### ISSUE TITLE
bug: (Tiktok) v31.0.4 hide ads failed. Using com.zhiliaoapp.musically

### ISSUE THREAD

**Issue by Kantotero** [ReVanced/revanced-patches#2885]
### Type

Error while patching

### Bug description

Trying to patch the latest tiktok 31.0.4. I thought all versions are compatible when looking at the [patches page](https://revanced.app/patches?pkg=com.zhiliaoapp.musically). Also when using revanced manager itself it says `all version` for compatibility. I get hide ads failed everytime.

### Steps to reproduce

1. Patch 31.0.4 on revanced manager
2. `Hide ads failed` everytime, rest of patches are succeeded

### Relevant log output

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Disable login requirement succeeded
Downloads succeeded
Feed filter succeeded
Fix google login succeeded
Hide ads failed: app.revanced.patcher.patch.PatchException
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:153)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:214)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$13(MainActivity.kt:213)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$6dokpIuPm1kqn7qLA9JtiVzSCi0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException
	at app.revanced.patches.tiktok.ad.patch.HideAdsPatch.execute(HideAdsPatch.kt:33)
	at app.revanced.patches.tiktok.ad.patch.HideAdsPatch.execute(HideAdsPatch.kt:18)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147)
	... 18 more
Playback speed succeeded
Settings succeeded
Show seekbar succeeded
Compiling modified dex files
Signing APK
Patched
```

### Additional context

Arm64v8a | Android 11

Can anyone tell me what's the latest tiktok version that's compatible to patch using revanced? Should I "downgrade" the tiktok patch version too using Cli?

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2832
