### ISSUE TITLE
bug: Error while patching Tiktok 32.5.3

### ISSUE THREAD

**Issue by grannymaster** [ReVanced/revanced-patches#2885]
### Bug description

Error patching Tiktok 32.5.3 "com.zhiliaoapp.musically" using the default patch options. Didn't touch any of the settings.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.19.3
Model: SM-S918B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.zhiliaoapp.musically v32.5.3 (Suggested: 32.5.3)
Patches version: v4.3.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Applied 8 patches
Compiling patched dex files
Compiled 23 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 4253104 free bytes and 4153KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:124)
	at com.android.tools.smali.util.Utf8Utils.utf8BytesWithUtf16LengthToString(SourceFile:2)
	at com.android.tools.smali.dexlib2.dexbacked.DexReader.readString(Unknown Source:12)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:2)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(SourceFile:1)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(SourceFile:2)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(SourceFile:1)
	at com.android.tools.smali.dexlib2.dexbacked.reference.DexBackedTypeReference.getType(Unknown Source:8)
	at com.android.tools.smali.dexlib2.writer.pool.TypePool.getItemIndex(Unknown Source:0)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.getReferenceIndex(SourceFile:1)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.getReferenceIndex(SourceFile:2)
	at com.android.tools.smali.dexlib2.writer.InstructionWriter.write(SourceFile:9)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeCodeItem(Unknown Source:452)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(Unknown Source:211)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:2)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:1)
	at h6.h.c(Unknown Source:80)
	at h6.h.a(Unknown Source:0)
	at h6.h$a.a(Unknown Source:20)
	at h6.h$a.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/2511

**Comment by grannymaster** [comment]
I guess I need figure out how to use the CLI
