### ISSUE TITLE
bug(Youtube - GmsCore Support = 'com.google'): Crash using LineageOS MicroG

### ISSUE THREAD

**Issue by REmerald** [ReVanced/revanced-patches#2904]
### Bug description

When launch the patched apk, it prompts for notifications, displays empty home page with **Try searching to get started** box for half-second, then immediately crashes.

To reprodude:
1. Include GmsCore Support patch. Everything else is default (except Dark AMOLED - off, Custom Branding - on)
2. Click on the gear and set the value to `com.google`.
3. Patch, install, launch.
4. Crash

I use LineageOS for MicroG, this is the GmsCore package: `package:/product/priv-app/GmsCore/GmsCore.apk=com.google.android.gms`

### Error logs

```shell
03-23 21:58:05.432  1633  2510 D CoreBackPreview: Window{b33d1b4 u0 Splash Screen app.revanced.android.youtube EXITING}: Setting back callback null
03-23 21:58:05.433  1633  8308 W InputManager-JNI: Input channel object 'b33d1b4 Splash Screen app.revanced.android.youtube (client)' was disposed without first being removed with the input manager!
03-23 21:58:05.457 27352 27352 D GmsGcmRegister: onBind: Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
03-23 21:58:05.467 27352 27352 D GmsGcmRegister: handleMessage: package=app.revanced.android.youtube what=1 id=39
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: java.lang.RuntimeException: Checkin disabled
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at org.microg.gms.gcm.PushRegisterServiceKt.ensureCheckinIsUpToDate(PushRegisterService.kt:33)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at org.microg.gms.gcm.PushRegisterServiceKt.access$ensureCheckinIsUpToDate(PushRegisterService.kt:1)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at org.microg.gms.gcm.PushRegisterHandler$handleMessage$1.invokeSuspend(PushRegisterService.kt:313)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:376)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at androidx.lifecycle.LifecycleCoroutineScope.launchWhenStarted(Lifecycle.kt:96)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at org.microg.gms.gcm.PushRegisterHandler.handleMessage(PushRegisterService.kt:309)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at android.os.Looper.loopOnce(Looper.java:201)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at android.os.Looper.loop(Looper.java:288)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at java.lang.reflect.Method.invoke(Native Method)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-23 21:58:05.475 27352 27352 W GmsGcmRegister: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
03-23 21:58:05.481  1982  2051 W FrameTracker: Missed App frame:JANK_APP_DEADLINE_MISSED, 8977293, 19013067, CUJ=J<SPLASHSCREEN_EXIT_ANIM>
03-23 21:58:05.481  1982  2051 W FrameTracker: Missed App frame:UNKNOWN: 72, 8977535, 36504670, CUJ=J<SPLASHSCREEN_EXIT_ANIM>
03-23 21:58:05.481  1982  2051 W FrameTracker: Missing HWUI jank callback for vsyncId: 8977622, CUJ=J<SPLASHSCREEN_EXIT_ANIM>
03-23 21:58:05.966 27161 27161 W YT.mlplayer: Stayawake OFF

03-23 21:58:06.016  1633  8308 W InputManager-JNI: Input channel object '50e547b app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity (client)' was disposed without first being removed with the input manager!
03-23 21:58:06.019 27161 27161 E WindowManager: android.view.WindowLeaked: Activity com.google.android.apps.youtube.app.watchwhile.MainActivity has leaked window DecorView@6946dbd[InternalMainActivity] that was originally added here
03-23 21:58:06.019 27161 27161 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:943)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:931)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:391)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at android.app.Dialog.show(Dialog.java:352)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at android.app.AlertDialog$Builder.show(AlertDialog.java:1131)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at app.revanced.integrations.youtube.patches.announcements.AnnouncementsPatch.lambda$showAnnouncement$5(AnnouncementsPatch.java:108)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at app.revanced.integrations.youtube.patches.announcements.AnnouncementsPatch.$r8$lambda$t0c4W1Hqw0TNILNYdJP8KGItCtY(AnnouncementsPatch.java:0)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at app.revanced.integrations.youtube.patches.announcements.AnnouncementsPatch$$ExternalSyntheticLambda8.run(R8$$SyntheticClass:0)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at app.revanced.integrations.shared.Utils.lambda$runOnMainThreadDelayed$8(Utils.java:302)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at app.revanced.integrations.shared.Utils.$r8$lambda$2-PgGW-xRSXgOUFWr-sKo1kADqU(Utils.java:0)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at app.revanced.integrations.shared.Utils$$ExternalSyntheticLambda8.run(R8$$SyntheticClass:0)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at android.os.Looper.loop(Looper.java:288)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
03-23 21:58:06.019 27161 27161 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
03-23 21:58:06.023  1633  2510 W InputManager-JNI: Input channel object '159526b app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity (client)' was disposed without first being removed with the input manager!
03-23 21:58:06.027  1633  2510 W InputManager-JNI: Input channel object 'Letterbox_left_ActivityRecord{b8fc576 u0 app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity} t245} (client)' was disposed without first being removed with the input manager!
03-23 21:58:06.028  1633  2510 W InputManager-JNI: Input channel object 'Letterbox_top_ActivityRecord{b8fc576 u0 app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity} t245} (client)' was disposed without first being removed with the input manager!
03-23 21:58:06.028  1633  2510 W InputManager-JNI: Input channel object 'Letterbox_right_ActivityRecord{b8fc576 u0 app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity} t245} (client)' was disposed without first being removed with the input manager!
03-23 21:58:06.028  1633  2510 W InputManager-JNI: Input channel object 'Letterbox_bottom_ActivityRecord{b8fc576 u0 app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.InternalMainActivity} t245} (client)' was disposed without first being removed with the input manager!
03-23 21:58:06.034  1633  2510 W InputManager-JNI: Input channel object 'Letterbox_left_ActivityRecord{c1c1ec6 u0 app.revanced.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} t245} (client)' was disposed without first being removed with the input manager!
03-23 21:58:06.034  1633  2510 W InputManager-JNI: Input channel object 'Letterbox_top_ActivityRecord{c1c1ec6 u0 app.revanced.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} t245} (client)' was disposed without first being removed with the input manager!
03-23 21:58:06.034  1633  2510 W InputManager-JNI: Input channel object 'Letterbox_right_ActivityRecord{c1c1ec6 u0 app.revanced.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} t245} (client)' was disposed without first being removed with the input manager!
03-23 21:58:06.034  1633  2510 W InputManager-JNI: Input channel object 'Letterbox_bottom_ActivityRecord{c1c1ec6 u0 app.revanced.android.youtube/com.google.android.youtube.app.honeycomb.Shell$HomeActivity} t245} (client)' was disposed without first being removed with the input manager!
03-23 21:58:06.035  1633  8308 W WindowManager: Failed looking up window session=Session{31c7d13 27161:u0a10214} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:6058 com.android.server.wm.WindowManagerService.relayoutWindow:2293 com.android.server.wm.Session.relayout:253 
03-23 21:58:06.043  1633  5512 W WindowManager: Failed looking up window session=Session{31c7d13 27161:u0a10214} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:6058 com.android.server.wm.Session.setOnBackInvokedCallbackInfo:944 android.view.IWindowSession$Stub.onTransact:1180 
03-23 21:58:06.043  1633  5512 E WindowManager: setOnBackInvokedCallback(): No window state for package:app.revanced.android.youtube
03-23 21:58:06.043  1633  8308 W WindowManager: Failed looking up window session=Session{31c7d13 27161:u0a10214} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:6058 com.android.server.wm.WindowManagerService.removeWindow:2076 com.android.server.wm.Session.remove:230
```

### Additional context

Screenshot before crash:
![revanced-crash](https://github.com/ReVanced/revanced-patches/assets/55359236/0f5c5a83-2940-435d-953b-a7db675957b2)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by johnconner122** [comment]
If you are rooted, then don't include `microG support` or `GmsCore support` patch.

**Comment by oSumAtrIX** [comment]
Your GmsCore with group id com.google rejects YouTube die its signature

**Comment by REmerald** [comment]
> If you are rooted, then don't include `microG support` or `GmsCore support` patch.

I'm not rooted

> Your GmsCore with group id com.google rejects YouTube die its signature

Could you be more specific, please? Is there any way I can fix it within Revanced Manager?

**Comment by johnconner122** [comment]
Instead of setting value to `com.google`, instead set it to `app.revanced`. And install gmsCore:
https://github.com/ReVanced/GmsCore/releases/tag/v0.2.28.231657

**Comment by REmerald** [comment]
> Instead of setting value to `com.google`, instead set it to `app.revanced`. And install gmsCore: https://github.com/ReVanced/GmsCore/releases/tag/v0.2.28.231657

I would like not to install another gmscore just for revanced. I was asking about "the signature".

I installed and launched unpatched youtube and it worked flawlessly, so it seems possible to fix.

@oSumAtrIX, I didn't understand very well about the signature. Is there a fix like turning some feature on/off in MicroG app? Or do I report it to MicroG? Maybe related to [this](https://github.com/microg/GmsCore/issues/2253) issue?
FYI, I have everything turned on: Register Device, Cloud Messaging, Allow SafetyNet attestation (though integrity check fails: "ROM is not clean", "Bootloader is not locked", but it does not prevent normal youtube app to work).

**Comment by oSumAtrIX** [comment]
> I would like not to install another gmscore just for revanced. I was asking about "the signature".

Like I previously explained. Whatever GmsCore you are using right now, will reject modded apps such as YouTube patched with ReVanced. You will need a specially built one such as ReVanced MicroG or you can install the patched all by mounting to use with your distribution of GmsCore
