### ISSUE TITLE
bug(YouTube - Hide ads): Hide fullscreen ads crashes app on startup

### ISSUE THREAD

**Issue by yangton** [ReVanced/revanced-patches#2908]
### Bug description

yt revanced crashed 
The INJECT_EVENTS permission is a sensitive permission that allows apps to control user input. This permission is typically granted to system apps and apps that require accessibility services. Modified apps like Revanced do not have this permission by default.

### Error logs

```shell

SystemUptimeMs: 218588191
Process: app.revanced.android.youtube
PID: 13211
UID: 10355
Frozen: false
Flags: 0x30dbbe44
Package: app.revanced.android.youtube v1544154560 (19.04.37)
Foreground: Yes
Process-Runtime: 2894
Build: google/oriole_beta/oriole:14/AP21.240216.010/11529813:user/release-keys
Crash-Handler: hfy
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3183)
	at android.os.Parcel.createException(Parcel.java:3167)
	at android.os.Parcel.readException(Parcel.java:3150)
	at android.os.Parcel.readException(Parcel.java:3092)
	at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1682)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1415)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1425)
	at android.app.Instrumentation.sendKeySync(Instrumentation.java:1206)
	at android.app.Instrumentation.sendKeyDownUpSync(Instrumentation.java:1250)
	at app.revanced.integrations.youtube.patches.components.AdsFilter.lambda$closeFullscreenAd$1(AdsFilter.java:173)
	at app.revanced.integrations.youtube.patches.components.AdsFilter.$r8$lambda$OPSRVU8xFM5HCQeVyfFkDTp9xF0(AdsFilter.java:0)
	at app.revanced.integrations.youtube.patches.components.AdsFilter$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:935)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:788)
	at android.os.Binder.execTransactInternal(Binder.java:1500)
	at android.os.Binder.execTransact(Binder.java:1444)
```

### Solution

One potential solution is to grant the INJECT_EVENTS permission to the Revanced app. However, this is not recommended as it can pose a security risk.
A more secure solution would be to modify the Revanced app to avoid the need for the INJECT_EVENTS permission. This could involve redesigning the app's functionality or using different methods to achieve the desired results.

### Steps To Reproduce:
 * Install the Revanced app on an Android device.
 * Open the Revanced app and enable ad blocking.
 * Play a video with ads.
 * Tap on the ad to close it.
 * A "SecurityException" will be thrown.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by yangton** [comment]
> Leaving this open until the issue is fixed

Ok Thanks

**Comment by inotia00** [comment]
I too have been aware of this issue and have been trying to find a way to hide fullscreen ads on YouTube without using the `Instrumentation.SendKeySync(KeyEvent)` method.

Fullscreen ad was a custom AlertDialog, which can be easily hidden.

The related commits are:
https://github.com/inotia00/revanced-patches/commit/b25413cb3b3e96779af80aa5cd08f5da5718c7a8
https://github.com/inotia00/revanced-integrations/commit/9f4527150b9499213be57704cc396229792d4ce8
