### ISSUE TITLE
bug: messenger does not compile when patching

### ISSUE THREAD

**Issue by rayjay7225** [ReVanced/revanced-patches#2912]
### Bug description

i am trying to patch facebook messenger but it errors out after the "compiling modified resources" message. 

Command used to patch: 
`java -jar revanced-cli.jar patch -b revanced-patches.jar --exclusive --ii 71 --ii 73 --ii 124 base.apk`

i compiled in the /tmp/compiling directory for shorter paths
error:
![image](https://github.com/ReVanced/revanced-patches/assets/79537106/7d6f9f4c-422f-452c-b0d9-ab39a5095106)

used patches:

71 : Disable typing indicator
73 : Hide inbox ads
124 : Change package name (default package name)

### Error logs

```shell
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: Disable switching emoji to sticker excluded 
INFO: Override certificate pinning excluded 
INFO: Enable Android debugging excluded 
INFO: Remove screen capture restriction excluded 
INFO: Export all activities excluded 
INFO: Predictive back gesture excluded 
INFO: Spoof SIM country excluded 
INFO: Remove screenshot restriction excluded 
INFO: Spoof Wi-Fi connection excluded 
INFO: Setting patch options 
INFO: Deleting existing temporary files directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Disable typing indicator succeeded 
INFO: Hide inbox ads succeeded 
INFO: Change package name succeeded 
INFO: Compiling patched dex files 
INFO: Compiled classes.dex 
INFO: Compiled classes2.dex 
INFO: Compiled classes3.dex 
INFO: Compiled classes4.dex 
INFO: Compiled classes5.dex 
INFO: Compiled classes6.dex 
INFO: Compiled classes7.dex 
INFO: Compiled classes8.dex 
INFO: Compiled classes9.dex 
INFO: Compiled classes10.dex 
INFO: Compiled classes11.dex 
INFO: Compiling modified resources 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170009.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17000a.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17000b.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17000d.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17000e.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17000f.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170010.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170011.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170012.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170013.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170016.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170017.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170018.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170019.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17001a.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17001b.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17001c.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17008d.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17008e.xml'. 
WARNING: error: invalid file path '/tmp/compiling/base-patched-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f1700d3.xml'. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_128619343203083194843969452731537607519.tmp, compile, --dir, /tmp/compiling/base-patched-temporary-files/patcher/apk/res, --legacy, -o, /tmp/compiling/base-patched-temporary-files/patcher/apk/build/resources.zip]
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
        at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:134)
        at app.revanced.patcher.Patcher.get(Patcher.kt:268)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:303)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_128619343203083194843969452731537607519.tmp, compile, --dir, /tmp/compiling/base-patched-temporary-files/patcher/apk/res, --legacy, -o, /tmp/compiling/base-patched-temporary-files/patcher/apk/build/resources.zip]
        at brut.util.OS.exec(OS.java:104)
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
        ... 13 more
```

### Additional context

revanced patches version used: 4.3.0
(i also tried version 4.4.0-dev.10)

revanced cli version used: 4.5.0

OS: arch linux
java version: openjdk 11.0.22

version of messenger to patch: 450.0.0.43.109 
apk dumped via adb

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Resource patching breaks on Messenger, caused by including the change package name patch. Nothing that can be done, the issue originates in AAPT.
