### ISSUE TITLE
bug: change package name patch fails for Mi Home

### ISSUE THREAD

**Issue by GyDavid22** [ReVanced/revanced-patches#2916]
### Type

Error while patching

### Bug description

Patching Mi Home with the change package name patch gets aborted in the ReVanced Manager app.

### Steps to reproduce

1. Download Mi Home apk (other versions fail too) [https://www.apkmirror.com/apk/beijing-xiaomi-mobile-software-co-ltd/mihome/mihome-8-9-503-release/mi-home-8-9-503-android-apk-download/](url)
2. Open ReVanced Manager
3. On the Patch tab open the downloaded apk and select change package name patch
4. Start patching and wait

### Relevant log output

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Deleting existing resource cache directory
Decoding resources
Executing patches
Change package name succeeded
Compiling modified dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~qXGqZBWAzF08ry-CTb3k7w==/app.revanced.manager.flutter-kRm8HgBg9G4H3EHkbjAv4w==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUSTFW/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUSTFW/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
	at app.revanced.patcher.Patcher.get(Patcher.kt:232)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$13(MainActivity.kt:244)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$6dokpIuPm1kqn7qLA9JtiVzSCi0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~qXGqZBWAzF08ry-CTb3k7w==/app.revanced.manager.flutter-kRm8HgBg9G4H3EHkbjAv4w==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUSTFW/cache/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XUSTFW/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
	... 7 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by fnfontana** [comment]
I'm facing something similar when trying to patch YouTube. Here is my log:
```
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Client spoof succeeded
Disable Shorts on startup succeeded
Hide ads succeeded
Remember video quality succeeded
SponsorBlock succeeded
Vanced MicroG support succeeded
Video ads succeeded
Compiling modified dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~cS-ydWrCwSJVouZU3Gef6A==/app.revanced.manager.flutter-YSCFdFJrdpLP3Uc0tVNwMg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NNLPSG/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1539440064, --version-name, 18.32.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL2587077579515926134.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NNLPSG/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NNLPSG/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NNLPSG/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
	at app.revanced.patcher.Patcher.get(Patcher.kt:232)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$13(MainActivity.kt:244)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$6dokpIuPm1kqn7qLA9JtiVzSCi0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~cS-ydWrCwSJVouZU3Gef6A==/app.revanced.manager.flutter-YSCFdFJrdpLP3Uc0tVNwMg==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NNLPSG/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 33, --version-code, 1539440064, --version-name, 18.32.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL2587077579515926134.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NNLPSG/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NNLPSG/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-NNLPSG/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

**Comment by oSumAtrIX** [comment]
This is not caused by any patch and is an issue with aapt which is out of scopd

**Comment by fnfontana** [comment]
What is aapt? Can you please give some clue of where I should seek for help?

Em sáb., 2 de set. de 2023 02:13, oSumAtrIX ***@***.***>
escreveu:

**Comment by oSumAtrIX** [comment]
Here you can find more about AAPT2: https://developer.android.com/tools/aapt2
