### ISSUE TITLE
bug: YouTube ReVanced crash at startup

### ISSUE THREAD

**Issue by cj81499** [ReVanced/revanced-patches#2931]
### Bug description

Using latest revanced manager and latest default patches, Samsung Galaxy S21.

### Error logs

```shell
03-27 18:20:22.992 32732 32732 D AndroidRuntime: Shutting down VM
03-27 18:20:22.992 32732 32732 E AndroidRuntime: FATAL EXCEPTION: main
03-27 18:20:22.992 32732 32732 E AndroidRuntime: Process: app.revanced.android.youtube, PID: 32732
03-27 18:20:22.992 32732 32732 E AndroidRuntime: java.lang.NoSuchMethodError: No static method setContext(Landroid/content/Context;)V in class Lapp/revanced/integrations/shared/Utils; or its super classes (declaration of 'app.revanced.integrations.shared.Utils' appears in /data/app/~~VgJxuVC7m85V89vhkmrTbg==/app.revanced.android.youtube-yNrtaq2zYhRgE-rX59uSLA==/base.apk!classes7.dex)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at ajmv.onCreate(Unknown Source:0)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at fxf.e(PG:2)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at fxh.h(PG:7)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at fxf.onCreate(PG:18)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1316)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7685)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8893)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
03-27 18:20:22.992 32732 32732 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

### Additional context

I saw https://github.com/ReVanced/GmsCore/issues/8 and https://github.com/ReVanced/revanced-patches/pull/2907#issuecomment-2020300362, but I already have the "stock" YouTube app installed.

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The method is present but you may be using old integrations. Reinstall ReVanced Manager or force it to redownload the patches and integrations by resetting the API.

**Comment by cj81499** [comment]
Reinstalling ReVanced Manager and repatching worked.

Thank you for the **VERY** fast response and your work on the ReVanced project. Take care!
