### ISSUE TITLE
bug: Revanced youtube patching error

### ISSUE THREAD

**Issue by analgaming12** [ReVanced/revanced-patches#2933]
### Bug description

Steps:
1-download revanced manager v1.19.3
2-download YouTube 19.09.37
3-use that youtube apk in app
4-select default patches
5-error

### Error logs

```shell
That command returned nothing after 5 minutes
```

### Additional context

Patching error logs:
- Device Info
ReVanced Manager: 1.19.3
Model: SM-G998U
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.09.37 (Suggested: 19.09.37)
Patches version: v4.4.0
Patches added: Default
Patches removed: None
Default patch options changed: Theme [Dark theme background color: @android:color/system_neutral1_900, Light theme background color: @android:color/system_neutral1_50]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
An error occurred:
t0.b: Could not generate: values-gu/strings.xml
	at u0.b.e(Unknown Source:99)
	at u0.b.c(Unknown Source:190)
	at app.revanced.patcher.data.ResourceContext.decodeResources$revanced_patcher(Unknown Source:44)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:224)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:1)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:2)
	at b6.f.b(Unknown Source:2)
	at b6.a.a(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at y5.o0.run(Unknown Source:93)
	at y5.u0.P(Unknown Source:46)
	at y5.e.t0(Unknown Source:23)
	at y5.h.a(Unknown Source:73)
	at y5.g.c(Unknown Source:0)
	at y5.h.b(Unknown Source:6)
	at y5.g.d(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: e1.d: file must be a directory: /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-RBTQEV/revanced-temporary-files/apk/res/values-gu
	at e1.f.<init>(Unknown Source:31)
	at e1.f.n(Unknown Source:14)
	at e1.a.k(Unknown Source:22)
	at e1.a.j(Unknown Source:24)
	at u0.b.e(Unknown Source:6)
	... 20 more

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You don't have enough space on your device

**Comment by analgaming12** [comment]
thanks for the reply. do you think in the future there could be an error message that makes the issue more evident?
