### ISSUE TITLE
bug: Failure to patch Infinity 6.2.1 with Oauth2

### ISSUE THREAD

**Issue by warmoans** [ReVanced/revanced-patches#2940]
### Type

Error while patching

### Bug description

Unable to patch Infinity 6.2.1 with Oauth2 patch

### Steps to reproduce

Patch infinity 6.2.1 with Oauth2 patch

### Relevant log output

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Executing patches
Spoof client failed: app.revanced.patcher.patch.PatchException: Failed to resolve GetHttpBasicAuthHeaderFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:23)
	at app.revanced.patches.reddit.customclients.AbstractSpoofClientPatch.execute$executePatch(AbstractSpoofClientPatch.kt:50)
	at app.revanced.patches.reddit.customclients.AbstractSpoofClientPatch.execute(AbstractSpoofClientPatch.kt:52)
	at app.revanced.patches.reddit.customclients.AbstractSpoofClientPatch.execute(AbstractSpoofClientPatch.kt:14)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:214)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$13(MainActivity.kt:213)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$6dokpIuPm1kqn7qLA9JtiVzSCi0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Compiling modified dex files
Signing APK
Patched
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by johnconner122** [comment]
Latest is [6.1.1](https://github.com/Docile-Alligator/Infinity-For-Reddit/releases/tag/v6.1.1)

**Comment by BabyOilJohnson** [comment]
Issue here too on v6.2.1.

**Comment by johnconner122** [comment]
Use previous version as new version is subscription based, no need to change oAuth key.

**Comment by Shadowvaporwarez** [comment]
6.1.1 isn't functional 

> Use previous version as new version is subscription based, no need to change oAuth key.

6.1.1 isn't functional for me anymore, even if it's patched. But sure if it's been nuked with 6.2.3 coming out?

**Comment by johnconner122** [comment]
> 6.1.1 isn't functional
> 
> > Use previous version as new version is subscription based, no need to change oAuth key.
> 
> 6.1.1 isn't functional for me anymore, even if it's patched. But sure if it's been nuked with 6.2.3 coming out?

I am using 5.4.2, and it's working fine for me.

**Comment by swebow** [comment]
Can add I get the same error with 6.2.3 that I downloaded from their Github.

https://github.com/Docile-Alligator/Infinity-For-Reddit/releases/tag/v6.2.3

**Comment by johnconner122** [comment]
> Can add I get the same error with 6.2.3 that I downloaded from their Github.

Newer versions have different code, so latest supported version is 6.1.1

**Comment by PandoraPandorita** [comment]
If it helps, I noticed that the F-droid version did patch successfully, however, I don't know how long that one will last up/being up-to-date.

**Comment by sinkaf** [comment]
I was going to try it, but the patch does not appear in Revanced Manager right now.

**Comment by Shadowvaporwarez** [comment]
> I was going to try it, but the patch does not appear in Revanced Manager right now.

It depends which version you use, some of the versions released (6.2.2 until 6.2.5) we're using a different package name and different code. 6.2.5 has returned to the normal package name so the patch appears but it throws errors when you try and patch

**Comment by sinkaf** [comment]
> > I was going to try it, but the patch does not appear in Revanced Manager right now.
> 
> It depends which version you use, some of the versions released (6.2.2 until 6.2.5) we're using a different package name and different code. 6.2.5 has returned to the normal package name so the patch appears but it throws errors when you try and patch 


Thank you for your reply.

I tried with 6.1.1. It shows up now, I think there was another problem a few hours ago. Any progress on the version that will work with the patch?

**Comment by dragibusnoir** [comment]
> > > I was going to try it, but the patch does not appear in Revanced Manager right now.
> > 
> > It depends which version you use, some of the versions released (6.2.2 until 6.2.5) we're using a different package name and different code. 6.2.5 has returned to the normal package name so the patch appears but it throws errors when you try and patch 
> 
> 
> Thank you for your reply.
> 
> I tried with 6.1.1. It shows up now, I think there was another problem a few hours ago. Any progress on the version that will work with the patch?

6.1.1 F-droid version

**Comment by sinkaf** [comment]
Thank you but I get an error code;

Spoof client failed: app.revanced.patcher.patch.PatchException: / storage/emulated/0/ reddit_client_id_revanced.txt: open failed: EACCES (Permission denied at app.revanced.patcher.Patcher$apply $1.invokeSuspend $executePatch(Patcher.kt:153 at app.revanced.patcher.Patcher$apply $1.invokeSuspend(Patcher.kt:170 at app.revanced.patcher.Patcher$apply $1.invoke(Unknown Source:8 at app.revanced.patcher.Patcher$apply $1.invoke(Unknown Source:4 at

It may be an error on my part.


@dragibusnoir

**Comment by dragibusnoir** [comment]
@sinkaf 

It worked for me, maybe you didn't give all the permissions to the revanced manager app.

And I made a new ID too

**Comment by sinkaf** [comment]
> @sinkaf 
> 
> It worked for me, maybe you didn't give all the permissions to the revanced manager app.
> 
> And I made a new ID too

Thanks a hundred times, but the problem was because the "permission to manage all files" was not granted. I missed a simple permission, your warning worked. Version 6.1.1 is patched and working.

**Comment by AndhikaWB** [comment]
I'm using 6.1.1 and the patch itself is successful, but still can't connect to Reddit since 3-4 hours ago.
