### ISSUE TITLE
bug (facebook/hide story ads): patch fails to apply on 457.0.0.54.84

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#2961]
### Bug description

The patch fails to apply on the newest base version of Facebook (457.0.0.54.84)

### Error logs

```shell
Hide story ads failed: app.revanced.patcher.patch.PatchException: Failed to resolve FetchMoreAdsFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
	at app.revanced.patches.facebook.ads.story.HideStoryAdsPatch.execute(HideStoryAdsPatch.kt:24)
	at app.revanced.patches.facebook.ads.story.HideStoryAdsPatch.execute(HideStoryAdsPatch.kt:12)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:1)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:2)
	at b6.f.b(Unknown Source:2)
	at b6.a.a(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at y5.o0.run(Unknown Source:93)
	at y5.u0.P(Unknown Source:46)
	at y5.e.t0(Unknown Source:23)
	at y5.h.a(Unknown Source:73)
	at y5.g.c(Unknown Source:0)
	at y5.h.b(Unknown Source:6)
	at y5.g.d(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.k(Unknown Source:0)
	at app.revanced.manager.flutter.f.run(Unknown Source:20)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/96

**Comment by n1cKz1** [comment]
That's a different issue that has to do with this: 

> The patches only works with [Facebook APK for Android 11+](https://www.apkmirror.com/apk/facebook-2/facebook/facebook-441-0-0-32-109-release/facebook-441-0-0-32-109-9-android-apk-download/). So choose it, but if your device running Android below Android 11, just waiting for the fix. Hopefully it will get fixes.

The patch worked for me until this base version

**Comment by oSumAtrIX** [comment]
Include your issue as a comment, both is the same

**Comment by Aqqly** [comment]
I have this issue as well, Android 15
