### ISSUE TITLE
bug: return yt dislikes fails to get patched

### ISSUE THREAD

**Issue by Ferixy** [ReVanced/revanced-patches#2977]
### Type

Error while patching

### Bug description

Hi there. I'm trying to patch youtube 18.23.35(as suggested by revanced manager) and revanced manager fails to patch the following components:
"return youtube dislikes" and "hide layout components"

I'm using the latest revanced manager and revanced patches.
my device is galaxy s22 ultra (snapdragon edition)

### Steps to reproduce

- try to patch yt v18.23.35 with default/recommended patch selection
- builds the apk successfully but fails to patch the 2 particular patches

### Relevant log output

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Always autorepeat succeeded
Client spoof succeeded
Comments succeeded
Copy video url succeeded
Custom branding succeeded
Disable Shorts on startup succeeded
Disable auto captions succeeded
Disable player popup panels succeeded
Disable zoom haptics succeeded
Enable debugging succeeded
External downloads succeeded
HDR auto brightness succeeded
Hide Shorts components succeeded
Hide ads succeeded
Hide album cards succeeded
Hide autoplay button succeeded
Hide breaking news shelf succeeded
Hide captions button succeeded
Hide cast button succeeded
Hide crowdfunding box succeeded
Hide email address succeeded
Hide endscreen cards succeeded
Hide filter bar succeeded
Hide floating microphone button succeeded
Hide info cards succeeded
Hide layout components failed: app.revanced.patcher.patch.PatchException: Failed to resolve ParseElementFromBufferFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:23)
	at app.revanced.patches.youtube.layout.hide.general.patch.HideLayoutComponentsPatch.execute(HideLayoutComponentsPatch.kt:273)
	at app.revanced.patches.youtube.layout.hide.general.patch.HideLayoutComponentsPatch.execute(HideLayoutComponentsPatch.kt:25)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:214)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$13(MainActivity.kt:213)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$6dokpIuPm1kqn7qLA9JtiVzSCi0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Hide load more button succeeded
Hide player buttons succeeded
Hide seekbar succeeded
Hide timestamp succeeded
Hide video action buttons succeeded
Hide watermark succeeded
Minimized playback succeeded
Navigation buttons succeeded
Old video quality menu succeeded
Open links externally succeeded
Playback speed succeeded
Player flyout menu succeeded
Premium heading succeeded
Remember video quality succeeded
Return YouTube Dislike failed: app.revanced.patcher.patch.PatchException: Failed to resolve TextComponentAtomicReferenceFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:23)
	at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:90)
	at app.revanced.patches.youtube.layout.returnyoutubedislike.patch.ReturnYouTubeDislikePatch.execute(ReturnYouTubeDislikePatch.kt:30)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:147)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:170)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:214)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$13(MainActivity.kt:213)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$6dokpIuPm1kqn7qLA9JtiVzSCi0(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Seekbar tapping succeeded
SponsorBlock succeeded
Spoof app version succeeded
Swipe controls succeeded
Tablet mini player succeeded
Theme succeeded
Vanced MicroG support succeeded
Video ads succeeded
Wide searchbar succeeded
Compiling modified dex files
Compiling modified resources
Signing APK
Patched
Installing patched file using nonroot method
Installed!
```

### Solution

nothing so far

### Additional context

ily

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Unsupported version.

**Comment by Ferixy** [comment]
sorry but revanced manager literally suggested me to use this version of yt?!

**Comment by oSumAtrIX** [comment]
Send a picture

**Comment by Ferixy** [comment]
before opening the issue here I reinstalled revanced manager just in case. and now that you said you want a screenshot app is showing a newer version as suggested version and also it sometimes shows all versions as suggested. idk if I'm on zaza or something but I swear it suggested me that particular version. anyways, even if I'm not blind I'm sorry.
![Screenshot_20230912_130743_ReVanced Manager](https://github.com/ReVanced/revanced-patches/assets/77561374/498c71e7-ce14-4226-b16c-aacbaed7f0d7)
![Screenshot_20230912_130718_ReVanced Manager](https://github.com/ReVanced/revanced-patches/assets/77561374/5b7505b4-a28e-4b01-a1a6-6ebec3bf2db2)

**Comment by Ferixy** [comment]
yes after reinstalling revanced manager and getting suggested to use 18.32.39 I'm downloading it to the exact thing
