### ISSUE TITLE
bug: Tiktok error

### ISSUE THREAD

**Issue by samaraboy** [ReVanced/revanced-patches#3007]
### Type

Error while patching

### Bug description

Hello Team! I selected all the patches and an error occurs when creating a mod. I used the latest version of Tikok 31.1.5

### Steps to reproduce

1. I downloaded tiktok from apkmirrior, application version 31.1.5
2. I selected all the patches in the revanced manager.
3. I got errors.

### Relevant log output

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
An error occurred:
lanchon.multidexlib2.DuplicateTypeException: Lcom/bytedance/libbytevc1enc10bit/R$drawable;
	at lanchon.multidexlib2.MultiDexContainerBackedDexFile.<init>(MultiDexContainerBackedDexFile.java:44)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:36)
	at app.revanced.patcher.data.BytecodeContext$classes$2.invoke(BytecodeContext.kt:44)
	at app.revanced.patcher.data.BytecodeContext$classes$2.invoke(BytecodeContext.kt:42)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at app.revanced.patcher.data.BytecodeContext.getClasses(BytecodeContext.kt:42)
	at app.revanced.patcher.data.BytecodeContext$Integrations.flush(BytecodeContext.kt:120)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:157)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:240)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$17(MainActivity.kt:239)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$ano5ZEDeC0qujvhPEYSwCbNnLNQ(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda3.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Screenshots or videos

![Screenshot_2023-09-21-11-40-16-585_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/128523572/d125d829-41a5-4c4e-b241-5705c9b88c56)
![Screenshot_2023-09-21-11-40-30-653_app revanced manager flutter](https://github.com/ReVanced/revanced-patches/assets/128523572/11f9d011-ca23-4b1e-9572-792f8324a976)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
Isn't it related to: https://github.com/ReVanced/revanced-patches/issues/2832
30.9.xx & upper version already doesn't work with hide ads patch
Try to patch 30.7.xx

**Comment by samaraboy** [comment]
Working tiktok version: 30.8.4
Higher versions do not work
