### ISSUE TITLE
bug: (Tumblr) Patches specified to be included are excluded

### ISSUE THREAD

**Issue by mmrobledo** [ReVanced/revanced-patches#3011]
### Bug description

I have breen trying to patch Tumblr using ReVanced CLI, since it's not possible on my phone. I'm not too familiar with these kind of things so I have been following the step-by-step guides here on GitHub. _Ideally_ I want all five patches, but the most important one to me is the "Fix old versions" patch so I have been adding `-i 'Include patch 5'` in all my attempts, however, every single time at the very beginning alongside some other options I get "INFO: Fix old versions excluded". I'm unsure if I'm doing something wrong or if it's indeed a bug? I copy-pasted below what I have on my console (I hope this is the right place to post this lol, if not, my bad.)

### Error logs

```shell
PS C:\Users\mmrob\Downloads\ReVanced> java -jar revanced-cli-4.6.0-all.jar patch -b revanced-patches-4.6.0.jar -i 'Include patch 5' -m revanced-integrations-1.7.0.apk -o tumblrv2.apk tumblr.apk --options tumblr-options.json
INFO: Loading patches
INFO: Decoding app manifest
INFO: Spoof SIM country excluded
INFO: Remove screenshot restriction excluded
INFO: Spoof Wi-Fi connection excluded
INFO: Override certificate pinning excluded
INFO: Enable Android debugging excluded
INFO: Change package name excluded
INFO: Export all activities excluded
INFO: Predictive back gesture excluded
INFO: Remove screen capture restriction excluded
INFO: Fix old versions excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Executing patches
INFO: Disable blog notification reminder succeeded
SEVERE: Disable dashboard ads failed:
app.revanced.patcher.patch.PatchException: 'Disable dashboard ads' depends on 'TimelineFilterPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Failed to resolve TimelineFilterIntegrationFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
        at app.revanced.patches.tumblr.timelinefilter.TimelineFilterPatch.execute(TimelineFilterPatch.kt:54)
        at app.revanced.patches.tumblr.timelinefilter.TimelineFilterPatch.execute(TimelineFilterPatch.kt:16)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:155)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:303)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:302)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:160)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:303)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:302)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

INFO: Disable gift message popup succeeded
INFO: Disable in-app update succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Aligning APK
INFO: Signing APK
INFO: Saved to C:\Users\mmrob\Downloads\ReVanced\tumblrv2.apk
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
-i expects the patch name as the option value. In your case it is `Fix old versions`.
