### ISSUE TITLE
bug: (YouTube Music): Some patches fail to be applied in 6.49.53

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#3082]
### Bug description

`Hide 'Get Music Premium' label` and `Remove upgrade button` fails to be applied
Patch with CLI with default patches:

```
java -jar revanced-cli-4.6.0-all.jar patch -p -o Install\YouTube_Music_6.49.53-arm64-v8a_ReVanced.apk --options options.json -b revanced-patches-4.8.0-dev.8.jar --keystore-entry-alias=******** --keystore-password=******** --keystore-entry-password=******** --keystore=********.keystore -m revanced-integrations-1.9.0-dev.4.apk Apps\com.google.android.apps.youtube.music-6.49.53-arm64-v8a.apk
```

### Error logs

```shell
INFO: Loading patches
INFO: Decoding app manifest
INFO: Spoof Wi-Fi connection excluded
INFO: Remove screenshot restriction excluded
INFO: Remove screen capture restriction excluded
INFO: Export all activities excluded
INFO: Enable Android debugging excluded
INFO: Override certificate pinning excluded
INFO: Hex excluded
INFO: Change package name excluded
INFO: Spoof SIM country excluded
INFO: Predictive back gesture excluded
INFO: Hide category bar excluded
INFO: Permanent repeat excluded
INFO: Permanent shuffle excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing temporary files directory
INFO: Decoding resources
INFO: Executing patches
INFO: Bypass certificate checks succeeded
INFO: Enable exclusive audio playback succeeded
INFO: GmsCore support succeeded
SEVERE: Hide 'Get Music Premium' label failed:
app.revanced.patcher.patch.PatchException: Failed to resolve HideGetPremiumFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:26)
        at app.revanced.patches.music.layout.premium.HideGetPremiumPatch.execute(HideGetPremiumPatch.kt:48)
        at app.revanced.patches.music.layout.premium.HideGetPremiumPatch.execute(HideGetPremiumPatch.kt:16)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:303)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:302)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

INFO: Hide music video ads succeeded
INFO: Minimized playback succeeded
SEVERE: Remove upgrade button failed:
app.revanced.patcher.patch.PatchException: Failed to resolve PivotBarConstructorFingerprint
        at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:26)
        at app.revanced.patches.music.layout.upgradebutton.RemoveUpgradeButtonPatch.execute(RemoveUpgradeButtonPatch.kt:82)
        at app.revanced.patches.music.layout.upgradebutton.RemoveUpgradeButtonPatch.execute(RemoveUpgradeButtonPatch.kt:22)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:173)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:205)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$1$1.invokeSuspend(PatchCommand.kt:303)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:302)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

INFO: Change package name succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Compiling modified resources
INFO: Aligning APK
INFO: Signing APK
INFO: Saved to E:\ANDROID\APPS\ReVanced\Patched\Install\YouTube_Music_6.49.53-arm64-v8a_ReVanced.apk
INFO: Purging temporary files
INFO: Failed to purge resource cache directory
```

### Solution

Better constrain YouTube Music to version which is supported by current patches like on YouTube one.

### Acknowledgements

- [ ] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Both issues are regarding patching issues, there's no point in splitting the issues
