### ISSUE TITLE
bug: TikTok - OutOfMemoryError

### ISSUE THREAD

**Issue by 98xe** [ReVanced/revanced-patches#3109]
### Bug description

Getting an OutOfMemoryError error when trying to patch TikTok.

### Error logs

```shell
~ Device Info
ReVanced Manager: 1.11.2
Build: release
Model: SM-G975W
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi

~ Patch Info
App: com.zhiliaoapp.musically v30.8.4
Patches version: v2.193.0
Patches: Hide ads, Feed filter, Downloads, Show seekbar, Playback speed, Disable login requirement, Fix Google login, Settings

~ Settings
Enabled changing patches: false
Enabled universal patches: false
Enabled experimental patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

~ Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Disable login requirement succeeded
Downloads succeeded
Feed filter succeeded
Fix Google login succeeded
Hide ads succeeded
Playback speed succeeded
Settings succeeded
Show seekbar succeeded
Compiling modified dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 9622368 byte allocation with 9238504 free bytes and 9021KB until OOM, target footprint 536870912, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3161)
	at com.android.tools.smali.dexlib2.writer.io.MemoryDataStore.growBufferIfNeeded(MemoryDataStore.java:91)
	at com.android.tools.smali.dexlib2.writer.io.MemoryDataStore.access$000(MemoryDataStore.java:39)
	at com.android.tools.smali.dexlib2.writer.io.MemoryDataStore$1.write(MemoryDataStore.java:79)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
	at com.android.tools.smali.dexlib2.writer.DexDataWriter.write(DexDataWriter.java:86)
	at com.android.tools.smali.dexlib2.writer.DexDataWriter.write(DexDataWriter.java:80)
	at com.android.tools.smali.dexlib2.writer.io.MemoryDeferredOutputStream.writeTo(MemoryDeferredOutputStream.java:60)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1132)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:415)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:370)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:158)
	at lanchon.multidexlib2.DexIO.access$000(DexIO.java:38)
	at lanchon.multidexlib2.DexIO$1.call(DexIO.java:99)
	at lanchon.multidexlib2.DexIO$1.call(DexIO.java:96)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```
```


### Solution

_No response_

### Additional context

APK downloaded from APKMirror.

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by lvm12** [comment]
@oSumAtrIX what does "closed this as not planned" mean?

**Comment by oSumAtrIX** [comment]
It means one of those: 
![image](https://github.com/ReVanced/revanced-patches/assets/13122796/9cad7495-d45a-41cc-82c8-ed378e6affd2)
