### ISSUE TITLE
bug(YouTube - Restore old video quality menu): App crashes if Shorts flyout menu quality is opened

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patches#3134]
### Bug description

Some accounts now show a quality menu in the Shorts flyout menu.

Selecting this menu crashes the app, as it's using the old video quality menu hook.

### Error logs

```shell
RestoreOldVideoQualityMenuPatch: Added listener to old type of quality menu
RestoreOldVideoQualityMenuPatch: Added listener to old type of quality menu
RestoreOldVideoQualityMenuPatch: Added listener to old type of quality menu
RestoreOldVideoQualityMenuPatch: Added listener to old type of quality menu
RestoreOldVideoQualityMenuPatch: Added listener to old type of quality menu
RestoreOldVideoQualityMenuPatch: Found advanced menu item in old type of quality menu
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: app.revanced.android.youtube, PID: 14805
AndroidRuntime: java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
AndroidRuntime: 	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
AndroidRuntime: 	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
AndroidRuntime: 	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
AndroidRuntime: 	at java.util.Objects.checkIndex(Objects.java:359)
AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:434)
AndroidRuntime: 	at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:394)
AndroidRuntime: 	at mqd.onItemClick(PG:1)
AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1360)
AndroidRuntime: 	at app.revanced.integrations.youtube.patches.playback.quality.RestoreOldVideoQualityMenuPatch$1.onChildViewAdded(RestoreOldVideoQualityMenuPatch.java:65)
AndroidRuntime: 	at android.view.ViewGroup.dispatchViewAdded(ViewGroup.java:5379)
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The advanced menu is the last item in the list, so an OOB can be prevented by using the last index
