### ISSUE TITLE
Bug(x) : downloads

### ISSUE THREAD

**Issue by shifoc** [ReVanced/revanced-patches#3146]
### Bug description

Patching X v10.40.0-release.0-310400000 is returning this error

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: SM-S908E
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.twitter.android v10.39.0-release.0 (Suggested: Any)
Patches version: v4.7.0
Patches added: Default
Patches removed: Dynamic color, Hide recommended users
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Applied 2 patches
Unlock downloads failed: app.revanced.patcher.patch.PatchException: com.android.tools.smali.dexlib2.builder.instruction.BuilderInstruction35c cannot be cast to com.android.tools.smali.dexlib2.iface.instruction.TwoRegisterInstruction
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:239)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.ClassCastException: com.android.tools.smali.dexlib2.builder.instruction.BuilderInstruction35c cannot be cast to com.android.tools.smali.dexlib2.iface.instruction.TwoRegisterInstruction
	at app.revanced.patches.twitter.interaction.downloads.UnlockDownloadsPatch$execute$2.invoke(UnlockDownloadsPatch.kt:54)
	at app.revanced.patches.twitter.interaction.downloads.UnlockDownloadsPatch$execute$2.invoke(UnlockDownloadsPatch.kt:52)
	at app.revanced.patches.twitter.interaction.downloads.UnlockDownloadsPatch.execute$patch(UnlockDownloadsPatch.kt:38)
	at app.revanced.patches.twitter.interaction.downloads.UnlockDownloadsPatch.execute(UnlockDownloadsPatch.kt:52)
	at app.revanced.patches.twitter.interaction.downloads.UnlockDownloadsPatch.execute(UnlockDownloadsPatch.kt:23)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	... 18 more
Compiling patched dex files
Compiled 12 dex files
Aligning APK
Signing APK
Patched APK
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by shifoc** [comment]
It worked thanks

**Comment by oSumAtrIX** [comment]
It is likely the user tried to patch the patched app
