### ISSUE TITLE
bug: compiling TikTok patches failed.

### ISSUE THREAD

**Issue by not-programmer98** [ReVanced/revanced-patches#3166]
### Bug description

I tried this several times with different versions and different set of patches. it fails everytime with same error

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: M2102J20SG
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.ss.android.ugc.trill v34.5.6 (Suggested: 32.5.3)
Patches version: v4.7.0
Patches added: Default
Patches removed: Feed filter, Remember clear display, Downloads, Playback speed, Settings
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 23 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 24 byte allocation with 1393856 free bytes and 1361KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.android.tools.smali.dexlib2.dexbacked.instruction.DexBackedInstruction.buildInstruction(Unknown Source:237)
	at com.android.tools.smali.dexlib2.dexbacked.instruction.DexBackedInstruction.readFrom(Unknown Source:43)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.DexBackedMethodImplementation$1$1.readNextItem(SourceFile:0)
	at com.android.tools.smali.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.computeNext(Unknown Source:2)
	at com.android.tools.smali.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.tryToComputeNext(Unknown Source:3)
	at com.android.tools.smali.dexlib2.dexbacked.util.VariableSizeLookaheadIterator.hasNext(Unknown Source:8)
	at com.android.tools.smali.util.IteratorUtils.getLast(Unknown Source:4)
	at com.android.tools.smali.dexlib2.dexbacked.util.DebugInfo$DebugInfoImpl.iterator(Unknown Source:38)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugItem(Unknown Source:57)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(Unknown Source:198)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:80)
	at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by not-programmer98** [comment]
It is a dupe of ReVanced/revanced-patcher#193
