### ISSUE TITLE
bug: TikTok patches throw Out Of Memory Error

### ISSUE THREAD

**Issue by fuji97** [ReVanced/revanced-patches#3172]
### Bug description

When patching the suggested version of TikTok with Revanced Manager, it throws `java.lang.OutOfMemoryError`. 
I don't know if this is a patches issue or a manager issue because, even if it is an OutOfMemoryError, it only happens when patching TikTok.

I also tested an older version (29.9.4) and it patches correctly, although I can't patch settings and download because they are not compatible.

### Error logs

```shell
~ Device Info
ReVanced Manager: 1.13.1
Build: release
Model: Pixel 6 Pro
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi

~ Patch Info
App: com.zhiliaoapp.musically v30.8.4
Patches version: v2.195.0
Patches: Disable login requirement, Downloads, Feed filter, Fix Google login, Hide ads, Playback speed, Settings, Show seekbar

~ Settings
Allow changing patch selection: true
Show universal patches: false
Version compatibility check: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

~ Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Disable login requirement succeeded
Downloads succeeded
Feed filter succeeded
Fix Google login succeeded
Hide ads succeeded
Playback speed succeeded
Settings succeeded
Show seekbar succeeded
Compiling patched dex files
Compiled classes.dex
Compiled classes2.dex
Compiled classes3.dex
Compiled classes4.dex
Compiled classes5.dex
Compiled classes6.dex
Compiled classes7.dex
Compiled classes8.dex
Compiled classes9.dex
Compiled classes10.dex
Compiled classes11.dex
Compiled classes12.dex
Compiled classes13.dex
Compiled classes14.dex
Compiled classes15.dex
Compiled classes16.dex
Compiled classes17.dex
Compiled classes18.dex
Compiled classes19.dex
Compiled classes20.dex
Compiled classes21.dex
Compiled classes22.dex
Compiled classes23.dex
Compiled classes24.dex
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 2143952 free bytes and 2093KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
 at com.android.tools.smali.dexlib2.dexbacked.DexBuffer.readerAt(DexBuffer.java:144)
 at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:334)
 at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$5.get(DexBackedDexFile.java:329)
 at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:372)
 at com.android.tools.smali.dexlib2.dexbacked.DexBackedDexFile$6.get(DexBackedDexFile.java:367)
 at com.android.tools.smali.dexlib2.dexbacked.reference.DexBackedFieldReference.getDefiningClass(DexBackedFieldReference.java:51)
 at com.android.tools.smali.dexlib2.base.reference.BaseFieldReference.equals(BaseFieldReference.java:51)
 at java.util.HashMap.getNode(HashMap.java:571)
 at java.util.LinkedHashMap.get(LinkedHashMap.java:464)
 at com.android.tools.smali.dexlib2.writer.pool.BaseIndexPool.getItemIndex(BaseIndexPool.java:52)
 at com.android.tools.smali.dexlib2.writer.InstructionWriter.getReferenceIndex(InstructionWriter.java:594)
 at com.android.tools.smali.dexlib2.writer.InstructionWriter.getReferenceIndex(InstructionWriter.java:582)
 at com.android.tools.smali.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:285)
 at com.android.tools.smali.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1319)
 at com.android.tools.smali.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:1115)
 at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:415)
 at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(DexWriter.java:370)
 at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(DexIO.java:162)
 at lanchon.multidexlib2.DexIO.access$000(DexIO.java:37)
 at lanchon.multidexlib2.DexIO$1.call(DexIO.java:102)
 at lanchon.multidexlib2.DexIO$1.call(DexIO.java:99)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)
```

### Additional context

[revanced-manager_logcat_20231020121950090485.log](https://github.com/ReVanced/revanced-patches/files/13053249/revanced-manager_logcat_20231020121950090485.log)

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Dupe

**Comment by oli-laban** [comment]
@oSumAtrIX Closed as dupe yet on older issues you say they're outdated and to create a new one. There is also no solution for this anywhere, yet clearly there is a problem as lots of people are experiencing the same issue...

**Comment by oSumAtrIX** [comment]
It is a dupe of https://github.com/ReVanced/revanced-patcher/issues/193
