### ISSUE TITLE
bug: Revanced crashes on launch using WSA

### ISSUE THREAD

**Issue by mrmouss** [ReVanced/revanced-patches#3178]
### Bug description

Revanced does not launch on WSA on Windows 11 and immediately crashes at launch. Not sure if this is a priority for the team but I think some people might want to use Revanced on their desktops given the recent AD popup from Google. It used to work before but I don't remember at what point it stopped working.

### Error logs

```shell
10-21 17:03:21.246  3588  3721 E AndroidRuntime: FATAL EXCEPTION: firebase-installations-executor-2
10-21 17:03:21.246  3588  3721 E AndroidRuntime: Process: app.revanced.android.youtube, PID: 3588
10-21 17:03:21.246  3588  3721 E AndroidRuntime: java.lang.RuntimeException: Unable to find a default SSL provider.
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.google.android.libraries.stitch.sslguard.SslGuardSocketFactory.a(PG:8)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.google.android.libraries.stitch.sslguard.SslGuardSocketFactory.createSocket(PG:6)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:185)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at akny.g(PG:1)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at akny.b(PG:17)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at aknj.run(PG:19)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
10-21 17:03:21.246  3588  3721 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is not a ReVanced issue, you can reproduce this with YouTube.

**Comment by mrmouss** [comment]
Indeed, even the non modified apk crashes so it's not a Revanced issue.
I opened the issue based on a Reddit discussion I had with a member and he confirmed that the non modified apk works fine, which is not the case. Let's hope it gets fixed upstream, thanks.

**Comment by YT-Advanced** [comment]
I checked with my WSA and it worked flawlessly. What WSA version are u using and where u download it

**Comment by mrmouss** [comment]
> I checked with my WSA and it worked flawlessly. What WSA version are u using and where u download it

I used the latest 64bits build from with Magisk support https://github.com/MustardChef/WSABuilds

**Comment by YT-Advanced** [comment]
Can you check this build:
https://github.com/YT-Advanced/WSA-Script

**Comment by mrmouss** [comment]
> Can you check this build: https://github.com/YT-Advanced/WSA-Script

Hi, thanks for your reply. I tried with the version you specified and it still crashes. Weird.

**Comment by Chibi-Usa** [comment]
did you install the apk from building it on another device or did you build it within the wsa container?

**Comment by Chibi-Usa** [comment]
and i decided to check the most recent youtube build 18.46.1 and that works fine, so something got fixed, id try an older build of yt to patch.
