### ISSUE TITLE
bug(YouTube - Theme): Patch fails to compile resources

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patches#3190]
### Bug description

Patch using latest dev release.

Patcher gives a generic resource compilation error.

Exclude `Theme` and patching works.

### Error logs

```shell
INFO: Compiling modified resources 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/fl/y1nm82nj2n96vtck6yqhndb00000gn/T/brut_util_Jar_154522920395485656796600586205553016911.tmp, compile, --dir, /temp/revanced-resource-cache./res, --legacy, -o, /temp/revanced-resource-cache./build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
	at app.revanced.patcher.Patcher.get(Patcher.kt:262)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:234)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I have accidentally prefixed the resource string value with a #. This is what causes patches to fail to compile. Implementing logging for AAPT invoking as once proposed will help to determine issues like this in the future
