### ISSUE TITLE
bug: Failed to pacth YT Music and Youtube Apps using ReVanced Manager

### ISSUE THREAD

**Issue by hzm25** [ReVanced/revanced-patches#3202]
### Bug description

At first, i try to patch YT Music version 7.01.52 but there is an error. 
The error is about : GMS Core Support, Hide 'Get Music Premium' label, and Remove upgrade button.
Then there is someone suggest to clear the manager, i do so and even clear cache, temporary file, and logs even clean all data in the manager, but weirdly the error change. 

Second, after doing the suggested, i try repatching again YT Music v7.01.52 but result in different error, and i even try it using the previous version v.6.51.53. which, i already copy the logs in the additional information here in the issue i made. I add the previous error log in the 'Additional context' form

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: Redmi Note 8 Pro
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.youtube.music v7.01.52 (Suggested: Any)
Patches version: v4.8.0
Patches added: Hide category bar
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 2 patches
An error occurred:
java.lang.NoSuchMethodError: No static method decode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String; in class Ljava/net/URLDecoder; or its super classes (declaration of 'java.net.URLDecoder' appears in /apex/com.android.art/javalib/core-oj.jar)
 at app.revanced.patches.shared.misc.integrations.BaseIntegrationsPatch.getCurrentJarFilePath(BaseIntegrationsPatch.kt:80)
 at app.revanced.patches.shared.misc.integrations.BaseIntegrationsPatch.getPatchesManifestEntry(BaseIntegrationsPatch.kt:64)
 at app.revanced.patches.shared.misc.integrations.BaseIntegrationsPatch.execute(BaseIntegrationsPatch.kt:47)
 at app.revanced.patches.shared.misc.integrations.BaseIntegrationsPatch.execute(BaseIntegrationsPatch.kt:20)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:91)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
 at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
 at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
 at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
 at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
 at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
 at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
 at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
 at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
 at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
 at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
 at java.lang.Thread.run(Thread.java:923)
```

### Additional context

- Device Info
ReVanced Manager: 1.20.1
Model: Redmi Note 8 Pro
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.youtube.music v7.01.52 (Suggested: Any)
Patches version: v4.8.0
Patches added: Hide category bar
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 6 patches
GmsCore support failed: app.revanced.patcher.patch.PatchException: 'GmsCore support' depends on 'IntegrationsPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Could not find hook target fingerprint.
 at app.revanced.patches.shared.misc.integrations.BaseIntegrationsPatch$IntegrationsFingerprint.invoke(BaseIntegrationsPatch.kt:140)
 at app.revanced.patches.shared.misc.integrations.BaseIntegrationsPatch.execute(BaseIntegrationsPatch.kt:39)
 at app.revanced.patches.shared.misc.integrations.BaseIntegrationsPatch.execute(BaseIntegrationsPatch.kt:17)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:91)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
 at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
 at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
 at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
 at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
 at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
 at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
 at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
 at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
 at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
 at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
 at java.lang.Thread.run(Thread.java:923)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:148)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
 at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
 at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
 at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
 at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
 at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
 at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
 at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
 at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
 at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
 at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
 at java.lang.Thread.run(Thread.java:923)
Hide 'Get Music Premium' label failed: app.revanced.patcher.patch.PatchException: Failed to resolve HideGetPremiumFingerprint
 at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:26)
 at app.revanced.patches.music.layout.premium.HideGetPremiumPatch.execute(HideGetPremiumPatch.kt:48)
 at app.revanced.patches.music.layout.premium.HideGetPremiumPatch.execute(HideGetPremiumPatch.kt:16)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
 at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
 at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
 at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
 at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
 at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
 at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
 at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
 at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
 at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
 at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
 at java.lang.Thread.run(Thread.java:923)
Remove upgrade button failed: app.revanced.patcher.patch.PatchException: Failed to resolve PivotBarConstructorFingerprint
 at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:26)
 at app.revanced.patches.music.layout.upgradebutton.RemoveUpgradeButtonPatch.execute(RemoveUpgradeButtonPatch.kt:82)
 at app.revanced.patches.music.layout.upgradebutton.RemoveUpgradeButtonPatch.execute(RemoveUpgradeButtonPatch.kt:22)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
 at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
 at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
 at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
 at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
 at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
 at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
 at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
 at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
 at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
 at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
 at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
 at java.lang.Thread.run(Thread.java:923)
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Aligning APK
Signing APK
Patched APK

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The issue was fixed with v4.8.1
