### ISSUE TITLE
bug: MyFitnessPal failed to hide ads

### ISSUE THREAD

**Issue by eiqnepm** [ReVanced/revanced-patches#3233]
### Bug description

MyFitnessPal failed to hide ads

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: Pixel 7 Pro
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.myfitnesspal.android v24.18.0 (Suggested: Any)
Patches version: v4.8.2
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Executing patches
Hide ads failed: app.revanced.patcher.patch.PatchException: Failed to resolve IsPremiumUseCaseImplFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:26)
	at app.revanced.patches.myfitnesspal.ads.HideAdsPatch.execute(HideAdsPatch.kt:29)
	at app.revanced.patches.myfitnesspal.ads.HideAdsPatch.execute(HideAdsPatch.kt:12)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 14 dex files
Aligning APK
Signing APK
Patched APK
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by eiqnepm** [comment]
Hopefully the patch gets updated at some point as MyFitnessPal has had a few bug fixes in the meantime, but until then I've created a pull request for the latest version I could get working using universal packages from APKMirror.
