### ISSUE TITLE
bug: Unlock pro patch failed [Nyx Music Player V2.2.8]

### ISSUE THREAD

**Issue by hassan1395** [ReVanced/revanced-patches#3233]
### Bug description

- Error while patching

Hide Unlock pro patch failed while patching Nyx Music Player V2.2.8

### Error logs

```shell
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: Export all activities excluded 
INFO: Change package name excluded 
INFO: Enable Android debugging excluded 
INFO: Override certificate pinning excluded 
INFO: Remove screenshot restriction excluded 
INFO: Predictive back gesture excluded 
INFO: Spoof Wi-Fi connection excluded 
INFO: Remove screen capture restriction excluded 
INFO: Setting patch options 
INFO: Executing patches 
SEVERE: Unlock pro failed:
app.revanced.patcher.patch.PatchException: Failed to resolve CheckProFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:21)
	at app.revanced.patches.nyx.misc.pro.UnlockProPatch.execute(UnlockProPatch.kt:23)
	at app.revanced.patches.nyx.misc.pro.UnlockProPatch.execute(UnlockProPatch.kt:11)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:237)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:236)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
 
INFO: Compiling patched dex files 
INFO: Compiled classes.dex 
INFO: Compiled classes2.dex 
INFO: Compiled classes3.dex 
INFO: Compiled classes4.dex 
INFO: Compiled classes5.dex 
INFO: Aligning base.apk 
INFO: Signing base.apk 
INFO: Purging temporary files 
INFO: Purged resource cache directory 



Rooted: false
Arch: arm64-v8a
App: Nyx-Music-Player v2.2.8
CLI: revanced-cli-v4.1.0.jar
Patches: revanced-patches-v2.196.0.jar
Integrations: revanced-integrations-v0.121.0.apk
Patches argument: -i Unlock pro
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The patch will be staged for removal according to the contribution guidelines

**Comment by oSumAtrIX** [comment]
The patch prior to that date is unaffected and will persist in the commit history, but any future changes are

**Comment by cyberboh** [comment]
> The patch prior to that date is unaffected and will persist in the commit history, but any future changes are

Oh, understood. Better constrain it to last working version and don't update the pro patch. For new version, better add some announcements (like on YT) about the patch.

**Comment by oSumAtrIX** [comment]
What is the version that has last worked?
