### ISSUE TITLE
feat: ReVanced MicroG for NonRoot

### ISSUE THREAD

**Issue by shadow578** [revanced/revanced-patches#325]
### Type

Other

### Issue

currently, revanced uses the microG fork from old vanced for nonroot installs.
That fork is (imho) a mess and will probably not get updates anymore (also because it's a mess).

### Feature

basically a fork of microG for use with revanced, kinda like old vanced did it.
This would also have the advantage of not using old vanced's wonky fork

### Motivation

- get updates from upstream microG
- package name of revanced microG could be changed to something less stupid (currently it's `com.mgoogle.android.gms`, could be changed to `app.revanced.android.gms`)
- replace wonky vanced codebase with something less bad

### Additional context

as common with my issues, i've already done my homework and laid the groundwork for this. see https://github.com/shadow578/GmsCore.

**Comment by OxrxL** [comment]
> That fork is (imho) a mess and will probably not get updates anymore (also because it's a mess).

It's just a debloated version of original microg, with specific login patch for Huawei devices.

Not really a mess, at least not as microg is in its original form (with the huge amount of useless s**t, compared to which ReVanced needs).

**Comment by shadow578** [comment]
> Not really a mess, at least not as microg is in its original form (with the huge amount of useless s**t, compared to which ReVanced needs).

the 'its a mess' part was actually more referring to the way some things were implemented and the commit quality, and not about the final 'product'.

That being said, i think it could be advantageous to __not__ slim down microG quite as much as Vanced did with their fork. 
While it is true that YT ReVanced does not require much more than `GAuth`, `GCM` (and maybe `Phenotype`...), other apps may be different. 

The ReVanced patcher is a tool that can be used for all sorts of mods, so might as well provide a full GMS implementation and make it easier.

**Comment by OxrxL** [comment]
> the 'its a mess' part was actually more referring to the way some things were implemented and the commit quality, and not about the final 'product'.

Unfortunately microg project never followed qualitative rules for merging new code, and this situation affects the amount of bug reports (which increase continuously).

> so might as well provide a full GMS implementation and make it easier.

This should be discussed, because having an almost exact copy of the play services (with all those services and poor code quality) could result in unsustainable battery consumption.

**Comment by anil-al** [comment]
> > the 'its a mess' part was actually more referring to the way some things were implemented and the commit quality, and not about the final 'product'.
> Unfortunately microg project never followed qualitative rules for merging new code, and this situation affects the amount of bug reports (which increase continuously).

This is definitely true. I have been suffering from stopping of the app out of the blue for no reason in the background in all three devices of me and there is no uptade for months, so these clearly shows how much it is mistreated.

**Comment by pascua28** [comment]
Yeah. Commits look really messy that's why I forked microG here: https://github.com/pascua28/VancedGmsCore

**Comment by AkechiShiro** [comment]
I've been hitting very recently an issue, my Google Account cannot be logged into, I've tried 3 differents YouTube versions 17.29.34, 17.36.37 and experimentally 17.38.35.

At first, YouTube Revanced 17.36.37 with almost all patches but RYD and SponsorBlock was working fine, until yesterday's morning, I launched the app to listen to music and hit a connection issue, I was pretty sure my connection was working.

I thus later, reinstalled a patched Revanced using the Revanced Manager, and saw that the connection issue was gone, but actually was still present when I tried to log in to my Google Account, and thus indicating an issue with Vanced MicroG, or so I believe.

All, the mentioned versions (above) show the latest video feed, with the latest videos from YouTube, however, when I click on getting connected in order to add a video in a playlist or like a video, a popup shows my Google Account and says "connection failed, please check your connection".

Installing YouTube 17.36.37 with no patches whatsoever, allows me to login successfully to my Google Account, but this must be using Google Services and not Vanced MicroG.

Are there any steps to debug Vanced MicroG, in the meantime that a Revanced MicroG gets more mature ??

**Comment by oSumAtrIX** [comment]
@AkechiShiro you said, including patches causes issues on your end, which patches?

**Comment by AkechiShiro** [comment]
I did not pinpoint any specific patches that causes my Google account to not be loggable into, but I will narrow down to one or 2 patches and see if that changes anything @oSumAtrIX 

Trying just now with only one patch the microg-support failed, weird...
```
SEVERE: microg-support failed: 
app.revanced.patcher.patch.PatchResultError: 'microg-support' depends on 'microg-support' but the following error was raised: 'microg-resource-patch' depends on 'microg-resource-patch' but the following error was raised: java.io.FileNotFoundException: revanced-cache/AndroidManifest.xml (No such file or directory)
	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:259)
	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:46)
	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:383)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

I'm updating to the latest sources upstream : 
```
Aur (3)                    Old Version  New Version  Make Only
aur/revanced-patches       2.69.4-1     2.71.2-1     No
aur/revanced-cli           1:2.12.0-1   1:2.12.0-1   No
aur/revanced-integrations  0.43.1-1     0.44.0-1     No
```
And giving it a try, the error is still there, only the microg-support patch fails, putting all my usual patches works tho.

All patches but :
```
--exclude=sponsorblock --exclude=return-youtube-dislike --exclude=client-spoof
```

**Comment by AkechiShiro** [comment]
@oSumAtrIX could you link the issue ? Which patch is needed so I could do some testing with minimal patches ? (If you have any idea ? Or should I just bruteforce it ?)

**Comment by AkechiShiro** [comment]
@oSumAtrIX the issue has been fixed, but my connection issue with MicroG hasn't been fixes yet, I'm using YouTube Revanced 17.36.37 with only the microg-support patch.

And I cannot connect to my Google account.

This narrows down the issue to either a bug in the microg patch or either a bug in Vanced MicroG

I will try to reinstall MicroG Vanced and see if that solves the issue or not.

**Comment by AkechiShiro** [comment]
A quick update. My issue is solved however I installed a beta Revanced MicroG (0.2.25.223212) instead of v0.2.24.220220

So 2 possibilities are left, either the beta fixes a bug or either reinstalling and logging back in, fixed my weird one time bug.

**Comment by anil-al** [comment]
> A quick update. My issue is solved however I installed a beta Revanced MicroG (0.2.25.223212) instead of v0.2.24.220220
> 
> So 2 possibilities are left, either the beta fixes a bug or either reinstalling and logging back in, fixed my weird one time bug.

From where have you downloaded a beta version of it?

**Comment by oSumAtrIX** [comment]
There is no ReVanced MicroG.

**Comment by AkechiShiro** [comment]
@anil-al from here https://github.com/cuynu/ytvanced, more precisely https://github.com/cuynu/ytvanced/releases/download/17.03.38/Vanced.microG_0.2.25.223212.apk

Release here : https://github.com/cuynu/ytvanced/releases

You're right @oSumAtrIX I wanted to say Vanced MicroG

**Comment by Hak-Init** [comment]
Can't reactivate chrome login after uninstalling revanced microg

Any guidance please
