### ISSUE TITLE
bug: Spoof client patch fails (Infinity for reddit) 

### ISSUE THREAD

**Issue by Shazzkid** [ReVanced/revanced-patches#3254]
### Bug description

Reddit has made some changes affecting 3rd party apps client authorisation so all old versions now fail to load content. The Infinity dev has released a working version for paid users, but this version wont successfully execute the spoof client patch.

Ive tested old versions of the app (v6.0.4 to 7.2.1), they patch successfully, but are broken because of reddits changes. So the only working version is the latest version (v7.2.3), but it fails to patch. Confirmed by other users in the Infinity for reddit sub, who all confirm the new version always fails to expected the spoof client patch. 

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: SM-F926B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: ml.docilealligator.infinityforreddit v7.2.3 (Suggested: Any)
Patches version: v4.8.2
Patches added: Default
Patches removed: None
Default patch options changed: Spoof client [OAuth client ID: [redacted] 

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Executing patches
Spoof client failed: app.revanced.patcher.patch.PatchException: Failed to resolve APIUtilsFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:26)
	at app.revanced.patches.reddit.customclients.BaseSpoofClientPatch.execute$executePatch(BaseSpoofClientPatch.kt:44)
	at app.revanced.patches.reddit.customclients.BaseSpoofClientPatch.execute(BaseSpoofClientPatch.kt:46)
	at app.revanced.patches.reddit.customclients.BaseSpoofClientPatch.execute(BaseSpoofClientPatch.kt:11)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Unlock subscription failed: app.revanced.patcher.patch.PatchException: 'Unlock subscription' depends on 'Spoof client' that raised an exception:
app.revanced.patcher.patch.PatchException: 'Spoof client' did not succeed previously
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:45)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:91)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)

	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:148)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 4 dex files
Aligning APK
Signing APK
Patched APK
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by JVT038** [comment]
Same here

**Comment by ddulz** [comment]
[this version works for me](https://www.apkmirror.com/apk/docile-alligator/infinity-for-reddit/infinity-for-reddit-7-2-3-release/infinity-for-reddit-7-2-3-2-android-apk-download/)

Probably because revanced always asks for nodpi version, but I am not sure.

**Comment by Shazzkid** [comment]
> [this version works for me](https://www.apkmirror.com/apk/docile-alligator/infinity-for-reddit/infinity-for-reddit-7-2-3-release/infinity-for-reddit-7-2-3-2-android-apk-download/)
> 
> Probably because revanced always asks for nodpi version, but I am not sure.

Can confirm that version works fine. Thanks!

**Comment by oSumAtrIX** [comment]
Closing unless this is an actual issue.

**Comment by EliasGagnef** [comment]
The latest GitHub version of Infinity is giving me this error, shouldn't both versions work? the GitHub version has alwaysworked for me before this latest update

**Comment by oSumAtrIX** [comment]
I don't know what you mean. Are they versioned the same?

**Comment by Shazzkid** [comment]
> I don't know what you mean. Are they versioned the same?

I thought they were, but the version on apkmirror linked [in this earlier reply](https://github.com/ReVanced/revanced-patches/issues/3254#issuecomment-2140956555) is slightly bigger and patches just fine. But the official github release doesn't patch. There is a difference between the 2 versions hence the difference in file size and whether or not it successfully patches.

**Comment by oSumAtrIX** [comment]
If the signature of the app matches, the linked one is official. I think it is a built for a Google Play Store release.

**Comment by Shazzkid** [comment]
> If the signature of the app matches, the linked one is official. I think it is a built for a Google Play Store release.

They are likely both official, but still different enough that 1 patches successfully and the other doesn't. The weird thing is that it's the github release that doesn't patch, but the apkmirror release does. All we know for sure is the github release is definitely official and it doesn't seem to patch successfully for anyone.

**Comment by oSumAtrIX** [comment]
That's because the fingerprint is made for a method that only exists on the Google Play Store release. Use that release.

**Comment by ddulz** [comment]
> > If the signature of the app matches, the linked one is official. I think it is a built for a Google Play Store release.
> 
> They are likely both official, but still different enough that 1 patches successfully and the other doesn't. The weird thing is that it's the github release that doesn't patch, but the apkmirror release does. All we know for sure is the github release is definitely official and it doesn't seem to patch successfully for anyone.

You have to ask infinity dev then, some version before this release was 11.4 MB, now suddenly it have 10.9. probably dev change some dependency that doesn't bode well with revanced in github release only.

**Comment by BabyOilJohnson** [comment]
The [latest ver](https://github.com/Docile-Alligator/Infinity-For-Reddit/releases) from GitHub worked.
