### ISSUE TITLE
bug: (Reddit) Failed to patch

### ISSUE THREAD

**Issue by Rairof** [ReVanced/revanced-patches#3273]
### Bug description

Upon patching Reddit v2024.17.0 it failed to patch at compiling resources point saying I'm out of memory even though I have a 12gb ram phone and nothing was running in the background.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: 2107113SG
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.reddit.frontpage v2024.17.0 (Suggested: 2024.17.0)
Patches version: v4.8.3
Patches added: Predictive back gesture, Remove screen capture restriction, Remove screenshot restriction, Spoof Wi-Fi connection
Patches removed: Enable Android debugging, Override certificate pinning, Export all activities, Spoof SIM country
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 8 patches
Compiling patched dex files
Compiled 12 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 8 free bytes and 8B until OOM, target footprint 536870912, growth limit 536870912
	at java.util.AbstractList.listIterator(AbstractList.java:340)
	at com.google.common.collect.Lists$TransformingRandomAccessList.listIterator(Unknown Source:4)
	at java.util.AbstractList.listIterator(AbstractList.java:311)
	at java.util.AbstractList.equals(AbstractList.java:544)
	at com.android.tools.smali.util.CharSequenceUtils.listEquals(Unknown Source:10)
	at com.android.tools.smali.dexlib2.base.reference.BaseMethodProtoReference.equals(Unknown Source:29)
	at java.util.HashMap.getNode(HashMap.java:568)
	at java.util.LinkedHashMap.get(LinkedHashMap.java:465)
	at com.android.tools.smali.dexlib2.writer.pool.BaseIndexPool.getItemIndex(Unknown Source:2)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeMethods(Unknown Source:80)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at com.android.tools.smali.dexlib2.writer.DexWriter.writeTo(SourceFile:0)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:80)
	at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

### Solution

Not sure how to solve this.

### Additional context

I'm using Xiaomi 11T Pro with A14 custom rom, Lineage OS 21

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
#190

**Comment by Rairof** [comment]
https://github.com/ReVanced/revanced-patches/issues/3273#issuecomment-2143516764
Got it. I didn't found that issue when searching for duplicate issues similar to me as I was patching Reddit and they patched tiktok, pretty hard to look through all 100+ posts manually to search for the same issue I got.
