### ISSUE TITLE
bug: Failed patch for Messenger

### ISSUE THREAD

**Issue by Marekk2k** [ReVanced/revanced-patches#3277]
### Bug description

What exact version do you recommend for patching Messenger? I just made 3 patches in Manager and I have these errors... 

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: SM-A546B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.facebook.orca v460.0.0.48.109 (Suggested: Any)
Patches version: v4.8.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Executing patches
Disable switching emoji to sticker failed: app.revanced.patcher.patch.PatchException: Failed to resolve SwitchMessangeInputEmojiButtonFingerprint
	at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:26)
	at app.revanced.patches.messenger.inputfield.patch.DisableSwitchingEmojiToStickerPatch.execute(DisableSwitchingEmojiToStickerPatch.kt:34)
	at app.revanced.patches.messenger.inputfield.patch.DisableSwitchingEmojiToStickerPatch.execute(DisableSwitchingEmojiToStickerPatch.kt:13)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:292)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Applied 2 patches
Compiling patched dex files
Compiled 10 dex files
Aligning APK
Signing APK
Patched APK
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by Marekk2k** [comment]
The manager supposedly shows the suggested version for any...

**Comment by kazimmt** [comment]
#3090
