### ISSUE TITLE
Facebook Patch - Failing

### ISSUE THREAD

**Issue by nightznero** [ReVanced/revanced-patches#3290]
### Bug description

When Patch fail its always aborted but in Facebook case its failing patching but still "patch"
![Screenshot_20231118_121450_ReVanced Manager](https://github.com/ReVanced/revanced-patches/assets/61750641/d9737e99-9fad-44aa-b83f-072906a8738c)

### Solution

Abort or propely adding a patch

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by kennyfs** [comment]
log
Facebook: 441.0.0.32.109
revanced-patches: 2.197.0
revanced-integrations: 0.122.0
revanced-cli: 4.1.0
```
SEVERE: Hide story ads failed:
app.revanced.patcher.patch.PatchException: Failed to resolve FetchMoreAdsFingerprint
        at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:24)
        at app.revanced.patches.facebook.ads.story.HideStoryAdsPatch.execute(HideStoryAdsPatch.kt:24)
        at app.revanced.patches.facebook.ads.story.HideStoryAdsPatch.execute(HideStoryAdsPatch.kt:12)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:202)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:237)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:236)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)
```

**Comment by cyberboh** [comment]
The patches only works with [Facebook APK for Android 11+](https://www.apkmirror.com/apk/facebook-2/facebook/facebook-441-0-0-32-109-release/facebook-441-0-0-32-109-9-android-apk-download/). So choose it, but if your device running Android below Android 11, just waiting for the fix. Hopefully it will get fixes.
