### ISSUE TITLE
bug(YouTube - Spoof client): Crash when opening a video / livestream

### ISSUE THREAD

**Issue by 123jjck** [ReVanced/revanced-patches#3290]
### Bug description

App: YouTube v19.16.39
Patches: v4.9.0

Steps to reproduce:
1. Open app
2. Click on any video or livestream 
(Shorts works fine)

Used patches:
```
Always repeat
Bypass URL redirects
Comments
Copy video URL
Disable resuming Shorts on startup
Disable suggested video end screen
GmsCore support
Hide Shorts components
Hide ads
Hide autoplay button
Hide cast button
Hide floating microphone button
Hide layout components
Minimized playback
Navigation buttons
Open links externally
Remember video quality
Remove tracking query parameter
Remove viewer discretion dialog
Restore old video quality menu
Return YouTube Dislike
SponsorBlock
Spoof app version
Spoof client
Theme
Video ads
```

### Error logs

```shell
06-02 23:06:19.136 15374 15374 E AndroidRuntime: FATAL EXCEPTION: main
06-02 23:06:19.136 15374 15374 E AndroidRuntime: Process: app.revanced.android.youtube, PID: 15374
06-02 23:06:19.136 15374 15374 E AndroidRuntime: azqy: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.NoSuchMethodError: No static method enablePlayerGesture(Z)Z in class Lapp/revanced/integrations/youtube/patches/spoof/SpoofClientPatch; or its super classes (declaration of 'app.revanced.integrations.youtube.patches.spoof.SpoofClientPatch' appears in /data/app/~~8WScMOQETsGnp0tt_7Iy3A==/app.revanced.android.youtube-cn9ERlhsFtjKd53dfdlQIg==/base.apk!classes5.dex)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at azfw.k(PG:39)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at azqi.run(PG:8)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:958)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:230)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:319)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8919)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
06-02 23:06:19.136 15374 15374 E AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No static method enablePlayerGesture(Z)Z in class Lapp/revanced/integrations/youtube/patches/spoof/SpoofClientPatch; or its super classes (declaration of 'app.revanced.integrations.youtube.patches.spoof.SpoofClientPatch' appears in /data/app/~~8WScMOQETsGnp0tt_7Iy3A==/app.revanced.android.youtube-cn9ERlhsFtjKd53dfdlQIg==/base.apk!classes5.dex)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at com.google.android.libraries.youtube.innertube.model.media.PlayerConfigModel.aq(PG:10)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at mru.a(PG:63)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at baqw.vS(PG:9)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at azzi.f(PG:40)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at azzg.run(PG:18)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at azeh.run(PG:27)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        at azqi.run(PG:3)
06-02 23:06:19.136 15374 15374 E AndroidRuntime:        ... 8 more
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by 123jjck** [comment]
Thank you, it helped

**Comment by GatoXmeansXcat** [comment]
same happened after updating yt revanced.
Just disable spoof client on:
ReVanced>Misc>Spoof client

Also fixes stream playback not working.
