### ISSUE TITLE
bug: Error opening ReVanced

### ISSUE THREAD

**Issue by Pamilg8** [ReVanced/revanced-patches#3306]
### Bug description

1.By patching YouTube using standard patches.
2.Open ReVanced and crash, sometimes crash is delayed.

### Error logs

```shell
FATAL EXCEPTION: ComponentLayoutThread1-1
Process: app.revanced.android.youtube, PID: 18103
ezb: Real Cause => java.lang.NullPointerException: Attempt to invoke virtual method 'app.revanced.integrations.patches.components.FilterGroup$FilterGroupResult app.revanced.integrations.patches.components.ByteArrayFilterGroup.check(byte[])' on a null object reference
Litho Context:
  layout_stack: LazilyConvertedElement
  log_tag: LithoRVSLCBinder
  tree_root: <cls>rpt</cls>
  thread_name: ComponentLayoutThread1-1
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'app.revanced.integrations.patches.components.FilterGroup$FilterGroupResult app.revanced.integrations.patches.components.ByteArrayFilterGroup.check(byte[])' on a null object reference
	at app.revanced.integrations.patches.components.LayoutComponentsFilter.filterMixPlaylists(LayoutComponentsFilter.java:258)
	at qjt.b(PG:4)
	at qpe.b(PG:1)
	at agzg.a(PG:15)
	at rpt.aC(PG:8)
	at fan.aB(PG:2)
	at exh.h(PG:11)
	at exh.A(PG:4)
	at eww.call(PG:33)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at ewx.a(PG:2)
	at com.facebook.litho.ComponentTree.m(PG:15)
	at ewv.a(PG:1)
	at fau.run(PG:1)
	at akng.run(PG:2)
	at aivz.run(PG:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at dwx.run(PG:14)
	at java.lang.Thread.run(Thread.java:1012)
```

### Solution

I don't know

### Additional context

Samsung A21s,Android 12
The latest version of the ReVanced patches
Latest ReVanced Manager version.I didn't need a screenshot,video

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [ ] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Send the versions of all involved apps and tools

**Comment by Pamilg8** [comment]
Version: 1.15.1
Manager:Model: SM-A217F
Android Version: 12
Supported Archs: arm64-v8a, armeabi-v7a, armeabi

Patches:
![Screenshot_20231119-223937_ReVanced Manager](https://github.com/ReVanced/revanced-patches/assets/149590337/cbd5f714-39c3-4fc5-98f3-b88f5ea1600b)

**Comment by Pamilg8** [comment]
It didn't fix.

**Comment by oSumAtrIX** [comment]
Open a new issue with updated steps as well as a recording of the full patching process til the error occurrence

**Comment by Pamilg8** [comment]
Ok.

**Comment by Pamilg8** [comment]
"Patches" version v2.200.0 no longer repeats the error. It's a miracle to fix☺️
