### ISSUE TITLE
bug: Failed Patching YouTube v18.45.41

### ISSUE THREAD

**Issue by AanAhmad** [ReVanced/revanced-patches#3312]
### Bug description

I previously used YouTube with a previous patch version. Then I saw the latest patch update which recommended using the latest version of YouTube. I'm trying to choose the features I want to use. During the recompiling process an error log appears as below

### Error logs

```shell
- Device Info
ReVanced Manager: 1.15.1
Build: release
Model: RMX2185
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v18.45.41
Patches version: v2.198.0
Patches: Bypass URL redirects, Enable slide to seek, External downloads, Hide ads, Minimized playback, Open links externally, SponsorBlock, Video ads

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Bypass URL redirects succeeded
Enable slide to seek succeeded
External downloads succeeded
Hide ads succeeded
Minimized playback succeeded
Open links externally succeeded
SponsorBlock succeeded
Video ads succeeded
Compiling patched dex files
Compiled classes.dex
Compiled classes2.dex
Compiled classes3.dex
Compiled classes4.dex
Compiled classes5.dex
Compiled classes6.dex
Compiled classes7.dex
Compiled classes8.dex
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~khrBjIvUiQcyTz8eNkjctw==/app.revanced.manager.flutter-ssitPtfgPed2fRRt15E_Gw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KGELET/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1541148096, --version-name, 18.45.41, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL5039897231509160130.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KGELET/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KGELET/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KGELET/cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
	at app.revanced.patcher.Patcher.get(Patcher.kt:262)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(MainActivity.kt:332)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$DSnYi-AHJ8SA5fRWgNkdGCm5Zgw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda4.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:923)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~khrBjIvUiQcyTz8eNkjctw==/app.revanced.manager.flutter-ssitPtfgPed2fRRt15E_Gw==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KGELET/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1541148096, --version-name, 18.45.41, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL5039897231509160130.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KGELET/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KGELET/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KGELET/cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 7 more
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Try patching a full APK. This is not a patches issue and can't be solved.
