### ISSUE TITLE
bug: Error when disabling microG support

### ISSUE THREAD

**Issue by IEduStu** [ReVanced/revanced-patches#3339]
### Bug description

Fails to compile when disabling the microG patch

### Error logs

```shell
- Device Info
ReVanced Manager: 1.17.0
Build: release
Model: DN2103
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v18.45.41
Patches version: v2.201.1
Patches added: Alternative thumbnails, Bypass URL redirects, Client spoof, Copy video url, Custom player overlay opacity, Disable player popup panels, Disable precise seeking gesture, Disable resuming Shorts on startup, Enable slide to seek, HDR auto brightness, Hide ads, Hide autoplay button, Hide breaking news shelf, Hide crowdfunding box, Hide email address, Minimized playback, Navigation buttons, Open links externally, Playback speed, Player flyout menu, Remember video quality, Restore old seekbar thumbnails, Restore old video quality menu, Return YouTube Dislike, Seekbar tapping, SponsorBlock, Spoof device dimensions, Swipe controls, Video ads, Wide searchbar
Patches removed: Hide ads, Video ads, Copy video url, External downloads, Disable precise seeking gesture, Seekbar tapping, Enable slide to seek, Swipe controls, Disable auto captions, Premium heading [Use premium heading: true], Hide video action buttons, Hide autoplay button, Hide captions button, Hide cast button, Navigation buttons, Hide player buttons, Hide album cards, Hide breaking news shelf, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Hide 'Load more' button, Hide email address, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Disable resuming Shorts on startup, Enable tablet layout, Tablet mini player, Theme [Dark theme background color: @android:color/black, Light theme background color: @android:color/white], Alternative thumbnails, Announcements, Always autorepeat, Enable debugging, Spoof device dimensions, Client spoof, Bypass URL redirects, Vanced MicroG support, Minimized playback, Remove tracking query parameter, Disable zoom haptics, HDR auto brightness, Remember video quality, Playback speed, Restore old video quality menu, Open links externally
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 30 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~vFuiGRTinIcXSbSPtRUEtA==/app.revanced.manager.flutter-x59mrm5eUSVqakgUCgEd4g==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KRXGDV/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1541148096, --version-name, 18.45.41, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3271155083064054473.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KRXGDV/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KRXGDV/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KRXGDV/cache/build/resources.zip]
at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
 at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
 at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
 at app.revanced.patcher.Patcher.get(Patcher.kt:262)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:354)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~vFuiGRTinIcXSbSPtRUEtA==/app.revanced.manager.flutter-x59mrm5eUSVqakgUCgEd4g==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KRXGDV/cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1541148096, --version-name, 18.45.41, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL3271155083064054473.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KRXGDV/cache/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KRXGDV/cache/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-KRXGDV/cache/build/resources.zip]
 at brut.util.OS.exec(OS.java:104)
 at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
 ... 7 more
```

### Additional context

My device is rooted and I am using version 18.45.41 of youtube
And the latest version of revanced: 1.17.0
OS: android 13, evolution

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Compiling does not fail if you disable the patch. It is caused by a different reason. Likely patching a Split APK file
