### ISSUE TITLE
bug: youtube v19.16.39 patch error

### ISSUE THREAD

**Issue by Seshiria** [ReVanced/revanced-patches#3347]
### Bug description

install youtube v19.16.39,then patch

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: ONEPLUS A5000
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.9.0
Patches added: Default
Patches removed: Copy video URL, Downloads, Disable precise seeking gesture, Seekbar tapping, Swipe controls, Disable auto captions, Hide captions button, Comments, Disable fullscreen ambient mode, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, Spoof app version, Change start page, Enable tablet layout, Tablet mini player, Theme, Alternative thumbnails, Announcements, Always repeat, Enable debugging, Disable zoom haptics, GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 33 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~8i2NVjfy8d6jyPrFuBRJJg==/app.revanced.manager.flutter-PfTukrwID1SOSDcUmLa6oQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUVZZN/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6286517858062566418.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUVZZN/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUVZZN/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUVZZN/revanced-temporary-files/apk/build/resources.zip]
 at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
 at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
 at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
 at app.revanced.patcher.Patcher.get(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
 at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
 at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~8i2NVjfy8d6jyPrFuBRJJg==/app.revanced.manager.flutter-PfTukrwID1SOSDcUmLa6oQ==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUVZZN/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 26, --target-sdk-version, 34, --version-code, 1545731520, --version-name, 19.16.39, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL6286517858062566418.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUVZZN/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUVZZN/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-QUVZZN/revanced-temporary-files/apk/build/resources.zip]
 at brut.util.OS.exec(Unknown Source:75)
 at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
 ... 7 more
```

### Additional context

patch:
•  Bypass URL redirects
•  Disable player popup panels
•  Disable resuming Shorts on startup
•  Disable rolling number animations
•  Disable suggested video end screen
•  Hide Shorts components
•  Hide ads
•  Hide album cards
•  Hide autoplay button
•  Hide cast button
•  Hide crowdfunding box
•  Hide endscreen cards
•  Hide filter bar
•  Hide floating microphone button
•  Hide info cards
•  Hide layout components
•  Hide player buttons
•  Hide seekbar
•  Hide timestamp
•  Hide video action buttons
•  Minimized playback
•  Navigation buttons
•  Open links externally
•  Playback speed
•  Player flyout menu
•  Remember video quality
•  Remove tracking query parameter
•  Remove viewer discretion dialog
•  Restore old video quality menu
•  SponsorBlock
•  Spoof client
•  Spoof device dimensions
•  Video ads

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Patch a full APK and use the recommended settings
