### ISSUE TITLE
bug: photomath not works in 8.33

### ISSUE THREAD

**Issue by speedlorenzo12** [ReVanced/revanced-patches#3371]
### Bug description

I literally can't open the app

### Error logs

```shell
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: 2112123AG
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No
- Patch Info
App: com.microblink.photomath v8.33.0
Patches version: v2.202.0
Patches added: Spoof device ID, Unlock plus
Patches removed: Spoof device ID, Unlock plus
Options changed: None
- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations
- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Executing patches
Spoof device ID failed: app.revanced.patcher.patch.PatchException: 'Spoof device ID' depends on 'SignatureDetectionPatch' that raised an exception:
app.revanced.patcher.patch.PatchException: Failed to resolve CheckSignatureFingerprint
	at app.revanced.extensions.ExtensionsKt.getException(Extensions.kt:24)
	at app.revanced.patches.photomath.detection.signature.SignatureDetectionPatch.execute(SignatureDetectionPatch.kt:22)
	at app.revanced.patches.photomath.detection.signature.SignatureDetectionPatch.execute(SignatureDetectionPatch.kt:12)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:156)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processN
```

### Solution

recrate the compatibility for the latest version

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Which version is the last that works?

**Comment by speedlorenzo12** [comment]
8.32 works but 8.33 no
