### ISSUE TITLE
bug: GmsCore support failed

### ISSUE THREAD

**Issue by juniosxs** [ReVanced/revanced-patches#3374]
### Bug description

GmsCore support failed

### Error logs

```shell
INFO: Exclusive audio playback succeeded
SEVERE: GmsCore support failed:
app.revanced.patcher.patch.PatchException: Index -1 out of bounds for length 157
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:185)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 157
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at com.android.tools.smali.dexlib2.builder.MutableMethodImplementation.replaceInstruction(MutableMethodImplementation.java:336)
        at app.revanced.patcher.extensions.InstructionExtensions.replaceInstruction(InstructionExtensions.kt:289)
        at app.revanced.patches.shared.misc.gms.AbstractGmsCoreSupportPatch.transformPrimeMethod(AbstractGmsCoreSupportPatch.kt:184)
        at app.revanced.patches.shared.misc.gms.AbstractGmsCoreSupportPatch.execute(AbstractGmsCoreSupportPatch.kt:80)
        at app.revanced.patches.shared.misc.gms.AbstractGmsCoreSupportPatch.execute(AbstractGmsCoreSupportPatch.kt:37)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        ... 24 more
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
More info needed

**Comment by juniosxs** [comment]
This error happens to me using revanced-patches v3.0.0-dev.5 and revanced-integrations v1.0.0-dev.5 with revanced-cli

**Comment by juniosxs** [comment]
Building YT Music ReVanced
INFO: Loading patches
INFO: Decoding app manifest
INFO: Export all activities excluded
INFO: Remove screen capture restriction excluded
INFO: Spoof SIM country excluded
INFO: Change package name excluded
INFO: Enable Android debugging excluded
INFO: Override certificate pinning excluded
INFO: Spoof Wi-Fi connection excluded
INFO: Remove screenshot restriction excluded
INFO: Predictive back gesture excluded
INFO: Permanent shuffle excluded
INFO: Permanent repeat excluded
INFO: Setting patch options
INFO: Merging integrations
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: Background play succeeded
INFO: Bypass certificate checks succeeded
INFO: Codecs unlock succeeded
INFO: Compact header succeeded
INFO: Exclusive audio playback succeeded
SEVERE: GmsCore support failed:
app.revanced.patcher.patch.PatchException: Index -1 out of bounds for length 157
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:185)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$apply$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
        at app.revanced.cli.command.PatchCommand$run$4$patcherResult$1$1.invokeSuspend(PatchCommand.kt:292)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:291)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 157
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at com.android.tools.smali.dexlib2.builder.MutableMethodImplementation.replaceInstruction(MutableMethodImplementation.java:336)
        at app.revanced.patcher.extensions.InstructionExtensions.replaceInstruction(InstructionExtensions.kt:289)
        at app.revanced.patches.shared.misc.gms.AbstractGmsCoreSupportPatch.transformPrimeMethod(AbstractGmsCoreSupportPatch.kt:184)
        at app.revanced.patches.shared.misc.gms.AbstractGmsCoreSupportPatch.execute(AbstractGmsCoreSupportPatch.kt:80)
        at app.revanced.patches.shared.misc.gms.AbstractGmsCoreSupportPatch.execute(AbstractGmsCoreSupportPatch.kt:37)
        at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
        ... 24 more

INFO: Hide get premium succeeded
INFO: Minimized playback music succeeded
INFO: Music video ads succeeded
INFO: Remove upgrade button succeeded
INFO: Change package name succeeded
INFO: Compiling patched dex files
INFO: Compiled classes.dex
INFO: Compiled classes2.dex
INFO: Compiled classes3.dex
INFO: Compiled classes4.dex
INFO: Compiled classes5.dex
INFO: Compiled classes6.dex
INFO: Compiled classes7.dex
INFO: Compiled classes8.dex
INFO: Compiling modified resources
INFO: Aligning com.google.android.apps.youtube.music_6.29.57-62957240_minAPI24(arm64-v8a)(nodpi)_apkmirror.com.apk
INFO: Signing com.google.android.apps.youtube.music_6.29.57-62957240_minAPI24(arm64-v8a)(nodpi)_apkmirror.com.apk
INFO: Saved to /sdcard/YTMusic-ReVanced.apk
INFO: Purging temporary files
INFO: Purged resource cache directory
Finished 😀

**Comment by KobeW50** [comment]
@oSumAtrIX If more information is still needed, here is a full patcher log from the ReVanced Manager. Let me know if I should provide anything else.

```
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: SM-S906U1
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.youtube.music v6.29.57
Patches version: v3.0.0
Patches added: Background play, GmsCore support [GmsCore Vendor: com.mgoogle], Music video ads
Patches removed: Music video ads, Codecs unlock, Exclusive audio playback, Minimized playback music, Hide get premium, Remove upgrade button, Bypass certificate checks, Background play, GmsCore support [GmsCore Vendor: com.mgoogle]
Options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Applied 3 patches
GmsCore support failed: app.revanced.patcher.patch.PatchException: Index -1 out of bounds for length 157
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:185)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Patcher.kt:203)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:8)
	at app.revanced.patcher.Patcher$apply$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(MainActivity.kt:324)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$36(MainActivity.kt:323)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$wwTqh4bVDMuwAT_qXBREk8gLHGU(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 157
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at com.android.tools.smali.dexlib2.builder.MutableMethodImplementation.replaceInstruction(MutableMethodImplementation.java:336)
	at app.revanced.patcher.extensions.InstructionExtensions.replaceInstruction(InstructionExtensions.kt:289)
	at app.revanced.patches.shared.misc.gms.AbstractGmsCoreSupportPatch.transformPrimeMethod(AbstractGmsCoreSupportPatch.kt:184)
	at app.revanced.patches.shared.misc.gms.AbstractGmsCoreSupportPatch.execute(AbstractGmsCoreSupportPatch.kt:80)
	at app.revanced.patches.shared.misc.gms.AbstractGmsCoreSupportPatch.execute(AbstractGmsCoreSupportPatch.kt:37)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Patcher.kt:174)
	... 18 more
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
Signing APK
Patched
```
