### ISSUE TITLE
bug: Revanced Tiktok not building

### ISSUE THREAD

**Issue by kazimmt** [revanced/revanced-patches#340]
### Type

Error while patching

### Bug description

I try to build TikTok Revanced version but it shows error.
I tried colab & windows command shell both.
But Same error happen.

### Steps to reproduce

--

### Relevant log output

```shell
C:\Users\User\Downloads\!RevanceBuilder\tiktok>java -jar revanced-cli.jar -a tik
tok.apk -c -o revanced.apk -b revanced-patches.jar -m revanced-integrations.apk
INFO: Deleting existing resource cache directory
INFO: Decoding resources
WARNING: Could not decode attr value, using undecoded value instead: ns=android,
 name=theme, value=0x7b060000
WARNING: Could not decode attr value, using undecoded value instead: ns=android,
 name=theme, value=0x7b060000
WARNING: Could not decode attr value, using undecoded value instead: ns=android,
 name=resource, value=0x6e020000
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
SEVERE: Could not decode file, replacing by FALSE value: o/gq.9.png
INFO: Reading dex files
INFO: Merging revanced-integrations.apk
WARNING: Skipping timeline-ads: Incompatible with com.ss.android.ugc.trill. This
 patch is only compatible with com.twitter.android
WARNING: Skipping general-reddit-ads: Incompatible with com.ss.android.ugc.trill
. This patch is only compatible with com.reddit.frontpage
WARNING: Skipping minimized-playback-music: Incompatible with com.ss.android.ugc
.trill. This patch is only compatible with com.google.android.apps.youtube.music

INFO: tiktok-ads succeeded
INFO: Compiling resources
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\anima
tor\a.xml:2: error: duplicate attribute.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\anima
tor\a.xml: error: file failed to compile.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\cw.xml:2: error: duplicate attribute.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\cw.xml: error: file failed to compile.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\cx.xml:2: error: duplicate attribute.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\cx.xml: error: file failed to compile.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\cy.xml:2: error: duplicate attribute.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\cy.xml: error: file failed to compile.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\cz.xml:2: error: duplicate attribute.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\cz.xml: error: file failed to compile.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\d0.xml:2: error: duplicate attribute.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\d0.xml: error: file failed to compile.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\d1.xml:2: error: duplicate attribute.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\d1.xml: error: file failed to compile.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\dz.xml:2: error: duplicate attribute.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\dz.xml: error: file failed to compile.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\gd.xml:2: error: duplicate attribute.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\gd.xml: error: file failed to compile.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\ge.xml:2: error: duplicate attribute.
WARNING: C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache\res\color
\ge.xml: error: file failed to compile.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit
 code = 1): [C:\Users\User\AppData\Local\Temp\brut_util_Jar_16386938541620061795
6420992820064840902.tmp, compile, --dir, C:\Users\User\Downloads\!RevanceBuilder
\tiktok\revanced-cache\res, --legacy, -o, C:\Users\User\Downloads\!RevanceBuilde
r\tiktok\revanced-cache\build\resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.ja
va:372)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.jav
a:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:204)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSame
Parent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.ja
va:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\
User\AppData\Local\Temp\brut_util_Jar_163869385416200617956420992820064840902.tm
p, compile, --dir, C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cache
\res, --legacy, -o, C:\Users\User\Downloads\!RevanceBuilder\tiktok\revanced-cach
e\build\resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.ja
va:368)
        ... 13 more
```

### Screenshots or videos

![tiktok-failed-1](https://user-images.githubusercontent.com/82371061/184617610-8943ade1-faa6-459f-a662-b66b850e0924.jpg)
![tiktok-failed-2](https://user-images.githubusercontent.com/82371061/184617783-abf48cf0-5520-4ff1-8c49-e97136460e66.jpg)

**Comment by reisxd** [comment]
Use the `-r` flag.

**Comment by kazimmt** [comment]
> Use the `-r` flag.

Thanks. It works.
