### ISSUE TITLE
bug: Cannot patch Tiktok app

### ISSUE THREAD

**Issue by FeralWriting** [ReVanced/revanced-patches#3406]
### Bug description

I want to remove Tiktok Revanced automatically keeping the same playback speed between videos as it's extremely annoying with no setting to turn it off in app. I tried to remove that feature by deselecting it in the selected patches section, but every time I run "patch", it throws a bunch of errors. Here are the patches:
![Screenshot_20240702-022655](https://github.com/ReVanced/revanced-patches/assets/69817846/63608c7a-6d21-4d62-9fd9-962d31cbb53f)

To reproduce this, select any given patches and choose patch.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: Pixel 7 Pro
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.ss.android.ugc.trill v32.5.3 (Suggested: 32.5.3)
Patches version: v4.10.0
Patches added: Default
Patches removed: Playback speed
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
An error occurred:
lanchon.multidexlib2.DuplicateTypeException: LX/czP;
	at lanchon.multidexlib2.MultiDexContainerBackedDexFile.<init>(Unknown Source:109)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(Unknown Source:6)
	at app.revanced.patcher.data.BytecodeContext$classes$2.invoke(SourceFile:0)
	at app.revanced.patcher.data.BytecodeContext$classes$2.invoke(SourceFile:0)
	at kotlin.SynchronizedLazyImpl.getValue(Unknown Source:20)
	at app.revanced.patcher.data.BytecodeContext.getClasses(Unknown Source:2)
	at app.revanced.patcher.data.BytecodeContext$Integrations.flush(Unknown Source:18)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:172)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:470)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Check if the issue occurs with default ReVanced Manager settings

**Comment by zero5enpai** [comment]
Never worked from the app for me cuz packages are too many or too large or sth. 
Use this to patch tiktok on PC:
[https://github.com/taku-nm/auto-cli](auto-cli)

Note: tiktok did not get support updates for ages, dont count on patches

**Comment by oSumAtrIX** [comment]
Issue should be fixed
