### ISSUE TITLE
bug: Error Patching Tiktok 32.5.3 using last patches

### ISSUE THREAD

**Issue by Solus32** [ReVanced/revanced-patches#3408]
### Bug description

Error patching Tiktok 32.5.3 "com.zhiliaoapp.musically" using the last patches; revanced-patches-3.0.1.jar, revanced-integrations-1.0.0.apk, revanced-cli-4.3.0-all.jar

### Error logs

```shell
INFORMACIÓN: Loading patches 
INFORMACIÓN: Decoding app manifest 
INFORMACIÓN: SIM spoof excluded 
INFORMACIÓN: Spoof SIM country excluded 
INFORMACIÓN: Export all activities excluded 
INFORMACIÓN: Spoof Wi-Fi connection excluded 
INFORMACIÓN: Predictive back gesture excluded 
INFORMACIÓN: Enable Android debugging excluded 
INFORMACIÓN: Override certificate pinning excluded 
INFORMACIÓN: Change package name excluded 
INFORMACIÓN: Setting patch options 
INFORMACIÓN: Merging integrations 
INFORMACIÓN: Deleting existing resource cache directory 
INFORMACIÓN: Decoding resources 
INFORMACIÓN: Executing patches 
INFORMACIÓN: Disable login requirement succeeded 
INFORMACIÓN: Downloads succeeded 
INFORMACIÓN: Feed filter succeeded 
INFORMACIÓN: Fix Google login succeeded 
INFORMACIÓN: Playback speed succeeded 
INFORMACIÓN: Remove screen capture restriction succeeded 
INFORMACIÓN: Remove screenshot restriction succeeded 
INFORMACIÓN: Settings succeeded 
INFORMACIÓN: Show seekbar succeeded 
INFORMACIÓN: Compiling patched dex files 
INFORMACIÓN: Compiled classes.dex 
INFORMACIÓN: Compiled classes2.dex 
INFORMACIÓN: Compiled classes3.dex 
INFORMACIÓN: Compiled classes4.dex 
INFORMACIÓN: Compiled classes5.dex 
INFORMACIÓN: Compiled classes6.dex 
INFORMACIÓN: Compiled classes7.dex 
INFORMACIÓN: Compiled classes8.dex 
INFORMACIÓN: Compiled classes9.dex 
INFORMACIÓN: Compiled classes10.dex 
INFORMACIÓN: Compiled classes11.dex 
INFORMACIÓN: Compiled classes12.dex 
INFORMACIÓN: Compiled classes13.dex 
INFORMACIÓN: Compiled classes14.dex 
INFORMACIÓN: Compiled classes15.dex 
INFORMACIÓN: Compiled classes16.dex 
INFORMACIÓN: Compiled classes17.dex 
INFORMACIÓN: Compiled classes18.dex 
INFORMACIÓN: Compiled classes19.dex 
INFORMACIÓN: Compiled classes20.dex 
INFORMACIÓN: Compiled classes21.dex 
INFORMACIÓN: Compiled classes22.dex 
INFORMACIÓN: Compiled classes23.dex 
INFORMACIÓN: Compiled classes24.dex 
INFORMACIÓN: Compiling modified resources 
ADVERTENCIA: /home/user/Android/ReVanced/tiktok-revanced_v32.5.3-resource-cache/AndroidManifest.xml:1318: error: '@1594359808' is incompatible with attribute resource (attr) reference. 
ADVERTENCIA: error: failed processing manifest. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_135191937463633785443087308845178646632.tmp, link, -o, /home/user/Android/ReVanced/tiktok-revanced_v32.5.3-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 2023205030, --version-name, 32.5.3, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL4622474111137003833.tmp, -0, arsc, -I, /home/user/Android/ReVanced/tiktok-revanced_v32.5.3-resource-cache/1.apk, --manifest, /home/user/Android/ReVanced/tiktok-revanced_v32.5.3-resource-cache/AndroidManifest.xml, /home/user/Android/ReVanced/tiktok-revanced_v32.5.3-resource-cache/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:246)
	at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
	at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:128)
	at app.revanced.patcher.Patcher.get(Patcher.kt:265)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:301)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_135191937463633785443087308845178646632.tmp, link, -o, /home/user/Android/ReVanced/tiktok-revanced_v32.5.3-resource-cache/aapt_temp_file, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 33, --version-code, 2023205030, --version-name, 32.5.3, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, /tmp/APKTOOL4622474111137003833.tmp, -0, arsc, -I, /home/user/Android/ReVanced/tiktok-revanced_v32.5.3-resource-cache/1.apk, --manifest, /home/user/Android/ReVanced/tiktok-revanced_v32.5.3-resource-cache/AndroidManifest.xml, /home/user/Android/ReVanced/tiktok-revanced_v32.5.3-resource-cache/build/resources.zip]
	at brut.util.OS.exec(OS.java:104)
	at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:242)
	... 13 more
```

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Read the warnings when you toggled the settings in ReVanced Manager

**Comment by oSumAtrIX** [comment]
In this case, use the default set of patches.
