### ISSUE TITLE
bug: reddit build fails

### ISSUE THREAD

**Issue by weirdal3333** [revanced/revanced-patches#342]
### Type

Error while patching

### Bug description

The reddit build fails using the latest version.

### Steps to reproduce

Command used: java -jar .\revanced-cli-2.9.3-all.jar -a .\Reddit_v2022.30.0_apkpure.com.apk -b .\revanced-patches-2.36.2.jar -m .\app-release-unsigned.apk -o revanced_r.apk

### Relevant log output

```shell
INFO: Deleting existing resource cache directory
WARNING: Skipping package group: com.reddit.frontpage.creatorkit_dynamicfeature
INFO: Decoding resources
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=theme, value=0x7e0c0000
WARNING: Could not decode attr value, using undecoded value instead: ns=android, name=resource, value=0x7e0e0000
INFO: Reading dex files
INFO: Merging .\app-release-unsigned.apk
WARNING: Skipping music-video-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping codecs-unlock: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping exclusive-audio-playback: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
INFO: Skipping compact-header: Not explicitly included
WARNING: Skipping minimized-playback-music: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping hide-get-premium: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music

WARNING: Skipping tasteBuilder-remover: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping upgrade-button-remover: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping music-microg-support: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping background-play: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.apps.youtube.music
WARNING: Skipping tiktok-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
WARNING: Skipping timeline-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.twitter.android
WARNING: Skipping promo-code-unlock: Incompatible with com.reddit.frontpage. This patch is only compatible with de.dwd.warnapp
WARNING: Skipping general-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping hide-infocard-suggestions: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping video-ads: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping seekbar-tapping: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping swipe-controls: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping amoled: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping hide-autoplay-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping premium-heading: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping custom-branding: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping hide-cast-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping disable-create-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping disable-fullscreen-panels: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping minimized-playback: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping old-quality-layout: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping return-youtube-dislike: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping hide-shorts-button: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping sponsorblock: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping tablet-mini-player: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping hide-watermark: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping enable-wide-searchbar: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping always-autorepeat: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping custom-playback-speed: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
INFO: Skipping enable-debugging: Not explicitly included
WARNING: Skipping hdr-auto-brightness: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping microg-support: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping remember-video-quality: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping settings: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
WARNING: Skipping custom-video-buffer: Incompatible with com.reddit.frontpage. This patch is only compatible with com.google.android.youtube
INFO: general-reddit-ads succeeded
INFO: Compiling resources
WARNING: C:\Users\User\Desktop\revanced-cache\AndroidManifest.xml:391: error: '@2114715648' is incompatible with attribute theme (attr) reference.
WARNING: C:\Users\User\Desktop\revanced-cache\AndroidManifest.xml:563: error: '@2114846720' is incompatible with attribute resource (attr) reference.
WARNING: error: failed processing manifest.
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\User\AppData\Local\Temp\brut_util_Jar_40937928054595268501073937078537976861.tmp, link, -o, C:\Users\User\Desktop\revanced-cache\aapt_temp_file, --min-sdk-version, 24, --target-sdk-version, 32, --version-code, 548620, --version-name, 2022.30.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\User\AppData\Local\Temp\APKTOOL18245638336374230814.tmp, -0, arsc, -I, revanced-cache\1.apk, --manifest, C:\Users\User\Desktop\revanced-cache\AndroidManifest.xml, C:\Users\User\Desktop\revanced-cache\build\resources.zip]
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:491)
        at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:626)
        at app.revanced.patcher.Patcher.save(Patcher.kt:204)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:28)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\User\AppData\Local\Temp\brut_util_Jar_40937928054595268501073937078537976861.tmp, link, -o, C:\Users\User\Desktop\revanced-cache\aapt_temp_file, --min-sdk-version, 24, --target-sdk-version, 32, --version-code, 548620, --version-name, 2022.30.0, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, -e, C:\Users\User\AppData\Local\Temp\APKTOOL18245638336374230814.tmp, -0, arsc, -I, revanced-cache\1.apk, --manifest, C:\Users\User\Desktop\revanced-cache\AndroidManifest.xml, C:\Users\User\Desktop\revanced-cache\build\resources.zip]
        at brut.util.OS.exec(OS.java:99)
        at brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:487)
        ... 13 more
```

### Solution

Fix the bug and/or say which versions that support the patch, just like you do for the official youtube app.

**Comment by reisxd** [comment]
Use the `-r` flag.

**Comment by weirdal3333** [comment]
This works.
