### ISSUE TITLE
bug: Tumblr patching unable to determine min Android version

### ISSUE THREAD

**Issue by SubZero5** [ReVanced/revanced-patches#3471]
### Bug description

An error occurred:
com.android.apksig.apk.MinSdkVersionException: Failed to determine APK's minimum supported Android platform version

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: REA-NX9
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.tumblr v35.5.0.110 (Suggested: Any)
Patches version: v4.11.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Applied 5 patches
Compiling patched dex files
Compiled 8 dex files
Aligning APK
Signing APK
An error occurred:
com.android.apksig.apk.MinSdkVersionException: Failed to determine APK's minimum supported Android platform version
	at com.android.apksig.ApkSigner.getMinSdkVersionFromApk(Unknown Source:16)
	at com.android.apksig.ApkSigner.sign(SourceFile:0)
	at com.android.apksig.ApkSigner.sign(SourceFile:0)
	at app.revanced.library.ApkSigner$Signer.signApk(SourceFile:0)
	at app.revanced.library.ApkUtils.sign(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:553)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.android.apksig.zip.ZipFormatException: Data Descriptor presence mismatch between Local File Header and Central Directory for entry AndroidManifest.xml. LFH: true, CD: false
	at com.android.apksig.internal.zip.LocalFileRecord.getRecord(SourceFile:0)
	at com.android.apksig.internal.zip.LocalFileRecord.outputUncompressedData(SourceFile:0)
	at com.android.apksig.internal.zip.LocalFileRecord.getUncompressedData(Unknown Source:27)
	at com.android.apksig.ApkSigner.getAndroidManifestFromApk(Unknown Source:12)
	at com.android.apksig.ApkSigner.getMinSdkVersionFromApk(Unknown Source:0)
	... 8 more
```

### Additional context

I downloaded Tumblr apkm and converted it to APK via ApkTool M using aapt2. Did not sign it.

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The APK file is corrupted

**Comment by SubZero5** [comment]
The APK file is not corrupted. It can be installed with zero problems.
Please try patching the Tumblr APK yourself...

**Comment by oSumAtrIX** [comment]
`Caused by: com.android.apksig.zip.ZipFormatException: Data Descriptor presence mismatch between Local File Header and Central Directory for entry AndroidManifest.xml. LFH: true, CD: false`

Yes it is corrupted. Installing it doesn't proof otherwise.
