### ISSUE TITLE
bug: Error at the end while patching Whatsapp

### ISSUE THREAD

**Issue by Pamilg9** [ReVanced/revanced-patches#3483]
### Bug description

1. Patching the latest version of Whatsapp
2. In the end, it fails

### Error logs

```shell
- Device Info
ReVanced Manager: 1.20.1
Model: SM-A217F
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.whatsapp v2.24.14.81 (Suggested: Any)
Patches version: v4.11.0
Patches added: Change version code, Remove screenshot restriction, Remove share targets
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
The app has no shortcuts
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~6Y_QWs4nPS1jV_N827XA2A==/app.revanced.manager.flutter-Vq13Ex9C4YCCvbAEc1CWKA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IVUAQG/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 34, --version-code, 241481004, --version-name, 2.24.14.81, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL5510843631188163331.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IVUAQG/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IVUAQG/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IVUAQG/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:563)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:104)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$hTJfH-rv2j-9Y91G5H_L5jFDN6U(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda5.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~6Y_QWs4nPS1jV_N827XA2A==/app.revanced.manager.flutter-Vq13Ex9C4YCCvbAEc1CWKA==/lib/arm64/libaapt2.so, link, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IVUAQG/revanced-temporary-files/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 34, --version-code, 241481004, --version-name, 2.24.14.81, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /data/user/0/app.revanced.manager.flutter/cache/APKTOOL5510843631188163331.tmp, -0, arsc, -I, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IVUAQG/revanced-temporary-files/1.apk, --manifest, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IVUAQG/revanced-temporary-files/apk/AndroidManifest.xml, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-IVUAQG/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:542)
	... 7 more
```

### Solution

I don't know

### Additional context

No. The error report contains information

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Resource patching failed due to AAPT. Refer to the warnings when you toggled settings in ReVanced Manager

**Comment by Pamilg9** [comment]
how did i fix it
