### ISSUE TITLE
bug: Failed to Patch X/Twitter v10.50.0

### ISSUE THREAD

**Issue by BedBug2479** [ReVanced/revanced-patches#3508]
### Bug description

1. Revanced Manager doesnot recognise the latest X/Twitter file
2. Used **AntiSplit M** to Unsplit the latest file
3. Revanced Manager now recognises the latest X/Twitter file
4. Started patching with the below patches
5. Patch failed while signing

### Error logs

```shell
- Device Info
ReVanced Manager: 1.21.1
Model: LE2121
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.twitter.android v10.50.0-release.0 (Suggested: Any)
Patches version: v4.12.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 5 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
Aligning APK
Signing APK
An error occurred:
com.android.apksig.apk.ApkFormatException: Malformed ZIP entry: META-INF/deeplinkdispatch_release.kotlin_module
	at com.android.apksig.ApkSigner.sign(SourceFile:0)
	at com.android.apksig.ApkSigner.sign(SourceFile:0)
	at app.revanced.library.ApkSigner$Signer.signApk(SourceFile:0)
	at app.revanced.library.ApkUtils.sign(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:520)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: com.android.apksig.zip.ZipFormatException: Data Descriptor presence mismatch between Local File Header and Central Directory for entry META-INF/deeplinkdispatch_release.kotlin_module. LFH: true, CD: false
	at com.android.apksig.internal.zip.LocalFileRecord.getRecord(SourceFile:0)
	at com.android.apksig.internal.zip.LocalFileRecord.getRecord(SourceFile:0)
	... 8 more
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by BedBug2479** [comment]
> 10.50.0 patches correctly for me.
> 
> You need to check "automatically select splits for your device specifications" inside antisplit app.
> 
> Or just patch a slightly older version of Twitter that has full apks.

Now I am getting a different issue

```
- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 48 byte allocation with 1259312 free bytes and 1229KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.nio.CharBuffer.allocate(CharBuffer.java:177)
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:858)
	at brut.androlib.res.decoder.StringBlock.decodeString(Unknown Source:18)
	at brut.androlib.res.decoder.StringBlock.getString(Unknown Source:41)
	at brut.androlib.res.decoder.StringBlock.getHTML(Unknown Source:0)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(Unknown Source:41)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(Unknown Source:72)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(Unknown Source:438)
	at brut.androlib.res.decoder.ARSCDecoder.readResourceTable(Unknown Source:150)
	at brut.androlib.res.decoder.ARSCDecoder.decode(Unknown Source:5)
	at brut.androlib.res.data.ResTable.loadResPackagesFromApk(Unknown Source:16)
	at brut.androlib.res.data.ResTable.loadFrameworkPkg(Unknown Source:43)
	at brut.androlib.res.data.ResTable.getPackage(Unknown Source:15)
	at brut.androlib.res.data.ResTable.getResSpec(SourceFile:0)
	at brut.androlib.res.data.ResTable.getResSpec(SourceFile:0)
	at brut.androlib.res.decoder.AXmlResourceParser.decodeFromResourceId(Unknown Source:4)
	at brut.androlib.res.decoder.AXmlResourceParser.getAttributeName(Unknown Source:26)
	at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeName(Unknown Source:2)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(Unknown Source:64)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(Unknown Source:82)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(Unknown Source:86)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(Unknown Source:39)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(Unknown Source:4)
	at brut.androlib.res.decoder.ResFileDecoder.decode(SourceFile:0)
	at brut.androlib.res.decoder.ResFileDecoder.decode(SourceFile:0)
	at brut.androlib.res.ResourcesDecoder.decodeResources(Unknown Source:160)
	at app.revanced.patcher.data.ResourceContext.decodeResources$revanced_patcher(Unknown Source:44)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:214)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:23)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:26)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:437)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/[data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk'](http://data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk'), path = '/[data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GZWGGM/out.apk'](http://data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-GZWGGM/out.apk') (OS Error: No such file or directory, errno = 2)
```

**Comment by BedBug2479** [comment]
Ignore the above comment istalled fine after a clean install of RManager

**Comment by FreakOfJunk** [comment]
Was able to patch 10.53.release but Revanced reports it's not compatible with my device after patch. No issues installing pre patch. Also you must keep uninstalling  Revanced to get a successful patch.

"
![Screenshot_20240807_102231_Package installer](https://github.com/user-attachments/assets/00ba08aa-f2e0-44c3-8c58-2b571d658c32)
App not installed as app isn't compatible with your phone."
