### ISSUE TITLE
bug (Google Photos): Unable to execute patch

### ISSUE THREAD

**Issue by SaleOff** [ReVanced/revanced-patches#3509]
### Bug description

![Screenshot_2024-08-06-14-58-55-904_app revanced manager flutter](https://github.com/user-attachments/assets/4eb0de1e-ddc8-48d6-9763-9daffca41924)
![Screenshot_2024-08-06-14-58-58-067_app revanced manager flutter](https://github.com/user-attachments/assets/bb2ac32c-ba67-47c1-ba76-364e3ba3b29b)
[revanced-manager_logcat_20240806150021198193.log](https://github.com/user-attachments/files/16507232/revanced-manager_logcat_20240806150021198193.log)

### Error logs

```shell
- Device Info
ReVanced Manager: 1.21.1
Model: 2112123AG
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v6.93.0.657009179 (Suggested: Any)
Patches version: v4.12.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: false
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 2 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~OE6Xk64NYjfpJrlphtKT-g==/app.revanced.manager.flutter-Ju2_pT39z_arWZxGSEt1kg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AOMLZV/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AOMLZV/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~OE6Xk64NYjfpJrlphtKT-g==/app.revanced.manager.flutter-Ju2_pT39z_arWZxGSEt1kg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AOMLZV/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AOMLZV/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-AOMLZV/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is a known issue and caused by toggling off save last patched apk in the settings
