### ISSUE TITLE
bug: Youtube patching failed

### ISSUE THREAD

**Issue by xDoge26** [ReVanced/revanced-patches#3526]
### Bug description

Im trying to patch youtube and it keeps failing

### Error logs

```shell
- Device Info
ReVanced Manager: 1.21.1
Model: 2201117TG
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.12.0
Patches added: Change header, Custom branding, Remove player controls background
Patches removed: Hide ads, Copy video URL, Remove viewer discretion dialog, Downloads, Disable precise seeking gesture, Swipe controls, Disable auto captions, Hide video action buttons, Hide autoplay button, Hide captions button, Navigation buttons, Hide player buttons, Hide album cards, Comments, Hide crowdfunding box, Hide endscreen cards, Hide filter bar, Hide floating microphone button, Disable fullscreen ambient mode, Hide layout components, Hide info cards, Player flyout menu, Disable rolling number animations, Hide seekbar, Hide Shorts components, Disable suggested video end screen, Hide timestamp, Miniplayer, Disable player popup panels, Custom player overlay opacity, Return YouTube Dislike, Wide searchbar, Restore old seekbar thumbnails, SponsorBlock, Spoof app version, Change start page, Disable resuming Shorts on startup, Enable tablet layout, Alternative thumbnails, Bypass image region restrictions, Announcements, Always repeat, Enable debugging, Spoof device dimensions, Bypass URL redirects, Remove tracking query parameter, Disable zoom haptics, Playback speed
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 14 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 10485776 byte allocation with 6328000 free bytes and 6179KB until OOM, target footprint 268435456, growth limit 268435456
	at java.util.Arrays.copyOf(Arrays.java:3578)
	at com.google.common.io.ByteStreams.combineBuffers(Unknown Source:23)
	at com.google.common.io.ByteStreams.toByteArrayInternal(Unknown Source:45)
	at com.google.common.io.ByteStreams.toByteArray(SourceFile:0)
	at com.android.tools.build.apkzlib.bytestorage.InMemoryByteStorage.fromStream(Unknown Source:0)
	at com.android.tools.build.apkzlib.bytestorage.InMemoryByteStorage.fromSource(Unknown Source:4)
	at com.android.tools.build.apkzlib.bytestorage.OverflowToDiskByteStorage.fromSource(Unknown Source:4)
	at com.android.tools.build.apkzlib.bytestorage.ChunkBasedByteStorage.fromSource(Unknown Source:29)
	at com.android.tools.build.apkzlib.zip.ZFile.mergeFrom(Unknown Source:195)
	at app.revanced.library.ApkUtils.applyTo(Unknown Source:153)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:484)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-WSJLGX/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
![Screenshot_20240811-163627](https://github.com/user-attachments/assets/ade8b4e0-b483-4508-ae48-0243304a2c3c)

**Comment by oSumAtrIX** [comment]
![Screenshot_20240811-163627](https://github.com/user-attachments/assets/ade8b4e0-b483-4508-ae48-0243304a2c3c)

**Comment by oSumAtrIX** [comment]
For support, move to one of our links at https://revanced.app.
