### ISSUE TITLE
Please help with patching Google photos 

### ISSUE THREAD

**Issue by marafaltus** [ReVanced/revanced-patches#3576]
- Device Info
ReVanced Manager: 1.21.2
Model: CPH2663
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v6.94.0.662644291 (Suggested: Any)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 8 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~RBkonSITKSP0iDPSOq2Ufg==/app.revanced.manager.flutter-Wcoi6Qow9ASDFHlr0kN4tw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XMHQPH/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XMHQPH/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:462)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~RBkonSITKSP0iDPSOq2Ufg==/app.revanced.manager.flutter-Wcoi6Qow9ASDFHlr0kN4tw==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XMHQPH/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XMHQPH/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/cache/patcher/tmp-XMHQPH/out.apk' (OS Error: No such file or directory, errno = 2)

**Comment by FordCorn** [comment]
Use Revancify and Termux:Monet to patch, what I personally did.

**Comment by jddcef** [comment]
> Use Revancify and Termux:Monet to patch, what I personally did.

This was amazing.  Didn't know about this. 
Termux:Monet is a virtual Linux terminal environment , which let's you run the Revancify command line software on the phone without a PC.
Revancify littel command line gui literally fetches the latest photos app, and patches it and saves the apk to a Revancify folder on disk which can be installed.  From the app itself i got an invalid message when trying to install.
