### ISSUE TITLE
bug: Soundcloud patch "Hide ADS" no longer works

### ISSUE THREAD

**Issue by alan7383** [ReVanced/revanced-patches#3619]
### Bug description

From Soundcloud version 2024.09.03-beta the "Hide ADS" patch no longer works, see logs.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.21.2
Model: 22101316G
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.soundcloud.android v2024.09.03-beta (Suggested: Any)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Executing patches
Applied 2 patches
Hide ads failed: app.revanced.patcher.patch.PatchException: Failed to resolve InterceptFingerprint
at app.revanced.util.BytecodeUtilsKt.getException(BytecodeUtils.kt:27)
at app.revanced.util.BytecodeUtilsKt.resultOrThrow(BytecodeUtils.kt:19)
at app.revanced.patches.soundcloud.ad.HideAdsPatch.execute(HideAdsPatch.kt:64)
at app.revanced.patches.soundcloud.ad.HideAdsPatch.execute(HideAdsPatch.kt:17)
at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:190)
at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:282)
at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:23)
at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:26)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:437)
at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
at java.lang.Thread.run(Thread.java:1012)
Compiling patched dex files
Compiled 12 dex files
Aligning APK
Signing APK
Patched APK
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
What is the latest version that works?

**Comment by alan7383** [comment]
The version 2024.08.22-release/beta Works well
