### ISSUE TITLE
bug: google photos patch fails

### ISSUE THREAD

**Issue by rowi123** [ReVanced/revanced-patches#3635]
### Bug description

I cannot patch google photos.
Tried many different versions of the apk.
Also tried 3 latest revanced versions.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.22.0
Model: SM-A536B
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.apps.photos v6.98.0.670003362 (Suggested: Any)
Patches version: v4.13.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 3 patches
Compiling patched dex files
Compiled 9 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~bShsYtdayl9RoT3tgPEt3Q==/app.revanced.manager.flutter-IrkR-VRGStOnO1SK3b3ATg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-UMXOSS/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-UMXOSS/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~bShsYtdayl9RoT3tgPEt3Q==/app.revanced.manager.flutter-IrkR-VRGStOnO1SK3b3ATg==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-UMXOSS/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-UMXOSS/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-UMXOSS/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by rowi123** [comment]
I don't understand: what does not planned mean?

**Comment by oSumAtrIX** [comment]
![image](https://github.com/user-attachments/assets/85a39fa9-75d2-4a71-b1c5-dcdc98e56d8b)

![image](https://github.com/user-attachments/assets/afc9b9b1-f763-49de-a966-1e7c2bfc8512)
