### ISSUE TITLE
bug: Crash when viewing YouTube videos on Google Feed/App

### ISSUE THREAD

**Issue by Lunchb0ne** [revanced/revanced-patches#368]
### Type

Error at runtime

### Bug description

The crash happens when a video is focused in the Google App Feed (either from right swipe page in the Pixel Launcher) or just through the Google App.

I've attached the associated stacktrace.

### Steps to reproduce

Step 1. Scroll through Google Feed
Step 2. Stop at a Video Recommendation
Step 3. Wait for it while it tries to play the video
Step 4. Get stuck at Step 3 because the YouTube App will keep crashing

### Relevant log output

```shell
time: 1661115187454
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at app.revanced.integrations.settings.SettingsEnum.getBoolean(SettingsEnum.java:222)
	at app.revanced.integrations.patches.MinimizedPlaybackPatch.isMinimizedPlaybackEnabled(MinimizedPlaybackPatch.java:8)
	at zpz.i(Unknown Source:0)
	at zpq.e(PG:2)
	at zpi.d(PG:1)
	at wvb.X(PG:1)
	at aapz.h(PG:5)
	at aapw.d(PG:2)
	at aanh.run(PG:22)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Additional context

Interestingly enough, not including the Minimized playback patch doesn't circumvent this too.

**Comment by Lunchb0ne** [comment]
https://github.com/TeamVanced/Vanced/issues/1643

This might be a related issue from original Vanced's implementation.
