### ISSUE TITLE
Tiktok patch error 

### ISSUE THREAD

**Issue by dwk601** [ReVanced/revanced-patches#3690]
- Device Info
ReVanced Manager: 1.22.0
Model: LE2127
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.zhiliaoapp.musically v36.5.4 (Suggested: 36.5.4)
Patches version: v4.15.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Applied 8 patches
Compiling patched dex files
Compiled 22 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 944032 free bytes and 921KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at com.android.tools.smali.dexlib2.dexbacked.value.DexBackedArrayEncodedValue.getValue(Unknown Source:0)
	at com.android.tools.smali.dexlib2.base.value.BaseArrayEncodedValue.hashCode(Unknown Source:0)
	at com.android.tools.smali.dexlib2.base.BaseAnnotationElement.hashCode(Unknown Source:14)
	at java.util.AbstractSet.hashCode(AbstractSet.java:124)
	at com.android.tools.smali.dexlib2.base.BaseAnnotation.hashCode(Unknown Source:21)
	at java.util.HashMap.hash(HashMap.java:337)
	at java.util.HashMap.put(HashMap.java:617)
	at com.android.tools.smali.dexlib2.writer.pool.AnnotationPool.intern(Unknown Source:7)
	at com.android.tools.smali.dexlib2.writer.pool.AnnotationSetPool.intern(Unknown Source:43)
	at com.android.tools.smali.dexlib2.writer.pool.ClassPool.intern(Unknown Source:298)
	at com.android.tools.smali.dexlib2.writer.pool.DexPool.internClass(Unknown Source:4)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:27)
	at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-EYJEFO/out.apk' (OS Error: No such file or directory, errno = 2)

**Comment by ikerinagy** [comment]
I got the same error. I cannot even patch it using WSA, it bugs out at around the 22nd-23rd dex file.

**Comment by oSumAtrIX** [comment]
Follow the issue template
