### ISSUE TITLE
bug(Google Photos - Restore hidden 'Back up while charging' toggle): App crashes when feature is turned on

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-patches#3714]
### Bug description

Patched ReVanced Google Photos always crash whenever to try switch on "Restore hidden 'Back up while charging' toggle".
Patched with default patches. 

### Error logs

```shell
09-29 17:47:04.838 18696 18696 E AndroidRuntime: FATAL EXCEPTION: main
09-29 17:47:04.838 18696 18696 E AndroidRuntime: Process: app.revanced.android.photos, PID: 18696
09-29 17:47:04.838 18696 18696 E AndroidRuntime: java.lang.NullPointerException: throw with null exception
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at pme.a(PG:1490)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at axpa.Q(PG:5)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at axpr.q(PG:11)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at axpa.fE(PG:8)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at com.google.android.libraries.social.settings.PreferenceScreen.onItemClick(PG:16)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1397)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3494)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at android.widget.AbsListView$5.run(AbsListView.java:4543)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:900)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:103)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8668)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
09-29 17:47:04.838 18696 18696 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

### Additional context

Tested on Environment:
Android 10 device.
Patches [v4.16.0-dev.6](https://github.com/ReVanced/revanced-patches/releases/tag/v4.16.0-dev.6) 
Integrations [v1.15.0-dev.2](https://github.com/ReVanced/revanced-integrations/releases/tag/v1.15.0-dev.2)
CLI [v4.6.0](https://github.com/ReVanced/revanced-cli/releases/tag/v4.6.0)
[Google Photos version 7.0.0.674947721 build 49236444](https://www.apkmirror.com/apk/google-inc/photos/photos-7-0-0-674947721-release/google-photos-7-0-0-674947721-android-apk-download/)

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by harshads-dev** [comment]
I also have same issue
