### ISSUE TITLE
Getting error on patching "X" app

### ISSUE THREAD

**Issue by HUMENTH** [ReVanced/revanced-patches#3726]
### Bug description

Getting error on patching X app 

### Error logs

```shell
- Device Info
ReVanced Manager: 1.22.1-dev.2
Model: 23090RA98I
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.twitter.android v10.48.0-release.0 (Suggested: 10.48.0-release.0)
Patches version: v4.16.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 5 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~XIY7EbddBwhhHJyQ-6hSpg==/app.revanced.manager.flutter-tWQ_vNfKV32twLdAAjYk8g==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-YBOIGU/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-YBOIGU/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~XIY7EbddBwhhHJyQ-6hSpg==/app.revanced.manager.flutter-tWQ_vNfKV32twLdAAjYk8g==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-YBOIGU/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-YBOIGU/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-YBOIGU/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Solution

N/A

### Additional context

N/A

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by HUMENTH** [comment]
Getting error after denying root permission to Revanced Manager.

- Device Info
ReVanced Manager: 1.22.1-dev.2
Model: 23090RA98I
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.twitter.android v10.48.0-release.0 (Suggested: 10.48.0-release.0)
Patches version: v4.16.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 5 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~XIY7EbddBwhhHJyQ-6hSpg==/app.revanced.manager.flutter-tWQ_vNfKV32twLdAAjYk8g==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-XCEYGI/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-XCEYGI/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~XIY7EbddBwhhHJyQ-6hSpg==/app.revanced.manager.flutter-tWQ_vNfKV32twLdAAjYk8g==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-XCEYGI/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-XCEYGI/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-XCEYGI/out.apk' (OS Error: No such file or directory, errno = 2)

**Comment by oSumAtrIX** [comment]
Still says that it has root permissions

**Comment by HUMENTH** [comment]
Please check the attached screen recording.
https://github.com/user-attachments/assets/f39a9b71-ae4f-4a2f-a2d8-cae7e56cf373



Error log:
- Device Info
ReVanced Manager: 1.22.1-dev.2
Model: 23090RA98I
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: Yes

- Patch Info
App: com.twitter.android v10.48.0-release.0 (Suggested: 10.48.0-release.0)
Patches version: v4.16.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 5 patches
Compiling patched dex files
Compiled 12 dex files
Compiling modified resources
An error occurred:
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~XIY7EbddBwhhHJyQ-6hSpg==/app.revanced.manager.flutter-tWQ_vNfKV32twLdAAjYk8g==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-TOWMNY/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-TOWMNY/revanced-temporary-files/apk/build/resources.zip]
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:144)
	at brut.androlib.AaptInvoker.invokeAapt(Unknown Source:106)
	at app.revanced.patcher.data.ResourceContext.get(SourceFile:0)
	at app.revanced.patcher.Patcher.get(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:495)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/data/app/~~XIY7EbddBwhhHJyQ-6hSpg==/app.revanced.manager.flutter-tWQ_vNfKV32twLdAAjYk8g==/lib/arm64/libaapt2.so, compile, --dir, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-TOWMNY/revanced-temporary-files/apk/res, --legacy, -o, /data/user/0/app.revanced.manager.flutter/files/patcher/tmp-TOWMNY/revanced-temporary-files/apk/build/resources.zip]
	at brut.util.OS.exec(Unknown Source:75)
	at brut.androlib.AaptInvoker.invokeAapt2(Unknown Source:122)
	... 7 more
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-TOWMNY/out.apk' (OS Error: No such file or directory, errno = 2)

**Comment by oSumAtrIX** [comment]
Clear manager daza6abd select a full APK
