### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by iSuckAtCoding8** [ReVanced/revanced-patches#3732]
### Bug description

Can't patch TikTok 36.5.4

### Error logs

```shell
- Device Info
ReVanced Manager: 1.22.0
Model: SM-S928U1
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.zhiliaoapp.musically v36.5.4 (Suggested: 36.5.4)
Patches version: v4.16.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: false
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Executing patches
Applied 8 patches
Compiling patched dex files
Compiled 22 dex files
An error occurred:
java.lang.OutOfMemoryError: Failed to allocate a 88 byte allocation with 5225840 free bytes and 5103KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.util.Arrays.copyOf(Arrays.java:3585)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:177)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:543)
	at java.lang.StringBuffer.append(StringBuffer.java:319)
	at java.io.StringWriter.write(StringWriter.java:106)
	at java.io.StringWriter.append(StringWriter.java:150)
	at java.io.StringWriter.append(StringWriter.java:41)
	at com.android.tools.smali.dexlib2.formatter.DexFormattedWriter.writeSimpleName(Unknown Source:2)
	at com.android.tools.smali.dexlib2.formatter.DexFormattedWriter.writeClass(Unknown Source:37)
	at com.android.tools.smali.dexlib2.formatter.DexFormattedWriter.writeType(Unknown Source:25)
	at com.android.tools.smali.dexlib2.formatter.DexFormattedWriter.writeShortMethodDescriptor(Unknown Source:34)
	at com.android.tools.smali.dexlib2.formatter.DexFormatter.getShortMethodDescriptor(Unknown Source:9)
	at com.android.tools.smali.dexlib2.writer.pool.ClassPool.intern(Unknown Source:200)
	at com.android.tools.smali.dexlib2.writer.pool.DexPool.internClass(Unknown Source:4)
	at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:27)
	at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-WYKHBV/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Additional context

This is the second time I've tried. It took about 40 minutes on a flagship device. Went up to patching classes23.dex then failed. The first time, I swiped out of the app then when I came back the patching process failed. Tried again, but kept getting out of memory exceptions until I force closed revanced manager and tried again (with the result below).

### Acknowledgements

- [ ] I have checked all open and closed bug reports and this is not a duplicate.
- [ ] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Patcher can detect if it's running on Android by attempting to access a class exclusive to Android, like `android.os.Build`. However, it’s not the patcher's responsibility to handle this. The patcher has no direct connection to the manager, and the issue is not limited to Android. It can occur in any environment with insufficient RAM. On a related note, the source of the memory issue seems to have been identified.

A single DEX file can only contain a limited number of classes. This means, at any given time, only the maximum number of classes that fit within a single DEX need to be allocated in memory. However, we observe a linear memory usage increase with each DEX compilation. This suggests that the garbage collector is not clearing the references to the classes that have already been compiled into a DEX. 
 
Compiling classes into multiple DEX files is managed by `multidexlib`, which splits the list of classes to compile them into individual DEX files. As a result, the original list continues to reference the classes that have already been compiled. According to this theory, a potential memory leak fix would be getting rid of the original list after splitting it. This way, the compiled classes would lose their last reference once the list is split and the classes are compiled, allowing the GC to free up the memory.

I have not tested the theory, but it makes the most sense, and I think this would resolve all memory issues in one go and reduce max memory consumption to a fraction.
