### ISSUE TITLE
bug(Facebook): Patching fails

### ISSUE THREAD

**Issue by jpa102** [ReVanced/revanced-patches#3822]
### Bug description

from this [pull request](https://github.com/ReVanced/revanced-patches/pull/3627), i should be able to patch facebook. it has the patches `Hide sponsored stories` and `Hide story ads`

but since the author didn't specify which specific versions that's able to be patched (only the major versions and api level), i tried guessing which one

it fails every time with it expecting a value `view` and not `View` (case sensitive?)

i tried excluding universal patches, leaving out the 2 patches but still unsuccessful in patching

### Error logs

- Device Info
ReVanced Manager: 1.22.0
Model: SM-M127F
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.facebook.katana v480.0.0.55.88 (Suggested: Any)
Patches version: v4.17.0
Patches added: Hide mock location, Predictive back gesture, Remove screen capture restriction, Remove screenshot restriction, Spoof SIM country [Network ISO Country Code: JP, Sim ISO Country Code: JP], Spoof Wi-Fi connection
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches
Integration source: revanced/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
An error occurred:
java.lang.IllegalArgumentException: expected element name 'view' and not 'View'
	at org.xmlpull.renamed.MXSerializer.endTag(Unknown Source:94)
	at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.endTag(Unknown Source:2)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(Unknown Source:78)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(Unknown Source:85)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(Unknown Source:39)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(Unknown Source:4)
	at brut.androlib.res.decoder.ResFileDecoder.decode(SourceFile:0)
	at brut.androlib.res.decoder.ResFileDecoder.decode(SourceFile:0)
	at brut.androlib.res.ResourcesDecoder.decodeResources(Unknown Source:159)
	at app.revanced.patcher.data.ResourceContext.decodeResources$revanced_patcher(Unknown Source:44)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:214)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$2.invokeSuspend(Unknown Source:76)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:23)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:26)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(Unknown Source:464)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$t9VOe3aFJZkCMY59Ya4Pcinu-pA(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-ORJNPF/out.apk' (OS Error: No such file or directory, errno = 2)

### Solution

maybe i should use the command line version of the patcher, but i haven't tried it out yet

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
You are using resource patches which break decoding. The issue occurs in the Androlib library from ApkTool and is out of our reach. Report the issue to ApkTool.
