### ISSUE TITLE
bug: Patch fails on Facebook using cli

### ISSUE THREAD

**Issue by Solus32** [ReVanced/revanced-patches#3910]
### Bug description

Error patching Facebook v489.0.0.66.81 using cli

Architecture: arm64-v8a
App: Facebook v489.0.0.66.81
CLI: revanced-cli-5.0.0-all.jar
Patches: patches-5.0.2.rvp

java -jar revanced-cli.jar patch com.facebook.katana.apk -o facebook-revanced_v489.0.0.66.81.apk -p patches.rvp --keystore=revanced-key.keystore -e "Change package name" -e "Hide story ads" -e "Sponsored Stories" -e "Remove screenshot restriction" -e "Remove screen capture restriction" -e "Hide 'Sponsored Stories'"

### Error logs

```shell
INFORMACIÓN: Loading patches 
INFORMACIÓN: Deleting existing temporary files directory 
INFORMACIÓN: Decoding app manifest 
INFORMACIÓN: "Export all activities" disabled 
INFORMACIÓN: "Spoof build info" disabled 
INFORMACIÓN: "Hide mock location" disabled 
INFORMACIÓN: "Spoof SIM country" disabled 
INFORMACIÓN: "Spoof Wi-Fi connection" disabled 
INFORMACIÓN: "Enable Android debugging" disabled 
INFORMACIÓN: "Change data directory location" disabled 
INFORMACIÓN: "Hex" disabled 
INFORMACIÓN: "Predictive back gesture" disabled 
INFORMACIÓN: "Override certificate pinning" disabled 
INFORMACIÓN: "Remove share targets" disabled 
INFORMACIÓN: "Change version code" disabled 
INFORMACIÓN: Setting patch options 
INFORMACIÓN: Deleting existing temporary files directory 
INFORMACIÓN: Decoding resources 
java.lang.IllegalArgumentException: expected element name 'view' and not 'View'
	at org.xmlpull.renamed.MXSerializer.endTag(MXSerializer.java:708)
	at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.endTag(XmlSerializerDelegate.java:124)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:215)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:78)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:137)
	at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:28)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:153)
	at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:133)
	at brut.androlib.res.ResourcesDecoder.decodeResources(ResourcesDecoder.java:177)
	at app.revanced.patcher.patch.ResourcePatchContext.decodeResources$revanced_patcher(ResourcePatchContext.kt:64)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Patcher.kt:96)
	at app.revanced.patcher.Patcher$invoke$1.invoke(Patcher.kt)
	at app.revanced.patcher.Patcher$invoke$1.invoke(Patcher.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226)
	at app.revanced.cli.command.PatchCommand$run$1$4.invokeSuspend(PatchCommand.kt:315)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:314)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Resource patches wont work on facebokn, some of those that are disabled are resource patches

**Comment by oSumAtrIX** [comment]
I have recently bumped our fork with the upstream commits. However last time i checked twitch for example it still failed with resources
