### ISSUE TITLE
bug(YouTube Music): `Hide category bar` patch fails

### ISSUE THREAD

**Issue by Rajeshsahoo12** [ReVanced/revanced-patches#3956]
### Bug description

My machine is running with WINDOWS 10. I have tried to patch YT MUSIC v7.28.51 apk with below mentioned command. Have used exclusively disabling of `Permanent shuffle, Permanent repeat`.

`java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.0.2.rvp YouTubeMusic7.28.51.apk -o YouTubeMusicRevanced7.28.51.apk -e "Hide category bar" -d "Permanent shuffle" -d "Permanent repeat"`

But encountered with terminal log saying `Hide category bar` cannot be applied. And remaining patches gets applied. The base apk gets patched.

Where as on `https://revanced.app/patches?pkg=com.google.android.apps.youtube.music` for this patch `Hide category bar` is says to have any version of YT MUSIC.

### Error logs

```shell
java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.0.2.rvp YouTubeMusic7.28.51.apk -o YouTubeMusicRevanced7.28.51.apk -e "Hide category bar" -d "Permanent shuffle" -d "Permanent repeat"
 
 
INFO: Loading patches
INFO: Decoding app manifest
INFO: "Export all activities" disabled
INFO: "Spoof build info" disabled
INFO: "Hide mock location" disabled
INFO: "Spoof SIM country" disabled
INFO: "Spoof Wi-Fi connection" disabled
INFO: "Enable Android debugging" disabled
INFO: "Change data directory location" disabled
INFO: "Hex" disabled
INFO: "Predictive back gesture" disabled
INFO: "Override certificate pinning" disabled
INFO: "Change package name" disabled
INFO: "Remove screen capture restriction" disabled
INFO: "Remove screenshot restriction" disabled
INFO: "Remove share targets" disabled
INFO: "Change version code" disabled
INFO: "Permanent repeat" disabled manually
INFO: "Permanent shuffle" disabled manually
INFO: Setting patch options
INFO: Deleting existing temporary files directory
SEVERE: Failed to delete existing temporary files directory
INFO: Decoding resources
INFO: Initializing lookup maps
INFO: Executing patches
INFO: "Bypass certificate checks" succeeded
INFO: "Enable exclusive audio playback" succeeded
INFO: "GmsCore support" succeeded
INFO: "Hide 'Get Music Premium' label" succeeded
SEVERE: "Hide category bar" failed:
app.revanced.patcher.patch.PatchException: Failed to match the fingerprint: app.revanced.patcher.Fingerprint@5c9831a7
        at app.revanced.patcher.Fingerprint.getException(Fingerprint.kt:254)
        at app.revanced.patcher.Fingerprint.getMatch(Fingerprint.kt:263)
        at app.revanced.patcher.Fingerprint.getMethod(Fingerprint.kt:392)
        at app.revanced.patches.music.layout.compactheader.HideCategoryBarKt.hideCategoryBar$lambda$2$lambda$1(HideCategoryBar.kt:17)
        at app.revanced.patcher.patch.Patch.execute(Patch.kt:71)
        at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(Patch.kt:159)
        at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Patcher.kt:84)
        at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Patcher.kt:109)
        at app.revanced.patcher.Patcher$invoke$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$invoke$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226)
        at app.revanced.cli.command.PatchCommand$run$1$4.invokeSuspend(PatchCommand.kt:315)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:314)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
 
INFO: "Hide music video ads" succeeded
INFO: "Remove background playback restrictions" succeeded
INFO: "Remove upgrade button" succeeded
INFO: Compiling modified resources
INFO: Aligning APK
INFO: Signing APK
INFO: Saved to C:\Revanced Yt Building\YouTubeMusicRevanced7.28.51.apk
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [ ] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
which version is the last this patch works with?

**Comment by Rajeshsahoo12** [comment]
> which version is the last this patch works with?

I have tested till version of `YT MUSIC 7.16.52` That patch works fine.

**Comment by Rajeshsahoo12** [comment]
> Does permanent shuffle work with `7.16.52`?
> 
> [#3505](https://github.com/ReVanced/revanced-patches/issues/3505)

Here is the complete patch log for `YT MUSIC v7.16.52` with both patches enabled exclusively `"Hide category bar" & "Permanent shuffle"`

`java -Xmx1024M -jar revanced-cli-5.0.0-all.jar patch -p patches-5.0.2.rvp YouTubeMusic7.16.52.apk -o YouTubeMusicRevanced7.16.52.apk -e "Hide category bar" -e "Permanent shuffle" -d "Permanent repeat"`

`https://pastebin.com/vwtw6XQ9`

Message related to patch `Permanent shuffle` on `YT MUSIC v7.16.52` in patch log :-

`WARNING: "Permanent shuffle" incompatible with com.google.android.apps.youtube.music 7.16.52 but compatible with com.google.android.apps.youtube.music 6.45.54, 6.51.53, 7.01.53, 7.02.52, 7.03.52`


But app patch process is successful.

**Comment by Rajeshsahoo12** [comment]
> Does permanent shuffle work with `7.16.52`?
> 
> [#3505](https://github.com/ReVanced/revanced-patches/issues/3505)

I have just tried now patch `Hide category bar & Permanent repeat` is compatible with `YT MUSIC v7.16.52`

Here is the entire patch log for that too = https://pastebin.com/SqWN2TYw
