### ISSUE TITLE
bug: YouTube patching errors

### ISSUE THREAD

**Issue by BigFlubba** [ReVanced/revanced-patches#3957]
### Bug description

I'm not sure if this is an issue or not, but I've been getting these errors the past couple of patches. I've made sure that everything is up to date.

### Error logs

```shell
- Device Info
ReVanced Manager: 1.23.2
Model: SM-S906U1
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.43.41 (Suggested: 19.43.41)
Patches version: v5.0.2
Patches added: Change header [Header: ReVanced (borderless logo)], Custom branding, Enable slide to seek, Predictive back gesture, Remove screen capture restriction, Remove screenshot restriction
Patches removed: Copy video URL, Disable precise seeking gesture, Swipe controls, Hide endscreen cards, Hide info cards, Disable rolling number animations, Hide seekbar, Hide Shorts components, Hide timestamp, Wide searchbar, Always repeat, Open links externally, Disable zoom haptics
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Initializing lookup maps
Executing patches
Applied 44 patches
Change header failed: app.revanced.patcher.patch.PatchException: The provided path is not a directory: ReVanced (borderless logo)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatchKt.changeHeaderPatch$lambda$23$lambda$22$lambda$21(ChangeHeaderPatch.kt:112)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatchKt.$r8$lambda$83oFK-GBRxMUp4yE8IZNvcDbQBQ(Unknown Source:0)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatchKt$$ExternalSyntheticLambda8.invoke(Unknown Source:6)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatchKt.changeHeaderPatch$lambda$23$lambda$22(ChangeHeaderPatch.kt:138)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatchKt.$r8$lambda$ZtL7btzUWC5WTfywltQ8cO3lG64(Unknown Source:0)
	at app.revanced.patches.youtube.layout.branding.header.ChangeHeaderPatchKt$$ExternalSyntheticLambda2.invoke(Unknown Source:4)
	at app.revanced.patcher.patch.Patch.execute(SourceFile:71)
	at app.revanced.patcher.patch.ResourcePatch.execute$revanced_patcher(SourceFile:246)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:84)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Compiling modified resources
Aligning APK
Signing APK
Patched APK
```

### Additional context

[revanced-manager_logcat_20241121135046516028.log](https://github.com/user-attachments/files/17851310/revanced-manager_logcat_20241121135046516028.log)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
`Change header failed: app.revanced.patcher.patch.PatchException: The provided path is not a directory: ReVanced (borderless logo)`

Reset the patch options for the `Change header` patch or select the preset again
