### ISSUE TITLE
bug: Facebook: "Hide 'Sponsored Stories'" Patch Fails

### ISSUE THREAD

**Issue by X-555** [ReVanced/revanced-patches#4008]
### Bug description

I encountered an issue when attempting to apply the "**Hide 'Sponsored Stories**'" patch to a merged Facebook APK using ReVanced CLI. The patch fails with the following error message:

### Error logs

```shell
SEVERE: "Hide 'Sponsored Stories'" failed:
app.revanced.patcher.patch.PatchException: Failed to match the fingerprint: app.revanced.patcher.Fingerprint@1f02ce3
        at app.revanced.patcher.Fingerprint.getException(Fingerprint.kt:254)
        at app.revanced.patcher.Fingerprint.getMatch(Fingerprint.kt:263)
        at app.revanced.patcher.Fingerprint.getOriginalMethod(Fingerprint.kt:368)
        at app.revanced.patches.facebook.ads.mainfeed.HideSponsoredStoriesPatchKt.hideSponsoredStoriesPatch$lambda$2$lambda$1(HideSponsoredStoriesPatch.kt:20)
        at app.revanced.patcher.patch.Patch.execute(Patch.kt:71)
        at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(Patch.kt:159)
        at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Patcher.kt:84)
        at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Patcher.kt:109)
        at app.revanced.patcher.Patcher$invoke$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$invoke$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226)
        at app.revanced.cli.command.PatchCommand$run$1$4.invokeSuspend(PatchCommand.kt:315)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:314)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
```

### Additional context

- ReVanced CLI version: **5.0.0**

- Patches version: **5.2.0-dev.4**

- Facebook APK version: **492.0.0.60.80**

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by X-555** [comment]
> Check which last version of the app works with the patches.

Version `490.0.0.63.82`

**Comment by PantlessCoding** [comment]
I will take a look at this in the next few days. In the meantime, v487.x.x.x.x and lower are known to work. Also this patch only work for Android 11 and up due to different package structure in the different releases.

**Comment by depablo** [comment]
@PantlessCoding Is this issue fixed?

**Comment by DerekZiemba** [comment]
I tried to patch versions 489 to 497 but only v490.0.0.63.82  was successful.    However, it is not possible to install it.    

![Screenshot_20250128_065025_MiXplorer.png](https://github.com/user-attachments/assets/7aa716cd-06f3-4ca3-a4c1-7a92a2f6d104)


When I go to install, I get "conflicts with another package already installed!".  This is after uninstalling Facebook v496 & ensuring there's not a FB app on the system partition.  This goes for any FB version patched by ReVanced.  
 If I install an earlier official version such as v489, then try upgrading to the patched v490, same issue occurs.    

My attempts to circumvent this is with the `Change package name` patch also fail because that patch too, is broken. 

 

```
`- Device Info
ReVanced Manager: 1.23.3
Model: SM-S926U
Android version: 14
Supported architectures: arm64-v8a
Root permissions: No

- Patch Info
App: com.facebook.katana v490.0.0.63.82 (Suggested: Any)
Patches version: v5.9.0
Patches added: Change package name [Update permissions: true, Update providers: true]
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: true
Patches source: revanced/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
An error occurred:
java.lang.IllegalArgumentException: expected element name 'view' and not 'View'
	at org.xmlpull.renamed.MXSerializer.endTag(Unknown Source:91)
	at org.xmlpull.v1.wrapper.classic.XmlSerializerDelegate.endTag(Unknown Source:2)
	at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(Unknown Source:87)
	at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(Unknown Source:85)
	at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(Unknown Source:35)
	at brut.androlib.res.decoder.ResFileDecoder.decode(Unknown Source:22)
	at app.revanced.patcher.patch.ResourcePatchContext.decodeResources$revanced_patcher(Unknown Source:1004)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:105)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:75)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:130)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:90)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:364)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-UNDCAO/out.apk' (OS Error: No such file or directory, errno = 2)`
```

**Comment by mainLink0435** [comment]
@DerekZiemba do you still have Messenger installed when trying to install the FB app? I had the same error as you, but then I also uninstalled Messenger, then the patched app installed fine.

For me though, the main patch I'd like to see (and I'm sure it's been requested somewere already) is not showing any 'suggested' posts. I just get a pile of crappy AI-generated images from random groups.

**Comment by DerekZiemba** [comment]
Hmm. Yes I do. That would be a no-go because I need Messenger more than I need FB.

**Comment by Shinseiki555** [comment]
> [@DerekZiemba](https://github.com/DerekZiemba) do you still have Messenger installed when trying to install the FB app? I had the same error as you, but then I also uninstalled Messenger, then the patched app installed fine.
> 
> Of course, unfortunately now, it means I can't install Messenger from the Play Store.

You need to patch both app on Revanced to make them work together.

> > Check which last version of the app works with the patches.
> 
> Version `490.0.0.63.82`

Thanks for this information but the manager still say "Any version" in the suggested version, wouldn't it be wise to change that ?

**Comment by Fffrank** [comment]
Is there no maintainer for this patch? It is terribly broken and at the minimum should be updated with version constraints after 4+ months of this topic.
