### ISSUE TITLE
bug: Nyx Music Player version 2.6.8 not patching

### ISSUE THREAD

**Issue by lontrafag** [ReVanced/revanced-patches#4072]
### Bug description

I've tried to patch newer version of Nyx multiple times but without success, always getting errors, or by Revanced Manager or by Revanced CLI.

Step 1 - Since apk is now spliced I've used a tool to merge them, on PC was APKEditor and on Android was AntiSplit-M
Step 2 - Merged files can now be used inside Revanced, using **patches-5.2.3** on Android and PC
Step 3 - Errors occurs, on Android seems that even with errors, Revanced output a file but no patch is applied

### Error logs

```shell
Android log:
- Device Info
ReVanced Manager: 1.23.2
Model: Mi Note 10
Android version: 11
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.awedea.nyx v2.6.8 (Suggested: Any)
Patches version: v5.2.3
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Initializing lookup maps
Executing patches
Unlock pro failed: app.revanced.patcher.patch.PatchException: Failed to match the fingerprint: app.revanced.patcher.Fingerprint@1b34ea7
	at app.revanced.patcher.Fingerprint.getException(SourceFile:254)
	at app.revanced.patcher.Fingerprint.getMatch(SourceFile:263)
	at app.revanced.patcher.Fingerprint.getMethod(SourceFile:392)
	at app.revanced.patches.nyx.misc.pro.UnlockProPatchKt.unlockProPatch$lambda$1$lambda$0(UnlockProPatch.kt:13)
	at app.revanced.patches.nyx.misc.pro.UnlockProPatchKt.$r8$lambda$7bQBPvoTZRCxKypLA9saZcecd-M(Unknown Source:0)
	at app.revanced.patches.nyx.misc.pro.UnlockProPatchKt$$ExternalSyntheticLambda0.invoke(Unknown Source:2)
	at app.revanced.patcher.patch.Patch.execute(SourceFile:71)
	at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(SourceFile:159)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:84)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:923)
Aligning APK
Signing APK
Patched APK

PC log:
G:\SamA04e>java -jar  revanced-cli-5.0.0-all.jar patch -p patches-5.2.3.rvp com.awedea.nyx_2.6.8_merged.apk
INFO: Loading patches
INFO: Deleting existing temporary files directory
INFO: Decoding app manifest
INFO: "Export all activities" disabled
INFO: "Spoof build info" disabled
INFO: "Hide mock location" disabled
INFO: "Spoof SIM country" disabled
INFO: "Spoof Wi-Fi connection" disabled
INFO: "Enable Android debugging" disabled
INFO: "Change data directory location" disabled
INFO: "Hex" disabled
INFO: "Predictive back gesture" disabled
INFO: "Override certificate pinning" disabled
INFO: "Change package name" disabled
INFO: "Remove screen capture restriction" disabled
INFO: "Remove screenshot restriction" disabled
INFO: "Remove share targets" disabled
INFO: "Change version code" disabled
INFO: Setting patch options
INFO: Initializing lookup maps
INFO: Executing patches
SEVERE: "Unlock pro" failed:
app.revanced.patcher.patch.PatchException: Failed to match the fingerprint: app.revanced.patcher.Fingerprint@61288814
        at app.revanced.patcher.Fingerprint.getException(Fingerprint.kt:254)
        at app.revanced.patcher.Fingerprint.getMatch(Fingerprint.kt:263)
        at app.revanced.patcher.Fingerprint.getMethod(Fingerprint.kt:392)
        at app.revanced.patches.nyx.misc.pro.UnlockProPatchKt.unlockProPatch$lambda$1$lambda$0(UnlockProPatch.kt:13)
        at app.revanced.patcher.patch.Patch.execute(Patch.kt:71)
        at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(Patch.kt:159)
        at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Patcher.kt:84)
        at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Patcher.kt:109)
        at app.revanced.patcher.Patcher$invoke$1.invoke(Patcher.kt)
        at app.revanced.patcher.Patcher$invoke$1.invoke(Patcher.kt)
        at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:57)
        at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:226)
        at app.revanced.cli.command.PatchCommand$run$1$4.invokeSuspend(PatchCommand.kt:315)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:314)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)

INFO: Aligning APK
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1192)
        at app.revanced.library.ApkSigner.newKeyStore(ApkSigner.kt:52)
        at app.revanced.library.ApkUtils.newPrivateKeyCertificatePair(ApkUtils.kt:113)
        at app.revanced.library.ApkUtils.signApk(ApkUtils.kt:165)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:336)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more

G:\SamA04e>
```

### Additional context

Revanced Manager shows that any version could be patched
![Image](https://github.com/user-attachments/assets/6b44bd23-9418-4ece-b213-48fe49e62d9a)

Trying to install the output file from Manager have no results and app is flagged as free version
![Image](https://github.com/user-attachments/assets/39289eae-22e3-489b-a881-431bcd919cd5)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The patch will be removed according to the contribution guidelines.
