### ISSUE TITLE
bug: patched Reddit still crashing after latest fix

### ISSUE THREAD

**Issue by SilentFlyBy** [ReVanced/revanced-patches#4086]
### Bug description

Follow-up of [this issue](https://github.com/ReVanced/revanced-patches/issues/4067) which was marked as [fixed](https://github.com/ReVanced/revanced-patches/commit/70bdc6840d465399625aa1ae0259f49e72711955), but still produces a very similar error.

Patches:

    Disable screenshot popup
    Hide ads
    Sanitize sharing links
    Unlock premium Reddit icons

### Error logs

```shell
12-09 17:52:01.576 12640 12751 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-8
12-09 17:52:01.576 12640 12751 E AndroidRuntime: Process: com.reddit.frontpage, PID: 12640
12-09 17:52:01.576 12640 12751 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lapp/revanced/extension/reddit/patches/FilterPromotedLinksPatch;
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	at com.reddit.domain.model.listing.Listing.<init>(Listing.kt:2)
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	at com.reddit.domain.model.listing.Listing.<init>(Listing.kt:12)
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	at com.reddit.data.remote.RemoteGqlLinkDataSource.l(RemoteGqlLinkDataSource.kt:553)
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	at com.reddit.link.impl.data.repository.RedditLinkRepository.W(RedditLinkRepository.kt:118)
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	at com.reddit.feeds.impl.data.RedditFeedLinkRepository.g(RedditFeedLinkRepository.kt:263)
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	at com.reddit.feeds.impl.domain.paging.RedditFeedPager$load$1.invokeSuspend(RedditFeedPager.kt:1502)
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	at kotlinx.coroutines.n0.run(DispatchedTask.kt:124)
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	at kotlinx.coroutines.internal.g$a.run(LimitedDispatcher.kt:4)
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	at mn1.i.run(Tasks.kt:3)
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$b.run(CoroutineScheduler.kt:101)
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [y1{Cancelling}@f1e1d09, Dispatchers.IO]
12-09 17:52:01.576 12640 12751 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: app.revanced.extension.reddit.patches.FilterPromotedLinksPatch
12-09 17:52:01.576 12640 12751 E AndroidRuntime: 	... 11 more
```

### Additional context

Reddit app: com.reddit.frontpage
Reddit version: 2024.17.0
ReVanced manager: 1.23.2
ReVanced patches: 5.3.0
Device: Google Pixel 8 Pro
Android: 15 (GrapheneOS)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The class exists, and the extension is being merged as no error is thrown about that:

![Image](https://github.com/user-attachments/assets/fa1f4033-e78d-48b5-b4dc-dec5d7022d85)

**Comment by oSumAtrIX** [comment]
The extension classes are present, possibly a bug in patcher?
![Image](https://github.com/user-attachments/assets/364b5d9c-5434-44e4-8338-744eec1ed0ef)
