### ISSUE TITLE
bug: Error patching YouTube

### ISSUE THREAD

**Issue by jojobozo** [ReVanced/revanced-patches#4118]
### Bug description

Patching YouTube with the latest patches isn't working, YT Music worked fine tho

### Error logs

```shell
- Device Info
ReVanced Manager: 1.23.2
Model: 24069PC21G
Android version: 15
Supported architectures: arm64-v8a
Root permissions: Yes

- Patch Info
App: com.google.android.youtube v19.46.42 (Suggested: 19.46.42)
Patches version: v5.4.0
Patches added: Default
Patches removed: GmsCore support
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Initializing lookup maps
Executing patches
Alternative thumbnails failed: app.revanced.patcher.patch.PatchException: The patch "Alternative thumbnails" depends on "BytecodePatch", which raised an exception:
app.revanced.patcher.patch.PatchException: Could not find insert indexes
	at app.revanced.patches.youtube.misc.navigation.NavigationBarHookPatchKt.navigationBarHookPatch$lambda$12$lambda$11$addHook(NavigationBarHookPatch.kt:56)
	at app.revanced.patches.youtube.misc.navigation.NavigationBarHookPatchKt.navigationBarHookPatch$lambda$12$lambda$11(NavigationBarHookPatch.kt:72)
	at app.revanced.patches.youtube.misc.navigation.NavigationBarHookPatchKt.$r8$lambda$ma1lFLbKcpMaJVNMWBRAz1SE0S8(Unknown Source:0)
	at app.revanced.patches.youtube.misc.navigation.NavigationBarHookPatchKt$$ExternalSyntheticLambda7.invoke(Unknown Source:2)
	at app.revanced.patcher.patch.Patch.execute(SourceFile:71)
	at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(SourceFile:159)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:84)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:72)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)

	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:75)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Applied 24 patches
Bypass URL redirects failed: app.revanced.patcher.patch.PatchException: Failed to match the fingerprint: app.revanced.patcher.Fingerprint@91a4999
	at app.revanced.patcher.Fingerprint.getException(SourceFile:254)
	at app.revanced.patcher.Fingerprint.getMatch(SourceFile:263)
	at app.revanced.patcher.Fingerprint.getMethod(SourceFile:392)
	at app.revanced.patches.youtube.misc.links.BypassURLRedirectsPatchKt.bypassURLRedirectsPatch$lambda$3$lambda$2(BypassURLRedirectsPatch.kt:64)
	at app.revanced.patches.youtube.misc.links.BypassURLRedirectsPatchKt.$r8$lambda$o7ApMUQ7azjKR4_ndr-YzQ24nUE(Unknown Source:0)
	at app.revanced.patches.youtube.misc.links.BypassURLRedirectsPatchKt$$ExternalSyntheticLambda0.invoke(Unknown Source:2)
	at app.revanced.patcher.patch.Patch.execute(SourceFile:71)
	at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(SourceFile:159)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:84)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Copy video URL failed: app.revanced.patcher.patch.PatchException: The patch "Copy video URL" depends on "BytecodePatch", which raised an exception:
app.revanced.patcher.patch.PatchException: The patch "BytecodePatch" depends on "BytecodePatch", which raised an exception:
app.revanced.patcher.patch.PatchException: Failed to match the fingerprint: app.revanced.patcher.Fingerprint@42471a4
	at app.revanced.patcher.Fingerprint.getException(SourceFile:254)
	at app.revanced.patcher.Fingerprint.getMatch(SourceFile:263)
	at app.revanced.patcher.Fingerprint.getMethod(SourceFile:392)
	at app.revanced.patches.youtube.video.videoid.VideoIdPatchKt.videoIdPatch$lambda$3$lambda$2(VideoIdPatch.kt:106)
	at app.revanced.patches.youtube.video.videoid.VideoIdPatchKt.$r8$lambda$ffZ7f2WZ_07wvrxxFY2RCjEZbNM(Unknown Source:0)
	at app.revanced.patches.youtube.video.videoid.VideoIdPatchKt$$ExternalSyntheticLambda1.invoke(Unknown Source:2)
	at app.revanced.patcher.patch.Patch.execute(SourceFile:71)
	at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(SourceFile:159)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:84)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:72)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:72)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)

	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:75)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:72)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)

	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:75)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Disable auto captions failed: app.revanced.patcher.patch.PatchException: Failed to match the fingerprint: app.revanced.patcher.Fingerprint@e73cb09
	at app.revanced.patcher.Fingerprint.getException(SourceFile:254)
	at app.revanced.patcher.Fingerprint.getMatch(SourceFile:263)
	at app.revanced.patcher.Fingerprint.getMethod(SourceFile:392)
	at app.revanced.patches.youtube.layout.autocaptions.AutoCaptionsPatchKt.autoCaptionsPatch$lambda$2$lambda$1(AutoCaptionsPatch.kt:47)
	at app.revanced.patches.youtube.layout.autocaptions.AutoCaptionsPatchKt.$r8$lambda$abzUSfOLGYewU9MWqizFv_94ErY(Unknown Source:0)
	at app.revanced.patches.youtube.layout.autocaptions.AutoCaptionsPatchKt$$ExternalSyntheticLambda0.invoke(Unknown Source:2)
	at app.revanced.patcher.patch.Patch.execute(SourceFile:71)
	at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(SourceFile:159)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:84)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Disable suggested video end screen failed: app.revanced.patcher.patch.PatchException: Failed to match the fingerprint: app.revanced.patcher.Fingerprint@405801a
	at app.revanced.patcher.Fingerprint.getException(SourceFile:254)
	at app.revanced.patcher.Fingerprint.getMatch(SourceFile:263)
	at app.revanced.patcher.Fingerprint.getMethod(SourceFile:392)
	at app.revanced.patches.youtube.layout.hide.suggestedvideoendscreen.DisableSuggestedVideoEndScreenPatchKt.disableSuggestedVideoEndScreenPatch$lambda$4$lambda$3(DisableSuggestedVideoEndScreenPatch.kt:69)
	at app.revanced.patches.youtube.layout.hide.suggestedvideoendscreen.DisableSuggestedVideoEndScreenPatchKt.$r8$lambda$6_NvWd_53sMRfYStglIhIIotOA8(Unknown Source:0)
	at app.revanced.patches.youtube.layout.hide.suggestedvideoendscreen.DisableSuggestedVideoEndScreenPatchKt$$ExternalSyntheticLambda0.invoke(Unknown Source:2)
	at app.revanced.patcher.patch.Patch.execute(SourceFile:71)
	at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(SourceFile:159)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:84)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Downloads failed: app.revanced.patcher.patch.PatchException: The patch "Downloads" depends on "BytecodePatch", which raised an exception:
app.revanced.patcher.patch.PatchException: The patch "BytecodePatch" depends on "BytecodePatch", which raised an exception:
app.revanced.patcher.patch.PatchException: The patch 'BytecodePatch' failed previously
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:67)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:72)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:72)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)

	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:75)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:72)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.rev
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I think they are patching a patched app (after mounting it)
