### ISSUE TITLE
bug: can get youtube to be patched

### ISSUE THREAD

**Issue by FirasTelmoudi** [ReVanced/revanced-patches#4152]
### Bug description

Hello, can someone please tells me what's wrong with this?
I tried multiple times but now working

### Error logs

```shell
- Device Info
ReVanced Manager: 1.23.2
Model: 2312CRAD3C
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.46.42 (Suggested: 19.46.42)
Patches version: v5.5.1
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Initializing lookup maps
Executing patches
Applied 54 patches
Compiling modified resources
Aligning APK
An error occurred:
java.io.IOException: Wrong version of key store.
	at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineLoad(go/retraceme e614ebda4fc88b52ac2bb501006c67905c1b69a072a5d6330346ba6625c5e47d:31)
	at java.security.KeyStore.load(KeyStore.java:1505)
	at app.revanced.library.ApkSigner.readKeyStore(SourceFile:82)
	at app.revanced.library.ApkUtils.readPrivateKeyCertificatePairFromKeyStore(SourceFile:137)
	at app.revanced.library.ApkUtils.signApk(SourceFile:163)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:347)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Something went wrong:
PathNotFoundException: Cannot copy file to '/data/user/0/app.revanced.manager.flutter/files/lastPatchedApp.apk', path = '/data/user/0/app.revanced.manager.flutter/files/patcher/tmp-JJDVFP/out.apk' (OS Error: No such file or directory, errno = 2)
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The keystore you used in manager is not compatible. Reset the keystore.

**Comment by FirasTelmoudi** [comment]
That did it, thanks mate
