### ISSUE TITLE
bug: Twitch revanced settings not present

### ISSUE THREAD

**Issue by XvPunisheR007vX** [ReVanced/revanced-patches#4165]
### Bug description

ReVanced settings are not present after patching twitch v22.4.0 reverting back to v16.9.1

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by XvPunisheR007vX** [comment]
![Image](https://github.com/user-attachments/assets/ca71b095-1282-43d4-8c4e-4f69592049e4)

**Comment by corrupteddrive** [comment]
Have this with 25.2.0 as well.

**Comment by XvPunisheR007vX** [comment]
- Device Info
ReVanced Manager: 1.25.1
Model: SM-S918B
Android version: 15
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: tv.twitch.android.app v25.5.1 (Suggested: Any)
Patches version: v5.33.0
Patches added: Default
Patches removed: None
Default patch options changed: None

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: revanced/revanced-patches

- Logs
Reading APK
Decoding app manifest
Loading patches
Deleting existing temporary files directory
Decoding resources
Initializing lookup maps
Executing patches
Auto claim channel points failed: app.revanced.patcher.patch.PatchException: The patch "Auto claim channel points" depends on "Settings", which raised an exception:
app.revanced.patcher.patch.PatchException: Failed to match the fingerprint: app.revanced.patcher.Fingerprint@83d1ece
	at app.revanced.patcher.Fingerprint.getException(Unknown Source:16)
	at app.revanced.patcher.Fingerprint.getMatch(Unknown Source:7)
	at app.revanced.patcher.Fingerprint.getClassDef(Unknown Source:5)
	at app.revanced.patches.twitch.misc.settings.SettingsPatchKt.settingsPatch$lambda$2$lambda$0$injectMenuItem(SettingsPatch.kt:100)
	at app.revanced.patches.twitch.misc.settings.SettingsPatchKt.settingsPatch$lambda$2$lambda$0(SettingsPatch.kt:134)
	at app.revanced.patches.twitch.misc.settings.SettingsPatchKt.$r8$lambda$dmqJ5q2MiHsKD3OO5VwTRybf_kY(Unknown Source:0)
	at app.revanced.patches.twitch.misc.settings.SettingsPatchKt$$ExternalSyntheticLambda0.invoke(Unknown Source:2)
	at app.revanced.patcher.patch.Patch.execute(Unknown Source:7)
	at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(Unknown Source:12)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:124)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:65)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)

	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:113)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)
Block audio ads failed: app.revanced.patcher.patch.PatchException: The patch "Block audio ads" depends on "Settings", which raised an exception:
app.revanced.patcher.patch.PatchException: The patch 'Settings' failed previously
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:38)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:65)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)

	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:113)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)
Block embedded ads failed: app.revanced.patcher.patch.PatchException: The patch "Block embedded ads" depends on "Block video ads", which raised an exception:
app.revanced.patcher.patch.PatchException: The patch "Block video ads" depends on "Settings", which raised an exception:
app.revanced.patcher.patch.PatchException: The patch 'Settings' failed previously
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:38)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:65)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:65)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)

	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:113)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:65)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)

	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:113)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)
Block video ads failed: app.revanced.patcher.patch.PatchException: The patch "Block video ads" depends on "Settings", which raised an exception:
app.revanced.patcher.patch.PatchException: The patch 'Settings' failed previously
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:38)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:65)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)

	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:113)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)
Settings failed: app.revanced.patcher.patch.PatchException: The patch 'Settings' failed previously
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:38)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)
Show deleted messages failed: app.revanced.patcher.patch.PatchException: The patch "Show deleted messages" depends on "Settings", which raised an exception:
app.revanced.patcher.patch.PatchException: The patch 'Settings' failed previously
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:38)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:65)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)

	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(Unknown Source:113)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(Unknown Source:190)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:2)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:1)
	at kotlinx.coroutines.flow.SafeFlow.collect(Unknown Source:102)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(Unknown Source:74)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:134)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:91)
	at kotlinx.coroutines.JobKt.runBlocking$default(Unknown Source:104)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(Unknown Source:360)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(Unknown Source:18)
	at java.lang.Thread.run(Thread.java:1119)
Compiling modified resources
Aligning APK
Signing APK
Patched APK

**Comment by XvPunisheR007vX** [comment]
[revanced-manager_logcat_20250807125856512067.log](https://github.com/user-attachments/files/21650058/revanced-manager_logcat_20250807125856512067.log)
