### ISSUE TITLE
bug: YouTube buffering/not playing

### ISSUE THREAD

**Issue by a4h7** [ReVanced/revanced-patches#4197]
### Bug description

5.7.0

### Error logs

```shell
: FATAL EXCEPTION: main
12-21 04:12:52.763 E/AndroidRuntime(31375): Process: app.revanced.android.photos, PID: 31375
12-21 04:12:52.763 E/AndroidRuntime(31375): java.lang.NullPointerException
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at jtb.a(PG:1563)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at atcx.Q(PG:5)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at atdo.q(PG:11)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at atcx.hn(PG:8)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at com.google.android.libraries.social.settings.PreferenceScreen.onItemClick(PG:16)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1274)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3287)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at android.widget.AbsListView$3.run(AbsListView.java:4266)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at android.os.Handler.handleCallback(Handler.java:991)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at android.os.Looper.loopOnce(Looper.java:232)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at android.os.Looper.loop(Looper.java:317)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at android.app.ActivityThread.main(ActivityThread.java:8787)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at java.lang.reflect.Method.invoke(Native Method)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
12-21 04:12:52.763 E/AndroidRuntime(31375): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
12-21 04:23:12.362 I/trusty  (    0): sac-ssmt: 126: DSP: Setup TZ SSMT 0
12-21 04:23:12.362 I/trusty  (    0): sac-ssmt: 126: DSP: Setup TZ SSMT 1
12-21 04:23:13.057 I/trusty  (    0): sac-ssmt: 111: TPU: Setup TZ SSMT 0
12-21 04:23:13.057 I/trusty  (    0): sac-ssmt: 111: TPU: Setup TZ SSMT 1
12-21 04:26:17.481 E/AndroidRuntime( 7435): FATAL EXCEPTION: main
12-21 04:26:17.481 E/AndroidRuntime( 7435): Process: app.revanced.android.photos, PID: 7435
12-21 04:26:17.481 E/AndroidRuntime( 7435): java.lang.NullPointerException
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at jtb.a(PG:1563)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at atcx.Q(PG:5)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at atdo.q(PG:11)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at atcx.hn(PG:8)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at com.google.android.libraries.social.settings.PreferenceScreen.onItemClick(PG:16)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1274)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3287)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at android.widget.AbsListView$3.run(AbsListView.java:4266)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at android.os.Handler.handleCallback(Handler.java:991)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at android.os.Looper.loopOnce(Looper.java:232)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at android.os.Looper.loop(Looper.java:317)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at android.app.ActivityThread.main(ActivityThread.java:8787)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at java.lang.reflect.Method.invoke(Native Method)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
12-21 04:26:17.481 E/AndroidRuntime( 7435): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
12-21 04:29:15.739 I/trusty  (    0): [FPC_SENSOR_SDK][E]fpc_sensor_driver_capture.
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by a4h7** [comment]
Those are the only results for grep AndroidRuntime. Okay I'll try 5.7.1.

**Comment by a4h7** [comment]
> `grep AndroidRuntime` collects app crashes and not debug logs.
> 
> Instead use `grep revanced:`
> 
> Must also have debugging enabled in Misc settings.

Replaced logcat

**Comment by a4h7** [comment]
> Those logs are for Google photos and not YouTube.
> 
> Try patching using the latest dev release (7.5.1) using a computer, command prompt, and CLI tools.

5.7.1 not working either

**Comment by a4h7** [comment]
> Confirm if you have the spoof language set to "Account language". If you don't, change to that and try again.

Yes it's set correctly. Please check logcat again, I updated it now, hopefully it's helpful now.

**Comment by a4h7** [comment]
> That log has almost no entries, and it has a lot of unrelated system calls.
> 
> Try:
> 
> * force stopping YT (in the app info)
> * clear the device logs by running: `adb logcat -c`
> * open YT, play a video until playback fails
> * run `adb logcat | grep "revanced:" > log.txt`

Uploaded a new log

**Comment by a4h7** [comment]
Attached

**Comment by a4h7** [comment]
That seems to have fixed it. Thanks.

**Comment by a4h7** [comment]
🤷

**Comment by aayushrautela** [comment]
Having it set on app language causes playback issues. Both app and account are set as US English.

**Comment by mhertz** [comment]
> That is odd because specifying a language is exactly the same as using patches 7.5 (which gave problems for your setup).

Sorry for butting in, but for me with 7.5 then changing away from default 'app language' fixes this issue.

**Comment by aayushrautela** [comment]
> What if you manually pick English as the default stream language?

Then it works in my case

**Comment by Sub123945** [comment]
> 5.7.1 has the same issue and fix

YouTube is properly playing for me

**Comment by oSumAtrIX** [comment]
Try this release: https://github.com/ReVanced/revanced-patches/releases/tag/v5.7.2-dev.2
