### ISSUE TITLE
bug: Wi-Fi Spoof Patch Failing

### ISSUE THREAD

**Issue by JustAGuyAFAIK** [ReVanced/revanced-patches#4211]
### Bug description

I'm trying to patch YouTube using the recommended 19.47.53 release and manager 1.23.2, and while it does get patched, the wifi spoof patch constantly fails.

```
Spoof Wi-Fi connection failed: app.revanced.patcher.patch.PatchException: Extension "extensions/all/misc/connectivity/wifi/spoof/spoof-wifi.rve" not found
	at app.revanced.patches.all.misc.connectivity.wifi.spoof.SpoofWifiPatchKt$spoofWifiPatch$lambda$2$$inlined$extendWith$2.get(Patch.kt:404)
	at app.revanced.patches.all.misc.connectivity.wifi.spoof.SpoofWifiPatchKt$spoofWifiPatch$lambda$2$$inlined$extendWith$2.get(Patch.kt:403)
	at app.revanced.patcher.patch.BytecodePatchContext.mergeExtension$revanced_patcher(SourceFile:69)
	at app.revanced.patcher.patch.BytecodePatch.execute$revanced_patcher(SourceFile:158)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend$execute(SourceFile:84)
	at app.revanced.patcher.Patcher$invoke$1.invokeSuspend(SourceFile:109)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$invoke$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(SourceFile:57)
	at kotlinx.coroutines.flow.AbstractFlow.collect(SourceFile:226)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$patcherResult$1$1.invokeSuspend(SourceFile:319)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:33)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(SourceFile:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(SourceFile:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(SourceFile:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(SourceFile:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(SourceFile:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(SourceFile:1)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$34(SourceFile:313)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$_NYn7P0Ss3RCL0-SqEFL-opMsQw(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda6.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
Compiling modified resources
Aligning APK
Signing APK
Patched APK
```

### Error logs

```shell

```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by JustAGuyAFAIK** [comment]
Oh, I see, my bad
