### ISSUE TITLE
bug: YouTube music thumbs up or down not working

### ISSUE THREAD

**Issue by briantho** [ReVanced/revanced-patches#4246]
### Bug description

YouTube music revanced has a bug, where when you try playing a song via search, the rating system is inaccessible. Basically you can't do thumbs up or down. This used to work on previous versions. Not sure which version broke it

### Error logs

```shell
12-27 00:50:08.620   888   888 E AndroidRuntime: Process: com.github.catfriend1.syncthingandroid, PID: 888
          12-27 00:50:08.620   888   888 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.nutomic.syncthingandroid.service.SyncthingService@8852372 with null: android.app.ForegroundServiceStartNotAllowedException: Time limit already exhausted for foreground service type dataSync
                        12-27 00:50:08.620   888   888 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5165)
                                         12-27 00:50:08.620   888   888 E AndroidRuntime:       at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
  12-27 00:50:08.620   888   888 E AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
              12-27 00:50:08.620   888   888 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:107)
       12-27 00:50:08.620   888   888 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:232)
                                              12-27 00:50:08.620   888   888 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:317)
                          12-27 00:50:08.620   888   888 E AndroidRuntime:      at android.app.ActivityThread.main(ActivityThread.java:8705)
                            12-27 00:50:08.620   888   888 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
                 12-27 00:50:08.620   888   888 E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                            12-27 00:50:08.620   888   888 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                               12-27 00:50:08.620   888   888 E AndroidRuntime: Caused by: android.app.ForegroundServiceStartNotAllowedException: Time limit already exhausted for foreground service type dataSync
   12-27 00:50:08.620   888   888 E AndroidRuntime:    at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
             12-27 00:50:08.620   888   888 E AndroidRuntime:   at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
                      12-27 00:50:08.620   888   888 E AndroidRuntime:  at android.os.Parcel.readParcelableInternal(Parcel.java:5075)
                     12-27 00:50:08.620   888   888 E AndroidRuntime:   at android.os.Parcel.readParcelable(Parcel.java:5057)
             12-27 00:50:08.620   888   888 E AndroidRuntime:   at android.os.Parcel.createExceptionOrNull(Parcel.java:3237)
            12-27 00:50:08.620   888   888 E AndroidRuntime:    at android.os.Parcel.createException(Parcel.java:3226)
      12-27 00:50:08.620   888   888 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:3209)
                                                   12-27 00:50:08.620   888   888 E AndroidRuntime:     at android.os.Parcel.readException(Parcel.java:3151)
                                            12-27 00:50:08.620   888   888 E AndroidRuntime:    at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7193)
                   12-27 00:50:08.620   888   888 E AndroidRuntime:     at android.app.Service.startForeground(Service.java:863)
                12-27 00:50:08.620   888   888 E AndroidRuntime:        at com.nutomic.syncthingandroid.util.Util$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
    12-27 00:50:08.620   888   888 E AndroidRuntime:   at com.nutomic.syncthingandroid.service.NotificationHandler.updatePersistentNotification(NotificationHandler.java:228)
     12-27 00:50:08.620   888   888 E AndroidRuntime:  at com.nutomic.syncthingandroid.service.NotificationHandler.updatePersistentNotification(NotificationHandler.java:109)
     12-27 00:50:08.620   888   888 E AndroidRuntime:  at com.nutomic.syncthingandroid.service.SyncthingService.onStartCommand(SyncthingService.java:306)
                                         12-27 00:50:08.620   888   888 E AndroidRuntime:       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5147)
 12-27 00:50:08.620   888   888 E AndroidRuntime:      ... 9 more
         12-27 00:55:19.137  2203  2203 E AndroidRuntime: FATAL EXCEPTION: main
                       12-27 00:55:19.137  2203  2203 E AndroidRuntime: Process: com.github.catfriend1.syncthingandroid, PID: 2203
                  12-27 00:55:19.137  2203  2203 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.nutomic.syncthingandroid.service.SyncthingService@8852372 with null: android.app.ForegroundServiceStartNotAllowedException: Time limit already exhausted for foreground service type dataSync
                                12-27 00:55:19.137  2203  2203 E AndroidRuntime:        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5165)
                                                 12-27 00:55:19.137  2203  2203 E AndroidRuntime:       at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
          12-27 00:55:19.137  2203  2203 E AndroidRuntime:      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
                       12-27 00:55:19.137  2203  2203 E AndroidRuntime:         at android.os.Handler.dispatchMessage(Handler.java:107)
                       12-27 00:55:19.137  2203  2203 E AndroidRuntime:         at android.os.Looper.loopOnce(Looper.java:232)
              12-27 00:55:19.137  2203  2203 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:317)
                                                  12-27 00:55:19.137  2203  2203 E AndroidRuntime:      at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                    12-27 00:55:19.137  2203  2203 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
                                         12-27 00:55:19.137  2203  2203 E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
            12-27 00:55:19.137  2203  2203 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
               12-27 00:55:19.137  2203  2203 E AndroidRuntime: Caused by: android.app.ForegroundServiceStartNotAllowedException: Time limit already exhausted for foreground service type dataSync
                           12-27 00:55:19.137  2203  2203 E AndroidRuntime:     at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
                                      12-27 00:55:19.137  2203  2203 E AndroidRuntime:  at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
                                              12-27 00:55:19.137  2203  2203 E AndroidRuntime:  at android.os.Parcel.readParcelableInternal(Parcel.java:5075)
                                             12-27 00:55:19.137  2203  2203 E AndroidRuntime:   at android.os.Parcel.readParcelable(Parcel.java:5057)
                                     12-27 00:55:19.137  2203  2203 E AndroidRuntime:   at android.os.Parcel.createExceptionOrNull(Parcel.java:3237)
                                    12-27 00:55:19.137  2203  2203 E AndroidRuntime:    at android.os.Parcel.createException(Parcel.java:3226)
                              12-27 00:55:19.137  2203  2203 E AndroidRuntime:  at android.os.Parcel.readException(Parcel.java:3209)
                    12-27 00:55:19.137  2203  2203 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:3151)
            12-27 00:55:19.137  2203  2203 E AndroidRuntime:    at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7193)
                                           12-27 00:55:19.137  2203  2203 E AndroidRuntime:     at android.app.Service.startForeground(Service.java:863)
                                        12-27 00:55:19.137  2203  2203 E AndroidRuntime:        at com.nutomic.syncthingandroid.util.Util$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
                            12-27 00:55:19.137  2203  2203 E AndroidRuntime:    at com.nutomic.syncthingandroid.service.NotificationHandler.updatePersistentNotification(NotificationHandler.java:228)
                              12-27 00:55:19.137  2203  2203 E AndroidRuntime:  at com.nutomic.syncthingandroid.service.NotificationHandler.updatePersistentNotification(NotificationHandler.java:109)
                              12-27 00:55:19.137  2203  2203 E AndroidRuntime:  at com.nutomic.syncthingandroid.service.SyncthingService.onStartCommand(SyncthingService.java:306)
          12-27 00:55:19.137  2203  2203 E AndroidRuntime:      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5147)
                         12-27 00:55:19.137  2203  2203 E AndroidRuntime:       ... 9 more
                                  12-27 01:01:19.655  4332  4332 E AndroidRuntime: FATAL EXCEPTION: main
                                                12-27 01:01:19.655  4332  4332 E AndroidRuntime: Process: com.github.catfriend1.syncthingandroid, PID: 4332
                                           12-27 01:01:19.655  4332  4332 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.nutomic.syncthingandroid.service.SyncthingService@8852372 with null: android.app.ForegroundServiceStartNotAllowedException: Time limit already exhausted for foreground service type dataSync
 12-27 01:01:19.655  4332  4332 E AndroidRuntime:      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5165)
                12-27 01:01:19.655  4332  4332 E AndroidRuntime:        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
                                  12-27 01:01:19.655  4332  4332 E AndroidRuntime:      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
                                               12-27 01:01:19.655  4332  4332 E AndroidRuntime:         at android.os.Handler.dispatchMessage(Handler.java:107)
                                               12-27 01:01:19.655  4332  4332 E AndroidRuntime:         at android.os.Looper.loopOnce(Looper.java:232)
                                      12-27 01:01:19.655  4332  4332 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:317)
                  12-27 01:01:19.655  4332  4332 E AndroidRuntime:      at android.app.ActivityThread.main(ActivityThread.java:8705)
                    12-27 01:01:19.655  4332  4332 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
         12-27 01:01:19.655  4332  4332 E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                    12-27 01:01:19.655  4332  4332 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                       12-27 01:01:19.655  4332  4332 E AndroidRuntime: Caused by: android.app.ForegroundServiceStartNotAllowedException: Time limit already exhausted for foreground service type dataSync
                                                   12-27 01:01:19.655  4332  4332 E AndroidRuntime:     at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
      12-27 01:01:19.655  4332  4332 E AndroidRuntime: at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
             12-27 01:01:19.655  4332  4332 E AndroidRuntime:   at android.os.Parcel.readParcelableInternal(Parcel.java:5075)
             12-27 01:01:19.655  4332  4332 E AndroidRuntime:   at android.os.Parcel.readParcelable(Parcel.java:5057)
     12-27 01:01:19.655  4332  4332 E AndroidRuntime:  at android.os.Parcel.createExceptionOrNull(Parcel.java:3237)
   12-27 01:01:19.655  4332  4332 E AndroidRuntime:    at android.os.Parcel.createException(Parcel.java:3226)
                                                     12-27 01:01:19.655  4332  4332 E AndroidRuntime:   at android.os.Parcel.readException(Parcel.java:3209)
                                            12-27 01:01:19.655  4332  4332 E AndroidRuntime:    at android.os.Parcel.readException(Parcel.java:3151)
                                    12-27 01:01:19.655  4332  4332 E AndroidRuntime:    at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7193)
           12-27 01:01:19.655  4332  4332 E AndroidRuntime:     at android.app.Service.startForeground(Service.java:863)
        12-27 01:01:19.655  4332  4332 E AndroidRuntime:        at com.nutomic.syncthingandroid.util.Util$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
                                                    12-27 01:01:19.655  4332  4332 E AndroidRuntime:    at com.nutomic.syncthingandroid.service.NotificationHandler.updatePersistentNotification(NotificationHandler.java:228)
                                                      12-27 01:01:19.655  4332  4332 E AndroidRuntime:  at com.nutomic.syncthingandroid.service.NotificationHandler.updatePersistentNotification(NotificationHandler.java:109)
                                                      12-27 01:01:19.655  4332  4332 E AndroidRuntime:  at com.nutomic.syncthingandroid.service.SyncthingService.onStartCommand(SyncthingService.java:306)
                                  12-27 01:01:19.655  4332  4332 E AndroidRuntime:      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5147)
                                                 12-27 01:01:19.655  4332  4332 E AndroidRuntime:       ... 9 more
  12-27 02:29:45.540 23816 23816 E AndroidRuntime: FATAL EXCEPTION: main
                12-27 02:29:45.540 23816 23816 E AndroidRuntime: Process: com.github.catfriend1.syncthingandroid, PID: 23816
            12-27 02:29:45.540 23816 23816 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.nutomic.syncthingandroid.service.SyncthingService: java.lang.ClassCastException: android.app.Application cannot be cast to com.nutomic.syncthingandroid.SyncthingApp
  12-27 02:29:45.540 23816 23816 E AndroidRuntime:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:4990)
                  12-27 02:29:45.540 23816 23816 E AndroidRuntime:      at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
                                    12-27 02:29:45.540 23816 23816 E AndroidRuntime:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2444)
                                               12-27 02:29:45.540 23816 23816 E AndroidRuntime:         at android.os.Handler.dispatchMessage(Handler.java:107)
                                               12-27 02:29:45.540 23816 23816 E AndroidRuntime:         at android.os.Looper.loopOnce(Looper.java:232)
                                      12-27 02:29:45.540 23816 23816 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:317)
                  12-27 02:29:45.540 23816 23816 E AndroidRuntime:      at android.app.ActivityThread.main(ActivityThread.java:8705)
                    12-27 02:29:45.540 23816 23816 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
         12-27 02:29:45.540 23816 23816 E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                    12-27 02:29:45.540 23816 23816 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                       12-27 02:29:45.540 23816 23816 E AndroidRuntime: Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.nutomic.syncthingandroid.SyncthingApp
                                            12-27 02:29:45.540 23816 23816 E AndroidRuntime:    at com.nutomic.syncthingandroid.service.SyncthingService.onCreate(SyncthingService.java:248)
                    12-27 02:29:45.540 23816 23816 E AndroidRuntime:    at android.app.ActivityThread.handleCreateService(ActivityThread.java:4977)
                                   12-27 02:29:45.540 23816 23816 E AndroidRuntime:     ... 9 more
                                          12-27 02:29:46.016 23858 23858 E AndroidRuntime: FATAL EXCEPTION: main
                                                       12-27 02:29:46.016 23858 23858 E AndroidRuntime: Process: com.github.catfriend1.syncthingandroid, PID: 23858
                                                   12-27 02:29:46.016 23858 23858 E AndroidRuntime: java.lang.RuntimeException: Unable to start service com.nutomic.syncthingandroid.service.SyncthingService@8852372 with null: android.app.ForegroundServiceStartNotAllowedException: Time limit already exhausted for foreground service type dataSync
         12-27 02:29:46.016 23858 23858 E AndroidRuntime:       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5165)
                         12-27 02:29:46.016 23858 23858 E AndroidRuntime:       at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
                                          12-27 02:29:46.016 23858 23858 E AndroidRuntime:      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
                                                       12-27 02:29:46.016 23858 23858 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
                                                      12-27 02:29:46.016 23858 23858 E AndroidRuntime:  at android.os.Looper.loopOnce(Looper.java:232)
                                      12-27 02:29:46.016 23858 23858 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:317)
                  12-27 02:29:46.016 23858 23858 E AndroidRuntime:      at android.app.ActivityThread.main(ActivityThread.java:8705)
                    12-27 02:29:46.016 23858 23858 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
         12-27 02:29:46.016 23858 23858 E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                    12-27 02:29:46.016 23858 23858 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                       12-27 02:29:46.016 23858 23858 E AndroidRuntime: Caused by: android.app.ForegroundServiceStartNotAllowedException: Time limit already exhausted for foreground service type dataSync
                                                   12-27 02:29:46.016 23858 23858 E AndroidRuntime:     at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
      12-27 02:29:46.016 23858 23858 E AndroidRuntime: at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
             12-27 02:29:46.016 23858 23858 E AndroidRuntime:   at android.os.Parcel.readParcelableInternal(Parcel.java:5075)
             12-27 02:29:46.016 23858 23858 E AndroidRuntime:   at android.os.Parcel.readParcelable(Parcel.java:5057)
     12-27 02:29:46.016 23858 23858 E AndroidRuntime:  at android.os.Parcel.createExceptionOrNull(Parcel.java:3237)
   12-27 02:29:46.016 23858 23858 E AndroidRuntime:    at android.os.Parcel.createException(Parcel.java:3226)
                                                     12-27 02:29:46.016 23858 23858 E AndroidRuntime:   at android.os.Parcel.readException(Parcel.java:3209)
                                            12-27
```

### Additional context

Testing on a rooted (magisk)![Image](https://github.com/user-attachments/assets/c091742b-ae4a-4a4d-bf8c-2219652cfd07)
![Image](https://github.com/user-attachments/assets/b5300f13-c822-4fa6-87f1-7ae61ca38f09)
 pixel 6 pro running android 15, with revanced patcher version 1.23.2 
YouTube music 7.29.52
Mount type 
Patched date: Dec 30th 2024

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by briantho** [comment]
Ah ok, didn't realize this was already reported. I only searched for "thumbs up" issues. I didn't think to use like/dislike. My bad. Anyway, hopefully this will be resolved soon
