### ISSUE TITLE
bug: App crash when opening

### ISSUE THREAD

**Issue by kazimmt** [revanced/revanced-patches#445]
### Type

Other

### Bug description

My own revanced build failed to open
Device: poco f3
Android 12

### Steps to reproduce

1. Build the app on pc
2. Copy to mobile
3. Install
4. Try to open

### Relevant log output

```shell
java.lang.VerifyError: Verifier rejected class kyt: void kyt.z(boolean) failed to verify: void kyt.z(boolean): [0x187] register v13 has type Integer but expected Reference: android.view.View (declaration of 'kyt' appears in /data/app/~~soeit_pCOOY8JBmXemOORA==/app.revanced.android.youtube-gVUQs1SKTZINWCU2MEZDfw==/base.apk!classes6.dex)
	at kxq.s(Unknown Source:60)
	at ege.n(PG:27)
	at ege.a(PG:19)
	at aqhy.a(PG:1)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.o(PG:22)
	at jax.a(PG:56)
	at qj.onCreate(PG:3)
	at br.onCreate(PG:1)
	at erb.onCreate(PG:8)
	at kxr.onCreate(PG:1)
	at app.revanced.integrations.swipecontrols.SwipeControlsHostActivity.onCreate(SwipeControlsHostActivity.kt:69)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:4)
	at android.app.Activity.performCreate(Unknown Source:127)
	at android.app.Activity.performCreate(Unknown Source:1)
	at android.app.Instrumentation.callActivityOnCreate(Unknown Source:3)
	at android.app.ActivityThread.performLaunchActivity(Unknown Source:491)
	at android.app.ActivityThread.handleLaunchActivity(Unknown Source:94)
	at android.app.servertransaction.LaunchActivityItem.execute(Unknown Source:84)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(Unknown Source:77)
	at android.app.servertransaction.TransactionExecutor.execute(Unknown Source:73)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:159)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
```

### Screenshots or videos

https://user-images.githubusercontent.com/82371061/189113783-5e89e333-dca5-44ec-95a5-bf4ccc4a5cab.mp4

**Comment by Canny1913** [comment]
Please provide the version of YT you used.

**Comment by kazimmt** [comment]
> Please provide the version of YT you used.

App building log

INFO: Skipping custom-branding, reason: manually excluded
INFO: Skipping enable-debugging, reason: excluded by default
INFO: swipe-controls succeeded
INFO: downloads succeeded
INFO: seekbar-tapping succeeded
INFO: disable-create-button succeeded
INFO: hide-cast-button succeeded
INFO: return-youtube-dislike succeeded
INFO: hide-autoplay-button succeeded
INFO: premium-heading succeeded
INFO: disable-fullscreen-panels succeeded
INFO: old-quality-layout succeeded
SEVERE: theme failed:
app.revanced.patcher.patch.PatchResultError: null was passed into an option that requires a value
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:314)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:45)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:330)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:95)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:22)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:160)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: app.revanced.patcher.patch.RequirementNotMetException: null was passed into an option that requires a value
        at app.revanced.patcher.patch.RequirementNotMetException.<clinit>(PatchOption.kt)
        at app.revanced.patcher.patch.PatchOption.getValue(PatchOption.kt:86)
        at app.revanced.patches.youtube.layout.theme.patch.ThemePatch$Companion.getTheme(ThemePatch.kt:64)
        at app.revanced.patches.youtube.layout.theme.patch.ThemePatch.execute(ThemePatch.kt:23)
        at app.revanced.patches.youtube.layout.theme.patch.ThemePatch.execute(ThemePatch.kt:15)
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:309)
        ... 16 more
INFO: hide-shorts-button succeeded
INFO: hide-watermark succeeded
INFO: sponsorblock succeeded
INFO: enable-wide-searchbar succeeded
INFO: tablet-mini-player succeeded
INFO: minimized-playback succeeded
INFO: client-spoof succeeded
INFO: custom-video-buffer succeeded
INFO: always-autorepeat succeeded
INFO: microg-support succeeded
INFO: settings succeeded
INFO: custom-playback-speed succeeded
INFO: hdr-auto-brightness succeeded
INFO: remember-video-quality succeeded
INFO: video-ads succeeded
INFO: general-ads succeeded
INFO: hide-infocard-suggestions succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Writing dex file classes2.dex
INFO: Writing dex file classes3.dex
INFO: Writing dex file classes.dex
INFO: Writing dex file classes4.dex
INFO: Writing dex file classes6.dex
INFO: Writing dex file classes5.dex
INFO: Writing dex file classes7.dex
INFO: Writing dex file classes8.dex
INFO: Writing resources...
INFO: Aligning revanced35nonrootblack_raw.apk to revanced35nonrootblack_aligned.apk
INFO: Signing revanced35nonrootblack_aligned.apk to revanced35nonrootblack_signed.apk
INFO: Copying revanced35nonrootblack_signed.apk to revanced35nonrootblack.apk
INFO: Cleaned up cache directory
INFO: Finished

**Comment by damElo850** [comment]
> same here tried recommended version ..33.32 & ..34.36 building via shell script
> 
> ```
> ./revanced-builder.sh reinstall
> ./revanced-builder.sh run
> ```
> 
> 2 errors
> 
> ```
> [[builder] SEVERE: custom-branding failed:
> [builder] SEVERE: theme failed: app.revanced.patcher.patch.PatchResultError: null was passed into an option that requires a value at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:315) at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:45) at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:331)]
> ```

up
