### ISSUE TITLE
`java.io.FileNotFoundException: general-ads` error when patching with latest version of cli, patches, integrations.

### ISSUE THREAD

**Issue by WelsonLiong** [revanced/revanced-patches#47]
`java.io.FileNotFoundException: general-ads
        at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:64)
        at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:51)
        at lanchon.multidexlib2.MultiDexIO.readMultiDexContainer(MultiDexIO.java:42)
        at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:36)
        at app.revanced.patcher.Patcher.addFiles(Patcher.kt:117)
        at app.revanced.patcher.Patcher.addFiles$default(Patcher.kt:113)
        at app.revanced.utils.patcher.PatcherKt.mergeFiles(Patcher.kt:69)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:16)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:106)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)`

**Comment by oSumAtrIX** [comment]
Check https://github.com/revanced/revanced-cli/commit/b30c7375a7ea61184be5dca19062ee74d1f97692

**Comment by Sculas** [comment]
That's not the issue. Read the docs properly and try again.

**Comment by WelsonLiong** [comment]
> That's not the issue. Read the docs properly and try again.

-i does not work for adding patch anymore?
