### ISSUE TITLE
bug: TikTok crashes after patching when attempting to remove an unavailable video from saved/collection

### ISSUE THREAD

**Issue by Dondrejohnson5** [revanced/revanced-patches#496]
### Type

Error at runtime

### Bug description

When attempting to open a video that you saved but is no longer available, the app crashes 

### Steps to reproduce

1: select profile
2: go to your saved/collection
3: find a video you saved that shows a broken camcorder in they background as it's thumbnail. It indicates the video you previously saved had been removed from the app.
4: select that video and attempt to remove it from your saved
You will notice that before you can complete step 4 the app will crash

### Relevant log output

```shell
No log output I am aware of
```

### Screenshots or videos

https://photos.app.goo.gl/f1DCs265yWxjJhwWA

**Comment by Leseratte10** [comment]
Looks like clicking on a video a couple ones before the deleted one doesn't always help. 

I've had a similar crash happen multiple times now, after clicking on the first video of my "saved posts" list and then just scrolling through posts. 

Really hoping this can get fixed soon as it makes the saved or liked video list basically useless.

I'm not sure if this is the same cause or if another bug report would be better, but here's another crash I encountered while scrolling through saved TikToks. 

The crash from my comment before causes TikTok to crash completely and I need to manually restart it. 
This crash causes it to restart on its own: 

```
10-10 13:46:52.600 22366 22366 D AndroidRuntime: Shutting down VM
--------- beginning of crash
10-10 13:46:52.603 22366 22366 E AndroidRuntime: FATAL EXCEPTION: main
10-10 13:46:52.603 22366 22366 E AndroidRuntime: Process: com.zhiliaoapp.musically, PID: 22366
10-10 13:46:52.603 22366 22366 E AndroidRuntime: java.lang.NullPointerException: Attempt to write to field 'int com.ss.android.ugc.aweme.feed.model.VideoControl.showProgressBar' on a null object reference
10-10 13:46:52.603 22366 22366 E AndroidRuntime: 	at com.ss.android.ugc.aweme.feed.model.Aweme.getVideoControl(SourceFile:1)
10-10 13:46:52.603 22366 22366 E AndroidRuntime: 	at X.7cD.onPlayProgressChange(SourceFile:50790530)
10-10 13:46:52.603 22366 22366 E AndroidRuntime: 	at X.7mX.onPlayProgressChange(SourceFile:50462727)
10-10 13:46:52.603 22366 22366 E AndroidRuntime: 	at X.7oy.run(SourceFile:196625)
10-10 13:46:52.603 22366 22366 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-10 13:46:52.603 22366 22366 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-10 13:46:52.603 22366 22366 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
10-10 13:46:52.603 22366 22366 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8061)
10-10 13:46:52.603 22366 22366 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-10 13:46:52.603 22366 22366 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
10-10 13:46:52.603 22366 22366 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
10-10 13:46:52.616 22366 22366 W System.err: currentActivity=com.ss.android.ugc.aweme.detail.ui.DetailActivity@3350ff8
10-10 13:46:52.617 22366 22366 W System.err: uncaughtException=java.lang.NullPointerException: Attempt to write to field 'int com.ss.android.ugc.aweme.feed.model.VideoControl.showProgressBar' on a null object reference
10-10 13:46:52.617 22366 22366 W System.err: 	at com.ss.android.ugc.aweme.feed.model.Aweme.getVideoControl(SourceFile:1)
10-10 13:46:52.617 22366 22366 W System.err: 	at X.7cD.onPlayProgressChange(SourceFile:50790530)
10-10 13:46:52.617 22366 22366 W System.err: 	at X.7mX.onPlayProgressChange(SourceFile:50462727)
10-10 13:46:52.617 22366 22366 W System.err: 	at X.7oy.run(SourceFile:196625)
10-10 13:46:52.617 22366 22366 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
10-10 13:46:52.617 22366 22366 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-10 13:46:52.617 22366 22366 W System.err: 	at android.os.Looper.loop(Looper.java:236)
10-10 13:46:52.617 22366 22366 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8061)
10-10 13:46:52.617 22366 22366 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-10 13:46:52.617 22366 22366 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
10-10 13:46:52.617 22366 22366 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
10-10 13:46:52.974 22366 22366 W aoapp.musically: type=1400 audit(0.0:335212): avc: denied { getattr } for path="/sys/kernel/debug/tracing/trace_marker" dev="tracefs" ino=5209 scontext=u:r:untrusted_app:s0:c230,c257,c512,c768 tcontext=u:object_r:debugfs_trace_marker:s0 tclass=file permissive=0 app=com.zhiliaoapp.musically
10-10 13:46:52.620 22366 22366 W System.err: currentActivity=com.ss.android.ugc.aweme.detail.ui.DetailActivity@3350ff8
10-10 13:46:52.620 22366 22366 W System.err: uncaughtException=java.lang.NullPointerException: Attempt to write to field 'int com.ss.android.ugc.aweme.feed.model.VideoControl.showProgressBar' on a null object reference
10-10 13:46:52.621 22366 22366 W System.err: 	at com.ss.android.ugc.aweme.feed.model.Aweme.getVideoControl(SourceFile:1)
10-10 13:46:52.621 22366 22366 W System.err: 	at X.7cD.onPlayProgressChange(SourceFile:50790530)
10-10 13:46:52.621 22366 22366 W System.err: 	at X.7mX.onPlayProgressChange(SourceFile:50462727)
10-10 13:46:52.621 22366 22366 W System.err: 	at X.7oy.run(SourceFile:196625)
10-10 13:46:52.621 22366 22366 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
10-10 13:46:52.621 22366 22366 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-10 13:46:52.621 22366 22366 W System.err: 	at android.os.Looper.loop(Looper.java:236)
10-10 13:46:52.621 22366 22366 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8061)
10-10 13:46:52.621 22366 22366 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-10 13:46:52.974 22366 22366 W aoapp.musically: type=1400 audit(0.0:335213): avc: denied { getattr } for path="/sys/kernel/debug/tracing/trace_marker" dev="tracefs" ino=5209 scontext=u:r:untrusted_app:s0:c230,c257,c512,c768 tcontext=u:object_r:debugfs_trace_marker:s0 tclass=file permissive=0 app=com.zhiliaoapp.musically
10-10 13:46:52.621 22366 22366 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
10-10 13:46:52.621 22366 22366 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```
