### ISSUE TITLE
bug: YouTube v17.36.37 crashes at startup

### ISSUE THREAD

**Issue by joseph-20** [revanced/revanced-patches#525]
### Type

Error at runtime

### Bug description

YouTube v17.36.37 crashes at startup after patching

### Steps to reproduce

1. Patch apk
2. Install patched apk
3. YouTube crashes right after opening

### Relevant log output

```shell
09-18 12:13:38.665 E/DatabaseUtils( 5665): java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.google.android.youtube, sha256=[c27408fbffe7052e0277bcf15cdd0e9fe932997a42a931949670aae5694333e3], atk=false, ver=223514044.true (go/gsrlt)
09-18 12:13:38.665 E/DatabaseUtils( 5665): 	at xrn.d(:com.google.android.gms@223514044@22.35.14 (190400-473845267):3)
09-18 12:13:38.665 E/DatabaseUtils( 5665): 	at xrs.e(:com.google.android.gms@223514044@22.35.14 (190400-473845267):2)
09-18 12:13:38.665 E/DatabaseUtils( 5665): 	at com.google.android.gms.auth.account.be.legacy.AccountChimeraContentProvider.call(:com.google.android.gms@223514044@22.35.14 (190400-473845267):2)
09-18 12:13:38.665 E/DatabaseUtils( 5665): 	at wlv.call(:com.google.android.gms@223514044@22.35.14 (190400-473845267):4)
09-18 12:13:38.665 E/DatabaseUtils( 5665): 	at android.content.ContentProvider.call(ContentProvider.java:2464)
09-18 12:13:38.665 E/DatabaseUtils( 5665): 	at android.content.ContentProvider$Transport.call(ContentProvider.java:512)
09-18 12:13:38.665 E/DatabaseUtils( 5665): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
09-18 12:13:38.665 E/DatabaseUtils( 5665): 	at android.os.Binder.execTransactInternal(Binder.java:1179)
09-18 12:13:38.665 E/DatabaseUtils( 5665): 	at android.os.Binder.execTransact(Binder.java:1143)
09-18 12:13:38.666 E/Auth    (10406): [GoogleAuthUtil] Exception when getting accounts
09-18 12:13:38.666 E/Auth    (10406): java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.google.android.youtube, sha256=[c27408fbffe7052e0277bcf15cdd0e9fe932997a42a931949670aae5694333e3], atk=false, ver=223514044.true (go/gsrlt)
09-18 12:13:38.666 E/Auth    (10406): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
09-18 12:13:38.666 E/Auth    (10406): 	at android.os.Parcel.createException(Parcel.java:2410)
09-18 12:13:38.666 E/Auth    (10406): 	at android.os.Parcel.readException(Parcel.java:2393)
09-18 12:13:38.666 E/Auth    (10406): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
09-18 12:13:38.666 E/Auth    (10406): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
09-18 12:13:38.666 E/Auth    (10406): 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
09-18 12:13:38.666 E/Auth    (10406): 	at android.content.ContentProviderClient.call(ContentProviderClient.java:601)
09-18 12:13:38.666 E/Auth    (10406): 	at android.content.ContentProviderClient.call(ContentProviderClient.java:589)
09-18 12:13:38.666 E/Auth    (10406): 	at lwk.m(PG:8)
09-18 12:13:38.666 E/Auth    (10406): 	at quv.d(PG:1)
09-18 12:13:38.666 E/Auth    (10406): 	at qxq.i(PG:1)
09-18 12:13:38.666 E/Auth    (10406): 	at qwv.rA(PG:10)
09-18 12:13:38.666 E/Auth    (10406): 	at qwv.b(PG:2)
09-18 12:13:38.666 E/Auth    (10406): 	at kyq.t(PG:26)
09-18 12:13:38.666 E/Auth    (10406): 	at kyq.o(PG:1)
09-18 12:13:38.666 E/Auth    (10406): 	at kyq.d(PG:3)
09-18 12:13:38.666 E/Auth    (10406): 	at adqa.b(PG:22)
09-18 12:13:38.666 E/Auth    (10406): 	at adqg.l(PG:12)
09-18 12:13:38.666 E/Auth    (10406): 	at com.google.apps.tiktok.account.api.controller.AccountControllerImpl$AccountControllerLifecycleObserver.oK(PG:11)
09-18 12:13:38.666 E/Auth    (10406): 	at com.google.apps.tiktok.tracing.contrib.androidx.TracedDefaultLifecycleObserver.oK(PG:2)
09-18 12:13:38.666 E/Auth    (10406): 	at androidx.lifecycle.FullLifecycleObserverAdapter.a(PG:7)
09-18 12:13:38.666 E/Auth    (10406): 	at atv.d(PG:3)
09-18 12:13:38.666 E/Auth    (10406): 	at ami.l(PG:22)
09-18 12:13:38.666 E/Auth    (10406): 	at ami.i(PG:2)
09-18 12:13:38.666 E/Auth    (10406): 	at ami.e(PG:2)
09-18 12:13:38.666 E/Auth    (10406): 	at adwb.e(PG:10)
09-18 12:13:38.666 E/Auth    (10406): 	at amy.a(PG:6)
09-18 12:13:38.666 E/Auth    (10406): 	at amx.onActivityPostStarted(PG:1)
09-18 12:13:38.666 E/Auth    (10406): 	at android.app.Activity.dispatchActivityPostStarted(Activity.java:1377)
09-18 12:13:38.666 E/Auth    (10406): 	at android.app.Activity.performStart(Activity.java:8119)
09-18 12:13:38.666 E/Auth    (10406): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3732)
09-18 12:13:38.666 E/Auth    (10406): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
09-18 12:13:38.666 E/Auth    (10406): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
09-18 12:13:38.666 E/Auth    (10406): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
09-18 12:13:38.666 E/Auth    (10406): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
09-18 12:13:38.666 E/Auth    (10406): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
09-18 12:13:38.666 E/Auth    (10406): 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-18 12:13:38.666 E/Auth    (10406): 	at android.os.Looper.loopOnce(Looper.java:201)
09-18 12:13:38.666 E/Auth    (10406): 	at android.os.Looper.loop(Looper.java:288)
09-18 12:13:38.666 E/Auth    (10406): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
09-18 12:13:38.666 E/Auth    (10406): 	at java.lang.reflect.Method.invoke(Native Method)
09-18 12:13:38.666 E/Auth    (10406): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-18 12:13:38.666 E/Auth    (10406): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

### Additional context

Applied patches:
- General Ads 0.0.1
- Hdr Auto Brightness 0.0.2
- Hide Autoplay Button 0.0.1
- Hide Cast Button 0.0.1
- Hide Create Button 0.0.1
- Hide Shorts Button 0.0.1
- Hide Watermark 0.0.1
- Minimized Playback 0.0.1
- Old Quality Layout 0.0.1
- Remember Video Quality 0.0.1
- Return Youtube Dislike 0.0.1
- Sponsorblock 0.0.1
- Video Ads 0.0.1

Matlog log: 
[2022-09-18-12-13-31.txt](https://github.com/revanced/revanced-patches/files/9593750/2022-09-18-12-13-31.txt)

**Comment by joseph-20** [comment]
Ok, I found out that apparently Google is doing something with the YouTube apps (maybe to go against Vanced/ReVanced users?) where if you install older YT/Music versions in nonroot install they will crash at startup with the reason being them being unable to find Google Accounts or the Play Store as a whole.

The only way I know so far of successfully installing an older version of these two apps is to either use SAI in root mode or Aurora Store also in root mode (unfortunately Youtube is shipped only as an apk bundle and for now ReVanced Manager crashes with apk bundles, so normal apk from ApkMirror + SAI is the right method for YouTube).
