### ISSUE TITLE
bug: hdr-auto-brightness failes on `com.google.android.youtube` `v17.33.42`

### ISSUE THREAD

**Issue by AMSAMSAMSAMS** [revanced/revanced-patches#535]
### Type

Error while patching

### Bug description

revanced-cli: 2.10.2
revanced-patches: 2.59.0
revanced-integrations: 0.37.4

### Steps to reproduce

Just patch....

### Relevant log output

```shell
SEVERE: hdr-auto-brightness failed: 
app.revanced.patcher.patch.PatchResultError
	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:331)
	at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
	at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
	at app.revanced.patches.youtube.misc.hdrbrightness.patch.HDRBrightnessPatch.execute(HDRBrightnessPatch.kt:43)
	at app.revanced.patches.youtube.misc.hdrbrightness.patch.HDRBrightnessPatch.execute(HDRBrightnessPatch.kt:23)
	at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
	... 16 more
```

**Comment by AMSAMSAMSAMS** [comment]
Only happened to old v17.33.42....

**Comment by OxrxL** [comment]
Fix: https://github.com/revanced/revanced-patches/pull/602

**Comment by ILoveOpenSourceApplications** [comment]
Is this issue resolved @oSumAtrIX ?

**Comment by ILoveOpenSourceApplications** [comment]
Closing this as no further reports have been made.
