### ISSUE TITLE
bug: Spotify premium nav failded

### ISSUE THREAD

**Issue by Vretu-Dev** [revanced/revanced-patches#621]
### Type

Error while patching

### Bug description

Failed install patch hide-premium-navbar for Spotify

### Steps to reproduce

Compile with using "C:\Program Files\Zulu\zulu-17\bin\java.exe" -jar revanced-cli-v2.11.2.jar -a Spotify.apk -o revanced.pak -b revanced-patches-v2.69.1.jar -m revanced-integrations-v0.42.1.apk

### Relevant log output

```shell
SEVERE: hide-premium-navbar failed:
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:331)
        at app.revanced.patcher.Patcher.access$applyPatch(Patcher.kt:47)
        at app.revanced.patcher.Patcher$applyPatches$1.invokeSuspend(Patcher.kt:347)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:24)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:161)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.spotify.premium_navbar_tab.patch.PremiumNavbarTabPatch.execute(PremiumNavbarTabPatch.kt:36)
        at app.revanced.patches.spotify.premium_navbar_tab.patch.PremiumNavbarTabPatch.execute(PremiumNavbarTabPatch.kt:21)
        at app.revanced.patcher.Patcher.applyPatch(Patcher.kt:326)
        ... 16 more
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/82831707/192151571-9fca3aa1-ed55-4f03-aa4f-0c4cd3f4ccd5.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Which version of Spotify?

**Comment by Vretu-Dev** [comment]
> Which version of Spotify?

8.7.68.568 propably lates

**Comment by Pandoriaantje** [comment]
tested on spotify 8.7.58.457 up to 8.8.2.434. all fail with the same error.

`java -jar revanced-cli-2.20.0-all.jar -b revanced-patches-2.156.0.jar -m .\revanced-integrations-0.93.1.apk -a .\Spotify_8.7.66.532.apk -o .\revanced_Spotify_8.7.66.532.apk`

> SEVERE: hide-premium-navbar failed:
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:339)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:152)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.spotify.premium_navbar_tab.patch.PremiumNavbarTabPatch.execute(PremiumNavbarTabPatch.kt:36)
        at app.revanced.patches.spotify.premium_navbar_tab.patch.PremiumNavbarTabPatch.execute(PremiumNavbarTabPatch.kt:21)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:335)
        ... 16 more

>

**Comment by kazimmt** [comment]
Still Same Error

> INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Merging revanced-integrations-0.94.1.apk
INFO: Skipping predictive-back-gesture: Excluded by default
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
WARNING: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/card_frame_pressed.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/bg_tab_focused.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-mdpi-v4/card_frame_pressed.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/card_frame.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xxhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xhdpi-v4/card_frame.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xhdpi-v4/card_frame_pressed.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_normal_pressed.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xhdpi-v4/notification_bg_low_normal.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-xhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-mdpi-v4/card_frame.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-mdpi-v4/common_google_signin_btn_text_light_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-mdpi-v4/notification_bg_low_pressed.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png". Renaming it to *.png.
WARNING: Cant find 9patch chunk in file: "drawable-hdpi-v4/card_shadow.9.png". Renaming it to *.png.
INFO: disable-capture-restriction succeeded
SEVERE: hide-premium-navbar failed:
app.revanced.patcher.patch.PatchResultError
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:339)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:355)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:83)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:20)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:158)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
        at app.revanced.patches.spotify.premium_navbar_tab.patch.PremiumNavbarTabPatch.execute(PremiumNavbarTabPatch.kt:36)
        at app.revanced.patches.spotify.premium_navbar_tab.patch.PremiumNavbarTabPatch.execute(PremiumNavbarTabPatch.kt:21)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:335)
        ... 16 more
INFO: remove-screenshot-restriction succeeded
INFO: spotify-theme succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Aligning Spotify_8.8.4.518.apk to Spotify_8.8.4.518patched_aligned.apk
INFO: Signing Spotify_8.8.4.518patched_aligned.apk to Spotify_8.8.4.518patched_signed.apk
INFO: Copying Spotify_8.8.4.518patched_signed.apk to Spotify_8.8.4.518patched.apk
INFO: Failed to clean up cache directory
INFO: Finished

![spotify](https://user-images.githubusercontent.com/82371061/215473824-933ff017-c206-4cc6-b559-20fc8351a090.png)

App Version: Spotify_8.8.4.518.apk
