### ISSUE TITLE
Patches Removed after device reboot 

### ISSUE THREAD

**Issue by YouSummoner** [revanced/revanced-patches#676]
### Type

Other

### Bug description

I patched the YouTube and YouTube Music app using the revanced manager(Root), the apps work fine, but after I reboot my device, all the patches from both the apps are removed and the apps return to normal.

### Steps to reproduce

1. Patch YouTube/ YouTube Music using Revanced Manager
2. Reboot the device
3. Check the patches apps

### Relevant log output

```shell
--------- beginning of main
09-30 18:29:29.921 16542 16596 I OpenGLRenderer: Davey! duration=43994ms; Flags=1, FrameTimelineVsyncId=53744, IntendedVsync=587833312733, Vsync=587833312733, InputEventId=1913189234, HandleInputStart=587847528629, AnimationStart=587847530191, PerformTraversalsStart=587847530452, DrawStart=587896195712, FrameDeadline=587866479399, FrameInterval=587847525139, FrameStartTime=16666666, SyncQueued=587896412743, SyncStart=587896695400, IssueDrawCommandsStart=587896771702, SwapBuffers=587900434202, FrameCompleted=631828545800, DequeueBufferDuration=2592917, QueueBufferDuration=6349584, GpuCompleted=631828545800, SwapBuffersCompleted=587907867170, DisplayPresentTime=524770222944, 
09-30 18:30:01.417 16542 20254 I OpenGLRenderer: Davey! duration=69592ms; Flags=1, FrameTimelineVsyncId=54551, IntendedVsync=593746241607, Vsync=593746241607, InputEventId=1870843061, HandleInputStart=593758040085, AnimationStart=593758042533, PerformTraversalsStart=593758043210, DrawStart=593780599460, FrameDeadline=593779408273, FrameInterval=593758033575, FrameStartTime=16666666, SyncQueued=593780752377, SyncStart=593780833939, IssueDrawCommandsStart=593783634720, SwapBuffers=593793595293, FrameCompleted=663338925840, DequeueBufferDuration=5657656, QueueBufferDuration=1181198, GpuCompleted=663338925840, SwapBuffersCompleted=593795313210, DisplayPresentTime=524770224003, 
09-30 18:30:06.440 16542 16596 I OpenGLRenderer: Davey! duration=74603ms; Flags=1, FrameTimelineVsyncId=54551, IntendedVsync=593746241607, Vsync=593746241607, InputEventId=1870843061, HandleInputStart=593758040085, AnimationStart=593758042533, PerformTraversalsStart=593758043210, DrawStart=593780599460, FrameDeadline=593796074939, FrameInterval=593758033575, FrameStartTime=16666666, SyncQueued=593780752377, SyncStart=593780833939, IssueDrawCommandsStart=593783634720, SwapBuffers=593793595293, FrameCompleted=668349543754, DequeueBufferDuration=5657656, QueueBufferDuration=1181198, GpuCompleted=668349543754, SwapBuffersCompleted=593795313210, DisplayPresentTime=524770224003, 
09-30 18:30:24.842 16542 20254 I OpenGLRenderer: Davey! duration=54962ms; Flags=1, FrameTimelineVsyncId=57485, IntendedVsync=631778339582, Vsync=631778339582, InputEventId=1171446642, HandleInputStart=631792197258, AnimationStart=631792199289, PerformTraversalsStart=631792200175, DrawStart=631820169758, FrameDeadline=631811506248, FrameInterval=631792192727, FrameStartTime=16666666, SyncQueued=631820299758, SyncStart=631820387727, IssueDrawCommandsStart=631820491216, SwapBuffers=631824146320, FrameCompleted=686741024320, DequeueBufferDuration=2941302, QueueBufferDuration=1320156, GpuCompleted=686741024320, SwapBuffersCompleted=631826135747, DisplayPresentTime=524770224620, 
09-30 18:30:48.783 16542 16594 I OpenGLRenderer: Davey! duration=47390ms; Flags=1, FrameTimelineVsyncId=60437, IntendedVsync=663304795827, Vsync=663304795827, InputEventId=1581404099, HandleInputStart=663305483183, AnimationStart=663305484121, PerformTraversalsStart=663305484381, DrawStart=663333347350, FrameDeadline=663337962493, FrameInterval=663305480527, FrameStartTime=16666666, SyncQueued=663333450423, SyncStart=663333512246, IssueDrawCommandsStart=663333671413, SwapBuffers=663336854485, FrameCompleted=710695123061, DequeueBufferDuration=2478646, QueueBufferDuration=847604, GpuCompleted=710695123061, SwapBuffersCompleted=663338088235, DisplayPresentTime=524770224997, 
09-30 18:31:26.165 16542 16594 I OpenGLRenderer: Davey! duration=79752ms; Flags=1, FrameTimelineVsyncId=61027, IntendedVsync=668314736043, Vsync=668314736043, InputEventId=2080527081, HandleInputStart=668326257192, AnimationStart=668326259327, PerformTraversalsStart=668326260109, DrawStart=668343505890, FrameDeadline=668347902709, FrameInterval=668326252504, FrameStartTime=16666666, SyncQueued=668343624327, SyncStart=668343831671, IssueDrawCommandsStart=668343955421, SwapBuffers=668347586463, FrameCompleted=748067803047, DequeueBufferDuration=2944375, QueueBufferDuration=848594, GpuCompleted=748067803047, SwapBuffersCompleted=668348983181, DisplayPresentTime=524770225355, 
09-30 18:32:23.393 16542 16683 I OpenGLRenderer: Davey! duration=118609ms; Flags=1, FrameTimelineVsyncId=63203, IntendedVsync=686682841933, Vsync=686699508599, InputEventId=1591247177, HandleInputStart=686706293383, AnimationStart=686706294789, PerformTraversalsStart=686706295362, DrawStart=686734286560, FrameDeadline=686716008599, FrameInterval=686706289320, FrameStartTime=16666666, SyncQueued=686734668487, SyncStart=686734808018, IssueDrawCommandsStart=686734996820, SwapBuffers=686739227445, FrameCompleted=805292809327, DequeueBufferDuration=2655312, QueueBufferDuration=1290000, GpuCompleted=805292809327, SwapBuffersCompleted=686741298070, DisplayPresentTime=524770225712, 
09-30 18:32:23.563 16542 16590 I manager.flutter: Background young concurrent copying GC freed 2144089(42MB) AllocSpace objects, 0(0B) LOS objects, 32% free, 168MB/248MB, paused 439us,130us total 351.939ms
09-30 18:32:24.905 16542  2406 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:24.905 16542  2405 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:24.905 16542  2403 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:24.905 16542  2404 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:25.315 16542 16590 I manager.flutter: Background concurrent copying GC freed 14778516(307MB) AllocSpace objects, 0(0B) LOS objects, 31% free, 204MB/300MB, paused 136us,35us total 1.427s
09-30 18:32:25.315 16542  2406 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 412.498ms
09-30 18:32:25.315 16542  2406 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:25.315 16542  2405 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 410.140ms
09-30 18:32:25.315 16542  2405 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:25.320 16542  2403 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 414.489ms
09-30 18:32:25.320 16542  2403 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:25.320 16542  2404 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 414.880ms
09-30 18:32:25.320 16542  2404 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:26.008 16542 16590 I manager.flutter: Background young concurrent copying GC freed 7616228(150MB) AllocSpace objects, 0(0B) LOS objects, 18% free, 245MB/300MB, paused 571us,237us total 395.104ms
09-30 18:32:29.214 16542  2406 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:29.214 16542  2403 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:29.214 16542  2404 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:29.214 16542  2405 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:29.574 16542  2403 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:29.574 16542  2404 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:29.574 16542  2405 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:29.574 16542  2406 I manager.flutter: WaitForGcToComplete blocked Alloc on HeapTrim for 360.306ms
09-30 18:32:29.574 16542  2406 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:29.574 16542  2403 I manager.flutter: WaitForGcToComplete blocked Alloc on HeapTrim for 360.037ms
09-30 18:32:29.574 16542  2403 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:29.574 16542  2404 I manager.flutter: WaitForGcToComplete blocked Alloc on HeapTrim for 359.991ms
09-30 18:32:29.574 16542  2404 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:29.579 16542  2405 I manager.flutter: WaitForGcToComplete blocked Alloc on HeapTrim for 364.224ms
09-30 18:32:29.579 16542  2405 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:34.058 16542  2405 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:34.058 16542  2406 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:34.058 16542  2403 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:34.058 16542  2404 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:34.649 16542  2405 I manager.flutter: WaitForGcToComplete blocked Alloc on CollectorTransition for 591.911ms
09-30 18:32:34.650 16542  2405 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:34.650 16542  2406 I manager.flutter: WaitForGcToComplete blocked Alloc on CollectorTransition for 591.890ms
09-30 18:32:34.650 16542  2406 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:34.650 16542  2403 I manager.flutter: WaitForGcToComplete blocked Alloc on CollectorTransition for 591.839ms
09-30 18:32:34.650 16542  2403 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:34.650 16542  2404 I manager.flutter: WaitForGcToComplete blocked Alloc on CollectorTransition for 591.963ms
09-30 18:32:34.650 16542  2404 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:34.745 16542 16630 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
09-30 18:32:34.886 16542  2406 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:34.886 16542  2405 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:34.886 16542  2403 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:34.886 16542  2404 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:35.076 16542  2403 I manager.flutter: WaitForGcToComplete blocked Alloc on HeapTrim for 189.666ms
09-30 18:32:35.076 16542  2403 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:35.076 16542  2406 I manager.flutter: WaitForGcToComplete blocked Alloc on HeapTrim for 190.272ms
09-30 18:32:35.076 16542  2406 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:35.077 16542  2404 I manager.flutter: WaitForGcToComplete blocked Alloc on HeapTrim for 190.469ms
09-30 18:32:35.077 16542  2404 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:35.077 16542  2405 I manager.flutter: WaitForGcToComplete blocked Alloc on HeapTrim for 190.799ms
09-30 18:32:35.077 16542  2405 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:41.279 16542  2404 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:41.279 16542  2405 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:41.279 16542  2406 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:41.280 16542  2403 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:41.744 16542  2404 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 464.818ms
09-30 18:32:41.744 16542  2404 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:41.744 16542  2405 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 464.779ms
09-30 18:32:41.744 16542  2405 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:41.744 16542  2406 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 464.862ms
09-30 18:32:41.744 16542  2406 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:41.744 16542  2403 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 464.861ms
09-30 18:32:41.744 16542  2403 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: Error registering plugin root, com.gokul.root.RootPlugin
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: java.lang.IllegalStateException: The main shell was already created
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at com.topjohnwu.superuser.internal.MainShell.setBuilder(MainShell.java:98)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at com.topjohnwu.superuser.Shell.setDefaultBuilder(Shell.java:148)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at com.gokul.root.RootPlugin.onAttachedToEngine(RootPlugin.java:26)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:144)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:94)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1086)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at app.revanced.manager.flutter.MainActivity.configureFlutterEngine(MainActivity.kt:30)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:205)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8057)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.app.Activity.performCreate(Activity.java:8037)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1345)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.os.Looper.loopOnce(Looper.java:201)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.os.Looper.loop(Looper.java:288)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at android.app.ActivityThread.main(ActivityThread.java:7872)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at java.lang.reflect.Method.invoke(Native Method)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-30 18:32:44.845 16542 16542 E GeneratedPluginRegistrant: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
09-30 18:32:45.859 16542  2406 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:45.860 16542  2405 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:45.860 16542  2404 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:45.860 16542  2403 I manager.flutter: Waiting for a blocking GC Alloc
09-30 18:32:45.950 16542  9645 I flutter : dynamic_color: Core palette detected.
09-30 18:32:45.980 16542 16590 I manager.flutter: Background concurrent copying GC freed 11870721(258MB) AllocSpace objects, 29(5744KB) LOS objects, 27% free, 247MB/343MB, paused 209us,32us total 1.564s
09-30 18:32:45.980 16542  2406 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 120.299ms
09-30 18:32:45.980 16542  2406 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:45.980 16542  2405 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 120.324ms
09-30 18:32:45.980 16542  2405 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:45.980 16542  2404 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 120.469ms
09-30 18:32:45.980 16542  2404 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:45.980 16542  2403 I manager.flutter: WaitForGcToComplete blocked Alloc on Background for 120.227ms
09-30 18:32:45.980 16542  2403 I manager.flutter: Starting a blocking GC Alloc
09-30 18:32:46.036 16542  9646 E BLASTBufferQueue: [SurfaceView[app.revanced.manager.flutter/app.revanced.manager.flutter.MainActivity]#35](f:0,a:0) rejecting buffer:active_size=1080x2340, requested_size=1080x2340 buffer{size=1080x2298 transform=0}
09-30 18:32:46.057 16999 16999 W sh      : type=1400 audit(0.0:487): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c159,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
09-30 18:32:46.073 16999 16999 W sh      : type=1400 audit(0.0:488): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c159,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
09-30 18:32:46.101 16999 16999 W sh      : type=1400 audit(0.0:489): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c159,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
09-30 18:32:46.113 16999 16999 W sh      : type=1400 audit(0.0:490): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c159,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
09-30 18:32:46.133 16999 16999 W sh      : type=1400 audit(0.0:491): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c159,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
09-30 18:32:46.153 16999 16999 W sh      : type=1400 audit(0.0:492): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c159,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
09-30 18:32:46.173 16999 16999 W sh      : type=1400 audit(0.0:493): avc: denied { read } for name="/" dev="sda11" ino=2 scontext=u:r:untrusted_app:s0:c159,c257,c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0 app=app.revanced.manager.flutter
09-30 18:32:46.560 16542 16590 I manager.flutter: Background young concurrent copying GC freed 9538637(193MB) AllocSpace objects, 2(40KB) LOS objects, 31% free, 210MB/306MB, paused 557us,186us total 279.216ms
09-30 18:32:46.952 16542 16590 I manager.flutter: Background young concurrent copying GC freed 6637495(133MB) AllocSpace objects, 32(12MB) LOS objects, 32% free, 196MB/292MB, paused 287us,111us total 194.192ms
09-30 18:32:47.169 16542 16686 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-30 18:32:47.170 16542 16686 W SQLiteLog: (28) double-quoted string literal: "F5E2C61D1E4C82A3C6A956CD033BB7C5"
09-30 18:32:47.333 16542 16590 I manager.flutter: Background young concurrent copying GC freed 6311512(126MB) AllocSpace objects, 11(556KB) LOS objects, 33% free, 188MB/284MB, paused 595us,145us total 120.297ms
09-30 18:32:47.734 16542 16590 I manager.flutter: Background young concurrent copying GC freed 5719829(114MB) AllocSpace objects, 10(1256KB) LOS objects, 33% free, 189MB/284MB, paused 210us,136us total 132.082ms
09-30 18:32:47.797 16542 16686 W SQLiteLog: (28) double-quoted string literal: "484091CDFBF54C9C82180F6C7CC4C586"
09-30 18:32:47.797 16542 16686 W SQLiteLog: (28) double-quoted string literal: "AAA40660D562D1F7C65C49FFF615C4B2"
09-30 18:32:49.306 16542 16542 W FlutterJNI: Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: app.revanced.manager.flutter/installer. Response ID: 578
09-30 18:32:49.306 16542 16542 W FlutterJNI: Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 291
09-30 18:32:55.185 16542 16592 W System  : A resource failed to call close. 
09-30 18:33:47.068 16542 16595 I OpenGLRenderer: Davey! duration=61030ms; Flags=1, FrameTimelineVsyncId=74463, IntendedVsync=827946522968, Vsync=828113189628, InputEventId=0, HandleInputStart=828129297079, AnimationStart=828129299110, PerformTraversalsStart=828129299996, DrawStart=828130366193, FrameDeadline=827967022968, FrameInterval=828129292496, FrameStartTime=16666666, SyncQueued=828130823537, SyncStart=828130911402, IssueDrawCommandsStart=828131024006, SwapBuffers=828132394787, FrameCompleted=888977057524, DequeueBufferDuration=673125, QueueBufferDuration=901458, GpuCompleted=888977057524, SwapBuffersCompleted=828133634318, DisplayPresentTime=524770200214,
```

### Solution

None, I have to patch the apps again after reboot.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This could be a mount problem.

**Comment by YouSummoner** [comment]
> This could be a mount problem. 

After patching again, all the app settings are retained tho

**Comment by oSumAtrIX** [comment]
That is because the app is mounted, what is your device and what root do you use.
