### ISSUE TITLE
bug: remember video quality patch don't remember "higher picture quality"

### ISSUE THREAD

**Issue by naftali100** [revanced/revanced-patches#719]
### Type

Other

### Bug description

changing the quality to "higher picture quality" don't effect other videos

### Steps to reproduce

1. turn off "remember current video quality"
2. open video
3. change quality to "higher picture quality"
4. open another video
5. the quality is the same as last video when it's opened, and not "higher picture quality"

### Relevant log output

```shell
no log
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by AMSAMSAMSAMS** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: app/revanced/patcher/patch/impl/BytecodePatch
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at app.revanced.patcher.util.patch.PatchBundle.loadPatches$revanced_patcher(PatchBundle.kt:20)
	at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:38)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:134)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.ClassNotFoundException: app.revanced.patcher.patch.impl.BytecodePatch
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 22 more

**Comment by thevtn** [comment]
the bug is not fixed, you need to open the issue again

**Comment by SodaWithoutSparkles** [comment]
Can reproduce the issue, patched just now with manager 0.0.30 and YT 17.36.37

**Comment by SodaWithoutSparkles** [comment]
Can you check issue #743 to see if the same solution work for you?

**Comment by naftali100** [comment]
it's me who answered there.. and it works with normal qualities and not the "higher quality"

**Comment by Splarkszter** [comment]
i have classic quality layout. it does not remember it. i goes back to 480p.

**Comment by SodaWithoutSparkles** [comment]
@Splarkszter Which version of patch and YT are you using? Try repatching. 

Also read the fine text under RYT settings > misc > remember quality

**Comment by Splarkszter** [comment]
> Also read the fine text under RYT settings > misc > remember quality


Oh, well. i have to say options are a bit confusing then. i assume something i want it will signal the ON position, but this ui does the opposite on some options. would be good to rework that to make it more intuitive. 

Also make sure that the app tells you it has to restar for the change to apply.

otherwise, cool thing :)
