### ISSUE TITLE
bug: java.io.EOFException

### ISSUE THREAD

**Issue by mangkoran** [revanced/revanced-patches#798]
### Type

Error while patching

### Bug description

Got `java.io.EOFException` while patching using [CnC-Robert/revanced-cli-script](https://github.com/CnC-Robert/revanced-cli-script). However, I am fully confident that this is revanced issue.

### Steps to reproduce

1. Clone [CnC-Robert/revanced-cli-script](https://github.com/CnC-Robert/revanced-cli-script)
2. Exec `./build-from-prebuilt`. This will do the following:
2.1. Download latest cli, integration, and version. In this case, the downloaded tools are:
```
cli 2.14.0
integrations 0.52.0
patches 2.82.0
```
2.2. List patches that will be used. In this case:
```
swipe-controls
downloads
seekbar-tapping
remember-video-quality
enable-debugging
custom-playback-speed
minimized-playback
client-spoof
custom-video-buffer
settings
hdr-auto-brightness
always-autorepeat
general-ads
hide-infocard-suggestions
video-ads
hide-time-and-seekbar
old-quality-layout
enable-wide-searchbar
disable-fullscreen-panels
hide-autoplay-button
disable-startup-shorts-player
hide-create-button
hide-shorts-button
hide-video-buttons
theme
hide-email-address
sponsorblock
hide-cast-button
tablet-mini-player
return-youtube-dislike
hide-watermark
disable-auto-player-popup-panels
disable-auto-captions
```
2.3. Exec the patch

### Relevant log output

```shell
java.io.EOFException
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:203)
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:172)
        at se.vidstige.jadb.SyncTransport.readString(SyncTransport.java:50)
        at se.vidstige.jadb.SyncTransport.verifyStatus(SyncTransport.java:33)
        at se.vidstige.jadb.JadbDevice.push(JadbDevice.java:210)
        at se.vidstige.jadb.JadbDevice.push(JadbDevice.java:216)
        at app.revanced.utils.adb.CommandsKt.copy(Commands.kt:24)
        at app.revanced.utils.adb.Adb.deploy$revanced_cli(Adb.kt:40)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:193)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Try via the official CLI.

**Comment by mangkoran** [comment]
The script is indeed using the [official CLI](https://github.com/CnC-Robert/revanced-cli-script/blob/4424addd8a6312192cdc67e4a4386592f89ee707/build-from-prebuilt.sh#L173).

**Comment by mangkoran** [comment]
Okay just now I tried using official revanced manager, installing as root, and it works! Apologize for not trying it before.

Have a good day!
