### ISSUE TITLE
bug: video-ads failed: app.revanced.patcher.patch.PatchResultError

### ISSUE THREAD

**Issue by SecretlyJealous** [revanced/revanced-patches#836]
### Type

Error while patching

### Bug description

The video-ads patch keeps failing for me, this wasn't an issue 2 weeks ago so I'm not sure what's changed. The hide-shorts-button also fails.

### Steps to reproduce

1. Compile the patches

### Relevant log output

```shell
[builder] INFO: Reading dex files
[builder] INFO: Decoding AndroidManifest.xml only, because resources are not needed
[builder] INFO: Merging C:\Users\Destro\Desktop\ReVanced Builder\revanced\revanced-integrations-v0.55.0.apk
[builder] WARNING: Skipping tiktok-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-speed, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-download, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-seekbar, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-settings, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-force-login, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping tiktok-feed-filter, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.ss.android.ugc.trill, com.zhiliaoapp.musically
[builder] WARNING: Skipping timeline-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
[builder] WARNING: Skipping dynamic-color, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
[builder] WARNING: Skipping monochrome-icon, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.twitter.android
[builder] WARNING: Skipping promo-code-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with de.dwd.warnapp
[builder] WARNING: Skipping spotify-theme, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.spotify.music
[builder] WARNING: Skipping disable-capture-restriction, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.spotify.music
[builder] WARNING: Skipping hide-premium-navbar, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.spotify.music
[builder] INFO: Skipping enable-debugging, reason: manually excluded
[builder] WARNING: Skipping pflotsh-ecmwf-subscription-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.garzotto.pflotsh.ecmwf_a
[builder] WARNING: Skipping tasteBuilder-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping hide-get-premium, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping minimized-playback-music, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] INFO: Skipping compact-header, reason: excluded by default
[builder] WARNING: Skipping upgrade-button-remover, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping music-video-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping background-play, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping exclusive-audio-playback, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping codecs-unlock, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping music-microg-support, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.google.android.apps.youtube.music
[builder] WARNING: Skipping premium-icon-reddit, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
[builder] WARNING: Skipping general-reddit-ads, reason: incompatible with com.google.android.youtube. This patch is only compatible with com.reddit.frontpage
[builder] INFO: Deleting existing resource cache directory
[builder] SEVERE: Failed to delete existing resource cache directory
[builder] INFO: Decoding resources
[builder] INFO: hide-time-and-seekbar succeeded
[builder] INFO: hide-video-buttons succeeded
[builder] INFO: enable-wide-searchbar succeeded
[builder] INFO: hide-captions-button succeeded
[builder] SEVERE: hide-shorts-button failed:
[builder] app.revanced.patcher.patch.PatchResultError: pivot-bar-enum-fingerprint failed
[builder] at app.revanced.patches.youtube.layout.pivotbar.shortsbutton.patch.ShortsButtonRemoverPatch.execute(ShortsButtonRemoverPatch.kt:59) at app.revanced.patches.youtube.layout.pivotbar.shortsbutton.patch.ShortsButtonRemoverPatch.execute(ShortsButtonRemoverPatch.kt:26)
[builder] at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:342) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:362) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145)
[builder] at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7)
[builder] INFO: hide-create-button succeeded
[builder] INFO: disable-startup-shorts-player succeeded
[builder] INFO: hide-cast-button succeeded
[builder] INFO: sponsorblock succeeded
[builder] INFO: hide-autoplay-button succeeded
[builder] INFO: disable-auto-player-popup-panels succeeded
[builder] INFO: disable-auto-captions succeeded
[builder] INFO: disable-fullscreen-panels succeeded
[builder] INFO: return-youtube-dislike succeeded
[builder] INFO: theme succeeded
[builder] INFO: hide-email-address succeeded
[builder] INFO: tablet-mini-player succeeded
[builder] INFO: hide-watermark succeeded
[builder] INFO: hide-my-mix succeeded
[builder] INFO: custom-branding succeeded
[builder] INFO: premium-heading succeeded
[builder] INFO: old-quality-layout succeeded
[builder] INFO: general-ads succeeded
[builder] SEVERE: video-ads failed: app.revanced.patcher.patch.PatchResultError
[builder] at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:346) at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37) at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:362) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127) at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92) at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157) at picocli.CommandLine.executeUserObject(CommandLine.java:1939) at picocli.CommandLine.access$1300(CommandLine.java:145) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358) at picocli.CommandLine$RunLast.handle(CommandLine.java:2352) at picocli.CommandLine$RunLast.handle(CommandLine.java:2314) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179) at picocli.CommandLine$RunLast.execute(CommandLine.java:2316) at picocli.CommandLine.execute(CommandLine.java:2078) at app.revanced.cli.main.MainKt.main(Main.kt:7) Caused by: java.lang.NullPointerException at app.revanced.patches.youtube.ad.video.patch.VideoAdsPatch.execute(VideoAdsPatch.kt:44) at app.revanced.patches.youtube.ad.video.patch.VideoAdsPatch.execute(VideoAdsPatch.kt:22) at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:342) ... 16 more
[builder] INFO: hide-infocard-suggestions succeeded
[builder] INFO: swipe-controls succeeded
[builder] INFO: downloads succeeded
[builder] INFO: seekbar-tapping succeeded
[builder] INFO: settings succeeded
[builder] INFO: microg-support succeeded
[builder] INFO: custom-video-buffer succeeded
[builder] INFO: client-spoof succeeded
[builder] INFO: always-autorepeat succeeded
[builder] INFO: remember-video-quality succeeded
[builder] INFO: minimized-playback succeeded
[builder] INFO: custom-playback-speed succeeded
[builder] INFO: hdr-auto-brightness succeeded
[builder] INFO: Compiling resources
[builder] INFO: Writing modified dex files
[builder] INFO: Writing dex file classes.dex
[builder] INFO: Writing dex file classes3.dex
[builder] INFO: Writing dex file classes4.dex
[builder] INFO: Writing dex file classes2.dex
[builder] INFO: Writing dex file classes5.dex
[builder] INFO: Writing dex file classes6.dex
[builder] INFO: Writing dex file classes7.dex
[builder] INFO: Writing dex file classes8.dex
[builder] INFO: Writing resources...
[builder] INFO: Aligning revanced_raw.apk to revanced_aligned.apk
[builder] INFO: Signing revanced_aligned.apk to revanced_signed.apk
[builder] INFO: Copying revanced_signed.apk to revanced.apk
[builder] INFO: Finished
[builder] ReVanced has been built! Please transfer over revanced/ReVanced-YouTube-v17.40.41-cli_v2.14.0-patches_v2.85.2.apk and if you are using YT/YTM, revanced/microg.apk and install them!
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You are using an unofficial tool, and are missing proper reproduction steps. Please create a proper issue.
