### ISSUE TITLE
Throwing Exception when logo is applied using custom-branding patch

### ISSUE THREAD

**Issue by snoobysnoofy** [revanced/revanced-patches#864]
### Type

Error while patching

### Bug description

I wanted to add a custom logo to parched youtube apk, so I made different versions of the logo as required by revanced in the branding folder. when I tried to patch the app(version: 17.36.37) it was throwing the following exception, and after patching process is completed. the patched apk still has the original revanced logo instead of the one I want to add.

### Steps to reproduce

1. add path of the icon folder in `options.toml` file.

```
['custom-branding']
appName = "sustube"
appIconPath = "/home/user/tempo/revanced/res/branding/"
```

2. run the command
```
java -jar revanced-cli.jar \
 -a youtube.apk \
 -c \
 -d 330032c0a792c3fd \
 -o vanced.apk \
 -b revanced-patches.jar \
 -m app-release-unsigned.apk
```

### Relevant log output

```shell
SEVERE: Error while setting option appIconPath for patch custom-branding: Invalid option value type: null, expected java.lang.Object 
app.revanced.patcher.patch.InvalidTypeException: Invalid option value type: null, expected java.lang.Object
	at app.revanced.utils.OptionsLoader.readAndSet(OptionsLoader.kt:82)
	at app.revanced.utils.OptionsLoader.init(OptionsLoader.kt:26)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:137)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
This bug report was done for an older version. Is the issue still existant?

**Comment by khuldraeseth** [comment]
Not author, but the issue still exists. Now with the new name `iconPath` instead of `appIconPath`, but otherwise the same error:

    SEVERE: Error while setting option iconPath for patch custom-branding: Invalid option value type: null, expected java.lang.Object 
    app.revanced.patcher.patch.InvalidTypeException: Invalid option value type: null, expected java.lang.Object
        at app.revanced.utils.OptionsLoader.readAndSet(OptionsLoader.kt:82)
        at app.revanced.utils.OptionsLoader.init(OptionsLoader.kt:26)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:137)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

I see the same behavior with `packageName` for `change-package-name`.

Patches 2.173.0, CLI 2.20.1

**Comment by oSumAtrIX** [comment]
This has been fixed in the dev branch for CLI but a release is yet to be made.
