### ISSUE TITLE
App crashes after opening

### ISSUE THREAD

**Issue by dhishkyaon** [revanced/revanced-patches#903]
### Type

Error at runtime

### Bug description

App crashes

### Steps to reproduce

Just open the app

### Relevant log output

```shell
type: crash
osVersion: google/sunfish/sunfish:13/TP1A.221005.002/2022102600:user/release-keys
package: app.revanced.android.youtube:1532227008
process: app.revanced.android.youtube

java.lang.RuntimeException: Unable to start activity ComponentInfo{app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: java.lang.RuntimeException: EntityStore failed loading from .so
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3677)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3814)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2309)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7904)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: java.lang.RuntimeException: EntityStore failed loading from .so
	at usi.d(PG:4)
	at usi.a(PG:1)
	at feb.b(PG:1)
	at feb.<init>(PG:1)
	at fcd.j(PG:1)
	at ejw.o(PG:75)
	at ejw.a(PG:39)
	at aqxa.a(PG:1)
	at ejw.o(PG:80)
	at ejw.a(PG:39)
	at ejw.o(PG:81)
	at ejw.a(PG:39)
	at aqxa.a(PG:1)
	at eir.e(PG:31)
	at eir.a(PG:29)
	at aqxa.a(PG:1)
	at eir.b(PG:75)
	at eir.a(PG:40)
	at aqxa.a(PG:1)
	at eir.b(PG:9)
	at eir.a(PG:40)
	at aqxa.a(PG:1)
	at eir.m(PG:71)
	at eir.a(PG:35)
	at aqxa.a(PG:1)
	at eir.m(PG:72)
	at eir.a(PG:35)
	at aqxa.a(PG:1)
	at eir.n(PG:4)
	at eir.a(PG:34)
	at aqxa.a(PG:1)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.o(PG:22)
	at jei.a(PG:39)
	at qt.onCreate(PG:3)
	at bu.onCreate(PG:1)
	at etk.onCreate(PG:8)
	at lbs.onCreate(PG:1)
	at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:4)
	at android.app.Activity.performCreate(Activity.java:8341)
	at android.app.Activity.performCreate(Activity.java:8320)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1389)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3658)
	... 14 more
Caused by: eae: libelements.so
	at cbw.o(PG:51)
	at umx.bi(PG:7)
	at eld.a(PG:1)
	at agfv.e(PG:8)
	at agfv.f(PG:5)
	at agfv.c(PG:1)
	at nxz.a(PG:1)
	at use.<init>(PG:1)
	at usm.<init>(PG:6)
	at usi.g(PG:4)
	at usi.d(PG:1)
	at usi.a(PG:1)
	at feb.b(PG:1)
	at feb.<init>(PG:1)
	at fcd.j(PG:1)
	at ejw.o(PG:75)
	at ejw.a(PG:39)
	at aqxa.a(PG:1)
	at els.m(PG:1)
	at els.cM(PG:1)
	at ejw.g(PG:33)
	at ejw.a(PG:39)
	at hze.a(PG:4)
	at hvj.run(PG:34)
	at aeid.run(PG:3)
	at asui.call(PG:2)
	at afjz.a(PG:1)
	at afjf.run(PG:4)
	at afka.run(PG:1)
	at nux.run(PG:23)
	at ned.run(PG:24)
	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.q.run(PG:5)
	at java.lang.Thread.run(Thread.java:1012)

```
```


### Screenshots or videos



### Solution

_No response_

### Additional context

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Try repatching. And include reproduction steps.

**Comment by CnC-Robert** [comment]
I'm guessing this is a root install.
Make sure you have installed the stock app using a full apk if you're patching a full apk and make sure to disable auto-updates with a detach module.

**Comment by dhishkyaon** [comment]
@oSumAtrIX tried repatching with just MicroG Support patch (non-root method) but still not working.

Also i have split base APK file of YouTube that i patched, in case you want to know. 


GrapheneOS Android 12

**Comment by dhishkyaon** [comment]
@CnC-Robert no its a non-root install. I installed YouTube from Split APK file which i got from APKMirror.

**Comment by oSumAtrIX** [comment]
You need to patch a full apk.
