### ISSUE TITLE
bug: Live chat button in fullscreen causes YouTube to crash

### ISSUE THREAD

**Issue by CnC-Robert** [revanced/revanced-patches#904]
### Type

Error at runtime

### Bug description

Pressing the live chat button in fullscreen causes the app to crash on 17.41.37.
Also happens when fullscreen panels are enabled.
The issue doesn't occur on stock YouTube or patched 17.36.37.

### Steps to reproduce

1. Go to a livestream
2. Go into fullscreen
3. Press the live chat button

### Relevant log output

```shell
FATAL EXCEPTION: main
Process: app.revanced.android.youtube, PID: 7071
java.lang.ClassCastException: iql cannot be cast to ipc
    at ioz.onClick(PG:51)
    at android.view.View.performClick(View.java:7498)
    at android.view.View.performClickInternal(View.java:7471)
    at android.view.View.access$3700(View.java:843)
    at android.view.View$PerformClick.run(View.java:29098)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:233)
    at android.os.Looper.loop(Looper.java:344)
    at android.app.ActivityThread.main(ActivityThread.java:8248)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please disable patches until the error is gone, report back which patch causes the error.

**Comment by SodaWithoutSparkles** [comment]
Can confirm this happening. 
```
java.lang.ClassCastException: iql cannot be cast to ipc
	at ioz.onClick(PG:51)
	at android.view.View.performClick(View.java:7751)
	at android.view.View.performClickInternal(View.java:7724)
	at android.view.View.access$3700(View.java:858)
	at android.view.View$PerformClick.run(View.java:29332)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8290)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

```

**Comment by CnC-Robert** [comment]
> Please disable patches until the error is gone, report back which patch causes the error.

It's the Hide Autoplay Button patch.

**Comment by SodaWithoutSparkles** [comment]
Strange. Even if you enable that patch at compile time, but disable that at runtime, you still crash. 

But if you use the buttons next to the like/dislike to call the live chat panel out, then fullscreen, no issues. When fullscreen, close the panel, then a button appear on bottom-right. Click that button calls the panel out again at fullscreen, but it does not crash.

**Comment by kyan5221** [comment]
> Please disable patches until the error is gone, report back which patch causes the error.

I've deselected 'Hide Autoplay Button' in patch list and it's OK when I tab Chat button in fullscreen.
but Chat panel is shown only when I enable 'Show fullscreen panels' in 'Layout' menu.

**Comment by SodaWithoutSparkles** [comment]
> but Chat panel is shown only when I enable 'Show fullscreen panels' in 'Layout' menu.

Because Chat panel _is_ a fullscreen panel

**Comment by shion5425550** [comment]
fixed in 2.103.0

**Comment by ILoveOpenSourceAppications** [comment]
Can say, this issue isn't fixed still.

**Comment by ILoveOpenSourceAppications** [comment]
This has been fixed as far as I know. So can be closed.

**Comment by SodaWithoutSparkles** [comment]
Can confirm that it is fixed.
