### ISSUE TITLE
Spotify patch hide-premium-navbar failed

### ISSUE THREAD

**Issue by edzamber** [revanced/revanced-patches#906]
### Type

Error while patching

### Bug description

Hidding premium navbar not working

### Steps to reproduce

Patch under linux

java -jar revanced-cli.jar -a spotify.apk -c -o Spotify-ReVanced.apk -b revanced-patches.jar -m revanced-integrations.apk

### Relevant log output

```shell
INFOS: spotify-theme succeeded 
INFOS: disable-capture-restriction succeeded 
GRAVE: hide-premium-navbar failed: 
app.revanced.patcher.patch.PatchResultError
  at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:346)
  at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:37)
  at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:362)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:127)
  at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:92)
  at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:27)
  at app.revanced.cli.command.MainCommand.run(MainCommand.kt:157)
  at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
  at picocli.CommandLine.access$1300(CommandLine.java:145)
  at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
  at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
  at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
  at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
  at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
  at picocli.CommandLine.execute(CommandLine.java:2078)
  at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NullPointerException
  at app.revanced.patches.spotify.premium_navbar_tab.patch.PremiumNavbarTabPatch.execute(PremiumNavbarTabPatch.kt:36)
  at app.revanced.patches.spotify.premium_navbar_tab.patch.PremiumNavbarTabPatch.execute(PremiumNavbarTabPatch.kt:21)
  at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:342)
  ... 16 more
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by edzamber** [comment]
Same thing with Revanced manager app
![photo_2022-10-29_19-51-13](https://user-images.githubusercontent.com/16240238/198845993-673440ec-e8b3-4b36-8785-7c5a40c4b001.jpg)
