### ISSUE TITLE
ReVanced crashed when opened.

### ISSUE THREAD

**Issue by Nizami20052022** [revanced/revanced-patches#961]
### Type

Other

### Bug description

YouTube patch version 17.43.36.Install ReVanced.Open ReVanced. The application crashed.

### Steps to reproduce

Above.

### Relevant log output

```shell
How should I do it?
```

### Solution

I dont know.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
Unfortunate.

**Comment by oSumAtrIX** [comment]
Include crash logs via logcat.

**Comment by Nizami20052022** [comment]
> Unfortunate.

Happy

**Comment by OxrxL** [comment]
Both 17.42.35 and 17.43.36 are fully working for me with CLI patching.

**Comment by CnC-Robert** [comment]
> Probably is a Manager bug.

Probably a skill issue

**Comment by OxrxL** [comment]
> > Probably is a Manager bug.
> 
> Probably a skill issue

Not from me xD

As I said: everything works for me.

**Comment by oSumAtrIX** [comment]
To fix said issue we need a reproducible environment. Disable patches until the error disappears. It could be a conflict between two patches.

**Comment by OxrxL** [comment]
> To fix said issue we need a reproducible environment. Disable patches until the error disappears. It could be a conflict between two patches.

Already said this bug from a Reddit users anyway. Seems a bug that affects only root.

**Comment by E-D-W-I-N** [comment]
Same issue here. I can provide you some logs.

**Device** - Google Pixel 6 Pro
**OS version** - Android 13
**Youtube client version**  - v17.43.36
**Patched with ReVanced Manager**
**Applied Patches:**
1. Hide Create Button
2. MicroG Support
3. Settings (I didn't actually select this, maybe it's some technical patch or smth)

<details>
  <summary>Part of logcat with crash</summary>


    E  FATAL EXCEPTION: main
    Process: app.revanced.android.youtube, PID: 15025
	    java.lang.RuntimeException: Unable to start activity ComponentInfo{app.revanced.android.youtube/com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity}: java.lang.RuntimeException: EntityStore failed loading from .so
	    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
	    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
	    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	    at android.os.Handler.dispatchMessage(Handler.java:106)
	    at android.os.Looper.loopOnce(Looper.java:201)
	    at android.os.Looper.loop(Looper.java:288)
	    at android.app.ActivityThread.main(ActivityThread.java:7898)
	    at java.lang.reflect.Method.invoke(Native Method)
	    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    Caused by: java.lang.RuntimeException: EntityStore failed loading from .so
	    at vbs.d(PG:4)
	    at vbs.a(PG:1)
	    at flc.b(PG:1)
	    at flc.<init>(PG:1)
	    at ffg.j(PG:1)
	    at equ.o(PG:76)
	    at equ.a(PG:39)
	    at arjc.a(PG:1)
	    at equ.o(PG:81)
	    at equ.a(PG:39)
	    at equ.o(PG:82)
	    at equ.a(PG:39)
	    at arjc.a(PG:1)
	    at epq.e(PG:18)
	    at epq.a(PG:32)
	    at arjc.a(PG:1)
	    at epq.b(PG:75)
	    at epq.a(PG:43)
	    at arjc.a(PG:1)
	    at epq.b(PG:9)
	    at epq.a(PG:43)
	    at arjc.a(PG:1)
	    at epq.m(PG:60)
	    at epq.a(PG:38)
	    at arjc.a(PG:1)
	    at epq.m(PG:61)
	    at epq.a(PG:38)
	    at arjc.a(PG:1)
	    at epq.o(PG:91)
	    at epq.a(PG:36)
	    at arjc.a(PG:1)
	    at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.o(PG:22)
	    at jln.a(PG:38)
	    at qt.onCreate(PG:3)
	    at bu.onCreate(PG:1)
	    at fam.onCreate(PG:8)
	    at lja.onCreate(PG:1)
	    at com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity.onCreate(PG:4)
	    at android.app.Activity.performCreate(Activity.java:8290)
	    at android.app.Activity.performCreate(Activity.java:8269)
	    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
	    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813) 
	    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
	    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
	    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
	    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308) 
	    at android.os.Handler.dispatchMessage(Handler.java:106) 
	    at android.os.Looper.loopOnce(Looper.java:201) 
	    at android.os.Looper.loop(Looper.java:288) 
	    at android.app.ActivityThread.main(ActivityThread.java:7898) 
	    at java.lang.reflect.Method.invoke(Native Method) 
	    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
    Caused by: ehd: libelements.so
	    at epc.I(PG:51)
	    at tmy.am(PG:7)
	    at esd.a(PG:1)
	    at agqf.e(PG:8)
	    at agqf.f(PG:5)
	    at agqf.c(PG:1)
	    at ogh.a(PG:1)
	    at vbo.<init>(PG:1)
	    at vbw.<init>(PG:6)
	    at vbs.g(PG:4)
	    at vbs.d(PG:1)
	    at vbs.a(PG:1)
	    at flc.b(PG:1)
	    at flc.<init>(PG:1)
	    at ffg.j(PG:1)
	    at equ.o(PG:76)
	    at equ.a(PG:39)
	    at arjc.a(PG:1)
	    at equ.o(PG:81)
	    at equ.a(PG:39)
	    at equ.o(PG:82)
	    at equ.a(PG:39)
	    at arjc.a(PG:1)
	    at icp.<init>(PG:2)
	    at icd.g(PG:1)
	    at equ.d(PG:49)
	    at equ.a(PG:39)
	    at arjc.a(PG:1)
	    at ese.run(PG:151)
	    at tma.run(PG:7)
	    at ocy.run(PG:5)
	    at odc.run(PG:23)
	    at nlt.run(PG:33)
	    at com.google.android.apps.youtube.embeddedplayer.service.jar.client.s.run(PG:15)
	    at java.lang.Thread.run(Thread.java:1012)
</details>

If you need any additional info, please feel free to ask me. I'll be glad to help you

**Comment by OxrxL** [comment]
> 

This is literally a lib (yeah...the ones inside libs folder inside apk) crash.

It's honestly a weird bug.

**Comment by oSumAtrIX** [comment]
Please open an issue if it doesn't exist yet, this is unrelated to the PR.

**Comment by E-D-W-I-N** [comment]
> Please open an issue if it doesn't exist yet, this is unrelated to the PR.

What PR are you talking about? This is already an issue, I just added logs to it

**Comment by E-D-W-I-N** [comment]
> Applied Patches:

UPD: Now I patched only MicroG Support patch via Manager and the app is still crashes with the same error

**Comment by oSumAtrIX** [comment]
Please attach a full recording of how you patch the app.

**Comment by E-D-W-I-N** [comment]
> Please attach a full recording of how you patch the app.

Here's a [video](https://www.youtube.com/watch?v=UUAnFibYhUI) with patching
Plus [ReVanced Manager app logs](https://github.com/revanced/revanced-patches/files/9933916/revanced-manager_logcat_20221104030940489295.log) (I cleared it before patching, so logs are only related to this patch)

P.S. I could also provide full device logcat (from patching to launching the app) if you need one.

**Comment by oSumAtrIX** [comment]
You need a full APK.

**Comment by E-D-W-I-N** [comment]
It worked on the previous version of youtube app and I didn't get the warning about split APK on a last version. So, feels like newer version on YouTube is now split or smth.

I guess issue can be closed now.
Thanks guys!

**Comment by Nizami20052022** [comment]
This error occurs again.

**Comment by oSumAtrIX** [comment]
Open an issue.
