### ISSUE TITLE
Spotify force closes at runtime

### ISSUE THREAD

**Issue by edzamber** [revanced/revanced-patches#995]
### Type

Error at runtime

### Bug description

Spotify is force closing at runtime

### Steps to reproduce

Using patcher under linux and with Revanced Manager app

### Relevant log output

```shell
FATAL EXCEPTION: main
Process: com.spotify.music, PID: 3064
java.lang.RuntimeException: Unable to create application com.spotify.music.SpotifyApplication: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object p.iki.get()' on a null object reference
 at android.app.ActivityThread.handleBindApplication(Unknown Source:1031)
 at android.app.ActivityThread.access$1700(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(Unknown Source:785)
 at android.os.Handler.dispatchMessage(Unknown Source:19)
 at android.os.Looper.loopOnce(Unknown Source:167)
 at android.os.Looper.loop(Unknown Source:76)
 at android.app.ActivityThread.main(Unknown Source:107)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
 at com.android.internal.os.ZygoteInit.main(Unknown Source:330)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object p.iki.get()' on a null object reference
 at com.spotify.music.SpotifyApplication.onCreate(SourceFile:12)
 at android.app.Instrumentation.callApplicationOnCreate(Unknown Source:0)
 at android.app.ActivityThread.handleBindApplication(Unknown Source:891)
 ... 9 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nikhilbadyal** [comment]
Why would you use revanced Spotify in the first place when xmanager is there ?

**Comment by Alaric323** [comment]
This bug still occurs; specifically trying to apply recording patch to allow operation with Rootless JamesDSP.  Applying the patch causes the app to force close immediately on launch.

**Comment by oSumAtrIX** [comment]
You will need to mount via root.

**Comment by Alaric323** [comment]
Don't have and can't root, as much as I'd like to.  Hence Rootless JamesDSP.  Their github said to try this patch.

**Comment by oSumAtrIX** [comment]
Send crash logs.

**Comment by Alaric323** [comment]
How do I grab them?  I'm assuming through ADB?

For reference, the current version of Spotify is v8.8.12.545.  I apply only the "Disable Capture Restriction v0.0.2" plug in, and it succeeds in making the APK.  Before install, I uninstall the original Spotify, then move back to ReVanced Manager and install the patched version.  The patched version immediately crashes on startup.

**Comment by oSumAtrIX** [comment]
Yeah, crash logs work

**Comment by Alaric323** [comment]
[logcat grep spotify.txt](https://github.com/revanced/revanced-patches/files/10825770/logcat.grep.spotify.txt)

Here's a grepped logcat searching for spotify only, includes uninstallation of the stock app.

**Comment by fr34kyn01535** [comment]
Can confirm, still doesn't work
